### PR TITLE
enh: support real(sp) in cpu_time

### LINKED ISSUE #3919: incomprehensible error message from program OK with gfortran and ifx
The program and the last few lines of its lfortran output:
```
(lf2) john:~/Test/Glist$ cat explogtest.f90
program explogtest
  ! Which is faster: exp or log?
  integer:: n, k = 8
  real:: x,dx,y,z,t1,t2
  print "(A,I0)",'k = ',k
  dx = 1e-6
  call cpu_time(t1)
  x = 0d0
  do n = 1,10**k
     x = x+dx
     z = exp(1d0/x)
  end do
  call cpu_time(t2)
  print "(2(A,F0.3))",'after 10**k exp, abs(t2-t1) = ',abs(t2-t1),' s; z=',z
  x = 0d0
  do n = 1,10**k
     x = x+dx
     z = log(1d0/x)
  end do
  call cpu_time(t1)
  print "(2(A,F0.3))",'after 10**k log, abs(t2-t1) = ',abs(t2-t1),' s; z=',z
end program explogtest

code generation error: asr_to_llvm: module failed verification. Error:
Call parameter type does not match function signature!
  %t1 = alloca float, align 4
 double*  call void @__module_lfortran_intrinsic_math_cpu_time(float* %t1)
Call parameter type does not match function signature!
  %t2 = alloca float, align 4
 double*  call void @__module_lfortran_intrinsic_math_cpu_time(float* %t2)
Call parameter type does not match function signature!
  %t1 = alloca float, align 4
 double*  call void @__module_lfortran_intrinsic_math_cpu_time(float* %t1)
```
Output of the same program from gfortran (ifx was very similar)
```
k = 8
after 10**k exp, abs(t2-t1) = .899 s; z=1.032
after 10**k log, abs(t2-t1) = .915 s; z=-3.466
```

### PR DESCRIPTION
**Pull request by Pranavchiku**
Fixes #3919

### CODE REVIEW

File: src/runtime/impure/lfortran_intrinsic_math.f90 [hunk 1]
```diff
@@ -15,19 +15,34 @@ module lfortran_intrinsic_math
...
+
+pure subroutine dp_cpu_time(t)
+real(sp), intent(out) :: t
+interface
+    pure subroutine c_s_cpu_time(t) bind(c, name="_lfortran_s_cpu_time")
+    import :: c_float
+    real(c_float), intent(out) :: t
+    end subroutine
+end interface
+call c_s_cpu_time(t)
```
Comment (certik) [inline src/runtime/impure/lfortran_intrinsic_math.f90:45]: This is fine for now. Eventually I think we should move these into impure instrinsic functions in ASR, as other frontends would also like to use these timing routines, and it will clean up the Fortran-based runtime library. Also these would not belong into "math" anyway.

**Review by certik — APPROVED** [review]
Thanks!

File: integration_tests/intrinsics_213.f90 [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+  if (abs(z - 1.03174341) > 1e-8) error stop 
+  x = 0d0
+  do n = 1,10**k
+     x = x+dx
+     z = log(1d0/x)
+  end do
+  call cpu_time(t1)
+  print "(2(A,F0.3))",'after 10**k log, abs(t2-t1) = ',abs(t2-t1),' s; z=',z
+  if (abs(z - (-3.46573591)) > 1e-8) error stop
+end program intrinsics_213
```
Comment (certik) [inline integration_tests/intrinsics_213.f90:24]: This test takes 2s to run. Instead, it must run immediately. Also, the test is computing a numerical integral of `integrate(exp(1/x), (x, 0, 100))` which is equal to infinity. Also we are mixing single/double precision in `x = 0d0` (which should be written as `x = 0._dp`, but you really wanted `x = 0`. The same with `1d0/x`.

Comment (certik) [reply integration_tests/intrinsics_213.f90:24]: Also the printing doesn't seem to work super well in LFortran: https://github.com/lfortran/lfortran/issues/4001.
