### PR TITLE
fix: handling of nested pass array by data functions

### LINKED ISSUE #5909: [PRIMA] compile `cobyla_example_1.f90`
Branch: https://github.com/Pranavchiku/prima/tree/lf-cobyla_example_1-1

```console
% FC="lfortran --cpp" cmake -S . -B build -DCMAKE_INSTALL_PREFIX=$(pwd)/install -DCMAKE_Fortran_FLAGS=""  -DCMAKE_SHARED_LIBRARY_CREATE_Fortran_FLAGS=""  -DCMAKE_MACOSX_RPATH=OFF -DCMAKE_SKIP_INSTALL_RPATH=ON  -DCMAKE_SKIP_RPATH=ON && cmake --build build --target install
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
-- Setting PRIMA version to c2fc96c9-dirty
-- Configuring done (0.1s)
-- Generating done (0.0s)
-- Build files have been written to: /Users/pranavchiku/repos/prima/build
[ 73%] Built target primaf
[ 76%] Built target example_lincoa_fortran_2_exe
[ 77%] Building Fortran object fortran/CMakeFiles/example_cobyla_fortran_1_exe.dir/examples/cobyla/cobyla_example_1.f90.o
ASR verify pass error: The symbol table was not found in the scope of `symtab`.

ASR verify pass error: Var::m_v `calcfc_internal_real____0_real____2` cannot point outside of its symbol table
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2730
    LCompilers::print_stack_on_segfault();
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2626
    return compile_src_to_object_file(arg_file, outfile, false,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 1051
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 382
    compiler_options, run_fn, infile);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 10450
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 403
    apply_passes(al, asr, _passes_with_experimental_simplifier, pass_options, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 184
    throw LCompilersException("Verify failed in the pass: "
LCompilersException: Verify failed in the pass: pass_array_by_data
make[2]: *** [fortran/CMakeFiles/example_cobyla_fortran_1_exe.dir/examples/cobyla/cobyla_example_1.f90.o] Error 1
make[1]: *** [fortran/CMakeFiles/example_cobyla_fortran_1_exe.dir/all] Error 2
make: *** [all] Error 2
```

### LINKED ISSUE #5917: Variable cannot point outside symbol table in `pass_array_by_data`
Towards #5909

```fortran
module pintrf_mod
public :: OBJCON

contains

    subroutine OBJCON(x)
        implicit none
        real, intent(in) :: x(:)
    end subroutine OBJCON

end module pintrf_mod

subroutine cobyla(x)
    implicit none

    real, intent(inout) :: x(:)
    call evaluate(calcfc_internal)
    contains

    subroutine calcfc_internal(x_internal)
        implicit none
        real, intent(in) :: x_internal(:)
    end subroutine calcfc_internal

    subroutine evaluate(calcfc)
        use, non_intrinsic :: pintrf_mod, only : OBJCON
        implicit none
        procedure(OBJCON) :: calcfc
    end subroutine evaluate

end subroutine

program cobyla_exmp
end program
```

```console
% lfortran a.f90
ASR verify pass error: The symbol table was not found in the scope of `symtab`.

ASR verify pass error: Var::m_v `calcfc_internal_real____0` cannot point outside of its symbol table
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2730
    LCompilers::print_stack_on_segfault();
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2671
    err = compile_src_to_object_file(arg_file, tmp_o, false,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 1051
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 382
    compiler_options, run_fn, infile);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 10450
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 403
    apply_passes(al, asr, _passes_with_experimental_simplifier, pass_options, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 184
    throw LCompilersException("Verify failed in the pass: "
LCompilersException: Verify failed in the pass: pass_array_by_data
```

### PR DESCRIPTION
**Pull request by Pranavchiku**
Fixes #5917

### CODE REVIEW

File: src/libasr/pass/pass_array_by_data.cpp [hunk 1]
```diff
@@ -555,6 +635,22 @@ class EditProcedureCallsVisitor : public ASR::ASRPassBaseWalkVisitor<EditProcedu
...
+                    if ( new_x_name != nullptr ) {
+                        ASR::Function_t* new_func = ASR::down_cast<ASR::Function_t>(resolve_new_proc(subrout_sym));
+                        ASR::down_cast<ASR::Variable_t>(x.m_name)->m_type = new_func->m_function_signature;
+                        xx.m_name = new_x_name;
+                        xx.m_original_name = new_x_name;
+                        std::vector<size_t>& indices = v.proc2newproc[subrout_sym].second;
+                        Vec<ASR::call_arg_t> new_args = construct_new_args(x.n_args, x.m_args, indices);
+                        xx.m_args = new_args.p;
+                        xx.n_args = new_args.size();
+                        return;
```
Comment (Pranavchiku) [inline src/libasr/pass/pass_array_by_data.cpp:650]: The idea here is to fetch the type declaration of procedure, find its new proc, get the required number of arguments and use those to create subroutine / function call.

File: src/libasr/pass/pass_array_by_data.cpp [hunk 2]
```diff
@@ -313,11 +313,72 @@ class EditProcedureReplacer: public ASR::BaseExprReplacer<EditProcedureReplacer>
...
+        create `cobyla_real____0` and add it as a symbol in global scope. Then we visit `cobyla`,
+        create `calcfc_internal_real____0` as replacement of `calcfc_internal` and add it as a symbol
+        in scope of `cobyla`. Now, we visit `cobyla_real____0` and replace `calcfc_internal` with
+        `calcfc_internal_real____0`
+        
+        This means both symbols `cobyla` and `cobyla_real____0` have `calcfc_internal_real____0` as a symbol
+        but eventually `cobyla` is removed from scope.
+
+        In `proc2newproc` we map `cobyla(1) -> cobyla_real____0(2)` and `calcfc_internal(1.1) -> calcfc_internal_real____0(1.2)`
+        and also have `calcfc_internal(2.1) -> calcfc_internal_real____0(2.2)`. Where `(x)` represents symtab counter.
```
Comment (certik) [inline src/libasr/pass/pass_array_by_data.cpp:351]: Why do we create the `_real____0` suffixes?

Comment (Pranavchiku) [reply src/libasr/pass/pass_array_by_data.cpp:351]: This is done by `pass_array_by_data` pass. Here `real___0` represents, 0th argument is real array. No significance, but to distinguish it.

Comment (certik) [reply src/libasr/pass/pass_array_by_data.cpp:351]: I see, it generates new functions.

**Review by certik — APPROVED** [review]
I think that this is fine, thanks!
