### PR TITLE
Fix: Defer COMMON block size check across multiple statements

### LINKED ISSUE #10583: Common block size mismatch message issued too soon?
```
program common1
  implicit none

  integer :: i1, i2
  real :: r1, r2
  common /block/ i1, i2
  real :: x
  common x/block/ r1, r2

  x = 42.42
  call sub ()
  print *, i1+i2, merge (': pass', ': fail', i1+i2 == 579)
  print *, r1+r2, merge (': pass', ': fail', abs(r1+r2) < 0.0001)

end program

subroutine sub ()
  implicit none

  integer :: i1, i2
  real :: r1, r2

  common /block/ i1, i2  ! Message issued here, without considering the next line
  common /block/ r1, r2

  real :: x
  common //x

  print *, 'x =', x, merge (': pass', ': fail', abs (x - 42.42) < 0.0001)

  i1 = 123
  i2 = 456
  r1 = 3.14
  r2 = -3.14

end subroutine
```
```
$ lfortran common1.f90
semantic error: COMMON block storage size mismatch: this declaration has 8 bytes but previous declaration has 16 bytes
  --> common1.f90:23:3
   |
23 |   common /block/ i1, i2
   |   ^^^^^^^^^^^^^^^^^^^^^ 


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
$
```
```
$ gfortran common1.f90
(base) wws@w6ws-4:~/computer/fortran/fcvs/fcvs21_f95/wws$ ./a.out
 x =   42.4199982     : pass
         579 : pass
   0.00000000     : pass
$
```
If I compile this with `--continue-compilation`, I get errors from both statements:
```
$ lfortran --continue-compilation common1.f90
semantic error: COMMON block storage size mismatch: this declaration has 8 bytes but previous declaration has 16 bytes
  --> common1.f90:23:3
   |
23 |   common /block/ i1, i2
   |   ^^^^^^^^^^^^^^^^^^^^^ 

semantic error: COMMON block storage size mismatch: this declaration has 8 bytes but previous declaration has 16 bytes
  --> common1.f90:24:3
   |
24 |   common /block/ r1, r2
   |   ^^^^^^^^^^^^^^^^^^^^^ 


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
$
```

### PR DESCRIPTION
**Pull request by himanshumahajan138**
Fixes #10583

## Summary
- Fix COMMON block storage size mismatch error being issued too early when a block is split across multiple `common` statements in a program unit
- Add deferred size validation that waits until all `common` statements for a block are processed before checking against previous declarations
- Add integration test `common_29` reproducing the issue

## Scope
- Modified `src/lfortran/semantics/ast_common_visitor.h`:
  - Added `common_block_deferred_size_check` map to store canonical sizes for deferred validation
  - Modified `populate_common_dictionary()`: when a previously declared block is encountered, accumulate variables instead of immediately checking size
  - Modified `mark_common_blocks_as_declared()`: perform deferred size validation after all statements are processed
- Added `integration_tests/common_29.f90`
- Registered test in `integration_tests/CMakeLists.txt`

## Rationale
Fortran allows extending a COMMON block across multiple statements:
```fortran
common /block/ i1, i2
common /block/ r1, r2    ! extends /block/ to 16 bytes total

### CODE REVIEW

File: src/lfortran/semantics/ast_common_visitor.h [hunk 1]
```diff
@@ -3916,10 +3939,17 @@ class CommonVisitor : public AST::BaseVisitor<Derived> {
...
 		       COMMON blocks use storage association, so different layouts are
 		       allowed as long as the total byte size matches.
-		       We track byte offsets for each variable in this declaration. */
-		    size_t canonical_size = common_block_byte_sizes[common_block_name];
+		       Multiple COMMON statements may contribute to the same block,
+		       so defer size validation until all statements are processed. */
+
+		    // Save canonical size for deferred validation (only on first encounter in this scope)
+		    if (common_block_deferred_size_check.find(common_block_name) == common_block_deferred_size_check.end()) {
+			common_block_deferred_size_check[common_block_name] = {common_block_byte_sizes[common_block_name], x.base.base.loc};
```
Comment (HarshitaKalani) [inline src/lfortran/semantics/ast_common_visitor.h]: Here

File: src/lfortran/semantics/ast_common_visitor.h [hunk 2]
```diff
@@ -3933,18 +3963,10 @@ class CommonVisitor : public AST::BaseVisitor<Derived> {
...
-				     Level::Error, Stage::Semantic, {
-					 Label("",{x.base.base.loc})
-				     }));
-			throw SemanticAbort();
-		    }
+
+		    common_block_byte_sizes[common_block_name] = byte_offset;
+		    // Mark as accumulating so subsequent COMMON stmts for this block append
+		    cbd_it->second.first = true;
 		}
```
Comment (HarshitaKalani) [inline src/lfortran/semantics/ast_common_visitor.h:4013]: Here

**Review by HarshitaKalani — APPROVED** [review]
There are a few places where indentation can be improved. Otherwise, this is good.

**Comment by HarshilShah1804** [comment]
You'll need to resolve the conflicts.

**Comment by himanshumahajan138** [comment]
Hi @HarshilShah1804 done,  I have resolved the conflicts could u please review once
