### PR TITLE
fix: handle variable scopes in promote_allocatable_to_nonallocatable pass

### LINKED ISSUE #9884: Handle `Realloc` inside Associate Block with `--fast`
MRE: 
```fortran
program mre_concat
    implicit none

    type :: string_t
        character(len=:), allocatable :: s
    end type string_t

    type(string_t), allocatable :: build_dirs(:)
    type(string_t) :: temp

    ! temp%s = "build"
    allocate(build_dirs(0))
    associate(xx => temp)
        build_dirs = [build_dirs, temp]
    end associate

    ! if (size(build_dirs) /= 1) error stop "Wrong size"
    ! if (build_dirs(1)%s /= "build") error stop "Wrong value"

    ! print *, "OK:", build_dirs(1)%s
end program mre_concat
```

LFortran Error:
```console
(lf) jinang_shah@JNSLAP:~/Desktop/lfortran$ lfortran c.f90 --realloc-lhs-arrays --fast
LCOMPILERS_ASSERT failed: /home/jinang_shah/Desktop/lfortran/src/libasr/codegen/llvm_utils.cpp
function create_gep2(), line number 1528 at 
ds_pointee_type == t
ERROR MESSAGE:
Type mismatch in create_gep2: GEP target type does not match pointer's pointee type. This would cause crashes in LLVM <= 8 constant folder. Target type: %array = type { %string_t*, i32, %dimension_descriptor*, i1, i32 }, Pointer pointee type: [0 x %string_t]
Traceback (most recent call last):
  Binary file "/home/jinang_shah/Desktop/lfortran/src/bin/lfortran", in _start
  File "./csu/../csu/libc-start.c", line 360, in __libc_start_main
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main
  File "/home/jinang_shah/Desktop/lfortran/src/bin/lfortran.cpp", line 2808, in main
    return main_app(argc, argv);
  File "/home/jinang_shah/Desktop/lfortran/src/bin/lfortran.cpp", line 2732, in main_app(int, char**)
    err = compile_src_to_object_file(arg_file, tmp_o, compiler_options.time_report, false,
  File "/home/jinang_shah/Desktop/lfortran/src/bin/lfortran.cpp", line 1249, in (anonymous namespace)::compile_src_to_object_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, LCompilers::CompilerOptions&, LCompilers::PassManager&, bool)
    res = fe.get_llvm3(*asr, lpm, diagnostics, lm, infile, &time_opt);
  File "/home/jinang_shah/Desktop/lfortran/src/lfortran/fortran_evaluator.cpp", line 380, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, LCompilers::LocationManager&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int*)
    compiler_options, run_fn, "", infile, lm);
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 18952, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::LocationManager&)
    v.visit_asr((ASR::asr_t&)asr);
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 361, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_asr(LCompilers::ASR::asr_t const&)
    void visit_asr(const asr_t &b) { visit_asr_t(b, self()); }
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 335, in void LCompilers::ASR::visit_asr_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::asr_t const&, LCompilers::ASRToLLVMVisitor&)
    case asrType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 362, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_unit(LCompilers::ASR::unit_t const&)
    void visit_unit(const unit_t &b) { visit_unit_t(b, self()); }
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 22, in void LCompilers::ASR::visit_unit_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::unit_t const&, LCompilers::ASRToLLVMVisitor&)
    case unitType::TranslationUnit: { v.visit_TranslationUnit((const TranslationUnit_t &)x); return; }
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 1585, in LCompilers::ASRToLLVMVisitor::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    visit_symbol(*item.second);
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 364, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 30, in void LCompilers::ASR::visit_symbol_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::symbol_t const&, LCompilers::ASRToLLVMVisitor&)
    case symbolType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5021, in LCompilers::ASRToLLVMVisitor::visit_Program(LCompilers::ASR::Program_t const&)
    this->visit_stmt(*x.m_body[i]);
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 381, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 92, in void LCompilers::ASR::visit_stmt_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::stmt_t const&, LCompilers::ASRToLLVMVisitor&)
    case stmtType::AssociateBlockCall: { v.visit_AssociateBlockCall((const AssociateBlockCall_t &)x); return; }
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9672, in LCompilers::ASRToLLVMVisitor::visit_AssociateBlockCall(LCompilers::ASR::AssociateBlockCall_t const&)
    this->visit_stmt(*(associate_block->m_body[i]));
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 381, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 54, in void LCompilers::ASR::visit_stmt_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::stmt_t const&, LCompilers::ASRToLLVMVisitor&)
    case stmtType::ReAlloc: { v.visit_ReAlloc((const ReAlloc_t &)x); return; }
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2020, in LCompilers::ASRToLLVMVisitor::visit_ReAlloc(LCompilers::ASR::ReAlloc_t const&)
    handle_allocated(x.m_args[0].m_a);
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 17518, in LCompilers::ASRToLLVMVisitor::handle_allocated(LCompilers::ASR::expr_t*)
    tmp = arr_descr->get_is_allocated_flag(tmp, arg);
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/codegen/llvm_array_utils.cpp", line 982, in LCompilers::LLVMArrUtils::SimpleCMODescriptor::get_is_allocated_flag(llvm::Value*, LCompilers::ASR::expr_t*)
    memory_holder = get_pointer_to_data(array_exp, array_type, array, llvm_utils->module);
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/codegen/llvm_array_utils.cpp", line 728, in LCompilers::LLVMArrUtils::SimpleCMODescriptor::get_pointer_to_data(LCompilers::ASR::expr_t*, LCompilers::ASR::ttype_t*, llvm::Value*, llvm::Module*)
    return llvm_utils->create_gep2(array_desc_type, arr, 0);
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/codegen/llvm_utils.cpp", line 1528, in LCompilers::LLVMUtils::create_gep2(llvm::Type*, llvm::Value*, int)
    LCOMPILERS_ASSERT_MSG(ds_pointee_type == t,
  File "./stdlib/./stdlib/abort.c", line 79, in abort
  File "./signal/../sysdeps/posix/raise.c", line 26, in raise
  File "./nptl/./nptl/pthread_kill.c", line 43, in pthread_kill
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in <invalid>
Abort: Signal SIGABRT (abort) received

Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by jinangshah21**
Fixes #9884

### CODE REVIEW

File: src/libasr/pass/promote_allocatable_to_nonallocatable.cpp [hunk 1]
```diff
@@ -17,13 +17,29 @@ class IsAllocatedCalled: public ASR::CallReplacerOnExpressionsVisitor<IsAllocate
...
+            SymbolTable* sym_scope = ASRUtils::symbol_parent_symtab(sym);
+            SymbolTable* scope = current_scope;
+            while (scope != nullptr) {
+                scope2var[scope].push_back(sym);
+                if (scope->get_counter() == sym_scope->get_counter()) {
+                    break;
+                }
+                scope = scope->parent;
+            }
+        }
```
Comment (certik) [inline src/libasr/pass/promote_allocatable_to_nonallocatable.cpp:34]: What does `scope2var` do and is this a good design to push a variable to all scopes?

Comment (jinangshah21) [reply src/libasr/pass/promote_allocatable_to_nonallocatable.cpp:34]: In `scope2var` we keep track of reallocated variables or variables that we can't convert from allocatable to non-allocatable type. And we store it with scope as index (I also don't know why can't we directly keep verctor of symbols that can't be converted). 

So in this PR I just pushed symbol to all scopes from current scope till we get to symbol's parent symbol table. For eg.: In `Associate_Block` we reallocate symbol from parent symbol table so I just pushed symbol to that scope also along with associateBlock scope.

Comment (certik) [reply src/libasr/pass/promote_allocatable_to_nonallocatable.cpp:34]: Thank you. Do you know why it has to be stored in every scope, not just the scope that actually has the symbol? Is it for some rewriting algorithm?
