### PR TITLE
fix: extract correct length in case of Integer BinOp as length of string

### LINKED ISSUE #10554: ASR Verify Pass Error in Intrinsic subroutine having strings with length as integer binop
MRE
```fortran
program demo_match
    implicit none
    integer, parameter :: maxarg = 512
    character(len=MAXARG*2-1) :: argument
    call get_command_argument(1, argument)
end program demo_match
```

LFortran
```console
ASR verify pass error: The symbol table was not found in the scope of `symtab`.

ASR verify pass error: Var::m_v `maxarg` cannot point outside of its symbol table
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/harshil-shah/lfortran/src/bin/lfortran", in _start
  File "./csu/../csu/libc-start.c", line 360, in __libc_start_main
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main
  File "/home/harshil-shah/lfortran/src/bin/lfortran.cpp", line 2809, in main
    return main_app(argc, argv);
  File "/home/harshil-shah/lfortran/src/bin/lfortran.cpp", line 2733, in main_app(int, char**)
    err = compile_src_to_object_file(arg_file, tmp_o, compiler_options.time_report, false,
  File "/home/harshil-shah/lfortran/src/bin/lfortran.cpp", line 1249, in (anonymous namespace)::compile_src_to_object_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, LCompilers::CompilerOptions&, LCompilers::PassManager&, bool)
    res = fe.get_llvm3(*asr, lpm, diagnostics, lm, infile, &time_opt);
  File "/home/harshil-shah/lfortran/src/lfortran/fortran_evaluator.cpp", line 380, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, LCompilers::LocationManager&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int*)
    compiler_options, run_fn, "", infile, lm);
  File "/home/harshil-shah/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 20480, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::LocationManager&)
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/home/harshil-shah/lfortran/src/libasr/pass/pass_manager.h", line 318, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    apply_passes(al, asr, _passes, pass_options, diagnostics, cummulative_time_taken_by_passes_in_microseconds);
LCompilersException: Verify failed in the pass: intrinsic_subroutine
```

### PR DESCRIPTION
**Pull request by HarshilShah1804**
Fixes #10554

### CODE REVIEW

File: src/libasr/pass/intrinsic_subroutines.h [hunk 1]
```diff
@@ -574,7 +574,7 @@ namespace GetCommandArgument {
             b.Call(_lfortran_get_command_argument_length_interface, call_args, int32)));
             
         if (overload_id & VALUE_BIT) {
-            fill_func_arg_sub("value", arg_types[optional_arg_index], Out);
+            fill_func_arg_sub("value", ASRUtils::duplicate_type_with_empty_dims(al, arg_types[optional_arg_index], ASR::array_physical_typeType::DescriptorArray, false), Out);
```
Comment (assem2002) [inline src/libasr/pass/intrinsic_subroutines.h]: I think `value` is always a character type -- can we use assumedLength ASR::string type (`character(*)`) ?

Comment (HarshilShah1804) [reply src/libasr/pass/intrinsic_subroutines.h]: Thanks @assem2002. I have updated the fix.
