### PR TITLE
fix: error in Handling Array Intrinsics with Explicit Shaped arrays

### LINKED ISSUE #5487: prima: Error in Handling Array Intrinsics with Explicit Shaped arrays
```fortran
program main
    real(4) :: xpt(1, 1)
    call rescue(xpt)
    contains
    subroutine rescue(xpt)
        real(4), intent(inout) :: xpt(:, :)
        print *, sqrt(sum(xpt**2, dim=1))
    end subroutine
end program
```
```console
$ gfortran a.f90 && ./a.out
   3.07638317E-16
$ lfortran a.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/harshita/Desktop/lfortran/src/bin/lfortran", in _start
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2685, in main
    return main_app(argc, argv);
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2624, in main_app(int, char**)
    err = compile_src_to_object_file(arg_file, tmp_o, false,
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 1045, in (anonymous namespace)::compile_src_to_object_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, LCompilers::CompilerOptions&, LCompilers::PassManager&)
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/home/harshita/Desktop/lfortran/src/lfortran/fortran_evaluator.cpp", line 382, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 10372, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    v.visit_asr((ASR::asr_t&)asr);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5186, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_asr(LCompilers::ASR::asr_t const&)
    void visit_asr(const asr_t &b) { visit_asr_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5162, in void LCompilers::ASR::visit_asr_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::asr_t const&, LCompilers::ASRToLLVMVisitor&)
    case asrType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5187, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_unit(LCompilers::ASR::unit_t const&)
    void visit_unit(const unit_t &b) { visit_unit_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 4892, in void LCompilers::ASR::visit_unit_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::unit_t const&, LCompilers::ASRToLLVMVisitor&)
    case unitType::TranslationUnit: { v.visit_TranslationUnit((const TranslationUnit_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 988, in LCompilers::ASRToLLVMVisitor::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    visit_symbol(*item.second);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5189, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 4900, in void LCompilers::ASR::visit_symbol_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::symbol_t const&, LCompilers::ASRToLLVMVisitor&)
    case symbolType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3253, in LCompilers::ASRToLLVMVisitor::visit_Program(LCompilers::ASR::Program_t const&)
    visit_procedures(x);
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4288, in void LCompilers::ASRToLLVMVisitor::visit_procedures<LCompilers::ASR::Program_t>(LCompilers::ASR::Program_t const&)
    visit_Function(*s);
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4044, in LCompilers::ASRToLLVMVisitor::visit_Function(LCompilers::ASR::Function_t const&)
    generate_function(x);
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4240, in LCompilers::ASRToLLVMVisitor::generate_function(LCompilers::ASR::Function_t const&)
    this->visit_stmt(*x.m_body[i]);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5206, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 4940, in void LCompilers::ASR::visit_stmt_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::stmt_t const&, LCompilers::ASRToLLVMVisitor&)
    case stmtType::Print: { v.visit_Print((const Print_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 8109, in LCompilers::ASRToLLVMVisitor::visit_Print(LCompilers::ASR::Print_t const&)
    handle_print(x.m_text, nullptr);
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 8554, in LCompilers::ASRToLLVMVisitor::handle_print(LCompilers::ASR::expr_t*, llvm::Value*)
    compute_fmt_specifier_and_arg(fmt, args, arg, arg->base.loc);
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 8268, in LCompilers::ASRToLLVMVisitor::compute_fmt_specifier_and_arg(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, std::vector<llvm::Value*, std::allocator<llvm::Value*> >&, LCompilers::ASR::expr_t*, LCompilers::Location const&, bool)
    this->visit_expr_wrapper(v, true);
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5539, in LCompilers::ASRToLLVMVisitor::visit_expr_wrapper(LCompilers::ASR::expr_t*, bool)
    this->visit_expr(*x);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5254, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_expr(LCompilers::ASR::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5033, in void LCompilers::ASR::visit_expr_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::expr_t const&, LCompilers::ASRToLLVMVisitor&)
    case exprType::StringFormat: { v.visit_StringFormat((const StringFormat_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 10313, in LCompilers::ASRToLLVMVisitor::visit_StringFormat(LCompilers::ASR::StringFormat_t const&)
    compute_fmt_specifier_and_arg(fmt, args, x.m_args[i], x.base.base.loc,true);
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 8540, in LCompilers::ASRToLLVMVisitor::compute_fmt_specifier_and_arg(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, std::vector<llvm::Value*, std::allocator<llvm::Value*> >&, LCompilers::ASR::expr_t*, LCompilers::Location const&, bool)
    visit_expr(*array_size_expr);
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5254, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_expr(LCompilers::ASR::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/libasr/../libasr/asr.h", line 5045, in void LCompilers::ASR::visit_expr_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::expr_t const&, LCompilers::ASRToLLVMVisitor&)
    case exprType::ArraySize: { v.visit_ArraySize((const ArraySize_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 10116, in LCompilers::ASRToLLVMVisitor::visit_ArraySize(LCompilers::ASR::ArraySize_t const&)
    visit_ArraySizeUtil(x.m_v, x.m_type, x.m_dim, x.m_value);
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 10054, in LCompilers::ASRToLLVMVisitor::visit_ArraySizeUtil(LCompilers::ASR::expr_t*, LCompilers::ASR::ttype_t*, LCompilers::ASR::expr_t*, LCompilers::ASR::expr_t*)
    tmp = arr_descr->get_array_size(llvm_arg, llvm_dim, output_kind, dim_kind);
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/llvm_array_utils.cpp", line 709, in LCompilers::LLVMArrUtils::SimpleCMODescriptor::get_array_size(llvm::Value*, llvm::Value*, int, int)
    llvm::Value* dim_des_val = this->get_pointer_to_dimension_descriptor_array(array);
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/llvm_array_utils.cpp", line 217, in LCompilers::LLVMArrUtils::SimpleCMODescriptor::get_pointer_to_dimension_descriptor_array(llvm::Value*, bool)
    llvm::Value* dim_des_arr_ptr = llvm_utils->create_gep(arr, 2);
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/llvm_utils.cpp", line 1544, in LCompilers::LLVMUtils::create_gep(llvm::Value*, int)
    return LLVMUtils::CreateGEP(ds, idx_vec);
AssertFailed: t->isPointerTy()
```

### PR DESCRIPTION
**Pull request by Pranavchiku**
Fixes #5487.

### CODE REVIEW

**Comment by Pranavchiku** [comment]
Any fix in `array_op` needs a lot of debugging to understand "origin" of error.

File: src/libasr/pass/pass_utils.cpp [hunk 1]
```diff
@@ -359,6 +363,7 @@ namespace LCompilers {
             vars.reserve(al, n_vars);
             for (int i = 1; i <= n_vars; i++) {
                 std::string idx_var_name = "__" + std::to_string(i) + suffix;
+                idx_var_name = current_scope->get_unique_name(idx_var_name, false);
```
Comment (certik) [inline src/libasr/pass/pass_utils.cpp:366]: What was the problem --- was the variable name previously shadowed by some other variable?

**Review by certik — APPROVED** [review]
I think the change is fine. What exactly was the problem?

There are a lot of changes in the LLVM output, but it seems it' just renumbering.
