### PR TITLE
semantics: fix string concatenation for CHARACTER*1 dummies

### LINKED ISSUE #9263: codegen: string concat uses actual length instead of declared length for CHARACTER*1
## Summary

When a `CHARACTER*1` (or `CHARACTER`) dummy argument receives a longer string literal, string concatenation uses the actual passed length instead of the declared length, causing buffer overflows.

## MRE Branch

**Branch**: [`issue/string-concat-char1-overflow`](https://github.com/krystophny/lfortran/tree/issue/string-concat-char1-overflow)

**Test file**: `integration_tests/string_concat_char1_01.f90`

```fortran
program string_concat_char1_01
    implicit none
    call test_concat('Upper', 'Diag')
    print *, "PASS"
contains
    subroutine test_concat(a, b)
        character, intent(in) :: a, b  ! Both are CHARACTER*1
        character(2) :: result
        ! a should be 'U', b should be 'D', result should be 'UD'
        ! Bug: uses len('Upper')=5 + len('Diag')=4 = 9 chars
        result = a // b
        if (result /= 'UD') error stop "result should be 'UD'"
    end subroutine
end program
```

**Results**:
- gfortran: `len(a)=1, len(b)=1, result='UD'` → **PASS**
- lfortran: `malloc(): corrupted top size` → **CRASH**

### 1. ASR is correct

The ASR shows CHARACTER*1 with explicit constant length:
```
a: (Variable ... (String 1 (IntegerConstant 1 ...) ExpressionLength DescriptorString))
b: (Variable ... (String 1 (IntegerConstant 1 ...) ExpressionLength DescriptorString))
```

### 2. `get_string_length()` has correct logic

In `asr_to_llvm.cpp:669-672`:
```cpp
if(str->m_len && ASR::is_a<ASR::IntegerConstant_t>(*str->m_len)){
    ASR::IntegerConstant_t* len = ASR::down_cast<ASR::IntegerConstant_t>(str->m_len);
    return llvm::ConstantInt::get(context, llvm::APInt(64, len->m_n));
}
```

### 3. The bug: `_lcompilers_stringconcat` uses runtime lengths

In `intrinsic_functions.h:5187-5193`:
```cpp
fill_func_arg("s1", b.String(nullptr, ASR::AssumedLength))
fill_func_arg("s2", b.String(nullptr, ASR::AssumedLength))
// Result length computed from runtime StringLen:
b.String(b.Add(b.StringLen(args[0]), b.StringLen(args[1])), ASR::ExpressionLength)
```

The `_lcompilers_stringconcat` function uses `AssumedLength` for parameters, so it reads lengths from runtime descriptors. When called from code like `result = a // b`, the descriptors for `a` and `b` still contain their original lengths (5 and 4 from 'Upper' and 'Diag') instead of the declared CHARACTER*1 length (1).

### 4. Missing: descriptor length adjustment in call setup

When passing strings to subroutines, `convert_call_args()` doesn't adjust the string descriptor length to match the dummy argument's declared length. The original descriptor (with length 5) is passed directly, instead of creating a view with length 1.

## Related Issues

- #8620 - argument strings have issue with variable length (same underlying descriptor length mismatch)
- #6892 - Progress: Refactor string and string array (LLVM backend) - ongoing string handling refactoring
- #5801 - array of characters doesn't do actual stringcopying (pointer vs copy semantics)
- #346 - Implement Assumed Length (foundational assumed-length character support)

## Impact

This blocks running LAPACK test suite. LAPACK code pattern:
```fortran
CALL STRTRI('Upper', 'Non-unit', N, A, LDA, INFO)

SUBROUTINE STRTRI(UPLO, DIAG, ...)
  CHARACTER UPLO, DIAG  ! CHARACTER*1
  NB = ILAENV(1, 'STRTRI', UPLO // DIAG, N, -1, -1, -1)  ! Overflow here
END SUBROUTINE
```

## Proposed Fix

Two potential approaches:

1. **At call site**: When passing a string to a CHARACTER(n) dummy, create a new descriptor with `len = min(actual_len, n)` and same data pointer

2. **In `_lcompilers_stringconcat`**: Instead of using `AssumedLength`, compute result length from the ASR type's declared length when it's a constant

The first approach is more general as it would fix all operations on the dummy argument, not just concatenation.

### PR DESCRIPTION
**Pull request by krystophny**
## Summary

Fixes #9263

Fix string concatenation buffer overflow when concatenating CHARACTER*1 (declared with single character specifier) arguments.

**Before**: `result = a // b` with CHARACTER*1 arguments would use `len(a)` which returned the full string length passed by caller (e.g., 5 for "Upper"), causing buffer overflow.

**After**: Use `type->m_len` (declared length = 1) for allocation size instead of `ASR::StringLen` which returns actual string length.

## Changes

- `libasr/pass/intrinsic_functions.h`: Use declared length from type for CHARACTER*1 dummies in StringConcat

## Test Plan

- [x] `string_91.f90` - test concatenation with CHARACTER*1 dummies
- Reference test `string_03` updated to reflect correct behavior

### CODE REVIEW

**Comment by certik** [comment]
Conflicts have to be resolved.

File: src/libasr/pass/intrinsic_functions.h [hunk 1]
```diff
@@ -5172,54 +5172,66 @@ namespace StringConcat {
...
-        
         declare_basic_variables(intrinsic_fn_name)
 
-        /* Args */
+        ASR::String_t* s1_type = ASR::down_cast<ASR::String_t>(ASRUtils::extract_type(arg_types[0]));
+        ASR::String_t* s2_type = ASR::down_cast<ASR::String_t>(ASRUtils::extract_type(arg_types[1]));
+
+        // Use declared type length (m_len) if known, else fall back to runtime StringLen
+        // All lengths use int32 to match StringLen return type
+        ASR::expr_t* s1_len_arg = s1_type->m_len
```
Comment (assem2002) [inline src/libasr/pass/intrinsic_functions.h]: let's Use the `len` expression only when it's a compile-time expression -- use utility `ASR::is_value_constant`.
If it's an expression that needs runtime evaluation (e.g. function call) -- it wouldn't be the behavior we want (calling the function again), though it fortran a runtime length expression should be pure -- but let's just not do that.

File: src/libasr/pass/intrinsic_functions.h [hunk 2]
```diff
@@ -5172,54 +5172,66 @@ namespace StringConcat {
...
-        /* Body */
-        /*
-            function lcompilers_stringconcat(s1, s2) result(concat_result)
-                character(*) :: s1
-                character(*) :: s2
-                character(len(s1) + len(s2)) :: concat_result
-                concat_result(1 : len(s1)) = s1
-                concat_result(len(s1) + 1 : len(concat_result)) = s2
-            end function
-        */
```
Comment (assem2002) [inline src/libasr/pass/intrinsic_functions.h:5205]: can we keep that?
It needs modification btw according to the new signature.

File: src/libasr/pass/intrinsic_functions.h [hunk 3]
```diff
@@ -5172,54 +5172,66 @@ namespace StringConcat {
 
     
     inline ASR::expr_t* instantiate_StringConcat(Allocator &al, const Location &loc,
-        SymbolTable *scope, Vec<ASR::ttype_t*>& /*arg_types*/, ASR::ttype_t* /*return_type*/,
+        SymbolTable *scope, Vec<ASR::ttype_t*>& arg_types, ASR::ttype_t* /*return_type*/,
         Vec<ASR::call_arg_t>& new_args, int64_t /*overload_id*/){
+        // Fix for #9263: Pass explicit lengths instead of using descriptor lengths
+        // When CHARACTER*1 dummy receives longer actual (e.g., 'Upper'), the descriptor
+        // still carries the actual argument length (5), not the declared length (1).
+        // StringLen reads from descriptor, giving wrong result. Pass declared lengths explicitly.
```
Comment (assem2002) [inline src/libasr/pass/intrinsic_functions.h]: let's remove this.

File: src/libasr/pass/intrinsic_functions.h (hunk 1 above)
Comment (krystophny) [reply src/libasr/pass/intrinsic_functions.h]: done!

File: src/libasr/pass/intrinsic_functions.h (hunk 2 above)
Comment (krystophny) [reply src/libasr/pass/intrinsic_functions.h:5205]: kept and modified for new 4-arg signature

File: src/libasr/pass/intrinsic_functions.h (hunk 3 above)
Comment (krystophny) [reply src/libasr/pass/intrinsic_functions.h]: done!

**Comment by certik** [comment]
Not sure what is going on with the CI failure:
```
[100%] Project compiled successfully.
++ fpm --compiler=lfortran test --flag '--cpp --realloc-lhs-arrays'
[  0%]                  testdrive.F90
[  9%]                  testdrive.F90  done.
[  9%]                    libtoml-f.a
[ 18%]                    libtoml-f.a  done.
[ 18%]                      utils.f90
[ 27%]                      utils.f90  done.
[ 27%]                      build.f90
[ 36%]                      build.f90  done.
[ 36%]                      lexer.f90
[ 45%]                      lexer.f90  done.
[ 45%]                     parser.f90
[ 54%]                     parser.f90  done.
[ 54%]                       sort.f90
[ 63%]                       sort.f90  done.
[ 63%]                      json2toml
[ 72%]                      json2toml  done.
[ 72%]                      toml2json
[ 81%]                      toml2json  done.
[ 81%]                       main.f90
Error: Process completed with exit code 143.
```
Almost looks like a segfault in LFortran itself.

**Comment by certik** [comment]
Ok, the failure is real. It's either caused by this PR, or (hopefully not) by a failure in main.

**Comment by krystophny** [comment]
> Ok, the failure is real. It's either caused by this PR, or (hopefully not) by a failure in main.

Yes this was some infinite recursion. Hope this is resolved now.

**Review by certik — APPROVED** [review]
