### PR TITLE
fix: handle load of class and struct member in `deallocate`

### LINKED ISSUE #7648: Handle class instance member in `deallocate` properly
MRE:
```fortran 
program test_prune
    implicit none

    type :: toml_value
        character(len=:), allocatable :: kry
    end type toml_value

    class(toml_value), allocatable :: val

    allocate(val)
    val%kry = 'Some string'
    if (allocated(val%kry)) then
        deallocate(val%kry)
    end if
end program test_prune
```

LFortran Error:
```console
    void visit_unit(const unit_t &b) { visit_unit_t(b, self()); }
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 22, in void LCompilers::ASR::visit_unit_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::unit_t const&, LCompilers::ASRToLLVMVisitor&)
    case unitType::TranslationUnit: { v.visit_TranslationUnit((const TranslationUnit_t &)x); return; }
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 1027, in LCompilers::ASRToLLVMVisitor::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    visit_symbol(*item.second);
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 345, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 30, in void LCompilers::ASR::visit_symbol_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::symbol_t const&, LCompilers::ASRToLLVMVisitor&)
    case symbolType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3621, in LCompilers::ASRToLLVMVisitor::visit_Program(LCompilers::ASR::Program_t const&)
    this->visit_stmt(*x.m_body[i]);
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 361, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 69, in void LCompilers::ASR::visit_stmt_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::stmt_t const&, LCompilers::ASRToLLVMVisitor&)
    case stmtType::If: { v.visit_If((const If_t &)x); return; }
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 6922, in LCompilers::ASRToLLVMVisitor::visit_If(LCompilers::ASR::If_t const&)
    llvm_utils->create_if_else(tmp, [&]() {
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/../libasr/codegen/llvm_utils.h", line 429, in void LCompilers::LLVMUtils::create_if_else<LCompilers::ASRToLLVMVisitor::visit_If(LCompilers::ASR::If_t const&)::'lambda'(), LCompilers::ASRToLLVMVisitor::visit_If(LCompilers::ASR::If_t const&)::'lambda0'()>(llvm::Value*, LCompilers::ASRToLLVMVisitor::visit_If(LCompilers::ASR::If_t const&)::'lambda'(), LCompilers::ASRToLLVMVisitor::visit_If(LCompilers::ASR::If_t const&)::'lambda0'())
    if_block();
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 6924, in LCompilers::ASRToLLVMVisitor::visit_If(LCompilers::ASR::If_t const&)::'lambda'()::operator()() const
    this->visit_stmt(*x.m_body[i]);
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 361, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 58, in void LCompilers::ASR::visit_stmt_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::stmt_t const&, LCompilers::ASRToLLVMVisitor&)
    case stmtType::ExplicitDeallocate: { v.visit_ExplicitDeallocate((const ExplicitDeallocate_t &)x); return; }
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 1482, in LCompilers::ASRToLLVMVisitor::visit_ExplicitDeallocate(LCompilers::ASR::ExplicitDeallocate_t const&)
    visit_Deallocate(x);
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 1342, in void LCompilers::ASRToLLVMVisitor::visit_Deallocate<LCompilers::ASR::ExplicitDeallocate_t>(LCompilers::ASR::ExplicitDeallocate_t const&)
    this->visit_expr_wrapper(sm->m_v);
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 6425, in LCompilers::ASRToLLVMVisitor::visit_expr_wrapper(LCompilers::ASR::expr_t*, bool, bool)
    this->visit_expr(*x);
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 413, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_expr(LCompilers::ASR::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 175, in void LCompilers::ASR::visit_expr_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::expr_t const&, LCompilers::ASRToLLVMVisitor&)
    case exprType::Var: { v.visit_Var((const Var_t &)x); return; }
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 8182, in LCompilers::ASRToLLVMVisitor::visit_Var(LCompilers::ASR::Var_t const&)
    fetch_var(v);
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 8098, in LCompilers::ASRToLLVMVisitor::fetch_var(LCompilers::ASR::Variable_t*)
    fetch_ptr(x);
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 8046, in LCompilers::ASRToLLVMVisitor::fetch_ptr(LCompilers::ASR::Variable_t*)
    tmp = llvm_utils->CreateLoad(tmp);
AssertFailed: t->isPointerTy()
```

### PR DESCRIPTION
**Pull request by jinangshah21**
Fixes #7648

### CODE REVIEW

File: src/libasr/codegen/asr_to_llvm.cpp [hunk 1]
```diff
@@ -1339,30 +1339,23 @@ class ASRToLLVMVisitor : public ASR::BaseVisitor<ASRToLLVMVisitor>
...
-                            ASR::down_cast<ASR::StructType_t>(new_caller_type)->m_derived_type);
-                        if (ASRUtils::is_class_type(new_caller_type)) {
-                            dt = llvm_utils->CreateLoad2(dt_type->getPointerTo(), llvm_utils->create_gep(dt, 1));
-                        }
-                    }
+                struct_sym = ASRUtils::symbol_get_past_external(
+                    ASR::down_cast<ASR::StructType_t>(ASRUtils::extract_type(caller_type))->m_derived_type);
+                if (ASRUtils::is_class_type(ASRUtils::extract_type(caller_type))) {
+                    dt = llvm_utils->CreateLoad2(dt_type->getPointerTo(), llvm_utils->create_gep(dt, 1));
                 }
```
Comment (kmr-srbh) [inline src/libasr/codegen/asr_to_llvm.cpp:1359]:
```suggestion
                if (ASRUtils::is_class_type(ASRUtils::extract_type(caller_type))) {
                    dt = llvm_utils->CreateLoad2(dt_type->getPointerTo(), llvm_utils->create_gep(dt, 1));
                } else {
                    dt = llvm_utils->CreateLoad2(dt_type->getPointerTo(), dt);
                }
```

We need to do this, else nested cases like below fail:

```fortran
program test_prune
   implicit none

   type :: toml
      integer, allocatable :: kry(:)
   end type

   type :: toml_value
      type(toml), allocatable :: v
   end type toml_value

   type(toml_value), allocatable :: val

   allocate(val)
   allocate(val%v)
   allocate(val%v%kry(2))

   print *, allocated(val%v%kry)

   if (allocated(val%v%kry)) then
      print *, "allocated"
      deallocate(val%v%kry)
   end if
end program test_prune
```
```console
code generation error: asr_to_llvm: module failed verification. Error:
Stored value type does not match pointer operand type!
  store %toml** %57, %toml* %58, align 8
 %toml = type <{ %array* }>
```

Comment (kmr-srbh) [reply src/libasr/codegen/asr_to_llvm.cpp:1359]: The PR got merged while I was writing this. @jinangshah21 It would be great if you could address it in a different PR.

Comment (jinangshah21) [reply src/libasr/codegen/asr_to_llvm.cpp:1359]: Thanks! I will do it.
