### PR TITLE
WASM: Fix visit_ArrayBound()

### LINKED ISSUE #2170: WASM: Bug in visit_ArrayBound()
```fortran
(lf) ubaid@ubaids-MacBook-Pro lfortran % cat examples/expr2.f90
program expr2
implicit none

integer(8) :: x(4)

print *, lbound(x, dim=1), ubound(x, dim=1)

end program
```
```bash
(lf) ubaid@ubaids-MacBook-Pro lfortran % gfortran examples/expr2.f90 
(lf) ubaid@ubaids-MacBook-Pro lfortran % ./a.out 
           1           4
```
```bash
(lf) ubaid@ubaids-MacBook-Pro lfortran % lfortran_in_main examples/expr2.f90 
1 4
```
```bash
(lf) ubaid@ubaids-MacBook-Pro lfortran % lfortran_in_main examples/expr2.f90 --backend wasm
code generation error: ArrayBound: Kind 4 only supported currently


Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
fixes #2170

### CODE REVIEW

File: integration_tests/array_bound_2.f90 [hunk 1]
```diff
@@ -0,0 +1,8 @@
+program array_bound_2
+    implicit none
+
+    integer(8) :: x(4)
+
+    print *, lbound(x, dim=1), ubound(x, dim=1)
```
Comment (certik) [inline integration_tests/array_bound_2.f90:6]: It would be good to also add actual checks with "if -> error stop" style here, to ensure things work.

**Review by certik — APPROVED** [review]
Otherwise it looks good.
