### PR TITLE
fix: don't use m_value in initializing character arrays using array reshape

### LINKED ISSUE #8113: Segmentation fault when using character array
I hope this is not a duplicate issue.

Compiling the following minimal Fortran program with `lfortran` causes a segmentation fault:

**Code (test.f90)**:

```fortran
program test
   character(2), parameter :: arr(1:2,1:2)=reshape(['a ', '1 ', 'b ', '2 '], [2,2])
   ! print*, arr
end program
```

**Command**:

```bash
lfortran test.f90 -g --debug-with-line-column --verbose
```

**Output**:

```
Segmentation fault (core dumped)
```

**Tested with**:

```
lfortran --version
LFortran version: 0.54.0
Platform: Linux
LLVM: 19.1.1
Default target: x86_64-conda-linux-gnu
LSP Version: 3.17.0
JSON_RPC Version: 2.0
```

Best
Ali

### PR DESCRIPTION
**Pull request by HarshilShah1804**
Fixes #8113

### CODE REVIEW

File: integration_tests/arrays_constructor_01.f90 [hunk 1]
```diff
@@ -13,4 +13,8 @@ program arrays_constructor_01
     print *, [str(i+1:i+3), "aaa"]
     arr = [MyClass :: v1, v2, v3]
     print *, arr
+
+    character(4), parameter :: arr1(1:2,1:2)=reshape(['a ', '1 ', 'b ', '2 '], [2,2])
```
Comment (kmr-srbh) [inline integration_tests/arrays_constructor_01.f90]: Please move this declaration above all print statements.

**Review by kmr-srbh — APPROVED** [review]

File: integration_tests/arrays_constructor_01.f90 (hunk 1 above)
Comment (HarshilShah1804) [reply integration_tests/arrays_constructor_01.f90]: Oh! right. Thanks. I have made the changes.
