### PR TITLE
Fix 2 stdlib runtime bugs

### LINKED ISSUE #10664: Bug: sum() on a parameter complex array ignores the mask argument
```fortran
program mre_complex_sum_mask
! Bug: sum() on a parameter complex array ignores the mask argument.
! LFortran returns sum of ALL elements instead of only masked ones.
implicit none
integer, parameter :: sp = kind(1.0)
complex(sp), parameter :: x(3) = [(1.0, 0.0), (-2.0, 0.0), (3.0, 0.0)]
logical :: m(3) = [.true., .false., .true.]
complex(sp) :: s
s = sum(x, m)
! Expected: (4.0, 0.0) = (1,0) + (3,0)
! LFortran:  (2.0, 0.0) = (1,0) + (-2,0) + (3,0)  -- mask ignored
print *, s
if (abs(s - (4.0, 0.0)) > 1.0e-5) error stop 1
end program
```
Gives:
```console
$ lfortran mre_complex_sum_mask.f90
(2.00000000,0.00000000)
ERROR STOP 1
$ flang mre_complex_sum_mask.f90 && ./a.out
 (4.,0.)
```

### PR DESCRIPTION
**Pull request by jinangshah21**
Fixes #10664

### CODE REVIEW

**Comment by jinangshah21** [comment]
For https://github.com/lfortran/lfortran/pull/10665/commits/568620a7934e6dca31de907a5fa81b62befe9f9e, 
Original fortran code:
```fortran
program file_open_07
    integer :: u, ios
    character(len=*), parameter :: filename = "file_open_07_err.txt"

    open(newunit=u, file=filename, status="old", iostat=ios, err=100)
    print *, "opened"
    close(u)
    error stop 1

100 continue
    if (ios == 0) error stop 2
end program
```

Transformed code:
```fortran
program file_open_07
    integer :: u, ios
    character(len=*), parameter :: filename = "file_open_07_err.txt"

    open(newunit=u, file=filename, status="old", iostat=ios, err=100)
    if (ios /= 0) go to 100    !!!! This line is added
    print *, "opened"
    close(u)
    error stop 1

100 continue
    if (ios == 0) error stop 2
end program
```

File: integration_tests/sum_03.f90 [hunk 1]
```diff
@@ -0,0 +1,10 @@
+program sum_03
+    use iso_fortran_env, only: sp => real32
+    complex(sp), parameter :: x_sum_mask(3) = [(1.0_sp, 0.0_sp), (-2.0_sp, 0.0_sp), (3.0_sp, 0.0_sp)]
+    logical :: sum_mask(3)
+    complex(sp) :: sum_masked_res
+
+    sum_mask = [.true., .false., .true.]
+    sum_masked_res = sum(x_sum_mask, sum_mask)
```
Comment (certik) [inline integration_tests/sum_03.f90:9]: The fix below skips evaluation at compile time. While we are at this, let's also test compile time evaluation of this, using:
```fortran
    complex(sp), parameter :: x_sum_mask(3) = [(1.0_sp, 0.0_sp), (-2.0_sp, 0.0_sp), (3.0_sp, 0.0_sp)]
    logical, parameter :: sum_mask(3) = [.true., .false., .true.]
    complex(sp), parameter :: sum_masked_res = sum(x_sum_mask, sum_mask)
```
And ensure it works.

Comment (jinangshah21) [reply integration_tests/sum_03.f90:9]: Added.
Compile time evaluation:
```clojure
(Assignment
                        (Var 2 sum_masked_res_2)
                        (IntrinsicArrayFunction
                            Sum
                            [(ArrayPhysicalCast
                                (Var 2 x_sum_mask)
                                FixedSizeArray
                                DescriptorArray
                                (Array
                                    (Complex 4)
                                    [((IntegerConstant 1 (Integer 4) Decimal)
                                    (IntegerConstant 3 (Integer 4) Decimal))]
                                    DescriptorArray
                                )
                                ()
                            )
                            (ArrayPhysicalCast
                                (Var 2 sum_mask_2)
                                FixedSizeArray
                                DescriptorArray
                                (Array
                                    (Logical 4)
                                    [((IntegerConstant 1 (Integer 4) Decimal)
                                    (IntegerConstant 3 (Integer 4) Decimal))]
                                    DescriptorArray
                                )
                                ()
                            )]
                            2
                            (Complex 4)
                            (ComplexConstant
                                4.000000
                                0.000000
                                (Complex 4)
                            )
                        )
                        ()
                        .false.
                        .false.
                    )
```
