### PR TITLE
Fix : Set arrayPhysicalType of Array constructor to desciptorArray when any arg doesn't have compile time size

### LINKED ISSUE #5928: bug : created temp array variable (fixedSize) for `reshape` raise error
towards #5929 
MRE
```fortran
module testing_module
  contains 
  subroutine another_func(q)
    integer, intent(in) :: q(:,:)
    integer :: anew(16)
    anew = reshape([q], [16])
  end subroutine another_func
end module

program pp
  use testing_module
integer :: q(4,4)
call another_func(q)
end program pp
```

```Console
  Binary file "/home/assem/lfortran_test/lfortran/src/bin/lfortran", in _start
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main
  File "/home/assem/lfortran_test/lfortran/src/bin/lfortran.cpp", line 2733, in main
    return main_app(argc, argv);
  File "/home/assem/lfortran_test/lfortran/src/bin/lfortran.cpp", line 2671, in main_app(int, char**)
    err = compile_src_to_object_file(arg_file, tmp_o, false,
  File "/home/assem/lfortran_test/lfortran/src/bin/lfortran.cpp", line 1051, in (anonymous namespace)::compile_src_to_object_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, LCompilers::CompilerOptions&, LCompilers::PassManager&)
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/home/assem/lfortran_test/lfortran/src/lfortran/fortran_evaluator.cpp", line 382, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/home/assem/lfortran_test/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 10460, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    v.visit_asr((ASR::asr_t&)asr);
  File "/home/assem/lfortran_test/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 316, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_asr(LCompilers::ASR::asr_t const&)
    void visit_asr(const asr_t &b) { visit_asr_t(b, self()); }
  File "/home/assem/lfortran_test/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 292, in void LCompilers::ASR::visit_asr_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::asr_t const&, LCompilers::ASRToLLVMVisitor&)
    case asrType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/home/assem/lfortran_test/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 317, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_unit(LCompilers::ASR::unit_t const&)
    void visit_unit(const unit_t &b) { visit_unit_t(b, self()); }
  File "/home/assem/lfortran_test/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 22, in void LCompilers::ASR::visit_unit_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::unit_t const&, LCompilers::ASRToLLVMVisitor&)
    case unitType::TranslationUnit: { v.visit_TranslationUnit((const TranslationUnit_t &)x); return; }
  File "/home/assem/lfortran_test/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 975, in LCompilers::ASRToLLVMVisitor::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    visit_symbol(*mod);
  File "/home/assem/lfortran_test/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 319, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/assem/lfortran_test/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 31, in void LCompilers::ASR::visit_symbol_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::symbol_t const&, LCompilers::ASRToLLVMVisitor&)
    case symbolType::Module: { v.visit_Module((const Module_t &)x); return; }
  File "/home/assem/lfortran_test/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3194, in LCompilers::ASRToLLVMVisitor::visit_Module(LCompilers::ASR::Module_t const&)
    visit_procedures(x);
  File "/home/assem/lfortran_test/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4331, in void LCompilers::ASRToLLVMVisitor::visit_procedures<LCompilers::ASR::Module_t>(LCompilers::ASR::Module_t const&)
    visit_Function(*s);
  File "/home/assem/lfortran_test/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4087, in LCompilers::ASRToLLVMVisitor::visit_Function(LCompilers::ASR::Function_t const&)
    generate_function(x);
  File "/home/assem/lfortran_test/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4280, in LCompilers::ASRToLLVMVisitor::generate_function(LCompilers::ASR::Function_t const&)
    define_function_entry(x);
  File "/home/assem/lfortran_test/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4200, in LCompilers::ASRToLLVMVisitor::define_function_entry(LCompilers::ASR::Function_t const&)
    declare_local_vars(x);
  File "/home/assem/lfortran_test/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4059, in void LCompilers::ASRToLLVMVisitor::declare_local_vars<LCompilers::ASR::Function_t>(LCompilers::ASR::Function_t const&)
    declare_vars(x);
  File "/home/assem/lfortran_test/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3966, in void LCompilers::ASRToLLVMVisitor::declare_vars<LCompilers::ASR::Function_t>(LCompilers::ASR::Function_t const&, bool)
    process_Variable(var_sym, x, debug_arg_count);
  File "/home/assem/lfortran_test/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3696, in void LCompilers::ASRToLLVMVisitor::process_Variable<LCompilers::ASR::Function_t const>(LCompilers::ASR::symbol_t*, LCompilers::ASR::Function_t const&, unsigned int&)
    type = llvm_utils->get_type_from_ttype_t(
AssertFailed: ASRUtils::is_fixed_size_array(v_type->m_dims, v_type->n_dims)

```

### PR DESCRIPTION
**Pull request by assem2002**
fixes #5928 
towards #5929

### CODE REVIEW

File: integration_tests/arrays_reshape_19.f90 [hunk 1]
```diff
@@ -0,0 +1,17 @@
+module arrays_reshape_19_mod
+    contains 
+    subroutine another_func(q)
+      integer, intent(in) :: q(:,:)
+      integer :: anew(18)
+      anew = reshape([0,q,17], [18])
+      print *, anew
```
[the remark this answers is not in the document]
Comment (assem2002) [reply integration_tests/arrays_reshape_19.f90:7]: I don't know if this is another issue or not.

[the remark this answers is not in the document]
Comment (assem2002) [reply integration_tests/arrays_reshape_19.f90:7]: the same issue fail it main, opened issue #5931

File: integration_tests/arrays_reshape_19.f90 [hunk 2]
```diff
@@ -0,0 +1,17 @@
+module arrays_reshape_19_mod
+    contains 
+    subroutine another_func(q)
+      integer, intent(in) :: q(:,:)
+      integer :: anew(18)
+      anew = reshape([0,q,17], [18])
```
Comment (gxyd) [inline integration_tests/arrays_reshape_19.f90:6]: I'm looking at the ASR generated for the LHS (focusing on the `ArrayConstructor` argument of `reshape`), which looks like:
```clj
                                            (ArrayConstructor
                                                [(IntegerConstant 0 (Integer 4) Decimal)
                                                (Var 3 q)
                                                (IntegerConstant 17 (Integer 4) Decimal)]
                                                (Array
                                                    (Integer 4)
                                                    [((IntegerConstant 1 (Integer 4) Decimal)
                                                    (IntegerConstant 3 (Integer 4) Decimal))]
                                                    DescriptorArray
                                                )
                                                ()
                                                ColMajor
                                            )
```

The `ttype` is something I'm curious about, if you see that the dimension of `Array` ttype is:
```clj
                                                [((IntegerConstant 1 (Integer 4) Decimal)
                                                    (IntegerConstant 3 (Integer 4) Decimal))]
```
the length is mentioned to be `3`, which I'm not sure if it's correct. Do we usually set the `length` argument of `dimension` to be the count of elements, i.e. `[0, q, 17]`-> 3 or should it be the size of each of the element individually?

Is that supposed to be a separate bug?

File: src/lfortran/semantics/ast_common_visitor.h [hunk 3]
```diff
@@ -4867,6 +4867,7 @@ class CommonVisitor : public AST::BaseVisitor<Derived> {
         check_if_type_spec_has_asterisk(type);
 
         bool implied_do_loops_present = false;
+        bool use_descriptorArray = false; // Set to true if any argument has no fixed size (array arguments).
```
Comment (gxyd) [inline src/lfortran/semantics/ast_common_visitor.h:4870]: Is a better name `is_fixed_size_array`? Since then we can set the `dim.m_length = nullptr` when `is_fixed_size_array` is false

**Review by gxyd — APPROVED** [review]
Left one question and a suggestion. Otherwise this PR looks good to me. Thanks @assem2002

File: integration_tests/arrays_reshape_19.f90 (hunk 2 above)
Comment (assem2002) [reply integration_tests/arrays_reshape_19.f90:6]: I opened an issue for it #5934.

**Comment by assem2002** [comment]
the reference test update is due to that commit https://github.com/lfortran/lfortran/pull/5930/commits/b61981f5a0ff593ea7dd5ffd2f32e1db508fc82e
