### PR TITLE
fix: formatted READ format rescanning for arrays

### LINKED ISSUE #9991: Formatted READ: Format not rescanned when there are more items to read
```
program read_fmt5
  implicit none

  integer :: ia(5)
  integer :: i

  open (10, file='fort.10', status='unknown', form='formatted')

! Format gets repeated for each value of i on a new record
  write (10, '(i4)') (i, i=1,5)

  rewind (10)

! Should read each element of the array from the next record
  read (10, '(i4)') ia
  do, i=1, 5
    print *, 'ia(', i, ') =', ia(i),  &
        merge (': pass', ': fail', ia(i) == i)
  end do

end program
```
```
$ rm fort.10
$ lfortran read_fmt5.f90
ia(    1    ) =    1    : pass
ia(    2    ) =    0    : fail
ia(    3    ) =    0    : fail
ia(    4    ) =    0    : fail
ia(    5    ) =    4194368    : fail
(base) wws@w6ws-4:~/computer/fortran/fcvs/fcvs21_f95/wws$ cat fort.10
   1
   2
   3
   4
   5
$ 
```
```
$ rm fort.10
$ gfortran read_fmt5.f90
$ ./a.out
 ia(           1 ) =           1 : pass
 ia(           2 ) =           2 : pass
 ia(           3 ) =           3 : pass
 ia(           4 ) =           4 : pass
 ia(           5 ) =           5 : pass
$
```

### PR DESCRIPTION
**Pull request by opixdown**
fixes #9991

### CODE REVIEW

File: integration_tests/read_36.f90 [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+
+  rewind (10)
+
+  ! Should read each element from the next record
+  read (10, '(i4)') ia
+
+  do i = 1, 5
+     if (ia(i) /= i) then
+        print *, "FAIL: ia(", i, ") =", ia(i), " expected ", i
+        stop 1
```
Comment (certik) [inline integration_tests/read_36.f90:20]: I verified that this fails in main:
```console
$ lfortran a.f90
FAIL: ia(    2    ) =    0     expected     2
STOP 1
```
