### PR TITLE
fix : Handling Array Size in Function call in Pass array by data using Deep copy

### LINKED ISSUE #6147: Handle array with changing size in procedure when it is passed as argument in function
MRE: 
```fortran 
program test
   integer :: y = 2
   call temp(y)

contains
   subroutine temp(x)
        integer, intent(inout) :: x
        logical :: keep(x)
        integer :: tmp
        keep = [.false., .true.]
        x = 1
        print *, trueloc(keep)
   end subroutine
   function trueloc(x) result(loc)
        logical, intent(in) :: x(:)
        integer(4), allocatable :: loc(:)
        integer :: i, j
        allocate(loc(count(x)))
        j = 1
        do i = 1, size(x)
            if( x(i) ) then
                loc(j) = i
                j = j + 1
            end if
        end do
    end function trueloc

end program
```

GFortran Output : `2`
LFortran Output : ` `

Removes https://github.com/Pranavchiku/prima/commit/2c4955c1c62203ed0778eac24459d6b8f90c56f6.

### PR DESCRIPTION
**Pull request by AnshMehta1**
fix #6147 

MRE
```console
program arrays_08_size
   integer :: y = 2
   call temp(y)

contains
   subroutine temp(x)
        integer, intent(inout) :: x
        logical :: keep(x)
        integer :: result(x)
        keep = [.false., .true.]
        x = 1
        result = trueloc(keep)
        print * , result
   end subroutine
   function trueloc(x) result(loc)
        logical, intent(in) :: x(:)
        integer(4), allocatable :: loc(:)
        integer :: i, j
        allocate(loc(count(x)))
        j = 1
        do i = 1, size(x)
            if( x(i) ) then
                loc(j) = i
                j = j + 1
            end if
        end do
    end function trueloc

end program
```

LFortran output
```console
(lf) lordansh@LordAnsh:~/dev/lfort3/lfortran$ lfortran try.f90
2
0
```

### CODE REVIEW

File: src/libasr/codegen/asr_to_llvm.cpp [hunk 1]
```diff
@@ -8901,7 +8901,11 @@ class ASRToLLVMVisitor : public ASR::BaseVisitor<ASRToLLVMVisitor>
                     ASR::Variable_t *arg = EXPR2VAR(x.m_args[i].m_value);
                     uint32_t h = get_hash((ASR::asr_t*)arg);
                     if (llvm_symtab.find(h) != llvm_symtab.end()) {
-                        tmp = llvm_symtab[h];
+                        if (llvm_symtab_deep_copy.find(h) != llvm_symtab_deep_copy.end()) {
+                            tmp = llvm_symtab_deep_copy[h];
+                        } else {
+                            tmp = llvm_symtab[h];
+                        }
```
Comment (Pranavchiku) [inline src/libasr/codegen/asr_to_llvm.cpp:8908]: this is good, nice!

**Review by Pranavchiku — APPROVED** [review]
thanks for fixing this, looks good to me!
