### PR TITLE
fix: handle character intrinsics `len(), len_trim(), adjustl(), adjustr()` for polymorphic variables

### LINKED ISSUE #3689: Verify error on giving class(*) as argument to intrinsic `adjustl`
Ref: #3674
```fortran
subroutine print_generic(generic)
   class(*), intent(in), optional  :: generic
   select type(generic)
      type is (character(len=*))
         print*, adjustl(generic)
   end select
end subroutine print_generic
```
```console
$ gfortran a.f90 && ./a.out
$ lfortran a.f90
ASR verify pass error: Unexpected args, Adjustl expects (char) as arguments
 --> a.f90:5:18
  |
5 |          print*, adjustl(generic)
  |                  ^^^^^^^^^^^^^ failed here


Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.
```]

### LINKED ISSUE #9488: Handle `adjustr()` intrinsic inside select type statements for polymorphic arguments
Related to #9328, #3689 

MRE:
```
program temp
    implicit none

    call print_any("  Hello World  ")
    contains
    subroutine print_any(generic)
        class(*), intent(in) :: generic
        select type (generic)
        type is (character(len=*))
            print *, adjustr(generic)
        end select        
    end subroutine print_any
end program temp
```

Main:
```
$ gfortran a.f90 & ./a.out
[1]+  Done                    gfortran a.f90
[1] 153072
     Hello World

$ lfortran a.f90
ASR verify pass error: Unexpected args, Adjustr expects (char) as arguments
  --> a.f90:10:22
   |
10 |             print *, adjustr(generic)
   |                      ^^^^^^^^^^^^^^^^ failed here
```

### LINKED ISSUE #9489: Handle `len_trim()` intrinsic inside select type statements for polymorphic arguments
Related to https://github.com/lfortran/lfortran/issues/9328, https://github.com/lfortran/lfortran/issues/3689

MRE:
```
program temp
    implicit none

    call print_any("  Hello World  ")
    contains
    subroutine print_any(generic)
        class(*), intent(in) :: generic
        select type (generic)
        type is (character(len=*))
            print *, len_trim(generic)
        end select        
    end subroutine print_any
end program temp
```

Main:
```
$ lfortran a.f90
ASR verify pass error: Unexpected args, StringLenTrim expects (char) as arguments
  --> a.f90:10:22
   |
10 |             print *, len_trim(generic)
   |                      ^^^^^^^^^^^^^^^^^ failed here

$ gfortran a.f90 & ./a.out
[1]+  Done                    gfortran a.f90
[1] 154783
          13
```

### PR DESCRIPTION
**Pull request by YashNagda17**
Fixes #3689, Fixes #9488, Fixes #9489
Towards #9490

Changes made:
- Add support for more character intrinsics inside select block.
- For `len_trim(), adjustl(), adjustr()`; throw semantic error when accessed from outside of select block, for polymorphic arguments.

### CODE REVIEW

File: integration_tests/intrinsics_405.f90 [hunk 1]
```diff
@@ -5,13 +5,28 @@ program intrinsics_405
     contains
     subroutine print_any(generic)
         class(*), intent(in) :: generic
-        character(len = 15) :: a
+        character(len = 15) :: a, b, c 
+        integer :: d,e
         select type (generic)
         type is (character(len=*))
             a = trim(generic)
-            print *, trim(generic)
```
Comment (certik) [inline integration_tests/intrinsics_405.f90:12]: I think we need to keep testing this print statement, correct?

**Comment by certik** [comment]
Otherwise I think it looks good.

File: integration_tests/intrinsics_405.f90 [hunk 2]
```diff
@@ -5,13 +5,39 @@ program intrinsics_405
...
         class(*), intent(in) :: generic
-        character(len = 15) :: a
+        character(len = 15) :: a, b, c 
+        integer :: d,e
         select type (generic)
         type is (character(len=*))
+
             a = trim(generic)
             print *, trim(generic)
+
```
Comment (HarshitaKalani) [inline integration_tests/intrinsics_405.f90:15]:
```suggestion
if (trim(generic) /= "  Hello World") error stop
```
Can we add these error stop conditions to make it robust?

Comment (HarshitaKalani) [reply integration_tests/intrinsics_405.f90:15]: Same for below

File: integration_tests/intrinsics_405.f90 [hunk 3]
```diff
@@ -5,13 +5,39 @@ program intrinsics_405
...
+        print *, a
         if (a /= trim("  Hello World  ")) error stop
+        print *, b
+        if (b /= adjustl("  Hello World  ")) error stop 
+        print *, c 
+        if (c /= adjustr("  Hello World  ")) error stop
+        print *, d
+        if (d /= len_trim("  Hello World  ")) error stop
+        print * ,e
+        if (e /= len("  Hello World  ")) error stop
```
Comment (certik) [inline integration_tests/intrinsics_405.f90]: I think these tests will always pass, even if `adjustl`, etc. are buggy, since you compare `result == result`. Rather, change the RHS to be the reference result, i.e., replace `adjustl("  Hello World  ")` with the actual string that it should be. The same for the rest.

**Comment by certik** [comment]
Last two things to fix:

* https://github.com/lfortran/lfortran/pull/9491#discussion_r2686776970
* https://github.com/lfortran/lfortran/pull/9491#discussion_r2686913819

Check it at both places --- inside the generic block and outside as you currently do, but fix the tests per my comment.

**Review by certik — APPROVED** [review]

**Comment by certik** [comment]
Looks great, thanks! Let's run full tests to make sure nothing got broken.
