### PR TITLE
Restrict step size 0 in for loop

### LINKED ISSUE #1515: Do not allow step size 0 in DO loop
Just caught and fixed this case in https://github.com/lcompilers/lpython/pull/1674
`Fortran` equivalent code also fails.
```
program f
implicit none
integer :: i
do i = 1, 5, 0
    write(*,*) i
end do
end program f

(lf) faze-geek@DESKTOP-497JDCU:~/lfortran/lfortran$ gfortran ./examples/expr2.f90  && ./a.out
./examples/expr2.f90:4:12:

    4 | do i = 1, 5, 0
      |            1
Error: Step expression in DO loop at (1) cannot be zero

(lf) faze-geek@DESKTOP-497JDCU:~/lfortran/lfortran$ ./src/bin/lfortran ./examples/expr2.f90
(lf) faze-geek@DESKTOP-497JDCU:~/lfortran/lfortran$
```

### PR DESCRIPTION
**Pull request by Pranavchiku**
Fixes #1515.

### CODE REVIEW

File: src/lfortran/semantics/ast_body_visitor.cpp [hunk 1]
```diff
@@ -2350,6 +2350,13 @@ class BodyVisitor : public CommonVisitor<BodyVisitor> {
         if (x.m_increment) {
             visit_expr(*x.m_increment);
             increment = ASRUtils::EXPR(tmp);
+            // Check that the increment is not zero
+            if (increment->type == ASR::exprType::IntegerConstant) {
```
Comment (certik) [inline src/lfortran/semantics/ast_body_visitor.cpp:2354]:
```suggestion
            if (ASR::is_a<ASR::IntegerConstant_t>(*increment)) {
```

**Review by certik — APPROVED** [review]
Otherwise it looks good, thanks!
