### PR TITLE
Handle `IntegerBinOp_t` when setting array dimension through a module variable

### LINKED ISSUE #4013: Bug: Expressions in `DIMENSION` attribute of arrays inside a `SUBROUTINE` lead to an `ASR verify pass error`
#### Minimum Reproducible Example (MRE)

> m.f90
```fortran
MODULE m
   IMPLICIT NONE
   INTEGER :: nx = 2
END MODULE m
```
> example.f90
```fortran
MODULE example
   USE m
   IMPLICIT NONE
CONTAINS
   SUBROUTINE sub (n)

      INTEGER, DIMENSION(nx-1) :: n
      
   END SUBROUTINE sub
END MODULE example

PROGRAM test
   use example
END PROGRAM test
```
#### Output
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
ASR verify pass error: ASR::ttype_t in ASR::FunctionType cannot be tied to a scope.
 --> ./examples/example.f90:5:4 - 9:21
  |
5 |       SUBROUTINE sub (n)
  |       ^^^^^^^^^^^^^^^^^^...
...
  |
9 |       END SUBROUTINE sub
  | ...^^^^^^^^^^^^^^^^^^^^^ failed here


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

The bug was caught when trying to compile file `expxs.f90` of the SNAP package.<br><br>

The subroutine `expxs_slgg ( scat, map, cs )` causes the above error due to the parameter `cs` which is declared as `REAL(r_knd), DIMENSION(cmom-1,nx), INTENT(OUT) :: cs`. On further analysis, we find that the expression `cmom-1` is the cause of the issue. Other similar expressions like `cmom+1`, `cmom * 2`, etc also lead to the above error. We can simplify the issue to the MRE provided above.

### PR DESCRIPTION
**Pull request by kmr-srbh**
fixes #4013 

```fortran
subroutine a(cs)
   use xx
   real, dimension(nx - 1), intent(in) :: cs
end subroutine
```
is transformed to:
```fortran
pure integer function __lcompilers_get_nx()
use xx
get_nx = nx
end function

subroutine a(cs)
   use xx
   interface
      pure integer function __lcompilers_get_nx()
   end function
end interface
real, dimension(__lcompilers_get_nx() - 1), intent(in) :: cs
end subroutine
```

#### Working
```fortran
module xx
   integer :: nx = 4
end module xx

subroutine a(cs)
   use xx
   integer, dimension(nx - 1), intent(in) :: cs
   print *, cs
end subroutine

program main
   integer, dimension(4) :: cs
   cs = [1, 2, 3, 4]
   call a(cs)
end program
```
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
1 2 3 
```

### CODE REVIEW

File: src/lfortran/semantics/ast_common_visitor.h [hunk 1]
```diff
@@ -1250,6 +1250,71 @@ class CommonVisitor : public AST::BaseVisitor<Derived> {
...
                         end = func_call;
                     }
+                } else if(ASR::is_a<ASR::IntegerBinOp_t>(*end)) {
+                    ASR::IntegerBinOp_t* end_bin_op = ASR::down_cast<ASR::IntegerBinOp_t>(end);
+                    ASR::Var_t* end_var = nullptr;
+                    if (ASR::is_a<ASR::Var_t>(*end_bin_op->m_left)) {
+                        end_var = ASR::down_cast<ASR::Var_t>(end_bin_op->m_left);
+                    } else if (ASR::is_a<ASR::Var_t>(*end_bin_op->m_right)) {
+                        end_var = ASR::down_cast<ASR::Var_t>(end_bin_op->m_right);
+                    }
```
Comment (Pranavchiku) [inline src/lfortran/semantics/ast_common_visitor.h:1260]: This won't work if `integer, dimension(nx*ny) :: n`

File: src/lfortran/semantics/ast_common_visitor.h [hunk 2]
```diff
@@ -1250,6 +1250,71 @@ class CommonVisitor : public AST::BaseVisitor<Derived> {
...
+
+                    ASR::symbol_t* end_sym = end_var->m_v;
```
Comment (Pranavchiku) [inline src/lfortran/semantics/ast_common_visitor.h:1262]: `end_var` can be `nullptr`, that will lead to segfault.

File: src/lfortran/semantics/ast_common_visitor.h (hunk 1 above)
Comment (kmr-srbh) [reply src/lfortran/semantics/ast_common_visitor.h:1260]: You are right, thanks for catching this! We can handle this case here like:
```c++
if (ASR::is_a<ASR::Var_t>(*end_bin_op->m_left) && *end_bin_op->m_right) {
    // end_var is m_left
} else if (ASR::is_a<ASR::Var_t>(*end_bin_op->m_right) && *end_bin_op->m_left) {
    // end_var is m_right
} else {
    // end_var is the product of nx and ny
}
```

I think we can create a function for the transformation logic as then we can convert the above case to `get_nx() * get_ny()`.

File: src/lfortran/semantics/ast_common_visitor.h (hunk 2 above)
Comment (kmr-srbh) [reply src/lfortran/semantics/ast_common_visitor.h:1262]: https://github.com/lfortran/lfortran/pull/4034#discussion_r1605972643 will handle this.

File: src/lfortran/semantics/ast_common_visitor.h (hunk 1 above)
Comment (kmr-srbh) [reply src/lfortran/semantics/ast_common_visitor.h:1260]: The function can maybe have the following signature - `ASR::expr_t* get_transformed_function_call(ASR::symbol_t* sym)`.

**Comment by Pranavchiku** [comment]
Do you know how to fix CI?

File: src/lfortran/semantics/ast_common_visitor.h (hunk 1 above)
Comment (kmr-srbh) [reply src/lfortran/semantics/ast_common_visitor.h:1260]: You can suggest some other way to handle this also :)

Comment (Pranavchiku) [reply src/lfortran/semantics/ast_common_visitor.h:1260]: Let’s first get CI running then we will improve it

**Comment by kmr-srbh** [comment]
> Do you know how to fix CI?

I see that the CI failure is due to the SIGSEGV which you pointed out. Let's handle it.

File: src/lfortran/semantics/ast_common_visitor.h (hunk 1 above)
Comment (kmr-srbh) [reply src/lfortran/semantics/ast_common_visitor.h:1260]: Please see https://github.com/lfortran/lfortran/pull/4034#issuecomment-2119145643

**Comment by kmr-srbh** [comment]
I suspect this part of the code to be the culprit:
```fortran
program functions_20
real, dimension(3,3) :: A                ! <- variable declared here
real :: B(2)
integer :: k

interface
    function diag_rsp_mat(A, k) result(res)
        real, intent(in) :: A(:,:)           ! <- variable masked here
        integer, intent(in) :: k
        real :: res(minval(shape(A)) - abs(k))
    end function diag_rsp_mat
end interface
```

From the linter comments, I see that we have a re-declaration occurring here. I am new to the language and currently do not understand what `A(:, :)` means. @Pranavchiku could you please explain this?

**Comment by Pranavchiku** [comment]
Does this code give same error when you run it? If yes, seems like you are not checking if end is nullptr or not before processing.

A(:,:) means array of 2 dimension with variable size that will be decided at runtime.

File: src/lfortran/semantics/ast_common_visitor.h [hunk 3]
```diff
@@ -1250,6 +1250,71 @@ class CommonVisitor : public AST::BaseVisitor<Derived> {
                                                 func_sym, func_sym, nullptr, 0, ASRUtils::symbol_type(end_sym), nullptr, nullptr, false));
                         end = func_call;
                     }
+                } else if(ASR::is_a<ASR::IntegerBinOp_t>(*end)) {
```
Comment (Pranavchiku) [inline src/lfortran/semantics/ast_common_visitor.h:1253]:
```suggestion
                } else if(end && ASR::is_a<ASR::IntegerBinOp_t>(*end)) {
```

this shall do the trick.

**Comment by Pranavchiku** [comment]
If the comment above do not work then start adding print statement at each line and check where it segfaults.

**Comment by kmr-srbh** [comment]
> Does this code give same error when you run it? If yes, seems like you are not checking if end is nullptr or not before processing.
> 
> A(:,:) means array of 2 dimension with variable size that will be decided at runtime.

Yes it segfaults on my local machine too.

The error occurs on the following line `ASR::symbol_t* end_sym = end_var->m_v;`. https://github.com/lfortran/lfortran/pull/4034#discussion_r1605972643 can fix it.

File: src/lfortran/semantics/ast_common_visitor.h (hunk 3 above)
Comment (kmr-srbh) [reply src/lfortran/semantics/ast_common_visitor.h:1253]: Pleas see https://github.com/lfortran/lfortran/pull/4034#issuecomment-2119174802

**Comment by kmr-srbh** [comment]
With the latest commit, we now handle the case were both operands are variables. However, unexpected things are happening now. A lot of `Illegal instructions (core dumped)` errors are happening. @Pranavchiku could you please look into the code to see what is going wrong?

**Comment by kmr-srbh** [comment]
When running the integration tests, a lot of internal compiler errors pop up. But, running the failing tests one-by-one shows no error and the tests execute properly.

**Comment by kmr-srbh** [comment]
With the changes in this PR, we are now able to compile `expxs.f90` of the SNAP package.

**Comment by kmr-srbh** [comment]
This case fails for now `integer, dimension(nx * ny - 1), intent(in) :: cs`. I am looking into it.

**Comment by certik** [comment]
Cannot `integer, dimension(nx * ny - 1), intent(in) :: cs` by handled as `integer, dimension(get_cs_dim()), intent(in) :: cs` and put `nx * ny - 1` into `get_cs_dim()`?

**Comment by kmr-srbh** [comment]
> Cannot `integer, dimension(nx * ny - 1), intent(in) :: cs` by handled as `integer, dimension(get_cs_dim()), intent(in) :: cs` and put `nx * ny - 1` into `get_cs_dim()`?

It can be done. This was my initial thought when implementing the changes in this PR, but I chose to follow the implementation for variables as it was straight-forward. I think this is the correct way to implement this as then we can handle variables and expressions together with a single implementation. I am pushing the new changes.

**Comment by kmr-srbh** [comment]
I have a few questions:

1. When handling an expression like `nx * ny - 1`, how do we know we are dealing with variables which are an `ExternalSymbol`? For single variables, it was easier to check it by doing
```c++
ASR::Var_t* end_var = ASR::down_cast<ASR::Var_t>(end);
ASR::symbol_t* end_sym = end_var->m_v;
if (ASR::is_a<ASR::ExternalSymbol_t>(*end_sym)) {
    ...
}
```
We could similarly also handle variables in an `InterBinOp_t` by checking the operands. How do we handle it here?

2. As we were dealing solely with variables before, we named the new getter function by extracting the symbol name. Now that we deal with expressions as a whole, how do we go about naming it `__lcompilers_get_cs_dim()` as stated in https://github.com/lfortran/lfortran/pull/4034#issuecomment-2120621772?

@certik @Pranavchiku could you please guide me on the above? This will help me in completing the new implementation.

**Comment by certik** [comment]
Right, it would require a more thorough analysis, which might not be worth doing.

It might be easier then to use the `get_nx()*get_ny()-1` style. What is the issue in that approach?

**Comment by kmr-srbh** [comment]
> Right, it would require a more thorough analysis, which might not be worth doing.
> 
> It might be easier then to use the `get_nx()*get_ny()-1` style. What is the issue in that approach?

The issue occurs when dealing with arbitrary number of integer binary operations. When dealing with an expression like `nx * ny - 1`, we currently check both sides of the operator for a variable. If a variable is found, we convert it to a function call. In this case, we would have `nx * ny` and `1` as the operands, where one of the operands is again an `IntegerBinOp_t`. This is not handled and leads to the same issue described in #4013.

**Comment by certik** [comment]
Yes, I think it has to be handled recursively.

**Comment by kmr-srbh** [comment]
With the latest commit, we are now able to handle all the cases.
```fortran
module xx
   integer :: nx = 4
   integer :: ny = 1
end module xx

subroutine a(cs)
   use xx
   integer, dimension(nx * ny - 1), intent(in) :: cs
   print *, cs
end subroutine

program main
   integer, dimension(8) :: cs
   cs = [1, 2, 3, 4, 5, 6, 7, 8]
   call a(cs)
end program
```
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
1 2 3 
```

**Comment by kmr-srbh** [comment]
Currently, the following integration fails
```fortran
program arrays_op_20
implicit none

real, allocatable :: array(:, :), arrayoutput(:, :)

allocate(array(3, 3))
arrayoutput = f(5, array)
print *, size(arrayoutput)
if( size(arrayoutput) /= 24 ) error stop

contains

function f(m, input) result(output)
integer :: m
real :: input(m)
real :: output(2:m, m:2*m)
end function

end program
```
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
ASR verify pass error: ASR verify: The symbol table was not found in the scope of `symtab`.
  --> ./examples/example.f90:14:18
   |
14 |       integer :: m
   |                  ^ failed here

ASR verify pass error: FunctionCall::m_name `__lcompilers_get_m` cannot point outside of its symbol table
  --> ./examples/example.f90:14:18
   |
14 |       integer :: m
   |                  ^ failed here


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

**Comment by certik** [comment]
Not sure what is wrong. Save all the ASR to files (`--dump-all-passes`) and look at them to see when it becomes broken.

**Comment by kmr-srbh** [comment]
This implementation is now complete.

**Comment by certik** [comment]
@kmr-srbh beautiful, thank you for pushing this through! It looks ok at first glance to me, but we need to review more carefully.

@Shaikh-Ubaid do you think you could please review it carefully?

File: src/lfortran/semantics/ast_common_visitor.h [hunk 4]
```diff
@@ -1187,6 +1187,129 @@ class CommonVisitor : public AST::BaseVisitor<Derived> {
...
+                right = get_transformed_function_call(end_sym);
+            }
+            if (ASR::is_a<ASR::IntegerBinOp_t>(*left)) {
+                left = convert_integer_binop_to_function_call(left, is_argument);
+            }
+        } else if (ASR::is_a<ASR::Var_t>(*left) && ASR::is_a<ASR::Var_t>(*right)) {
+            // Handle expressions like `nx + ny` where both `nx` and `ny` are 
+            // external variables.
+            ASR::symbol_t* first_end_sym = (ASR::symbol_t*)ASR::down_cast<ASR::Var_t>(left)->m_v;
+            ASR::symbol_t* second_end_sym = (ASR::symbol_t*)ASR::down_cast<ASR::Var_t>(right)->m_v;
```
Comment (Shaikh-Ubaid) [inline src/lfortran/semantics/ast_common_visitor.h:1282]:
```suggestion
            ASR::symbol_t* first_end_sym = ASR::down_cast<ASR::Var_t>(left)->m_v;
            ASR::symbol_t* second_end_sym = ASR::down_cast<ASR::Var_t>(right)->m_v;
```
I think both are already `symbol_t*`. Unsure if you need to explicitly cast them.

Comment (kmr-srbh) [reply src/lfortran/semantics/ast_common_visitor.h:1282]: You are right. :+1:

File: src/lfortran/semantics/ast_common_visitor.h [hunk 5]
```diff
@@ -1187,6 +1187,129 @@ class CommonVisitor : public AST::BaseVisitor<Derived> {
...
+            an integer or an `IntegerBinOp_t`.
+
+            Examples - nx + 1 and nx + ny * nz
+            */
+            ASR::Var_t* end_var = ASR::down_cast<ASR::Var_t>(left);
+            ASR::symbol_t* end_sym = end_var->m_v;
+            SymbolTable* symbol_scope = ASRUtils::symbol_parent_symtab(end_sym);
+            if (ASR::is_a<ASR::ExternalSymbol_t>(*end_sym) ||
+                (symbol_scope->counter != current_scope->counter && is_argument &&
+                ASRUtils::expr_value(end) == nullptr) ) {
```
Comment (Shaikh-Ubaid) [inline src/lfortran/semantics/ast_common_visitor.h:1254]: This same condition seems to be repeating for around 4-5 times. I think we can extract this out and make a function of it (probably named "needs_transformation()"). Mention some comment like when a transformation is needed. I think we can/should do this in a new/separate PR.

**Review by Shaikh-Ubaid — APPROVED** [review]
It looks great to me. Thanks for this! We can improve this further as and when we see/find opportunities.

File: src/lfortran/semantics/ast_common_visitor.h (hunk 5 above)
Comment (kmr-srbh) [reply src/lfortran/semantics/ast_common_visitor.h:1256]: I had given this a thought, but making an `if` clause a function seemed a bit odd. Can we do this change in this PR only? It will complete the implementation.

Comment (Shaikh-Ubaid) [reply src/lfortran/semantics/ast_common_visitor.h:1256]: >Can we do this change in this PR only? It will complete the implementation.

Let's do it in a new PR.
