### PR TITLE
enh: support `compiletime_broadcast_elemental_intrinsic` for multiple arguments

### LINKED ISSUE #3673: Failure of elemental intrinsic functions on array input
```f90

program main
    implicit none
    print *, sign([1.2, 2.2, 3.3, 4.4], 1.2)  ! fails
    print *, floor([1.2, 2.2, 3.3, 4.4]) ! fails
    print *, ceiling([1.2, 2.2, 3.3, 4.4]) ! fails
end program main

```

each of the above elemental intrinsic function fail with an error:
```bash
Traceback (most recent call last):
  File "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran.cpp", line 2386
    LCompilers::print_stack_on_segfault();
  File "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran.cpp", line 2350
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/gxyd/OpenSource/lfortran/src/bin/lfortran.cpp", line 906
    result = fe.get_asr2(input, lm, diagnostics);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/fortran_evaluator.cpp", line 252
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/fortran_evaluator.cpp", line 274
    compiler_options.symtab_only, compiler_options);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 126
    if (res.ok) {
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 3585
    b.is_body_visitor = true;
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 143
    visit_ast(*x.m_items[i]);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4848
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4804
    case astType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4851
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4438
    case modType::BlockData: { v.visit_BlockData((const BlockData_t &)x); return; }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1546
    transform_stmts(body, x.n_body, x.m_body);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 114
    this->visit_stmt(*m_body[i]);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4894
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4564
    case stmtType::Return: { v.visit_Return((const Return_t &)x); return; }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 3058
    visit_expr(*x.m_values[i]);
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4945
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/ast.h", line 4602
    case exprType::Compare: { v.visit_Compare((const Compare_t &)x); return; }
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 5617
    bool is_function = true;
  File "/Users/gxyd/OpenSource/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 5191
    tmp = create_func(al, x.base.base.loc, args, diag);
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/pass/intrinsic_function_registry_util.h", line 1286
    m_value = eval_Floor(al, loc, return_type, args_values, diag);
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/pass/intrinsic_functions.h", line 1922
    ASR::RealConstant_t* x = ASR::down_cast<ASR::RealConstant_t>(args[0]);
  File "/Users/gxyd/OpenSource/lfortran/src/libasr/asr.h", line 41
    LCOMPILERS_ASSERT(is_a<T>(*f));
```

### PR DESCRIPTION
**Pull request by gxyd**
fixes #3673

### CODE REVIEW

File: src/libasr/asr_utils.h [hunk 1]
```diff
@@ -1224,8 +1224,9 @@ static inline bool is_value_in_range(ASR::expr_t* start, ASR::expr_t* end, ASR::
 }
 
 // Returns true if all arguments are evaluated
-static inline bool all_args_evaluated(const Vec<ASR::expr_t*> &args) {
+static inline bool all_args_evaluated(const Vec<ASR::expr_t*> &args, const bool allow_nullptr=false) {
     for (auto &a : args) {
+        if (allow_nullptr && !a) continue;
```
Comment (certik) [inline src/libasr/asr_utils.h:1229]: I am not sure about this change --- when can an argument here in the vector be null?

Comment (gxyd) [reply src/libasr/asr_utils.h:1229]: For something like: `floor(1.2)` where the second optional argument is set to `nullptr`.

Comment (certik) [reply src/libasr/asr_utils.h:1229]: Ok. Let's get all tests passing, then I'll review one more time.

**Comment by gxyd** [comment]
@certik , could you help me understand if the failing CI jobs are related to my changes?

the error says:
```bash
std::allocator<unsigned char> >, void>, bool)':
2024-03-20T10:25:01.8765884Z /home/runner/work/lfortran/lfortran/lfortran-0.33.1-866-ged79bd5c3/src/lfortran/fortran_kernel.cpp:346: undefined reference to `xeus::xinterpreter::publish_execution_result(int, nlohmann::json_abi_v3_11_3::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>,
 std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_3::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> >, void>, nlohmann::json_abi_v3_11_3::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, 
double, std::allocator, nlohmann::json_abi_v3_11_3::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> >, void>)'
```

Not able to understand how to go about this.

while the failing documentation job gives the error:
```bash
/usr/bin/ld: /home/runner/work/lfortran/lfortran/src/lfortran/fortran_kernel.cpp:511: undefined reference to `xeus::xkernel::xkernel(xeus::xconfiguration const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unique_ptr<xeus::xcontext, std::default_delete<xeus::xcontext> >, 
std::unique_ptr<xeus::xinterpreter, std::default_delete<xeus::xinterpreter> >, std::unique_ptr<xeus::xserver, std::default_delete<xeus::xserver> > (*)(xeus::xcontext&, xeus::xconfiguration const&,
 nlohmann::json_abi_v3_11_3::detail::error_handler_t), std::unique_ptr<xeus::xhistory_manager, std::default_delete<xeus::xhistory_manager> >, std::unique_ptr<xeus::xlogger, std::default_delete<xeus::xlogger> >, std::unique_ptr<xeus::xdebugger, std::default_delete<xeus::xdebugger> > (*)(xeus::xcontext&, xeus::xconfiguration
 const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, nlohmann::json_abi_v3_11_3::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_3::adl_serializer,
 std::vector<unsigned char, std::allocator<unsigned char> >, void> const&), nlohmann::json_abi_v3_11_3::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_3::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> >, void>, nlohmann::json_abi_v3_11_3::detail::error_handler_t)'
```

**Comment by certik** [comment]
It doesn't seem like triggered by your PR, but something is wrong, it's the same error on all 3 platforms.

Can you try submitting a simple PR to check if master passes?

**Comment by certik** [comment]
The CI failure is unrelated: https://github.com/lfortran/lfortran/issues/3687.

**Comment by gxyd** [comment]
This is ready for a review.

File: src/lfortran/semantics/ast_common_visitor.h [hunk 2]
```diff
@@ -5176,17 +5197,27 @@ class CommonVisitor : public AST::BaseVisitor<Derived> {
 
                     ASRUtils::create_intrinsic_function create_func =
                         ASRUtils::IntrinsicElementalFunctionRegistry::get_create_function(var_name);
-                    if (args.size() == 1 &&
+                    // broadcast when either,
+                    // 1. the only argument is an array
+                    // 2. or arg.size() is 2 and first arg is an array, and second arg "kind" is
+                    //   distributed to each broadcasted call
+                    // 
+                    if ((args.size() == 2 || args.size() == 1) &&
```
Comment (Pranavchiku) [inline src/lfortran/semantics/ast_common_visitor.h:5205]: I do not think we need this now, we shall go ahead and modify signature to

```diff
- void compiletime_broadcast_elemental_intrinsic(ASR::ArrayConstant_t* array, ASRUtils::create_intrinsic_function create_func, const Location& loc, Allocator& al)
+ void compiletime_broadcast_elemental_intrinsic(ASR::expr_t** args, ASRUtils::create_intrinsic_function  const Location& loc, Allocator& al)
```

Now iterate over args, and store in `std::vector<int> array_arg_indices`. Once we populate `array_arg_indices`, for example it has `{1, 2, 4}` and index `{0, 3, 5}` are scalar. We will create a helper funciton that takes `array_arg_indices` and all other necessary parameters and broadcast `X(s0, a1, a2, s3, a4, s5` as `[X(s0, a1[0], a2[0], s3, a4[0], s5), ...., ]`.

Comment (Pranavchiku) [reply src/lfortran/semantics/ast_common_visitor.h:5205]: The current approach handles only `kind` parameter and limits us to only two arguments ( same as main with 1 argument ).

File: src/libasr/asr_utils.h [hunk 3]
```diff
@@ -1224,8 +1224,9 @@ static inline bool is_value_in_range(ASR::expr_t* start, ASR::expr_t* end, ASR::
 }
 
 // Returns true if all arguments are evaluated
-static inline bool all_args_evaluated(const Vec<ASR::expr_t*> &args) {
+static inline bool all_args_evaluated(const Vec<ASR::expr_t*> &args, bool ignore_null=false) {
     for (auto &a : args) {
+        if (ignore_null && !a) continue;
```
Comment (Pranavchiku) [inline src/libasr/asr_utils.h:1229]: We do not need this because in `intrinsic_functions.h` it is already taken care that there will not be any nullptr. For frontend this happens because we `fill_optional_kind_arg` and cases like `max`, `min`, etc which has multiple arguments.

**Review by Pranavchiku — CHANGES_REQUESTED** [review]
Left some comments above, let me know if you wish more information about anything.  I am marking this as draft.

**Comment by Pranavchiku** [comment]
The approach in this PR works well, no doubts, that looks good as well. Just if we are fixing it, and we are no hurry at moment ( it is not a blocker afaik ), let us do it correctly. I'll be happy to help.

File: src/lfortran/semantics/ast_common_visitor.h (hunk 2 above)
Comment (gxyd) [reply src/lfortran/semantics/ast_common_visitor.h:5205]: Could you please give an example of an intrinsic function where broadcasting in this way would be needed? i.e. some being arrays, others being scalars, and it's an elemental intrinsic procedure? I'm just not able to think of something.

File: src/libasr/asr_utils.h (hunk 3 above)
Comment (gxyd) [reply src/libasr/asr_utils.h:1229]: So, you are saying that we can remove call to `fill_optional_kind_arg` as well as remove the `ignore_null` extra added keyword argument as well from `all_args_evaluated`?

Comment (Pranavchiku) [reply src/libasr/asr_utils.h:1229]: We can also have multiple array arguments
```fortran
program main
print *, max([1.0, 2.0, 3.0], [4.0, 5.0, 6.0])
end program
```

File: src/lfortran/semantics/ast_common_visitor.h (hunk 2 above)
Comment (Pranavchiku) [reply src/lfortran/semantics/ast_common_visitor.h:5205]: We can also have multiple array arguments
```fortran
program main
print *, max([1.0, 2.0, 3.0], [4.0, 5.0, 6.0])
end program
```

File: src/libasr/asr_utils.h (hunk 3 above)
Comment (gxyd) [reply src/libasr/asr_utils.h:1229]: > No, no, we need fill_optional_kind_arg, just check all_args_evaluated before filling optional arguments with nullptr.

I thought about this, and even if I do it before `fill_optional_kind_arg` as you mentioned that it would be filled with `nullptr` (for e.g. for `min`) that will happen even before `fill_optional_kind_arg`, as `args` is populated with `nullptr` in `handle_intrinsic_node_args` itself.

**Comment by gxyd** [comment]
Let me know how it looks now @Pranavchiku

File: integration_tests/intrinsics_195.f90 [hunk 4]
```diff
@@ -0,0 +1,7 @@
+program intrinsics_195
+    ! broadcasting "max" intrinsic
+    print *, max([-1, 2, 3], 2, 5, [4, 4, 5], [5, -8, 7])
+    print *, max(1, [-1, 2, 20])
+    print *, max([1, 2, 3], [1, 1, [2]])
+    print *, max([1, 2], -1, -4)
+end program
```
Comment (certik) [inline integration_tests/intrinsics_195.f90:7]: These need to have tests like `if (...) error stop` to ensure the answer is correct.

File: integration_tests/intrinsics_194.f90 [hunk 5]
```diff
@@ -0,0 +1,7 @@
+program intrinsics_194
+    ! broadcasting "min" intrinsic
+    print *, min([-1, 2, 3], 2, 5, [4, 4, 5], [5, -8, 7])
+    print *, min(1, [-1, 2, 20])
+    print *, min([1, 2, 3], [1, 1, [2]])
+    print *, min([1, 2], -1, -4)
```
Comment (certik) [inline integration_tests/intrinsics_194.f90:6]: This prints with GFortran:
```console
          -1          -8           2
          -1           1           1
           1           1           2
          -4          -4
```
How does this work? I don't understand what `min` does with a combination of array and scalar arguments like this.

Comment (certik) [reply integration_tests/intrinsics_194.f90:6]: I think it extends all arguments to be arrays like this:
```
min([-1, 2, 3], 2, 5, [4, 4, 5], [5, -8, 7])
->
min([-1, 2, 3], [2, 2, 2], [5, 5, 5], [4, 4, 5], [5, -8, 7])
```
And then it computes the minimum element-wise, so we get `[-1, -8, 2]`?

File: integration_tests/intrinsics_195.f90 (hunk 4 above)
Comment (certik) [reply integration_tests/intrinsics_195.f90:7]: Test shape and size of the resulting array also.

**Comment by certik** [comment]
@gxyd thanks for working on this. I think there are many bugs like these and we need to fix them all, so this is extremely useful.

File: integration_tests/intrinsics_194.f90 (hunk 5 above)
Comment (gxyd) [reply integration_tests/intrinsics_194.f90:6]: Yes, that's correct.

File: integration_tests/intrinsics_195.f90 (hunk 4 above)
Comment (gxyd) [reply integration_tests/intrinsics_195.f90:7]: Ah yes, I should've added it in the correct way, I'll change that.

**Comment by gxyd** [comment]
> I think there are many bugs like these

@certik are there open issues for such bugs (couldn't find any similar to this), let me know if there are more similar issues which need attention, I could take a look at those if needed.

**Comment by certik** [comment]
Yes, here are some:

* https://github.com/lfortran/lfortran/issues/3485
* https://github.com/lfortran/lfortran/issues/3203

**Comment by Pranavchiku** [comment]
I’ll review this PR in a while, around 11:30 IST.

**Review by Pranavchiku — APPROVED** [review]
This is good, thanks for doing this!
