### PR TITLE
enh: intrinsic function pass to allocate temporary of intrinsic Transpose

### LINKED ISSUE #5334: (PRIMA) Intrinsic function call in args of function causes error in Arraysize
Towards #4397

MRE : 
```fortran
program main

contains

subroutine trans(A)
real(8), intent(in) :: A(:,:)
print *, matprod(transpose(A))
end subroutine

function matprod(x) result(k)
real(8),intent(in) :: x(:,:)
real(8) :: k(size(x,1))
end function

end program 
```

LFortran Error : 
```console
LCOMPILERS_ASSERT failed: /mnt/c/lfortran/src/libasr/asr_utils.h
function make_ArraySize_t_util(), line number 2625 at
ASR::is_a<ASR::Var_t>(*a_v) || ASR::is_a<ASR::StructInstanceMember_t>(*a_v) || ASR::is_a<ASR::FunctionParam_t>(*a_v)
ERROR MESSAGE:
Found ASR::exprType::5
Traceback (most recent call last):
  Binary file "/mnt/c/lfortran/src/bin/lfortran", in _start
  File "/build/glibc-LcI20x/glibc-2.31/csu/../csu/libc-start.c", line 308, in __libc_start_main
  File "/mnt/c/lfortran/src/bin/lfortran.cpp", line 2679, in main
    return main_app(argc, argv);
  File "/mnt/c/lfortran/src/bin/lfortran.cpp", line 2621, in main_app(int, char**)
    err = compile_src_to_object_file(arg_file, tmp_o, false,
  File "/mnt/c/lfortran/src/bin/lfortran.cpp", line 1002, in (anonymous namespace)::compile_src_to_object_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, LCompilers::CompilerOptions&, LCompilers::PassManager&)
    result = fe.get_asr2(input, lm, diagnostics);
  File "/mnt/c/lfortran/src/lfortran/fortran_evaluator.cpp", line 270, in LCompilers::FortranEvaluator::get_asr2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::diag::Diagnostics&)
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/mnt/c/lfortran/src/lfortran/fortran_evaluator.cpp", line 292, in LCompilers::FortranEvaluator::get_asr3(LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&)
    compiler_options.symtab_only, compiler_options);
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 103, in LCompilers::LFortran::ast_to_asr(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::SymbolTable*, bool, LCompilers::CompilerOptions&)
    instantiate_types, instantiate_symbols, entry_functions, entry_function_arguments_mapping, data_structure);
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 4056, in LCompilers::LFortran::body_visitor(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::ASR::asr_t*, LCompilers::CompilerOptions&, std::map<unsigned long, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > > > > >&, std::map<unsigned long, LCompilers::ASR::symbol_t*, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, LCompilers::ASR::symbol_t*> > >&, std::map<unsigned long, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >&, std::map<unsigned int, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > > > > >&, std::map<unsigned int, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::symbol_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::symbol_t*> > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::symbol_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::symbol_t*> > > > > >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> > > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> > > > > > > >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<int, std::allocator<int> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<int, std::allocator<int> > > > >&, std::vector<LCompilers::ASR::stmt_t*, std::allocator<LCompilers::ASR::stmt_t*> >&)
    b.visit_TranslationUnit(ast);
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 166, in LCompilers::LFortran::BodyVisitor::visit_TranslationUnit(LCompilers::LFortran::AST::TranslationUnit_t const&)
    visit_ast(*x.m_items[i]);
  File "/mnt/c/lfortran/src/lfortran/ast.h", line 4884, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_ast(LCompilers::LFortran::AST::ast_t const&)
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/mnt/c/lfortran/src/lfortran/ast.h", line 4841, in void LCompilers::LFortran::AST::visit_ast_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::ast_t const&, LCompilers::LFortran::BodyVisitor&)
    case astType::mod: { v.visit_mod((const mod_t &)x); return; }
  File "/mnt/c/lfortran/src/lfortran/ast.h", line 4887, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_mod(LCompilers::LFortran::AST::mod_t const&)
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/mnt/c/lfortran/src/lfortran/ast.h", line 4474, in void LCompilers::LFortran::AST::visit_mod_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::mod_t const&, LCompilers::LFortran::BodyVisitor&)
    case modType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1647, in LCompilers::LFortran::BodyVisitor::visit_Program(LCompilers::LFortran::AST::Program_t const&)
    visit_program_unit(*x.m_contains[i]);
  File "/mnt/c/lfortran/src/lfortran/ast.h", line 4892, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_program_unit(LCompilers::LFortran::AST::program_unit_t const&)
    void visit_program_unit(const program_unit_t &b) { visit_program_unit_t(b, self()); }
  File "/mnt/c/lfortran/src/lfortran/ast.h", line 4482, in void LCompilers::LFortran::AST::visit_program_unit_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::program_unit_t const&, LCompilers::LFortran::BodyVisitor&)
    case program_unitType::Subroutine: { v.visit_Subroutine((const Subroutine_t &)x); return; }
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 2049, in LCompilers::LFortran::BodyVisitor::visit_Subroutine(LCompilers::LFortran::AST::Subroutine_t const&)
    transform_stmts(body, x.n_body, x.m_body);
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 121, in LCompilers::LFortran::BodyVisitor::transform_stmts(LCompilers::Vec<LCompilers::ASR::stmt_t*>&, unsigned long, LCompilers::LFortran::AST::stmt_t**)
    this->visit_stmt(*m_body[i]);
  File "/mnt/c/lfortran/src/lfortran/ast.h", line 4930, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_stmt(LCompilers::LFortran::AST::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/mnt/c/lfortran/src/lfortran/ast.h", line 4601, in void LCompilers::LFortran::AST::visit_stmt_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::stmt_t const&, LCompilers::LFortran::BodyVisitor&)
    case stmtType::Print: { v.visit_Print((const Print_t &)x); return; }
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 3279, in LCompilers::LFortran::BodyVisitor::visit_Print(LCompilers::LFortran::AST::Print_t const&)
    this->visit_expr(*x.m_values[i]);
  File "/mnt/c/lfortran/src/lfortran/ast.h", line 4982, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_expr(LCompilers::LFortran::AST::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/mnt/c/lfortran/src/lfortran/ast.h", line 4639, in void LCompilers::LFortran::AST::visit_expr_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::expr_t const&, LCompilers::LFortran::BodyVisitor&)
    case exprType::FuncCallOrArray: { v.visit_FuncCallOrArray((const FuncCallOrArray_t &)x); return; }
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 7330, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::visit_FuncCallOrArray(LCompilers::LFortran::AST::FuncCallOrArray_t const&)
    tmp = create_FunctionCallWithASTNode(x, v, args);
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 5086, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::create_FunctionCallWithASTNode(LCompilers::LFortran::AST::FuncCallOrArray_t const&, LCompilers::ASR::symbol_t*, LCompilers::Vec<LCompilers::ASR::call_arg_t>&, bool)
    return create_Function(x.base.base.loc, args, v);
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 5003, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::create_Function(LCompilers::Location const&, LCompilers::Vec<LCompilers::ASR::call_arg_t>&, LCompilers::ASR::symbol_t*)
    return_type = handle_return_type(return_type, loc, args, func);
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 4374, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::handle_return_type(LCompilers::ASR::ttype_t*, LCompilers::Location const&, LCompilers::Vec<LCompilers::ASR::call_arg_t>&, LCompilers::ASR::Function_t*)
    return ASRUtils::make_Array_t_util(
  File "/mnt/c/lfortran/src/libasr/asr_utils.h", line 2647, in LCompilers::ASRUtils::make_Array_t_util(Allocator&, LCompilers::Location const&, LCompilers::ASR::ttype_t*, LCompilers::ASR::dimension_t*, unsigned long, LCompilers::ASR::abiType, bool, LCompilers::ASR::array_physical_typeType, bool, bool)    
    m_dims[i].m_length = ASRUtils::EXPR(ASRUtils::make_ArraySize_t_util(
  File "/mnt/c/lfortran/src/libasr/asr_utils.h", line 2625, in LCompilers::ASRUtils::make_ArraySize_t_util(Allocator&, LCompilers::Location const&, LCompilers::ASR::expr_t*, LCompilers::ASR::expr_t*, LCompilers::ASR::ttype_t*, LCompilers::ASR::expr_t*, bool)
    LCOMPILERS_ASSERT_MSG(
  File "/build/glibc-LcI20x/glibc-2.31/stdlib/abort.c", line 79, in abort
  File "/build/glibc-LcI20x/glibc-2.31/signal/../sysdeps/unix/sysv/linux/internal-signals.h", line 86, in raise
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in <invalid>
Abort: Signal SIGABRT (abort) received

Aborted (core dumped)
```

I was working before a week, today I just updated my branch and got this error, so likely this is caused because of some recent PR.

### PR DESCRIPTION
**Pull request by Pranavchiku**
Fixes #5334.

### CODE REVIEW

File: src/libasr/pass/intrinsic_function.cpp [hunk 1]
```diff
@@ -380,6 +380,29 @@ class ReplaceFunctionCallReturningArray: public ASR::BaseExprReplacer<ReplaceFun
...
+                        alloc_dims.push_back(al, dim);
+                    }
+                    alloc_arg.m_a = result_var_; alloc_arg.m_len_expr = nullptr;
+                    alloc_arg.m_type = nullptr; alloc_arg.m_dims = alloc_dims.p;
+                    alloc_arg.n_dims = alloc_dims.size();
+                    alloc_args.push_back(al, alloc_arg);
+                    ASR::stmt_t* allocate_stmt = ASRUtils::STMT(ASR::make_Allocate_t(al,
+                                            x->base.base.loc, alloc_args.p, alloc_args.n, nullptr, nullptr, nullptr));
+                    pass_result.push_back(al, allocate_stmt);
+                }
```
Comment (Pranavchiku) [inline src/libasr/pass/intrinsic_function.cpp:405]: I think we need to write similar to this for most array functions

File: src/libasr/pass/intrinsic_function.cpp [hunk 2]
```diff
@@ -380,6 +380,29 @@ class ReplaceFunctionCallReturningArray: public ASR::BaseExprReplacer<ReplaceFun
...
                 if (ASRUtils::is_allocatable(ASRUtils::expr_type(result_var_)) &&
```
Comment (Pranavchiku) [inline src/libasr/pass/intrinsic_function.cpp:406]: this needs to be refactored

File: src/libasr/pass/intrinsic_function.cpp [hunk 3]
```diff
@@ -380,6 +380,29 @@ class ReplaceFunctionCallReturningArray: public ASR::BaseExprReplacer<ReplaceFun
                 result_var_ = PassUtils::create_var(result_counter,
                     std::string(ASRUtils::symbol_name(x->m_name)) + "_res",
                     x->base.base.loc, x->m_type, al, current_scope);
+                if ( ASRUtils::is_allocatable(ASRUtils::expr_type(result_var_)) &&
```
Comment (certik) [inline src/libasr/pass/intrinsic_function.cpp:383]: Shouldn't the simplifier or array_op take care of temporaries?

Can you give an example why this is needed?

Ideally we want to only handle such allocations at once place (eventually the simplifier).

Comment (Pranavchiku) [reply src/libasr/pass/intrinsic_function.cpp:383]: > Shouldn't the simplifier or array_op take care of temporaries?

No. The `IntrinsicArrayFunctions` that return arrays, we transform those to subroutines by passing return var to function argument. So they are basically subroutines. Hence we need this temporary.

Example:

```fortran
 Fortran code after applying the pass: intrinsic_function
program main
implicit none
real(4), dimension(2, 2), save :: a = reshape([1.00000000e+00, 2.00000000e+00, 3.00000000e+00, 4.00000000e+00], [2, 2])
call trans(a)

contains

subroutine matprod(x, k)
    real(4), dimension(:, :), intent(in) :: x
    real(4), dimension(size(x, 1)), intent(out) :: k
end subroutine matprod

subroutine trans(a)
    real(4), dimension(:, :), intent(in) :: a
    real(4), dimension(size(a, 1)) :: temporary_for_function_call_result
    real(4), dimension(:, :), allocatable :: temporary_for_transpose ! we create this because `lcompilers_transpose` expects this, and `result` var is `real(4), dimension(:, :),` thus we create allocatable
    ! allocate `temporary_for_transpose` but what to allocate?
    allocate(temporary_for_transpose(size(a, 2), size(a, 1)))
    call lcompilers_transpose(a, temporary_for_transpose) ! segfaults because `temporary_for_transpose` is not allocated
    call matprod(temporary_for_transpose, temporary_for_function_call_result)
    print *, temporary_for_function_call_result
end subroutine trans

subroutine lcompilers_transpose(matrix_a_t, result)
    integer(4) :: i
    integer(4) :: j
    real(4), dimension(:, :), intent(in) :: matrix_a_t
    real(4), dimension(:, :), intent(out) :: result
    do i = lbound(matrix_a_t, 1), ubound(matrix_a_t, 1)
        do j = lbound(matrix_a_t, 2), ubound(matrix_a_t, 2)
            result(j, i) = matrix_a_t(i, j)
        end do
    end do
    return
end subroutine lcompilers_transpose

end program main
```

Comment (gxyd) [reply src/libasr/pass/intrinsic_function.cpp:383]: I'm sorry, I think this whole block of code already has a `if (!ASRUtils::use_experimental_simplifier) {` above it, so that part is fine.

Comment (certik) [reply src/libasr/pass/intrinsic_function.cpp:383]: Ah --- this is a fix *until* we enable simplifier? Then it's fine.

My point was the simplifier should have fixed issues like this one.

Comment (certik) [reply src/libasr/pass/intrinsic_function.cpp:383]: Something is still fishy here --- intrinsic functions should not create any temporaries. They should transform intrinsics to functions; a separate pass should then decompose array expressions with functions into temporaries, and a separate pass should transform functions to subroutines.

But let's merge it, since it fixes an issue, but we need to clean this up.

**Review by certik — APPROVED** [review]

File: src/libasr/pass/intrinsic_function.cpp (hunk 3 above)
Comment (Pranavchiku) [reply src/libasr/pass/intrinsic_function.cpp:383]: Yes, we need to refactor it. I’ll try to comeup with a general idea.
