### PR TITLE
fix:: Support for Implied Do Loop Parameter Arrays for Strings

### LINKED ISSUE #8623: Segmentation Fault when initializing parameter character array using do-loops
MRE:
```
program char_array_test
implicit none
    integer::i
    character(len=1),parameter :: char_array(3) = (/(('A'), i=1,3) /)
print *, char_array
end program
```

Gfortran:
```
 gfortran a.f90 & ./a.out
[1]+  Done                    gfortran a.f90
[1] 121232
 AAA
```

Main:
```
$ lfortran a.f90 
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/yash/Desktop/lfortran/lfortran/src/bin/lfortran", in _start
  File "./csu/../csu/libc-start.c", line 360, in __libc_start_main
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main
  File "/home/yash/Desktop/lfortran/lfortran/src/bin/lfortran.cpp", line 2739, in main
    return main_app(argc, argv);
  File "/home/yash/Desktop/lfortran/lfortran/src/bin/lfortran.cpp", line 2663, in main_app(int, char**)
    err = compile_src_to_object_file(arg_file, tmp_o, compiler_options.time_report, false,
  File "/home/yash/Desktop/lfortran/lfortran/src/bin/lfortran.cpp", line 1137, in (anonymous namespace)::compile_src_to_object_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, LCompilers::CompilerOptions&, LCompilers::PassManager&, bool)
    result = fe.get_asr2(input, lm, diagnostics);
  File "/home/yash/Desktop/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 276, in LCompilers::FortranEvaluator::get_asr2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::diag::Diagnostics&)
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics, lm);
  File "/home/yash/Desktop/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 298, in LCompilers::FortranEvaluator::get_asr3(LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::LocationManager&)
    compiler_options.symtab_only, compiler_options, lm);
  File "/home/yash/Desktop/lfortran/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 77, in LCompilers::LFortran::ast_to_asr(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::SymbolTable*, bool, LCompilers::CompilerOptions&, LCompilers::LocationManager&)
    entry_function_arguments_mapping, data_structure, lm);
  File "/home/yash/Desktop/lfortran/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 4515, in LCompilers::LFortran::symbol_table_visitor(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::SymbolTable*, LCompilers::CompilerOptions&, std::map<unsigned long, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > > > > >&, std::map<unsigned long, LCompilers::ASR::symbol_t*, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, LCompilers::ASR::symbol_t*> > >&, std::map<unsigned long, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >&, std::map<unsigned long, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >&, std::map<unsigned int, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<LCompilers::ASR::ttype_t*, LCompilers::ASR::symbol_t*>, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::pair<LCompilers::ASR::ttype_t*, LCompilers::ASR::symbol_t*> > > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<LCompilers::ASR::ttype_t*, LCompilers::ASR::symbol_t*>, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::pair<LCompilers::ASR::ttype_t*, LCompilers::ASR::symbol_t*> > > > > > >&, std::map<unsigned int, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::symbol_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::symbol_t*> > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::symbol_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::symbol_t*> > > > > >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> > > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> > > > > > > >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<int, std::allocator<int> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<int, std::allocator<int> > > > >&, std::vector<LCompilers::ASR::stmt_t*, std::allocator<LCompilers::ASR::stmt_t*> >&, LCompilers::LocationManager&)
    v.visit_TranslationUnit(ast);
  File "/home/yash/Desktop/lfortran/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 84, in LCompilers::LFortran::SymbolTableVisitor::visit_TranslationUnit(LCompilers::LFortran::AST::TranslationUnit_t const&)
    visit_ast(*x.m_items[i]);
  File "/home/yash/Desktop/lfortran/lfortran/src/lfortran/ast.h", line 5016, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::SymbolTableVisitor>::visit_ast(LCompilers::LFortran::AST::ast_t const&)
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/home/yash/Desktop/lfortran/lfortran/src/lfortran/ast.h", line 4972, in void LCompilers::LFortran::AST::visit_ast_t<LCompilers::LFortran::SymbolTableVisitor>(LCompilers::LFortran::AST::ast_t const&, LCompilers::LFortran::SymbolTableVisitor&)
    case astType::mod: { v.visit_mod((const mod_t &)x); return; }
  File "/home/yash/Desktop/lfortran/lfortran/src/lfortran/ast.h", line 5019, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::SymbolTableVisitor>::visit_mod(LCompilers::LFortran::AST::mod_t const&)
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/home/yash/Desktop/lfortran/lfortran/src/lfortran/ast.h", line 4594, in void LCompilers::LFortran::AST::visit_mod_t<LCompilers::LFortran::SymbolTableVisitor>(LCompilers::LFortran::AST::mod_t const&, LCompilers::LFortran::SymbolTableVisitor&)
    case modType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/home/yash/Desktop/lfortran/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 479, in LCompilers::LFortran::SymbolTableVisitor::visit_Program(LCompilers::LFortran::AST::Program_t const&)
    visit_unit_decl2(*x.m_decl[i]);
  File "/home/yash/Desktop/lfortran/lfortran/src/lfortran/ast.h", line 5030, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::SymbolTableVisitor>::visit_unit_decl2(LCompilers::LFortran::AST::unit_decl2_t const&)
    void visit_unit_decl2(const unit_decl2_t &b) { visit_unit_decl2_t(b, self()); }
  File "/home/yash/Desktop/lfortran/lfortran/src/lfortran/ast.h", line 4620, in void LCompilers::LFortran::AST::visit_unit_decl2_t<LCompilers::LFortran::SymbolTableVisitor>(LCompilers::LFortran::AST::unit_decl2_t const&, LCompilers::LFortran::SymbolTableVisitor&)
    case unit_decl2Type::Declaration: { v.visit_Declaration((const Declaration_t &)x); return; }
  File "/home/yash/Desktop/lfortran/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 1847, in LCompilers::LFortran::SymbolTableVisitor::visit_Declaration(LCompilers::LFortran::AST::Declaration_t const&)
    visit_DeclarationUtil(x);
  File "/home/yash/Desktop/lfortran/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 4389, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::SymbolTableVisitor>::visit_DeclarationUtil(LCompilers::LFortran::AST::Declaration_t const&)
    LCOMPILERS_ASSERT(
  File "/home/yash/Desktop/lfortran/lfortran/src/libasr/asr_utils.h", line 418, in LCompilers::ASRUtils::expr_type(LCompilers::ASR::expr_t const*)
    return ASR::expr_type0(f);
AssertFailed: f != nullptr
```

### PR DESCRIPTION
**Pull request by YashNagda17**
Fixes #8623

Added support to use implied do loop for parameter character arrays initializations. 
Added Test Case:
```
program char_array_test
implicit none
    integer::i
    character(len=2),parameter :: char_array(2) = (/(('AB'), i=1,2) /)
print *, char_array
end program
```
Updated Main:
```
$ lfortran a.f90 
AB    AB
```
Gfortran:
```
$ gfortran a.f90 & ./a.out
[1]+  Done                    gfortran a.f90
[1] 117019
 ABAB
```

### CODE REVIEW

File: src/lfortran/semantics/ast_common_visitor.h [hunk 1]
```diff
@@ -9964,16 +9963,43 @@ class CommonVisitor : public AST::BaseVisitor<Derived> {
...
+                //Get length of Do-Loop Character Type
+                int len = -1;
+                ASRUtils::extract_value(
+                    ASR::down_cast<ASR::String_t>(ASRUtils::extract_type(type))->m_len, len);
+                char* char_data = new char[len * itr + 1];
+                for (int i = 0; i < itr; i++) {
+                    for (int j = 0; j < len; j++) {
+                        char_data[i*len + j] = array.p[i][j];
+                    }
+                }
```
Comment (assem2002) [inline src/lfortran/semantics/ast_common_visitor.h:9979]: Perfect! That should handle
```.f90
character(len=2),parameter :: char_array(2) = (/(('ABCDEFGH'), i=1,2) /)
```
It will dump any additional characters

**Review by assem2002 — APPROVED** [review]
Perfect! Thanks for working on this.

File: src/lfortran/semantics/ast_common_visitor.h [hunk 2]
```diff
@@ -9964,16 +9963,43 @@ class CommonVisitor : public AST::BaseVisitor<Derived> {
...
+                ASR::ttype_t* array_type = ASRUtils::TYPE(ASR::make_Array_t(al, x.base.base.loc, type, dims.p, dims.n, physical_type));
+                int64_t n_data = itr * ASRUtils::extract_kind_from_ttype_t(type);
+                if (ASRUtils::is_character(*type)) {
+                    int len;
+                    if(!ASRUtils::extract_value(ASR::down_cast<ASR::String_t>(ASRUtils::extract_type(type))->m_len, len)){
+                        LCOMPILERS_ASSERT(false);
+                    }
+                    n_data = itr * len;
+                }
+                ASR::expr_t* value = ASRUtils::EXPR(ASR::make_ArrayConstant_t(al, x.base.base.loc, n_data, data,
```
Comment (assem2002) [inline src/lfortran/semantics/ast_common_visitor.h:10002]: - Uses `pointerArray` with character type instead of `fixedsizeArray`
- Makes sure to set the `data` of the `void` constantArray to `elements * kind * len`

File: src/lfortran/semantics/ast_common_visitor.h (hunk 1 above)
Comment (certik) [reply src/lfortran/semantics/ast_common_visitor.h:9979]: Let's add a test for this also.

**Comment by assem2002** [comment]
It's fine to merge. @certik

File: src/lfortran/semantics/ast_common_visitor.h (hunk 1 above)
Comment (certik) [reply src/lfortran/semantics/ast_common_visitor.h:9979]: https://github.com/lfortran/lfortran/issues/8628
