### PR TITLE
ENH: handling compile time evaluation of elemental function

### LINKED ISSUE #3568: Binary operation on array constant and scalar throws error
```fortran
program main
real :: D(2)
D = [2.0, 3.0] + 2.0
print *, D
end program
```

```console
% lfortran a.f90 --show-asr --show-stacktrace
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2391
    LCompilers::print_stack_on_segfault();
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2269
    return emit_asr(arg_file, lfortran_pass_manager,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 622
    r = fe.get_asr2(input, lm, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 253
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 275
    compiler_options.symtab_only, compiler_options);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 127
    if (res.ok) {
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 3386
    b.is_body_visitor = true;
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 143
    visit_ast(*x.m_items[i]);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4848
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4804
    case astType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4851
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4438
    case modType::BlockData: { v.visit_BlockData((const BlockData_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1510
    transform_stmts(body, x.n_body, x.m_body);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 114
    this->visit_stmt(*m_body[i]);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4894
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4540
    case stmtType::Assign: { v.visit_Assign((const Assign_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 2236
    ASR::expr_t *target = ASRUtils::EXPR(tmp);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4945
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4596
    case exprType::BoolOp: { v.visit_BoolOp((const BoolOp_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 6445
    visit_BinOp2(al, x, left, right, tmp, binop2str[x.m_op], current_scope);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 6052
    ASRUtils::expr_value(left))
  File "/Users/pranavchiku/repos/lfortran/src/libasr/asr.h", line 41
    LCOMPILERS_ASSERT(is_a<T>(*f));
AssertFailed: is_a<T>(*f)
```

### PR DESCRIPTION
**Pull request by Pranavchiku**
Towards #3485. We can iteratively improve and add more tests if the direction looks good.

Fixes #3568.

### CODE REVIEW

File: src/libasr/asr_utils.h [hunk 1]
```diff
@@ -1201,6 +1201,15 @@ static inline bool is_value_in_range(ASR::expr_t* start, ASR::expr_t* end, ASR::
...
         ASR::expr_t* a_value = ASRUtils::expr_value(a);
+        if (ASR::is_a<ASR::Var_t>(*a)) {
+            ASR::Var_t* var = ASR::down_cast<ASR::Var_t>(a);
+            if (ASR::is_a<ASR::Variable_t>(*var->m_v)) {
+                ASR::Variable_t* var_v = ASR::down_cast<ASR::Variable_t>(var->m_v);
+                if (var_v->m_storage == ASR::storage_typeType::Parameter) {
+                    continue;
+                }
+            }
+        }
```
Comment (certik) [inline src/libasr/asr_utils.h:1212]: It looks like for the case `sin(A)` where `A` is a compile time parameter, the `a_value` is null, so the above change is working around that limitation. 

Instead, I think `A` has to have `a_value` present it should be equal to ArrayConstant. Then the check below will work. So the above change should not be necessary, once `value` is correctly assigned to `A`.

**Comment by certik** [comment]
I would always fully evaluate ArrayConstant to only contain RealConstants. So when `sin` is called on an ArrayConstant, we evaluate the sin for all elements, so the `value` of the variable `B = sin(A)` will be again ArrayConstant of RealConstants.

A separate issue is that ArrayConstant should only be allowed to contain other `*Constants`, never something that is not a constant. We might need to introduce `ArrayConstructor` to represent cases like `A = [sin(x), b]`.

**Comment by Pranavchiku** [comment]
> I would always fully evaluate ArrayConstant to only contain RealConstants

Yes, it is present in `m_value` of Variable. Whereas `m_symbolic_value` retains call to functions / intrinsics.

File: tests/reference/asr-arrays_06-9c8a08b.stdout [hunk 2]
```diff
@@ -341,14 +341,720 @@
...
+                                        (Real 4)
+                                        (RealConstant
+                                            7.000000
+                                            (Real 4)
+                                        )
+                                    )
+                                    RealToInteger
+                                    (Integer 4)
+                                    (IntegerConstant 7 (Integer 4))
+                                )]
```
Comment (certik) [inline tests/reference/asr-arrays_06-9c8a08b.stdout:1049]: This part here is very inefficient in terms of compilation time. After https://github.com/lfortran/lfortran/issues/3566 is fixed, this will become just one node with a contiguous set of elements, such as: `(ArrayConstant .. [1.0, 2.0, 3.0, ... 81.0])`.

**Review by certik — APPROVED** [review]
I think this is good enough to merge. Thank you!

We really need to fix https://github.com/lfortran/lfortran/issues/3566, to clean up these constant arrays. But we can do that later. Thanks for fixing this.

File: tests/reference/asr-arrays_06-9c8a08b.stdout (hunk 2 above)
Comment (Pranavchiku) [reply tests/reference/asr-arrays_06-9c8a08b.stdout:1049]: Yes, I was wondering the same. I'll focus on #3566 and get this done.
