### PR TITLE
fix : enforce directional StructType inheritance checks for class assignment

### LINKED ISSUE #7934: refactor: improve `StructType` type-checking to correctly resolve parent - child inheritance
### Minimal Reproducible Example

```fortran
program main
   implicit none

   type :: point2d
      real x, y
   end type point2d

   type, extends(point2d) :: point3d
      real :: z
   end type point3d

contains

   subroutine sub(p3d)

      class(point3d), intent(out), allocatable :: p3d

      type(point2d) :: p2d

      p3d = p2d
   end subroutine sub

end program main
```

### Output

```console
(lf) saurabhkumar@Mac lfortran % gfortran test.f90 && ./a.out             
test.f90:20:12:

   20 |       p3d = p2d
      |            1
Error: Cannot convert TYPE(point2d) to CLASS(point3d) at (1)
(lf) saurabhkumar@Mac lfortran % lfortran test.f90                        
(lf) saurabhkumar@Mac lfortran % echo $?                                  
0
```

This occurs for both variable assignments and pointer associations.

### PR DESCRIPTION
**Pull request by Jatinagarwal24**
fixes #7934

### CODE REVIEW

File: src/lfortran/semantics/ast_body_visitor.cpp [hunk 1]
```diff
@@ -5993,6 +5993,16 @@ class BodyVisitor : public CommonVisitor<BodyVisitor> {
                         throw SemanticAbort();
                 }
             }
+            if (ASRUtils::is_class_type(ASRUtils::type_get_past_array(target_type)) &&
```
Comment (kmr-srbh) [inline src/lfortran/semantics/ast_body_visitor.cpp]:
```suggestion
            if (ASRUtils::is_class_type(ASRUtils::extract_type(target_type)) &&
```

File: src/lfortran/semantics/ast_body_visitor.cpp [hunk 2]
```diff
@@ -5993,6 +5993,16 @@ class BodyVisitor : public CommonVisitor<BodyVisitor> {
...
+                ASR::is_a<ASR::StructType_t>(*ASRUtils::extract_type(value_type)) &&
+                !ASRUtils::check_class_assignment_compatibility(target, value)) {
+                diag.semantic_error_label(
+                    "Type mismatch in assignment, the types must be compatible",
+                    {target->base.loc, value->base.loc},
+                    "type mismatch (" + ltype + " and " + rtype + ")"
```
Comment (kmr-srbh) [inline src/lfortran/semantics/ast_body_visitor.cpp]:
```suggestion
                    "type mismatch (`" + ltype + "` and `" + rtype + "`)"
```

Comment (kmr-srbh) [inline src/lfortran/semantics/ast_body_visitor.cpp]: Can you please make the type to string utility return `derived` instead of `derived allocatable` for `ltype` in this case? I think we would need to pass the extracted type to it.

**Comment by kmr-srbh** [comment]
Thanks for this! Just the minor comments above, otherwise fine.

**Review by certik — APPROVED** [review]
