### PR TITLE
fix: use function return type for operator overloaded compare

### LINKED ISSUE #7876: Handle Struct array compare using operator overloading
MRE:
```fortran
module string_ops
  type :: string_t
    character(len=:), allocatable :: str
  end type
  interface operator(==)
    module procedure string_array_equal
  end interface
contains
  logical function string_array_equal(a, b)
    type(string_t), intent(in), allocatable :: a(:), b(:)
  end function
end module string_ops


program test
  use string_ops
  type(string_t), allocatable :: a(:), b(:)
 if (a == b) print *, "Hi"
end program test
```

LFortran Error:
```console
(base) jinang_shah@JNSLAP:~/Desktop/lfortran$ lfortran b.f90
semantic error: Expected logical expression in if statement, but recieved logical[:] instead
  --> b.f90:18:6
   |
18 |  if (a == b) print *, "Hi"
   |      ^^^^^^ logical[:] expression, expected logical
```

### PR DESCRIPTION
**Pull request by jinangshah21**
Fixes #7876

MRE to be handled in upcoming PR: 
```fortran
module operator_overloading_15_mod
  type :: string_t
    character(len=:), allocatable :: str
  end type
  interface operator(==)
    module procedure string_array_equal
  end interface
contains
  logical function string_array_equal(a, b)
    type(string_t), intent(in) :: a(:), b(:)
    integer :: i
    string_array_equal = .true.
    do i = 1, size(a)
      if (a(i)%str /= b(i)%str) then
        string_array_equal = .false.
        return
      end if
    end do
  end function
end module operator_overloading_15_mod

program operator_overloading_15
  use operator_overloading_15_mod
  type(string_t), allocatable :: a(:), b(:)
  allocate(a(1), b(1))
  a(1)%str = "Hello"
  b(1)%str = "HelloWorld"
  if (a == b) error stop
end program
```

### CODE REVIEW

File: integration_tests/template_commutative.f90 [hunk 1]
```diff
@@ -12,7 +12,8 @@ pure elemental function bin(x, y) result(bin)
         pure elemental function equal(x, y) result(equal)
             type(T), intent(in) :: x
             type(T), intent(in) :: y
-            type(T) :: equal
+            ! type(T) :: equal
+            logical :: equal
```
Comment (jinangshah21) [inline integration_tests/template_commutative.f90:16]: I changed this because in `visit_Compare` in AST->ASR we were directly making type `logical` but if it is an operator overloaded function we should use its return type.

Comment (certik) [reply integration_tests/template_commutative.f90:16]: That's fine --- make sense for `equal` to be logical.

**Comment by certik** [comment]
Looks good. I think you need to update reference results.

**Review by gxyd — APPROVED** [review]
Looks good to me, thanks @jinangshah21
