### PR TITLE
Resolve `Function_t` from `ExternalSymbol_t` in pass array_op

### LINKED ISSUE #1522: asr_to_llvm: module failed verification. Error: Call parameter type does not match function signature!
```fortran
module find_fit_module
contains

subroutine find_fit(expr)
interface
    function expr() result(y)
        real :: y(1)
    end function expr
end interface
end subroutine find_fit

end module find_fit_module

program example_primes

use find_fit_module, only: find_fit
implicit none

real :: data_x
integer :: i
call find_fit(expression)

contains

function expression() result(y)
real :: y(1)
end function expression

end program example_primes
```

> LFortran

```console
$ lfortran ./tests/temp.f90
; ModuleID = 'LFortran'
source_filename = "LFortran"

define void @__module_find_fit_module_find_fit(float ()* %expr) {
.entry:
  br label %return

return:                                           ; preds = %.entry
  ret void
}

declare float @expr()

define void @expression(float* %y) {
.entry:
  br label %return

return:                                           ; preds = %.entry
  ret void
}

define i32 @main(i32 %0, i8** %1) {
.entry:
  call void @_lpython_set_argv(i32 %0, i8** %1)
  %data_x = alloca float, align 4
  %i = alloca i32, align 4
  call void @__module_find_fit_module_find_fit(void (float*)* @expression)
  ret i32 0
}

declare void @_lpython_set_argv(i32, i8**)
code generation error: asr_to_llvm: module failed verification. Error:
Call parameter type does not match function signature!
void (float*)* @expression
 float ()*  call void @__module_find_fit_module_find_fit(void (float*)* @expression)



Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that must be fixed).
```

### PR DESCRIPTION
**Pull request by Pranavchiku**
Fixes #1522

### CODE REVIEW

File: src/libasr/pass/array_op.cpp [hunk 1]
```diff
@@ -1103,7 +1103,11 @@ class ArrayOpVisitor : public ASR::CallReplacerOnExpressionsVisitor<ArrayOpVisit
                                     }
                                     if ( is_arg ) {
                                         ASR::symbol_t* subrout = subrout_call->m_name;
-                                        if ( subrout->type == ASR::symbolType::Function ) {
+                                        if ( ASR::is_a<ASR::ExternalSymbol_t>(*subrout) ) {
+                                            ASR::ExternalSymbol_t* subrout_ext = ASR::down_cast<ASR::ExternalSymbol_t>(subrout);
+                                            subrout = subrout_ext->m_external;
+                                        }
+                                        if ( ASR::is_a<ASR::Function_t>(*subrout) ) {
```
Comment (czgdp1807) [inline src/libasr/pass/array_op.cpp:1110]: This should be harmless but can be condensed into,

```suggestion
                                        subrout = ASRUtils::symbol_get_past_external(subrout);
                                        if ( ASR::is_a<ASR::Function_t>(*subrout) ) {
```

**Review by czgdp1807 — CHANGES_REQUESTED** [review]

**Review by czgdp1807 — APPROVED** [review]

**Comment by Pranavchiku** [comment]
Thanks for completing this! I had a few quizzes today and hence was not able to apply the suggestions.
