### PR TITLE
fix: handle int64 values in read iostat

### LINKED ISSUE #10264: Handle int64 values for iostat read statements
Related to #5629

MRE:
```fortran
program tmp
      use iso_fortran_env, only: int64
      implicit none

      type :: string_t
          character(len=:), allocatable :: str
      end type

      type(string_t) :: val
      integer(int64) :: i1, istat

      val%str = "111"
      read(val%str, *, iostat=istat) i1  
      print*, i1, istat
      if (i1 /= 111) error stop
      if (istat /= 0) error stop

  end program
```

```
$ gfortran a.f90 & ./a.out
[1]+  Done                    gfortran a.f90
[1] 253181
                  111                    0

$ lfortran a.f90
code generation error: asr_to_llvm: module failed verification. Error:
Call parameter type does not match function signature!
  %istat = alloca i64, align 8
 i32*  call void @_lfortran_string_read_i64(i8* %10, i64 %12, i8* getelementptr inbounds ([4 x i8], [4 x i8]* @1, i32 0, i32 0), i64* %i1, i64* %istat)
```

### PR DESCRIPTION
**Pull request by YashNagda17**
Fixes #10264 
Towards #5629 

changes made:
- add llvm logic to handle int64 values inside iostat for read statements

### CODE REVIEW

File: src/libasr/codegen/asr_to_llvm.cpp [hunk 1]
```diff
@@ -14244,7 +14244,21 @@ class ASRToLLVMVisitor : public ASR::BaseVisitor<ASRToLLVMVisitor>
...
-                        builder->CreateCall(fn, { src_data, src_len, fmt, var_to_read_into, iostat });
+                        llvm::Value* iostat_arg = iostat;
+                        llvm::AllocaInst* tmp_iostat = nullptr;
+                        if (!llvm::isa<llvm::ConstantPointerNull>(iostat)) {
+                            llvm::AllocaInst* iostat_alloca = llvm::dyn_cast<llvm::AllocaInst>(iostat);
+                            if (iostat_alloca && !iostat_alloca->getAllocatedType()->isIntegerTy(32)) {
+                                tmp_iostat = builder->CreateAlloca(llvm::Type::getInt32Ty(context), nullptr, "tmp_iostat");
+                                iostat_arg = tmp_iostat;
+                            }
+                        }
```
Comment (certik) [inline src/libasr/codegen/asr_to_llvm.cpp:14255]: Is there a way to rewrite this logic using ASR types, instead of querying it the LLVM IR?

Comment (YashNagda17) [reply src/libasr/codegen/asr_to_llvm.cpp:14255]: Ohk, looking into it...
