### PR TITLE
Fix a bug in associate

### LINKED ISSUE #9704: Handle association of struct array reference to a scalar member
MRE:
```fortran
program mre
    implicit none

    type :: line_token
        integer :: first
    end type

    type(line_token), allocatable :: token(:)
    integer :: shift

    allocate(token(2))
    token%first = [2, 4]

    associate(first => token%first)
        shift = first(1) - 1
    end associate

    print *, shift
end program mre
```

LFortran Error:
```console
(lf) jinang_shah@JNSLAP:~/Desktop/lfortran$ lfortran d.f90
LCOMPILERS_ASSERT failed: /home/jinang_shah/Desktop/lfortran/src/libasr/codegen/llvm_utils.cpp
function create_gep2(), line number 1526 at
ds_pointee_type == t
ERROR MESSAGE:
Type mismatch in create_gep2: GEP target type does not match pointer's pointee type. This would cause crashes in LLVM <= 8 constant folder. Target type: %line_token = type { i32 }, Pointer pointee type: %line_token*
Traceback (most recent call last):
  Binary file "/home/jinang_shah/Desktop/lfortran/src/bin/lfortran", in _start
  File "./csu/../csu/libc-start.c", line 360, in __libc_start_main
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main
  File "/home/jinang_shah/Desktop/lfortran/src/bin/lfortran.cpp", line 2808, in main
    return main_app(argc, argv);
  File "/home/jinang_shah/Desktop/lfortran/src/bin/lfortran.cpp", line 2732, in main_app(int, char**)
    err = compile_src_to_object_file(arg_file, tmp_o, compiler_options.time_report, false,
  File "/home/jinang_shah/Desktop/lfortran/src/bin/lfortran.cpp", line 1249, in (anonymous namespace)::compile_src_to_object_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, LCompilers::CompilerOptions&, LCompilers::PassManager&, bool)
    res = fe.get_llvm3(*asr, lpm, diagnostics, lm, infile, &time_opt);
  File "/home/jinang_shah/Desktop/lfortran/src/lfortran/fortran_evaluator.cpp", line 380, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, LCompilers::LocationManager&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int*)
    compiler_options, run_fn, "", infile, lm);
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 18115, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::LocationManager&)
    v.visit_asr((ASR::asr_t&)asr);
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 361, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_asr(LCompilers::ASR::asr_t const&)
    void visit_asr(const asr_t &b) { visit_asr_t(b, self()); }
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 335, in void LCompilers::ASR::visit_asr_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::asr_t const&, LCompilers::ASRToLLVMVisitor&)
    case asrType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 362, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_unit(LCompilers::ASR::unit_t const&)
    void visit_unit(const unit_t &b) { visit_unit_t(b, self()); }
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 22, in void LCompilers::ASR::visit_unit_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::unit_t const&, LCompilers::ASRToLLVMVisitor&)
    case unitType::TranslationUnit: { v.visit_TranslationUnit((const TranslationUnit_t &)x); return; }
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 1580, in LCompilers::ASRToLLVMVisitor::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    visit_symbol(*item.second);
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 364, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 30, in void LCompilers::ASR::visit_symbol_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::symbol_t const&, LCompilers::ASRToLLVMVisitor&)
    case symbolType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4974, in LCompilers::ASRToLLVMVisitor::visit_Program(LCompilers::ASR::Program_t const&)
    this->visit_stmt(*x.m_body[i]);
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 381, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 92, in void LCompilers::ASR::visit_stmt_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::stmt_t const&, LCompilers::ASRToLLVMVisitor&)
    case stmtType::AssociateBlockCall: { v.visit_AssociateBlockCall((const AssociateBlockCall_t &)x); return; }
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9248, in LCompilers::ASRToLLVMVisitor::visit_AssociateBlockCall(LCompilers::ASR::AssociateBlockCall_t const&)
    this->visit_stmt(*(associate_block->m_body[i]));
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 381, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 58, in void LCompilers::ASR::visit_stmt_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::stmt_t const&, LCompilers::ASRToLLVMVisitor&)
    case stmtType::Associate: { v.visit_Associate((const Associate_t &)x); return; }
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 7068, in LCompilers::ASRToLLVMVisitor::visit_Associate(LCompilers::ASR::Associate_t const&)
    visit_expr(*x.m_value);
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 435, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_expr(LCompilers::ASR::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 193, in void LCompilers::ASR::visit_expr_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::expr_t const&, LCompilers::ASRToLLVMVisitor&)
    case exprType::StructInstanceMember: { v.visit_StructInstanceMember((const StructInstanceMember_t &)x); return; }
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4032, in LCompilers::ASRToLLVMVisitor::visit_StructInstanceMember(LCompilers::ASR::StructInstanceMember_t const&)
    tmp = llvm_utils->create_gep2(xtype, tmp, member_idx);
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/codegen/llvm_utils.cpp", line 1526, in LCompilers::LLVMUtils::create_gep2(llvm::Type*, llvm::Value*, int)
    LCOMPILERS_ASSERT_MSG(ds_pointee_type == t,
  File "./stdlib/./stdlib/abort.c", line 79, in abort
  File "./signal/../sysdeps/posix/raise.c", line 26, in raise
  File "./nptl/./nptl/pthread_kill.c", line 43, in pthread_kill
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in <invalid>
Abort: Signal SIGABRT (abort) received

Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by certik**
Test added.

Fixes #9704.

### CODE REVIEW

**Comment by jinangshah21** [comment]
```llvm
%array = type { i32*, i32, %dimension_descriptor*, i1, i32 }
%dimension_descriptor = type { i32, i32, i32 }
%array.0 = type { %line_token*, i32, %dimension_descriptor*, i1, i32 }
%line_token = type { i32 }
```

In this PR, we create temporary array of integer type and store `i32*` of first struct element, which will be invalid when we have more than one member. Consider below example and outputs:
```fortran
program mre
    implicit none

    type :: line_token
        integer :: first, second
    end type

    type(line_token), allocatable :: token(:)
    integer :: shift(4)

    allocate(token(4))
    token%first = [1, 2, 3, 4]

    associate(first => token%first)
        shift = first - 1
    end associate

    print *, shift
end program mre
```

Outputs:
```console
(base) jinang_shah@JNSLAP:~/Desktop/lfortran$ gfortran d.f90 && ./a.out
           0           1           2           3
(base) jinang_shah@JNSLAP:~/Desktop/lfortran$ lfortran d.f90
0    -1    1    -1
```

Here we need to copy member of all struct element in array (i.e. we need to iter to each struct element and store its member in local temporary array)

**Comment by certik** [comment]
Good catch! I am fixing it.

**Comment by certik** [comment]
I don't like the copying thing. Consider:
```diff
diff --git a/integration_tests/associate_24.f90 b/integration_tests/associate_24.f90
index 7d0112630..b039dd82e 100644
--- a/integration_tests/associate_24.f90
+++ b/integration_tests/associate_24.f90
@@ -13,7 +13,9 @@ program mre

     associate(first => token%first)
         shift = first - 1
+        first = first + 1
     end associate

     print *, shift
+    print *, token%first
 end program mre
```
This is broken currently:
```console
$ lfortran integration_tests/associate_24.f90
0    1    2    3
1    2    3    4
$ gfortran integration_tests/associate_24.f90 && ./a.out
           0           1           2           3
           2           3           4           5
```

**Comment by certik** [comment]
We should be using pointers, not array copy. So I am marking this as a Draft for now. All tests pass, so that's useful as a starting point.

**Comment by certik** [comment]
@assem2002 I reworked it to use pointers instead and improved the test using the case above that was failing before. Everything works for me locally at least.

File: src/libasr/codegen/asr_to_llvm.cpp [hunk 1]
```diff
@@ -6915,6 +6915,211 @@ class ASRToLLVMVisitor : public ASR::BaseVisitor<ASRToLLVMVisitor>
...
+            "component_dim_des");
+        builder->CreateStore(dim_des_array,
+            arr_descr->get_pointer_to_dimension_descriptor_array(target_desc_type, new_desc, false));
+
+        // Compute the stride multiplier: sizeof(struct) / sizeof(component)
+        // This is the number of component-sized elements between consecutive struct elements
+        llvm::DataLayout data_layout(module->getDataLayout());
+        uint64_t struct_size = data_layout.getTypeAllocSize(struct_llvm_type);
+        uint64_t component_size = data_layout.getTypeAllocSize(component_llvm_type);
+        uint64_t stride_multiplier = struct_size / component_size;
```
Comment (assem2002) [inline src/libasr/codegen/asr_to_llvm.cpp]: We should assert to avoid non integer -- `struct_size % component_size == 0`

File: src/libasr/codegen/asr_to_llvm.cpp [hunk 2]
```diff
@@ -6915,6 +6915,211 @@ class ASRToLLVMVisitor : public ASR::BaseVisitor<ASRToLLVMVisitor>
...
+
+                // Dimension size
+                llvm::Value* dim_size = llvm::ConstantInt::get(arr_descr->get_index_type(), 1);
+                if (dims[i].m_length) {
+                    visit_expr_wrapper(dims[i].m_length, true);
+                    dim_size = builder->CreateSExtOrTrunc(tmp, arr_descr->get_index_type());
+                }
+                builder->CreateStore(dim_size, arr_descr->get_dimension_size(target_dim_des, false));
+
+                // Stride for first dimension is stride_multiplier, for subsequent it's cumulative
```
Comment (assem2002) [inline src/libasr/codegen/asr_to_llvm.cpp]: I don't actually know. Do you think this is correct? If not let's add an assert to handle only 1D for now

**Review by assem2002 — APPROVED** [review]
Loos good for me. 
I think it would've been been better to use that exact same approach but with `visit_StructInstanceMember` itself.

**Comment by certik** [comment]
Thanks for the review. Yes, we should improve this. I think it's good enough to merge to unblock us, and then we'll improve it as we go.

**Comment by certik** [comment]
Thanks @jinangshah21. The exhaustive check Release build passed, so I am going to go ahead and merge this.

File: src/libasr/codegen/asr_to_llvm.cpp (hunk 1 above)
Comment (certik) [reply src/libasr/codegen/asr_to_llvm.cpp]: https://github.com/lfortran/lfortran/issues/9784

File: src/libasr/codegen/asr_to_llvm.cpp (hunk 2 above)
Comment (certik) [reply src/libasr/codegen/asr_to_llvm.cpp]: https://github.com/lfortran/lfortran/issues/9784
