### PR TITLE
parser: ignore ! directives unless --openmp

### LINKED ISSUE #6449: OpenMP directive is neither recognized nor treated as a comment
Code example:
```
module omp_module

   real (kind=8), dimension(:), allocatable :: arr
   !$omp threadprivate( arr )

end module omp_module

```
LFortran output:
```
syntax error: Token '!$omp threadprivate( arr )' (of type 'pragma') is unexpected here
 --> testlfort.f90:4:4
  |
4 |    !$omp threadprivate( arr )
  |    ^^^^^^^^^^^^^^^^^^^^^^^^^^ 


```

### PR DESCRIPTION
**Pull request by krystophny**
## Summary
- Treat OpenMP sentinel directives ! ... as comments when OpenMP is not enabled (no --openmp).
- Add integration test openmp_74 covering ! threadprivate in a module with OpenMP disabled.

- Fixes #6449 

## Tests
- integration_tests/openmp_74

### CODE REVIEW

File: src/lfortran/parser/parser.cpp [hunk 1]
```diff
@@ -237,6 +237,7 @@ Result<AST::TranslationUnit_t*> parse(Allocator &al, const std::string &s,
         diag::Diagnostics &diagnostics, const CompilerOptions &co)
 {
     Parser p(al, diagnostics, co.fixed_form, co.continue_compilation);
+    p.m_tokenizer.openmp_enabled = co.openmp;
```
Comment (certik) [inline src/lfortran/parser/parser.cpp]: Pass all these options into the constructor.
```suggestion
Parser p(al, diagnostics, co.fixed_form, co.continue_compilation, co.openmp);
```

**Comment by certik** [comment]
This is probably the way to fix it, otherwise we have to fiddle with the Bison grammar, which is more complex / fragile. So I think the above fix is good.

File: tests/reference/ast-pragma1-6b56efa.stdout [hunk 2]
```diff
@@ -94,17 +94,16 @@
...
-        [(Pragma
-            0
-            OMPPragma
-            .false.
-            "parallel do"
-            []
-            ()
-        )
-        (DoLoop
+        [(DoLoop
```
Comment (certik) [inline tests/reference/ast-pragma1-6b56efa.stdout]: Investigate if the pragma1 test was created to test the Pragma AST node. If so, then you need to provide the `--openmp` option to this test, to keep testing that. Since it now tests that pragma just becomes a comment, which is a totally different test.

File: run_tests.py [hunk 3]
```diff
@@ -155,10 +155,13 @@ def is_included(backend):
...
                 extra_args)
         else:
+            ast_cmd = "lfortran --show-ast --no-color {infile} -o {outfile}"
+            if asr_openmp:
+                ast_cmd = "lfortran --show-ast --no-color --openmp {infile} -o {outfile}"
             run_test(
                 filename,
                 "ast",
-                "lfortran --show-ast --no-color {infile} -o {outfile}",
+                ast_cmd,
```
Comment (certik) [inline run_tests.py:164]: I am trying to figure out what this change is doing --- is it changing the meaning of `ast`, based on if `asr_openmp` is present? If so, that doesn't seem like a good design.

Let's create `ast_openmp` if we need that.

Comment (certik) [reply run_tests.py:164]: You can do it in the next PR, so that we can get this one merged.

**Comment by certik** [comment]
I think this is good enough to merge. If you could please fix https://github.com/lfortran/lfortran/pull/9444#discussion_r2679111872 in a subsequent PR, I would really appreciate it.

**Comment by krystophny** [comment]
> I think this is good enough to merge. If you could please fix [#9444 (comment)](https://github.com/lfortran/lfortran/pull/9444#discussion_r2679111872) in a subsequent PR, I would really appreciate it.

Done in #9463
