### PR TITLE
fix: format reversion

### LINKED ISSUE #10125: I/O Format reversion not reverting correctly
Follow on to PR #9919:
```
program format_reversion
  implicit none

  integer :: ia_1d(20), ia_2d(10,2)

  integer :: i, j

  ia_1d(:) = [(i, i=1, 20)]
  do, j=1, 2
    do, i=1, 10
      ia_2d(i,j) = j*100 + i
    end do
  end do

  WRITE (*, 77751 ) 1, 2, 3, 9999,  &
     (ia_1d(i), i = 1, 20)
  print *, '-----------'

! Should repeat the 3(1I3), but instead is getting lost
! and doing some sort of i3,i4,3(i3) repetition.

  WRITE (*, 77752 ) 1, 2, 3, 9999,  &
     ((ia_2d(i,j), j = 1, 2), i = 1, 10)

77751 FORMAT ( 3(1I3), I4, 10(1I3) )
77752 FORMAT ( 3(1I3), I4, 3(1I3) )

end program
```
```
$ lfortran format_reversion.f90
  1  2  39999  1  2  3  4  5  6  7  8  9 10
 11  12 13 14 15 16 17 18 19 20
-----------
  1  2  39999101201102
202 103203104204
105 205106206107
207 108208109209
110 210
$
```
```
$ gfortran format_reversion.f90
$ ./a.out
  1  2  39999  1  2  3  4  5  6  7  8  9 10
 11 12 13 14 15 16 17 18 19 20
 -----------
  1  2  39999101201102
202103203
104204105
205106206
107207108
208109209
110210
$
```

### PR DESCRIPTION
**Pull request by HarshilShah1804**
Fixes #10125

### CODE REVIEW

File: integration_tests/file_53.f90 [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+! Should repeat the 3(1I3), but instead is getting lost
+! and doing some sort of i3,i4,3(i3) repetition.
+
+   WRITE (*, 77752 ) 1, 2, 3, 9999,  &
+      ((ia_2d(i,j), j = 1, 2), i = 1, 10)
+
+77751 FORMAT ( 3(1I3), I4, 10(1I3) )
+77752 FORMAT ( 3(1I3), I4, 3(1I3) )
+
+end program format_53
```
Comment (certik) [inline integration_tests/file_53.f90:28]: Register this in cmake to run in integration tests too.

**Review by certik — APPROVED** [review]

**Review by HarshitaKalani — APPROVED** [review]
