### PR TITLE
Bypass verification on expr_type

### LINKED ISSUE #3968: allocating using module variable and using module routine outside module throws error
> mms_copy.f90

```fortran
MODULE XX
  IMPLICIT NONE

  INTEGER, PUBLIC :: nx = 1000

END MODULE

MODULE mms_module

  USE XX, ONLY: nx

  IMPLICIT NONE
  REAL, ALLOCATABLE, DIMENSION(:), PUBLIC :: ref_flux

  REAL, ALLOCATABLE, DIMENSION(:), PUBLIC :: ref_fluxm

  CONTAINS

  SUBROUTINE mms_deallocate
  END SUBROUTINE mms_deallocate

  SUBROUTINE mms_allocate ( )
    ALLOCATE( ref_flux(nx), ref_fluxm(nx) )
  END SUBROUTINE mms_allocate
END MODULE mms_module
```

> dealloc.f90

```fortran
MODULE dealloc_module
  USE mms_module, ONLY: mms_deallocate
END MODULE dealloc_module
```

```console
% lfortran -c mms_copy.f90 && lfortran -c dealloc.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2459
    LCompilers::print_stack_on_segfault();
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2391
    return compile_to_object_file(arg_file, outfile, false,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 906
    result = fe.get_asr2(input, lm, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 252
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 274
    compiler_options.symtab_only, compiler_options);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 77
    if (res.ok) {
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 3457
    v.visit_TranslationUnit(ast);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 120
    visit_ast(*x.m_items[i]);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4878
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4834
    case astType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4881
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4465
    case modType::Module: { v.visit_Module((const Module_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 471
    visit_ModuleSubmoduleCommon<AST::Module_t, ASR::Module_t>(x);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 424
    visit_unit_decl1(*x.m_use[i]);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4890
    void visit_unit_decl1(const unit_decl1_t &b) { visit_unit_decl1_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4486
    case unit_decl1Type::Use: { v.visit_Use((const Use_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 2565
    t = (ASR::symbol_t*)(ASRUtils::load_module(al, tu_symtab,
  File "/Users/pranavchiku/repos/lfortran/src/libasr/asr_utils.cpp", line 308
    *symtab, intrinsic, pass_options);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/asr_utils.cpp", line 456
    ASR::TranslationUnit_t *asr = load_modfile(al, modfile, false, symtab);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/modfile.cpp", line 93
    ASR::asr_t *asr = deserialize_asr(al, asr_binary, load_symtab_id, symtab);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast_serialization.cpp", line 414
    Line not found
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast_serialization.cpp", line 430
    Line not found
  File "/Users/pranavchiku/repos/lfortran/src/libasr/asr_verify.cpp", line 1242
    v.visit_TranslationUnit(unit);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/asr_verify.cpp", line 111
    for (auto &a : x.m_symtab->get_scope()) {
  File "../libasr/asr.h", line 5143
  File "../libasr/asr.h", line 4855
  File "/Users/pranavchiku/repos/lfortran/src/libasr/asr_verify.cpp", line 333
    for (auto &a : x.m_symtab->get_scope()) {
  File "../libasr/asr.h", line 5143
  File "../libasr/asr.h", line 4856
  File "/Users/pranavchiku/repos/lfortran/src/libasr/asr_verify.cpp", line 454
    visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 5160
  File "../libasr/asr.h", line 4878
  File "/Users/pranavchiku/repos/lfortran/src/libasr/asr_verify.cpp", line 1218
    BaseWalkVisitor<VerifyVisitor>::visit_Allocate(x);
  File "../libasr/asr.h", line 5477
  File "../libasr/asr.h", line 6619
  File "/Users/pranavchiku/repos/lfortran/src/libasr/asr_verify.cpp", line 1171
    require_with_loc(ASRUtils::is_integer(
  File "../libasr/asr_utils.h", line 294
  File "../libasr/asr.h", line 50299
AssertFailed: e->m_external
```

### LINKED ISSUE #3977: AssertFailed: e->m_external
```console
$ make
lfortran  -c global.f90 -o global.o
lfortran  -c sn.f90 -o sn.o
lfortran  -c data.f90 -o data.o
lfortran  -c geom.f90 -o geom.o
lfortran  -c control.f90 -o control.o
cpp -P  time.0.F90 >time.f90
lfortran  -c time.f90
warning: Assuming implicit save attribute for variable declaration
  --> time.f90:60:25
   |
60 |     CHARACTER(LEN=1) :: star='*'
   |                         ^^^^^^^^ help: add explicit save attribute or initialize in a separate statement


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
cpp -P  plib.0.F90 >plib.f90
lfortran  -c plib.f90
lfortran  -c mms.f90 -o mms.o
warning: Assuming implicit save attribute for variable declaration
   --> mms.f90:522:25
    |
522 |     CHARACTER(LEN=1) :: star='*'
    |                         ^^^^^^^^ help: add explicit save attribute or initialize in a separate statement


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
lfortran  -c solvar.f90 -o solvar.o
lfortran  -c dealloc.f90 -o dealloc.o
Internal Compiler Error: Unhandled exception
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
BFD: DWARF error: invalid or unhandled FORM value: 0x23
Traceback (most recent call last):
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in _start()
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in __libc_start_main()
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in __libc_init_first()
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in main()
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in main_app(int, char**)
  File "lfortran.cpp", line 0, in (anonymous namespace)::compile_to_object_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, LCompilers::CompilerOptions&, LCompilers::PassManager&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::FortranEvaluator::get_asr2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::diag::Diagnostics&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::FortranEvaluator::get_asr3(LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::LFortran::ast_to_asr(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::SymbolTable*, bool, LCompilers::CompilerOptions&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::LFortran::symbol_table_visitor(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::SymbolTable*, LCompilers::CompilerOptions&, std::map<unsigned long, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > > > > >&, std::map<unsigned long, LCompilers::ASR::symbol_t*, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, LCompilers::ASR::symbol_t*> > >&, std::map<unsigned long, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >&, std::map<unsigned int, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > > > > >&, std::map<unsigned int, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::symbol_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::symbol_t*> > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::symbol_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::symbol_t*> > > > > >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> > > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> > > > > > > >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<int, std::allocator<int> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<int, std::allocator<int> > > > >&, std::vector<LCompilers::ASR::stmt_t*, std::allocator<LCompilers::ASR::stmt_t*> >&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::LFortran::SymbolTableVisitor::visit_TranslationUnit(LCompilers::LFortran::AST::TranslationUnit_t const&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::SymbolTableVisitor>::visit_ast(LCompilers::LFortran::AST::ast_t const&)
  File "ast_symboltable_visitor.cpp", line 0, in void LCompilers::LFortran::AST::visit_ast_t<LCompilers::LFortran::SymbolTableVisitor>(LCompilers::LFortran::AST::ast_t const&, LCompilers::LFortran::SymbolTableVisitor&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::SymbolTableVisitor>::visit_mod(LCompilers::LFortran::AST::mod_t const&)
  File "ast_symboltable_visitor.cpp", line 0, in void LCompilers::LFortran::AST::visit_mod_t<LCompilers::LFortran::SymbolTableVisitor>(LCompilers::LFortran::AST::mod_t const&, LCompilers::LFortran::SymbolTableVisitor&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::LFortran::SymbolTableVisitor::visit_Module(LCompilers::LFortran::AST::Module_t const&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in void LCompilers::LFortran::SymbolTableVisitor::visit_ModuleSubmoduleCommon<LCompilers::LFortran::AST::Module_t, LCompilers::ASR::Module_t>(LCompilers::LFortran::AST::Module_t const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::SymbolTableVisitor>::visit_unit_decl1(LCompilers::LFortran::AST::unit_decl1_t const&)
  File "ast_symboltable_visitor.cpp", line 0, in void LCompilers::LFortran::AST::visit_unit_decl1_t<LCompilers::LFortran::SymbolTableVisitor>(LCompilers::LFortran::AST::unit_decl1_t const&, LCompilers::LFortran::SymbolTableVisitor&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::LFortran::SymbolTableVisitor::visit_Use(LCompilers::LFortran::AST::Use_t const&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::ASRUtils::load_module(Allocator&, LCompilers::SymbolTable*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::Location const&, bool, LCompilers::PassOptions&, bool, std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::Location const&)>)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::ASRUtils::find_and_load_module(Allocator&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::SymbolTable&, bool, LCompilers::PassOptions&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::load_modfile(Allocator&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, LCompilers::SymbolTable&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::deserialize_asr(Allocator&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, LCompilers::SymbolTable&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::deserialize_asr(Allocator&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::asr_verify(LCompilers::ASR::TranslationUnit_t const&, bool, LCompilers::diag::Diagnostics&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::ASR::VerifyVisitor::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::ASR::BaseVisitor<LCompilers::ASR::VerifyVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
  File "asr_verify.cpp", line 0, in void LCompilers::ASR::visit_symbol_t<LCompilers::ASR::VerifyVisitor>(LCompilers::ASR::symbol_t const&, LCompilers::ASR::VerifyVisitor&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::ASR::VerifyVisitor::visit_Module(LCompilers::ASR::Module_t const&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::ASR::BaseVisitor<LCompilers::ASR::VerifyVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
  File "asr_verify.cpp", line 0, in void LCompilers::ASR::visit_symbol_t<LCompilers::ASR::VerifyVisitor>(LCompilers::ASR::symbol_t const&, LCompilers::ASR::VerifyVisitor&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::ASR::VerifyVisitor::visit_Function(LCompilers::ASR::Function_t const&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::ASR::BaseVisitor<LCompilers::ASR::VerifyVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
  File "asr_verify.cpp", line 0, in void LCompilers::ASR::visit_stmt_t<LCompilers::ASR::VerifyVisitor>(LCompilers::ASR::stmt_t const&, LCompilers::ASR::VerifyVisitor&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::ASR::VerifyVisitor::visit_Allocate(LCompilers::ASR::Allocate_t const&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::ASR::BaseWalkVisitor<LCompilers::ASR::VerifyVisitor>::visit_Allocate(LCompilers::ASR::Allocate_t const&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::ASR::BaseWalkVisitor<LCompilers::ASR::VerifyVisitor>::visit_alloc_arg(LCompilers::ASR::alloc_arg_t const&)
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in LCompilers::ASR::VerifyVisitor::visit_dimension(LCompilers::ASR::dimension_t const&)
  File "asr_verify.cpp", line 0, in LCompilers::ASRUtils::expr_type(LCompilers::ASR::expr_t const*)
AssertFailed: e->m_external
make: *** [Makefile:147: dealloc.o] Error 1
```

Possibly a duplicate of #3968.

### PR DESCRIPTION
**Pull request by assem2002**
closes #3968 , closes #3977 
I tried to bypass only the statements that would raise an error. @certik

### CODE REVIEW

File: src/libasr/asr_verify.cpp [hunk 1]
```diff
@@ -1161,16 +1163,20 @@ class VerifyVisitor : public BaseWalkVisitor<VerifyVisitor>
...
     void visit_dimension(const dimension_t &x) {
         if (x.m_start) {
-            require_with_loc(ASRUtils::is_integer(
-                *ASRUtils::expr_type(x.m_start)),
-                "Start dimension must be a signed integer", x.loc);
+            if(check_external){
+                require_with_loc(ASRUtils::is_integer(
+                    *ASRUtils::expr_type(x.m_start)),
+                    "Start dimension must be a signed integer", x.loc);
+            }
```
[the remark this answers is not in the document]
Comment (assem2002) [reply src/libasr/asr_verify.cpp:1170]: I don't quite get what you mean. We're trying to bypass every call to expr_type() when check_external is set to false.
I'm trying to follow the second possible solution mentioned here https://github.com/lfortran/lfortran/issues/3968#issuecomment-2152990288.

[the remark this answers is not in the document]
Comment (kmr-srbh) [reply src/libasr/asr_verify.cpp:1170]: Given https://github.com/lfortran/lfortran/issues/3968#issuecomment-2152990288, I think we should be doing `if (!check_external)`. This ensures that we do the verification when we are not checking for external symbols, and skip them otherwise.

With that being said, I think we need this check for external symbols as we cannot be sure of their type otherwise.

[the remark this answers is not in the document]
Comment (certik) [reply src/libasr/asr_verify.cpp:1170]: This change seems correct to me. `check_external` is true if we want to check ExternalSymbols. 

We can't check for them after deserialization, including indirectly via `expr_type`, so we skip it. 

We check for them alter when ASR is fully loaded and ExternalSymbols resolved.

File: src/libasr/asr_verify.cpp [hunk 2]
```diff
@@ -1209,13 +1215,15 @@ class VerifyVisitor : public BaseWalkVisitor<VerifyVisitor>
...
+        if(check_external){
+            for( size_t i = 0; i < x.n_args; i++ ) {
+                require(ASR::is_a<ASR::Allocatable_t>(*ASRUtils::expr_type(x.m_args[i].m_a)) ||
+                        ASR::is_a<ASR::Pointer_t>(*ASRUtils::expr_type(x.m_args[i].m_a)),
+                    "Allocate should only be called with  Allocatable or Pointer type inputs, found " +
+                    std::string(ASRUtils::get_type_code(ASRUtils::expr_type(x.m_args[i].m_a))));
+            }
+            BaseWalkVisitor<VerifyVisitor>::visit_Allocate(x);
         }
-        BaseWalkVisitor<VerifyVisitor>::visit_Allocate(x);
```
Comment (certik) [inline src/libasr/asr_verify.cpp:1218]: Does this need to be in the if statement?

**Review by certik — COMMENTED** [review]
Thanks for fixing this. I think it is the correct change.

I don't understand why the 3rd party CI test fails, we need to investigate it. Master seems to pass.

File: src/libasr/asr_verify.cpp (hunk 2 above)
Comment (certik) [reply src/libasr/asr_verify.cpp:1218]: This is the only change that I can think of could cause the CI failure. But not sure how currently. Still I think this should stay out of the if statement.

Comment (assem2002) [reply src/libasr/asr_verify.cpp:1218]: It invokes `visit_dimension()` which we handled already. I'm trying to do the smallest amount of damage to the verification phase :)

Comment (certik) [reply src/libasr/asr_verify.cpp:1218]: I think we don't need to skip it here, do we? We skip the external symbol in visit_dimension.

**Comment by assem2002** [comment]
> Thanks for fixing this. I think it is the correct change.
> 
> I don't understand why the 3rd party CI test fails, we need to investigate it. Master seems to pass.

I'll try to build the fpm package locally on my machine to see the reason behind the failing test.

File: src/libasr/asr_verify.cpp (hunk 2 above)
Comment (assem2002) [reply src/libasr/asr_verify.cpp:1218]: Yeah we do.

Comment (assem2002) [reply src/libasr/asr_verify.cpp:1218]: I'll push an new edit now.

**Comment by certik** [comment]
Ok, the last change fixed the CI. Not sure still how, but it must have something to do with the dependencies.

**Review by certik — APPROVED** [review]

**Comment by assem2002** [comment]
> Ok, the last change fixed the CI. Not sure still how, but it must have something to do with the dependencies.

Yeah. I don't know how passing a check point could cause such a problem.

**Comment by certik** [comment]
I think by skipping the visitor, we skipped visiting the dependencies (say for things like `allocate(x(number_of_rows ()))`), so the `number_of_rows()` function wasn't inserted into dependencies by the verifier, so it thought that it is superfluous in the failure:
```
ASR verify pass error: Function read_lines doesn't depend on number_of_rows but is found in its dependency list.
```

**Comment by assem2002** [comment]
Yeah that was the case. 
Thank you for helping me through this.

File: src/libasr/asr_verify.cpp (hunk 1 above)
[the remark this answers is not in the document]
Comment (kmr-srbh) [reply src/libasr/asr_verify.cpp:1170]: This is a bit confusing. `check_external` is `true` when we want to check for external symbols and we we wish to skip it here during ASR verification. I think we always want to verify external symbols so `check_external` is always `true`. The point of confusion for me is, when checking for external symbols, won't the above code translate to the below idea?
```
if (checking for external symbols) {
    check type of all symbols, including external ones
}
```
In the below program, `r` is an `ExternalSymbol`, but it is verified for the above condition, which is correct, but we do not skip it here.
> test_module.f90
```fortan
MODULE test_module
   IMPLICIT NONE
   REAL :: r = 5.67
END MODULE test_module
```
> example.f90
```fortran
PROGRAM test_program
   USE test_module
   IMPLICIT NONE

   INTEGER, DIMENSION(r) :: arr
   arr = [1, 2, 3, 4, 5]

   PRINT *, arr
END PROGRAM test_program
```
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran -c ./examples/test_module.f90
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
check external: 1
ASR verify pass error: Length dimension must be a signed integer
 --> ./examples/example.f90:5:23
  |
5 |    INTEGER, DIMENSION(r) :: arr
  |                       ^ failed here


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```
The changes fix the issue. I would be grateful to you if you could please help me understand why they do so.

[the remark this answers is not in the document]
Comment (assem2002) [reply src/libasr/asr_verify.cpp:1170]: when we import a mod file we first deserialize it then we call `asr_verify` on that mod file we just deserialized (notice that the call to `asr_verify` has its `check_external` parameter set to false ). after we load all mod files and verify them . we start to verify all of the imported mod files with `check_external` set to true so that's way the error you mention shows up.(you can check the first figure https://github.com/lfortran/lfortran/pull/4158#issue-2336658889 also).
BTW this example supposed to be invalid Fortran code, I think we have an issue opened for that.
