### PR TITLE
fix: real array cast to complex array

### LINKED ISSUE #3372: Handle type mismatch for `real` to `complex` array initialization
```
program main
    complex(8) :: D(3) = [1.0, 2.0, 3.0]
    print*, D
end
```

This code gives an error as real numbers are used to initialize a complex array. Refer: https://github.com/lfortran/lfortran/pull/3344 to fix this.

### PR DESCRIPTION
**Pull request by gxyd**
and use more clear name for defaultCase for casting

fixes #3372

### CODE REVIEW

**Review by certik — APPROVED** [review]
I think this is fine. @czgdp1807 can you please review this as well?

File: integration_tests/types_real_array_to_complex_array_cast.f90 [hunk 1]
```diff
@@ -0,0 +1,5 @@
+program types_real_array_to_complex_array_cast
+    complex(8) :: D(3) = [1.0, 2.0, 3.0]
+    print *, D
```
Comment (czgdp1807) [inline integration_tests/types_real_array_to_complex_array_cast.f90:3]: Add `if (any(D /= [1.0, 2.0, 3.0])) error stop`

File: integration_tests/types_real_to_complex_cast.f90 [hunk 2]
```diff
@@ -0,0 +1,8 @@
+program types_real_to_complex_cast
+    complex(8) :: c
+    real :: i
+    c = 1.0
+    i = 1.2
+    c = i
```
Comment (czgdp1807) [inline integration_tests/types_real_to_complex_cast.f90:6]: Add `if( abs(c - 1.2) > 1e-8 ) error stop`

**Review by czgdp1807 — DISMISSED** [review]

File: integration_tests/types_real_array_to_complex_array_cast.f90 (hunk 1 above)
Comment (gxyd) [reply integration_tests/types_real_array_to_complex_array_cast.f90]: Thanks, that makes more sense. I've made this change, and seems like there is a bug in inequality comparison of complex numbers. I've raised the relevant issue here: https://github.com/lfortran/lfortran/issues/3417.

File: integration_tests/types_real_to_complex_cast.f90 (hunk 2 above)
Comment (gxyd) [reply integration_tests/types_real_to_complex_cast.f90:6]: Done, I've used 1e-6 as tolerance. Since I was getting `4.76837158647214210e-08` as the difference.

**Comment by gxyd** [comment]
I've addressed the comments (and as always, I prefer if the commits can be squashed into one, if things looks good for merge).

File: integration_tests/types_real_to_complex_cast.f90 [hunk 3]
```diff
@@ -0,0 +1,8 @@
+program types_real_to_complex_cast
```
Comment (certik) [inline integration_tests/types_real_to_complex_cast.f90:1]:
```
integer, parameter :: dp = kind(0.d0)

File: integration_tests/types_real_to_complex_cast.f90 [hunk 4]
```diff
@@ -0,0 +1,8 @@
...
+    complex(8) :: c
+    real :: i
+    c = 1.0
```
Comment (certik) [inline integration_tests/types_real_to_complex_cast.f90:4]:
```suggestion
    c = 1.0_dp
```

File: integration_tests/types_real_to_complex_cast.f90 [hunk 5]
```diff
@@ -0,0 +1,8 @@
...
+    i = 1.2
+    c = i
+    if (abs(c - 1.2) > 1e-6) error stop
```
Comment (certik) [inline integration_tests/types_real_to_complex_cast.f90:7]:
```suggestion
    if (abs(c - 1.2_dp) > 1e-12_dp) error stop
```

File: integration_tests/types_real_to_complex_cast.f90 (hunk 2 above)
Comment (certik) [reply integration_tests/types_real_to_complex_cast.f90:6]: That's always a sign of a double/single precision corruption. It's time to add warnings to LFortran for this, since even @czgdp1807 still makes this mistake. :)

File: integration_tests/types_real_array_to_complex_array_cast.f90 [hunk 6]
```diff
@@ -0,0 +1,4 @@
+program types_real_array_to_complex_array_cast
```
Comment (certik) [inline integration_tests/types_real_array_to_complex_array_cast.f90:1]:
```
integer, parameter :: dp = kind(0.d0)
```

File: integration_tests/types_real_array_to_complex_array_cast.f90 [hunk 7]
```diff
@@ -0,0 +1,4 @@
...
+    complex(8) :: D(3) = [1.0, 2.0, 3.0]
```
Comment (certik) [inline integration_tests/types_real_array_to_complex_array_cast.f90:2]:
```suggestion
    complex(dp) :: D(3) = [1.0_dp, 2.0_dp, 3.0_dp]
```

File: integration_tests/types_real_array_to_complex_array_cast.f90 [hunk 8]
```diff
@@ -0,0 +1,4 @@
...
+    if (any(D /= [(1.0, 0.0), (2.0, 0.0), (3.0, 0.0)])) error stop
```
Comment (certik) [inline integration_tests/types_real_array_to_complex_array_cast.f90:3]: Append `_dp` everywhere.

**Comment by gxyd** [comment]
I've resolved your comments @certik. The use of double precision at recommended place now makes sense. I'll open a separate issue to raise warning for (possibly) unintentional change of precision, as I think that might require changes in a already existing test files as well.

**Comment by certik** [comment]
> I'll open a separate issue to raise warning for (possibly) unintentional change of precision, as I think that might require changes in a already existing test files as well.

It's part of this issue: https://github.com/lfortran/lfortran/issues/363

File: integration_tests/types_real_to_complex_cast.f90 [hunk 9]
```diff
@@ -0,0 +1,9 @@
+program types_real_to_complex_cast
+    integer, parameter :: dp = kind(0.d0)
+    complex(dp) :: c
+    real(dp) :: i
+    c = 1.0_dp
+    i = 1.2_dp
+    c = i
+    if (abs(c - 1.2_dp) > 1e-8) error stop
```
Comment (certik) [inline integration_tests/types_real_to_complex_cast.f90:8]:
```suggestion
    if (abs(c - 1.2_dp) > 1e-12_dp) error stop
```

**Comment by gxyd** [comment]
Fixed that one comment. Probably should be good now.

**Review by certik — APPROVED** [review]
I think that's good now, thanks!
