### PR TITLE
Solving Long BOZ Strings Truncations

### LINKED ISSUE #8253: Stoull Error when passing BOZ Literals larger than 64 Bits
MRE:
```
program long_boz
implicit none
integer::a = INT(z'F111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111')
PRINT *,a
end program
```

```
$ lfortran a.f90
std::exception: stoull
```

```
$gfortran a.f90 
a.f90:4:132:
    4 | nteger::a = INT(z'F111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111')
      |                                                                                                                                   1
Error: Line truncated at (1) [-Werror=line-truncation]
a.f90:4:132:
    4 | nteger::a = INT(z'F111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111')
      |                                                                                                                                   1
Error: Illegal character in BOZ constant at (1)
```

Stoull is a C++ Function, that converts BOZ to Unsigned Bits, which accepts only upto 64 Bits characters. So, an error message needs to be added, for passing BOZ Literals larger than 64 Bits.

### PR DESCRIPTION
**Pull request by YashNagda17**
Fixes #8253 

Truncating Most Significant Bits, for handling large BOZ Strings. Behavior consistent with flang and gfortran. Removed previous error throwing logic, and it's test. 

MRE:
```
program integer_boz_01
    implicit none
    integer:: boz_2 = int(Z'234567890abcdef1')
    integer:: boz_3 = int(Z'2234567890abcdef1')
    PRINT *, boz_2
    PRINT *, boz_3
end program
```

AMD Flang:
```
$ flang a.f90 & ./a.out
[1] 8284
180150001
180150001
F90-W-0015-Hexadecimal or octal constant truncated to fit data type (a.f90: 5)
```

gfortran:
```
$ gfortran a.f90 & ./a.out
[1] 50775
   180150001
   180150001
```

Updated Code:
```
$ lfortran a.f90
warning: BOZ literal constant with 'Z' prefix truncated to maximum 16 characters from left to fit data type
 --> a.f90:4:27
  |
4 |     integer:: boz_3 = int(Z'2234567890abcdef1')
  |                           ^^^^^^^^^^^^^^^^^^^^ BOZ truncation


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
180150001
180150001
```

### CODE REVIEW

File: integration_tests/boz_01.f90 [hunk 1]
```diff
@@ -1,11 +1,15 @@
...
-integer :: boz_1, boz_2, boz_3 
+integer :: boz_1, boz_2, boz_3, boz_4, boz_5
 
 boz_1 = int(b'01011101')
 boz_2 = int(o'2347')
 boz_3 = int(z'ABC')
+!Testing Truncation of BOZ
+boz_4 = int(Z'234567890abcdef1')
+boz_5 = int(Z'2234567890abcdef1')
+if (boz_4 /= boz_5) stop
```
Comment (certik) [inline integration_tests/boz_01.f90]: You must exit with an error:
```suggestion
if (boz_4 /= boz_5) error stop
```

File: integration_tests/boz_01.f90 [hunk 2]
```diff
@@ -1,11 +1,15 @@
...
 
 print *, boz_1, boz_2, boz_3
```
Comment (certik) [inline integration_tests/boz_01.f90]: After this, can you also add tests of this kind:
```fortran
if (boz_1 /= 123) error stop
```
And do it for all `boz_1`, ..., `boz_5` and test for the actual exact integer value that these variables should be equal to.

**Comment by certik** [comment]
Awesome, thanks!
