### PR TITLE
ASR Verify: visit function signature

### LINKED ISSUE #3264: Incorrect dependency injected for function
Requested in #3046.
```fortran
pure function linspace_n_1_cdp_cdp(n) result(res)
integer, intent(in) :: n

complex :: res(max(n, 0))
end function linspace_n_1_cdp_cdp
```

> LFortran

```console
% lfortran a.f90 --show-llvm
ASR verify pass error: ASR verify: Function linspace_n_1_cdp_cdp doesn't depend on _lcompilers_max0_i321 but is found in its dependency list.
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2371
    LCompilers::print_stack_on_segfault();
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2257
    return emit_llvm(arg_file, lfortran_pass_manager,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 847
    = fe.get_llvm(input, lm, pass_manager, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 292
    Result<std::unique_ptr<LLVMModule>> res = get_llvm2(code, lm, pass_manager, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 314
    diagnostics, lm.files.back().in_filename);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 360
    compiler_options, run_fn, infile);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9545
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 302
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 166
    throw LCompilersException("Verify failed in the pass: "
LCompilersException: Verify failed in the pass: intrinsic_function
```

### PR DESCRIPTION
**Pull request by Pranavchiku**
Fixes #3264, towards #3046.

With this PR we get `example_linspace_int16` working.

### CODE REVIEW

File: integration_tests/arrays_38.f90 [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+end function linspace_n_1_cdp_cdp
+
+program arrays_38
+implicit none
+integer :: n, i
+complex :: res(5)
+interface
+pure function linspace_n_1_cdp_cdp(n) result(res)
+integer, intent(in) :: n
+complex :: res(max(n, 0))
```
Comment (certik) [inline integration_tests/arrays_38.f90:15]:
```suggestion
    pure function linspace_n_1_cdp_cdp(n) result(res)
    integer, intent(in) :: n
    complex :: res(max(n, 0))
```

File: integration_tests/arrays_38.f90 [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+end function linspace_n_1_cdp_cdp
+end interface
+
+res = linspace_n_1_cdp_cdp(5)
+print *, res
+do i = 1, 5
+    if (abs(res(i) - (1.0, 3.0)) > 1e-8) error stop
+end do
```
Comment (certik) [inline integration_tests/arrays_38.f90:23]: Can you also add a test (in subsequent PR) for `linspace_n_1_cdp_cdp(-3)`? Ensuring everything works.

**Review by certik — APPROVED** [review]

**Review by certik — APPROVED** [review]
Looks great!
