### PR TITLE
fix: add deallocate statement for allocatable arrays for assignments between global array and temporary created

### LINKED ISSUE #10351: High Memory usage when allocating array to a scalar inside subroutine
Towards #5629

For the given n, program reaches maximum memory of 25GB, and it segfaults for higher values of n
MRE:
```fortran
program problem_12_mre

    implicit none
    integer, parameter :: n = 200  ! interior grid size
    integer :: i, j
    integer,  dimension(:,:,:), allocatable :: perimeter
    do i = 1, n
        do j = 1, n
            if (allocated(perimeter)) deallocate(perimeter)
            call go()
            print *, i,j
        end do
    end do

    contains
        subroutine go()
            if (.not. allocated(perimeter)) then
                allocate(perimeter(4, n, n)) 
                perimeter = 0 ! Commenting this line, code works fine, with usual memory consumption around 60KB
            end if
        end subroutine go

end program problem_12_mre
```

Main:
```
/usr/bin/time -v lfortran a.f90

Command being timed: "lfortran a.f90"
        User time (seconds): 14.38
        System time (seconds): 6.68
        Percent of CPU this job got: 99%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:21.07
        Maximum resident set size (kbytes): 25166508 

$ gfortran a.f90
$ /usr/bin/time -v ./a.out

Command being timed: "./a.out"
        User time (seconds): 1.54
        System time (seconds): 0.03
        Percent of CPU this job got: 92%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:01.70
        Maximum resident set size (kbytes): 2744
```

### PR DESCRIPTION
**Pull request by YashNagda17**
Fixes #10351
Towards #5629

Changes made:
- Add a deallocate statement for assignments between global arrays and local temporaries created for subroutine, to avoid memory leakage.
- This reduced overall memory usage for given code, from 1.5GB to 65 MB.

### CODE REVIEW

**Comment by YashNagda17** [comment]
I have kept bounds small, as we dont slow our CI for this test. For test-case in #10351, memory 
usage is the same (around 65MB), and the runtime reduced to upto 16 sec from 20 seconds seen originally in the issue.
Memory usage of this code before and after the fix (in debug mode)

Before Fix:
```
$ /usr/bin/time -v lfortran a.f90
        Command being timed: "lfortran a.f90"
        User time (seconds): 0.95
        System time (seconds): 0.46
        Percent of CPU this job got: 99%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:01.42
        Maximum resident set size (kbytes): 1605212
```

After Fix:
```
$ /usr/bin/time -v lfortran a.f90
        Command being timed: "lfortran a.f90"
        User time (seconds): 1.17
        System time (seconds): 0.09
        Percent of CPU this job got: 99%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:01.26
        Maximum resident set size (kbytes): 64984
```

**Comment by certik** [comment]
Can you please rebase it? Let's run full tests after that.

File: integration_tests/arrays_110.f90 [hunk 1]
```diff
@@ -0,0 +1,25 @@
+! This program caused a segfault due to memory leak in ReAlloc Node inside array_op pass
+program arrays_109
```
Comment (certik) [inline integration_tests/arrays_110.f90]:
```suggestion
program arrays_110
```

File: integration_tests/arrays_110.f90 [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+    end do
+    contains
+    subroutine go(i)
+        integer, intent(in) :: i
+        if (.not. allocated(perimeter)) then
+            allocate(perimeter(4, n, n)) 
+            perimeter = i
+        end if
+    end subroutine go
+end program arrays_109
```
Comment (certik) [inline integration_tests/arrays_110.f90]:
```suggestion
end program arrays_110
```

File: integration_tests/arrays_110.f90 [hunk 3]
```diff
@@ -0,0 +1,25 @@
+! This program caused a segfault due to memory leak in ReAlloc Node inside array_op pass
+program arrays_109
+    implicit none
+    integer, parameter :: n = 100
```
Comment (certik) [inline integration_tests/arrays_110.f90]: This takes over 3s:
```
2087/2593 Test  #406: arrays_110 .........................................   Passed    3.04 sec
```
Way too slow. It must take 0.00s. So reduce this number so that the test runs instantly.

**Review by certik — COMMENTED** [review]
Otherwise I think this is good.

**Comment by certik** [comment]
Looks good. Please rebase.

File: src/libasr/pass/array_op.cpp [hunk 4]
```diff
@@ -1371,6 +1371,17 @@ class ArrayOpVisitor: public ASR::CallReplacerOnExpressionsVisitor<ArrayOpVisito
         // Don't generate a loop for a move assignment
         // The assignment should be handled in the backend
         if (x.m_move_allocation) {
+            if (ASRUtils::is_allocatable(ASRUtils::expr_type(x.m_target)) && vars.size() != 1) {
+                // ReAlloc was inserted for an allocatable target in previous part,
+                // but the move assignment overwrites target.data
+                // with value.data — leaking the buffer ReAlloc just allocated.
+                // Free it first to avoid this memory leak.
```
Comment (certik) [inline src/libasr/pass/array_op.cpp]: Please comment here to mention that we still have a bug in the backend that should have deallocated this array. But this fix is good.

**Comment by certik** [comment]
Sorry, one more rebase please.

**Comment by certik** [comment]
@YashNagda17 thanks, please ping me once it passes, so that we can merge it.
