### PR TITLE
fix: allocate the variable before assignment if value type is function call

### LINKED ISSUE #9013: Handle allocatable type variable assigned to function call returning derived type
MRE:
```fortran
program mre1
    type :: temp
      integer, allocatable :: arr(:)
    end type 
    type(temp), allocatable :: x
    x = parse_temp()
contains
    function parse_temp() result(res)
          type(temp) :: res
          allocate(res%arr(2))
    end function
end program
```

LFortran segfaults on it.

### PR DESCRIPTION
**Pull request by HarshilShah1804**
Fixes #9013

### CODE REVIEW

File: src/lfortran/semantics/ast_body_visitor.cpp [hunk 1]
```diff
@@ -3710,6 +3710,25 @@ class BodyVisitor : public CommonVisitor<BodyVisitor> {
...
+                alloc_arg.m_len_expr = nullptr;
+                alloc_arg.m_sym_subclass = nullptr;
+                alloc_arg.m_type = nullptr;
+                Vec<ASR::alloc_arg_t> alloc_args;
+                alloc_args.reserve(al, 1);
+                alloc_args.push_back(al, alloc_arg);
+                ASR::stmt_t* alloc_stmt = ASRUtils::STMT(ASR::make_Allocate_t(al, target->base.loc,
+                                            alloc_args.p, alloc_args.n,
+                                            nullptr, nullptr, nullptr));
+                current_body->push_back(al, alloc_stmt);
```
Comment (certik) [inline src/lfortran/semantics/ast_body_visitor.cpp]: I think this is not the right fix. Consider:
```diff
--- a/integration_tests/functions_53.f90
+++ b/integration_tests/functions_53.f90
@@ -4,10 +4,11 @@ program functions_53
       integer, allocatable :: arr(:)
     end type
     type(temp), allocatable :: x
+    allocate(x)
     x = parse_temp()
 contains
     function parse_temp() result(res)
```
Now there are 2 allocate in ASR:
```
[(Allocate
                        [((Var 2 x)
                        []
                        ()
                        ()
                        ())]
                        ()
                        ()
                        ()
                    )
                    (Allocate
                        [((Var 2 x)
                        []
                        ()
                        ()
                        ())]
                        ()
                        ()
                        ()
                    )
                    (Assignment
                        (Var 2 x)
                        (FunctionCall
                            2 parse_temp
                            ()
                            []
                            (StructType
                                [(Allocatable
                                    (Array
                                        (Integer 4)
                                        [(()
                                        ())]
                                        DescriptorArray
                                    )
                                )]
                                []
                                .true.
                                .false.
                            )
                            ()
                            ()
                        )
                        ()
                        .false.
                        .false.
                    )]
```
And two allocations like this should fail in Debug mode (it currently doesn't but that's another bug: https://github.com/lfortran/lfortran/issues/9028).


This has to be fixed in ASR->LLVM. This is related to automatic reallocation of LHS. We do it for scalars, but not arrays.

Comment (HarshilShah1804) [reply src/lfortran/semantics/ast_body_visitor.cpp]: Okay. I'll change that.

Comment (HarshilShah1804) [reply src/lfortran/semantics/ast_body_visitor.cpp]: So, upon deeper inspection, I found out that we are not having any assignment node only in the final ASR. In the `subroutine_from_functions` pass, we transform the assignment statement to a subroutine call. So, I was not able to figure out how to handle it in LLVM. Now, I have thought of two approaches:

1. We can either keep the transformation as it is and then handle the unallocated structs in the generating code subroutine call in the backend. 
2. We keep the assignment statement and handle it while generating code for assignment statement.

We also generate wrong Fortran (and probably the ASR even) as the Fortran code generated using `--dump-all-passes-fortarn` also segfault with GFortran. So, I believe we should keep the assignment statement as it is and to get correct ASR and then handle it in the backend similar to automatic reallocation of scalars.

@certik Can you also please suggest which of the two would be a better approach.

Comment (HarshilShah1804) [reply src/lfortran/semantics/ast_body_visitor.cpp]: This input code:
```fortran
program mre1
    type :: temp
      integer, allocatable :: arr(:)
    end type 
    type(temp), allocatable :: x
    x = parse_temp()
contains
    function parse_temp() result(res)
          type(temp) :: res
          allocate(res%arr(2))
    end function
end program
```
gets transformed into this final code (before LLVM):
```fortran
! Fortran code after applying the pass: insert_deallocate
program mre1
implicit none
type :: temp
    integer(4), dimension(:), allocatable :: arr
end type temp
type(temp), allocatable :: x
call parse_temp(x)

contains

subroutine parse_temp(res)
    type(temp), intent(out) :: res
    allocate(res%arr(2))
end subroutine parse_temp

end program mre1
```

Comment (certik) [reply src/lfortran/semantics/ast_body_visitor.cpp]: One option is something like this:
```fortran
! Fortran code after applying the pass: insert_deallocate
program mre1
implicit none
type :: temp
    integer(4), dimension(:), allocatable :: arr
end type temp
type(temp), allocatable :: x
if (allocated(x)) deallocate(x)
allocate(x)
call parse_temp(x)

contains

subroutine parse_temp(res)
    type(temp), intent(out) :: res
    allocate(res%arr(2))
end subroutine parse_temp

end program mre1
```
Alternatively:
```fortran
type(temp), allocatable :: x
if (.not. allocated(x)) allocate(x)
call parse_temp(x)
```

This last one is the way to do it I think.

Comment (certik) [reply src/lfortran/semantics/ast_body_visitor.cpp]: Let's also consider when `x` is an array:
```fortran
program mre1
    type :: temp
      integer, allocatable :: arr(:)
    end type 
    type(temp), allocatable :: x(:)
    x = parse_temp(5)
contains
    function parse_temp(n) result(res)
          integer, intent(in) :: n
          integer :: i
          type(temp) :: res(n)
          do i = 1, n
              allocate(res(i)%arr(2))
          end do
    end function
end program
```

With `--realloc-lhs-arrays`, we reallocate `x` every time. Without `--realloc-lhs-arrays` we require `x` to be allocated and have the correct size, otherwise we must give a bounds check error.

Note: this already works. Let's see if we have an integration test and error tests for all these cases.

Comment (HarshilShah1804) [reply src/lfortran/semantics/ast_body_visitor.cpp]: I have made the changes as we discussed. I'll add the test for arrays in a subsequent PR.

**Comment by certik** [comment]
Let's run all tests first.

If all tests pass, then I think we can merge it, the PR is quite simple now.
