### PR TITLE
cpp: support comments in #if expressions, implement #warning and #error

### LINKED ISSUE #11260: CPP: Implement preprocessor comments on #if directives, #error and #warning
The following MRE demonstrates several annoying preprocessor misbehaviors in LFortran 0.63:

```C
# /* this is a CPP comment */
#if __LFORTRAN__ /* LFortran */ || defined(__flang__) /* LLVM Flang */ || __GFORTRAN__ /* GNU Gfortran */
#warning Successful warning! This warning message should be visible in a compiler diagnostic.
# /* the next line should trigger a compile error with user-provided message: */
#error Success! If you are seeing this error message, the test passed.
#else  /* another comment */
#endif /* and another */
```

Demonstration:
```
cgpu$ flang cpp-mre.F90
error: Could not scan cpp-mre.F90
./cpp-mre.F90:3:2: warning: #warning Successful warning! This warning message should be visible in a compiler diagnostic.
  #warning Successful warning! This warning message should be visible in a compiler diagnostic.
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
./cpp-mre.F90:5:2: error: #error Success! If you are seeing this error message, the test passed.
  #error Success! If you are seeing this error message, the test passed.
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

cgpu$ gfortran cpp-mre.F90      
cpp-mre.F90:3:2:

    3 | #warning Successful warning! This warning message should be visible in a compiler diagnostic.
      |  1~~~~~~
Warning: #warning Successful warning! This warning message should be visible in a compiler diagnostic. [-Wcpp]
cpp-mre.F90:5:2:

    5 | #error Success! If you are seeing this error message, the test passed.
      |  1~~~~
Error: #error Success! If you are seeing this error message, the test passed.

cgpu$ lfortran --cpp cpp-mre.F90 
C preprocessor error: Unexpected token '*' in factor()
 --> cpp-mre.F90:2:19
  |
2 | #if __LFORTRAN__ /* LFortran */ || defined(__flang__) /* LLVM Flang */ || __GFORTRAN__ /* GNU Gfortran */
  |                   ^^ 


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.

cgpu$ lfortran --version
LFortran version: 0.63.0
Status: alpha (expected to fail on third-party codes)
Platform: Linux
LLVM: 22.1.0
Default target: x86_64-unknown-linux-gnu
```

After deleting the problematic comments on line 2, the lfortran compilation then produces:
```
cgpu$ lfortran --cpp cpp-mre2.F90
warning: Unsupported macro
 --> cpp-mre2.F90:3:1
  |
3 | #warning Successful warning! This warning message should be visible in a compiler diagnostic.
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Ignored

warning: Unsupported macro
 --> cpp-mre2.F90:4:2
  |
4 | # /* the next line should trigger a compile error with user-provided message: */
  |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Ignored


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
/usr/bin/ld: /lib/x86_64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x1b): undefined reference to `main'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
...
```
The second seems to be an unimplemented case left-over from #11069.

After deleting those two lines, the lfortran compilation then produces:
```
cgpu$ lfortran --cpp cpp-mre3.F90  
warning: Unsupported macro
 --> cpp-mre3.F90:3:1
  |
3 | #error Success! If you are seeing this error message, the test passed.
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Ignored


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
/usr/bin/ld: /lib/x86_64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x1b): undefined reference to `main'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
...
```

The `#error` directive dates back to C89, and by widespread convention should cause translation to fail (not proceed to linking). 

`#warning` is new in C23, but widely implemented and also worth supporting.

### PR DESCRIPTION
**Pull request by certik**
The C preprocessor expression tokenizer used by #if directives now skips C-style /* ... */ and C++ // ... comments so they can appear between operands, e.g.:

    #if FOO /* desc */ || defined(BAR) /* desc */

In addition, #warning and #error directives are now recognized and handled by the preprocessor:

  - #warning emits a Warning diagnostic with the user-provided message
  - #error emits an Error diagnostic with the user-provided message and aborts compilation

Both directives respect conditional compilation: they are ignored inside branches that are not taken.

Closes #11260

### CODE REVIEW

File: integration_tests/cpp_pre_16.f90 [hunk 1]
```diff
@@ -0,0 +1,20 @@
+program cpp_pre_16
+    implicit none
+    integer :: x
+
+#if 1 /* taken */ || defined(__NOTDEFINED_MACRO__) /* not defined */
+    x = 42
```
Comment (bonachea) [inline integration_tests/cpp_pre_16.f90:6]: This doesn't cover one of the cases described in #11260, where a null directive inside a `#if` was generating an "unknown directive" warning.

Here is a one-line addition to add that coverage:
```suggestion
#if 1 /* taken */ || defined(__NOTDEFINED_MACRO__) /* not defined */
    x = 42
# /* a CPP null directive with a C-style comment, inside #if */    
```

File: integration_tests/cpp_pre_16.f90 [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+#else
+#error This branch must not be selected
+#endif
+
+#if 0 /* not taken */
+#error This #error must be ignored because branch is not taken
+#warning This #warning must be ignored because branch is not taken
```
Comment (bonachea) [inline integration_tests/cpp_pre_16.f90:13]: IIUC this test confirms that `#error` and `#warning` are correctly skipped inside skipped conditional blocks.

However there's no coverage for the case where `#error` and `#warning` are not skipped. Does your test infrastructure support "negative tests" that should generate a particular warning or error message?

**Review by bonachea — CHANGES_REQUESTED** [review]
Thanks for working on this!

I've added some suggestions to expand coverage of the test code.

File: integration_tests/cpp_pre_16.f90 (hunk 2 above)
Comment (certik) [reply integration_tests/cpp_pre_16.f90:13]: It does --- we have to test those from reference tests where we can capture the compiler output. I'll add it in a separate PR.

File: integration_tests/cpp_pre_16.f90 (hunk 1 above)
Comment (certik) [reply integration_tests/cpp_pre_16.f90:6]: I'll do it in the next PR, since CI is about halfway done.

Comment (bonachea) [reply integration_tests/cpp_pre_16.f90:6]: Sounds good. See also #11271

File: integration_tests/cpp_pre_16.f90 (hunk 2 above)
Comment (certik) [reply integration_tests/cpp_pre_16.f90:13]: Fixed in https://github.com/lfortran/lfortran/pull/11282.

File: integration_tests/cpp_pre_16.f90 (hunk 1 above)
Comment (certik) [reply integration_tests/cpp_pre_16.f90:6]: Fixed in https://github.com/lfortran/lfortran/pull/11282.

**Comment by bonachea** [comment]
Fix confirmed using the LFortran container @ 95ae229d2
Thanks @certik !
