### PR TITLE
Fix : Handle scalar mask with minloc/maxloc

### LINKED ISSUE #6664: bug: incorrect error for minloc with mask argument
```fortran
program main
    print*, minloc([1, 2], .true.)  
end program
```
```console
$ lfortran b.f90
semantic error: `dim` should be a scalar integer type
 --> b.f90:2:13
  |
2 |     print*, minloc([1, 2], .true.)  
  |             ^^^^^^^^^^^^^^^^^^^^^^ 


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
$ gfortran b.f90 && ./a.out
           1
```

### LINKED ISSUE #6666: bug: ICE in handling scalar mask for `minloc`
```fortran
program main
  implicit none
  real :: input(2)
  input = [1, 2]
  call solve(input)
contains

  subroutine solve(input)
    real :: input(2)
    print*, minloc(input, 1, .true.)  
  end subroutine
end program
```
```console
$ lfortran a.f90
ASR verify pass error: The variable in ArrayItem must be an array, not a scalar
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/harshita/Desktop/lfortran/src/bin/lfortran", in _start
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2687, in main
    return main_app(argc, argv);
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2614, in main_app(int, char**)
    err = compile_src_to_object_file(arg_file, tmp_o, compiler_options.time_report, false,
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 1161, in (anonymous namespace)::compile_src_to_object_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, LCompilers::CompilerOptions&, LCompilers::PassManager&)
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/home/harshita/Desktop/lfortran/src/lfortran/fortran_evaluator.cpp", line 382, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/home/harshita/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 10864, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/home/harshita/Desktop/lfortran/src/libasr/pass/pass_manager.h", line 311, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    apply_passes(al, asr, _passes, pass_options, diagnostics);
LCompilersException: Verify failed in the pass: intrinsic_function
$ gfortran a.f90 && ./a.out
           1
```

Same is the case with `maxloc`

### PR DESCRIPTION
**Pull request by assem2002**
Fixes #6664
fixes #6666
***
## Changes
- Don't throw error when second argument to `minloc` function call is a logical scalar (signature : 2nd arg = `dim`) -- treat it as the mask as long as `dim` isn't provided.
-  Modify **intrinsic minloc** logic to tolerate scalar logical mask, not only arrays.
- Remove some unnecessary visitors in **array_struct_temporary** pass.

### CODE REVIEW

File: src/libasr/pass/array_struct_temporary.cpp [hunk 1]
```diff
@@ -2391,27 +2387,6 @@ class ReplaceExprWithTemporaryVisitor:
     }
 
 
-    void visit_ArrayBroadcast(const ASR::ArrayBroadcast_t &x) {
```
Comment (assem2002) [inline src/libasr/pass/array_struct_temporary.cpp:2402]: Not used -- arrayBroadCast nodes are mostly trimmed before hitting the actual job of the pass .

**Comment by HarshitaKalani** [comment]
CI failure: https://github.com/lfortran/lfortran/pull/9296#issuecomment-3703269578
It is occuring for all the PRs for which the test fails with fortran flag.

**Review by HarshitaKalani — APPROVED** [review]
Looks good to me. Thanks @assem2002 .

File: integration_tests/intrinsics_312.f90 [hunk 2]
```diff
@@ -39,4 +39,8 @@ program intrinsics_312
 
 	print *, kind(minloc(["aa", "db", "ca"], 1, mask = [.false., .false., .false.], kind = 8))
 	if (kind(minloc(["aa", "db", "ca"], 1, mask = [.false., .false., .false.], kind = 8)) /= 8) error stop
+
+	arr = [3,2]
+	print *, minloc(arr, .true.)
+	if(any(minloc(arr, .true.) /= 2)) error stop
```
Comment (certik) [inline integration_tests/intrinsics_312.f90]: Either remove `gfortran` from the labels, or preferably: put this into a separate test, or fix the Fortran printer to work.

**Review by certik — APPROVED** [review]
