### PR TITLE
fix : mismatched argument and parameter doesn't raise error

### LINKED ISSUE #9177: Bug : mismatched argument and parameter doesn't raise error
```.f90
module bench_mod
   interface
      integer function f()
      end function f
   end interface
contains
   subroutine run(m)
      procedure(f) :: m
   end subroutine run

end module bench_mod


program main
   use bench_mod
   implicit none
   call run(1)
end program main
```
```
code generation error: asr_to_llvm: module failed verification. Error:
Call parameter type does not match function signature!
  %call_arg_value = alloca i32, align 4
 i32 ()*  call void @__module_bench_mod_run(i32* %call_arg_value)

```

### PR DESCRIPTION
**Pull request by opixdown**
## **Issue Fixed**
fixes #9177  mismatched argument and parameter doesn't raise error 

## **Summary**

After this PR, the type mismatch is caught during semantic analysis and reports a clear error message.

## **Reference Code**
```
module bench_mod
   interface
      integer function f()
      end function f
   end interface
contains
   subroutine run(m)
      procedure(f) :: m
   end subroutine run

end module bench_mod


program main
   use bench_mod
   implicit none
   call run(1)
end program main
```

## **Behaviour before this PR**
```
(lf) opixdown@Atharvs-MacBook-Air lfortran % lfortran ./t.f90
code generation error: asr_to_llvm: module failed verification. Error:
Call parameter type does not match function signature!
  %call_arg_value = alloca i32, align 4
```

## **Behaviour after this PR**
```
lf) opixdown@Atharvs-MacBook-Air lfortran % lfortran ./t.f90
semantic error: Type mismatch in argument `m`: expected a procedure but got `integer`
  --> ./t.f90:17:13
   |
17 |    call run(1)
   |             ^ 
```

### CODE REVIEW

**Comment by HarshilShah1804** [comment]
Thanks @opixdown for the PR. Please add the error test in `continue_compilation_*.f90`

**Comment by opixdown** [comment]
> Thanks @opixdown for the PR. Please add the error test in `continue_compilation_*.f90`

 on it !

**Review by HarshitaKalani — APPROVED** [review]
Looks good to me. Thanks!

File: src/lfortran/semantics/ast_body_visitor.cpp [hunk 1]
```diff
@@ -4776,6 +4776,19 @@ class BodyVisitor : public CommonVisitor<BodyVisitor> {
...
+                            std::string passed_str =ASRUtils::type_to_str_fortran_expr(passed_type, nullptr);
+                            diag.add(diag::Diagnostic(
+                                "Type mismatch in argument `" + std::string(v->m_name) +
+                                "`: expected a procedure but got `" + passed_str + "`",
+                                diag::Level::Error, diag::Stage::Semantic, {
+                                    diag::Label("", {passed_arg->base.loc})
+                                }));
+                            throw SemanticAbort();
+                        }
+                    }
```
Comment (certik) [inline src/lfortran/semantics/ast_body_visitor.cpp]: The indentation is incorrect.

**Review by certik — APPROVED** [review]

File: src/lfortran/semantics/ast_body_visitor.cpp
Comment (certik) [inline src/lfortran/semantics/ast_body_visitor.cpp:4800]: I think the above check should go into `check_equal_type`, we should not be special casing this particular case above. The `ASRUtils::check_equal_type` should return false for `integer` and `procedure`.

**Comment by certik** [comment]
@opixdown if you plan to implement the proper fix, we can merge the above as a temporary workaround. Otherwise I would leave the PR open until it's implemented properly, so that we don't increase technical debt.

**Comment by opixdown** [comment]
@certik thank you for the clarification. I think we can merge this as a temporary workaround and follow up with a proper fix in ASRUtils::check_equal_type in a separate PR shortly. Please let me know if that works.

**Comment by certik** [comment]
That works. The PR is in (thanks!) and you can now go ahead and implement the proper fix.
