### PR TITLE
fix: externalize struct type in select type class default

### LINKED ISSUE #9896: bug: serialization assert read_symbol() while compiling fortplot_figure_render_engine
## Summary
While building fortplot with LFortran, compilation crashes with an internal assertion in ASR serialization:

```text
LCOMPILERS_ASSERT failed: .../src/libasr/serialization.cpp
function read_symbol(), line number 133 at
id_symtab_map.find(symtab_id) != id_symtab_map.end()
```

This is currently the next fortplot blocker after `#9892` / draft fix `#9894`.

## Reproduction

From `lfortran-dev` meta-repo root:

```bash
MAMBA_ROOT_PREFIX=/home/ert/micromamba scripts/build_fortplot.sh
```

## Current Behavior

Fortplot build progresses to ~55% and fails when compiling:

```text
./src/figures/management/fortplot_figure_render_engine.f90
```

Relevant output:

```text
+ lfortran -c ././src/figures/management/fortplot_figure_render_engine.f90 ...
<ERROR> Compilation failed for object " src_figures_management_fortplot_figure_render_engine.f90.o "
LCOMPILERS_ASSERT failed: /home/ert/code/lfortran-dev/lfortran/src/libasr/serialization.cpp
function read_symbol(), line number 133 at
id_symtab_map.find(symtab_id) != id_symtab_map.end()
```

## Expected Behavior

Compiler should not ICE/assert. It should compile successfully or emit a regular semantic/codegen diagnostic.

## Environment

- LFortran: `0.59.0-315-gbdda5f74b-dirty`
- LLVM: `11.1.0`
- Platform: Linux x86_64
- Context commit used while reproducing: `c903b237346d6b0f9c1c4a2a5e718123f458d2fa` (branch `fix/array-section-shape-9892`)

## Meta tracking

- Meta issue: #9895

### PR DESCRIPTION
**Pull request by krystophny**
## Summary
- Fix modfile deserialization crash (assertion failure) when `class default` in `select type` references polymorphic types from external modules

Fixes #9896

## Why
When `select type` has a `class default` clause on a polymorphic component from an external module (e.g., `class(base_t), allocatable`), the association variable's `m_type_declaration` was set to the internal struct symbol directly, bypassing `ExternalSymbol`. During modfile serialization, this wrote a symtab ID from the external module. During deserialization in another compilation unit, that symtab ID was not present in the deserializer's `id_symtab_map`, causing an assertion failure.

**Stage:** Semantics

## Changes
- [`src/lfortran/semantics/ast_body_visitor.cpp#L3264-L3268`](https://github.com/lfortran/lfortran/blob/fcdc56cf1103eeea70027681fc6f9d8991dc25d2/src/lfortran/semantics/ast_body_visitor.cpp#L3264-L3268): Use `import_struct_type()` to externalize the type declaration symbol in the `ClassDefault` case, matching how `ClassStmt` and `TypeStmtName` branches already handle their symbols

## Tests
- [`integration_tests/modules_65.f90`](https://github.com/lfortran/lfortran/blob/fcdc56cf1103eeea70027681fc6f9d8991dc25d2/integration_tests/modules_65.f90): Multi-module test with `select type` + `class default` on polymorphic external type

### Test fails on main
```
$ git checkout upstream/main
$ cd /tmp/mre_9896 && rm -f *.o *.mod
$ lfortran -c mre_serialization_crash_types.f90
$ lfortran -c mre_serialization_crash_main.f90
LCOMPILERS_ASSERT failed: /home/ert/code/lfortran-dev/lfortran/src/libasr/serialization.cpp
function read_symbol(), line number 133 at
id_symtab_map.find(symtab_id) != id_symtab_map.end()
Aborted (core dumped)
```

### Test passes after fix
```
$ git checkout fix/modfile-select-type-9896
$ cd /tmp/mre_9896 && rm -f *.o *.mod
$ lfortran -c mre_serialization_crash_types.f90
$ lfortran -c mre_serialization_crash_main.f90
$ # No error, exit code 0

$ scripts/lf.sh itest -b llvm -t modules_65
1/1 Test #1040: modules_65 .......................   Passed    0.00 sec
100% tests passed, 0 tests failed out of 1

$ scripts/lf.sh itest -b gfortran -t modules_65
1/1 Test #1056: modules_65 .......................   Passed    0.00 sec
100% tests passed, 0 tests failed out of 1

$ scripts/lf.sh itest -b llvm
100% tests passed, 0 tests failed out of 2342

$ scripts/lf.sh test
# All reference tests pass
```

### CODE REVIEW

File: src/libasr/asr_utils.h [hunk 1]
```diff
@@ -4812,6 +4812,9 @@ static inline ASR::symbol_t* import_struct_type(Allocator& al, ASR::symbol_t* st
         return struct_sym;
     }
     std::string struct_name = ASRUtils::symbol_name(struct_sym);
+    if (struct_name == "~unlimited_polymorphic_type") {
+        return struct_sym;
+    }
```
Comment (certik) [inline src/libasr/asr_utils.h:4817]: I don't know if this belongs here or not, or what it does.

Comment (certik) [reply src/libasr/asr_utils.h:4817]: The git commit log talks about it. I am still not sure it's a right design to have a bunch of special cases.
