### PR TITLE
fix: optional arguments in findLoc()

### LINKED ISSUE #4679: `gfortran` treats the next logical arg as `mask` instead of `dim`
RESULT = FINDLOC(ARRAY, VALUE, DIM [, MASK] [,KIND] [,BACK])

```fortran
program main
    logical :: x(3) = [.true., .false., .true.], y = .true., back = .true.
    print *, findloc(x, y, back)
end program
```
```console
$ gfortran a.f90 && ./a.out
           1
$ lfortran a.f90
semantic error: `dim` should be a scalar integer type
 --> a.f90:3:14
  |
3 |     print *, findloc(x, y, back)
  |              ^^^^^^^^^^^^^^^^^^^ 


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

### PR DESCRIPTION
**Pull request by jinangshah21**
Fixes #4679.
Still not Complete. I am keeping it in draft.

### CODE REVIEW

**Comment by certik** [comment]
Add a test, so that we can see what exact features you are trying to implement.

**Review by Pranavchiku — CHANGES_REQUESTED** [review]
Check if mask is an array then only create an array item

File: src/libasr/pass/intrinsic_array_function_registry.h [hunk 1]
```diff
@@ -3236,18 +3236,29 @@ namespace FindLoc {
         int dim = 0, kind = 4; // default kind
         ASR::expr_t *dim_expr = nullptr;
         ASR::expr_t *mask_expr = nullptr;
-        if (args[2]) {
-            dim_expr = args[2];
-            if ( !ASR::is_a<ASR::Integer_t>(*expr_type(args[2])) ) {
-                append_error(diag, "`dim` should be a scalar integer type", loc);
+        
+        // Checking for type findLoc(Array, value, mask)
+        if( args[2] && !args[3] && is_logical(*expr_type(args[2])) ){
```
Comment (gxyd) [inline src/libasr/pass/intrinsic_array_function_registry.h:3241]: The problem with an approach like this is that a similar problem exists for a lot of intrinsic functions, like: `minval`, `maxval`, `findloc` etc.

E.g.; documentation of GFortran here for `maxval`: https://gcc.gnu.org/onlinedocs/gfortran/MAXVAL.html with syntax:
```f90
Syntax:
RESULT = MAXVAL(ARRAY, DIM [, MASK])
RESULT = MAXVAL(ARRAY [, MASK])
```

So, a similar check might be needed for a lot of other intrinsic functions as well, where the `dim` and `mask` are assigned depending on "position" and "type".

With the approach described above, it would lead to a lot of repeated code and hence a possibility to  miss something or cause a bug.

I ideally would be more happy with a general approach here.

File: integration_tests/intrinsics_301.f90 [hunk 2]
```diff
@@ -43,7 +46,9 @@ program intrinsics_301
     if (any(findloc(x2, y2, mask = mask1, back = back2) /= 5)) error stop
     print *, findloc(x1, y1, mask = mask1, back = back2, kind = 8)
     if (any(findloc(x1, y1, mask = mask1, back = back2, kind = 8) /= 5)) error stop
-    
+    print *, findloc(x4, y4, mask3)
+    if (any(findloc(x4, y4, mask3) /= 1)) error stop
```
Comment (gxyd) [inline integration_tests/intrinsics_301.f90:50]: Also, we don't have a test case for when `dim` i.e. scalar is passed as an argument, there are test cases for when `dim` is passed as a keyword-argument though.

Comment (gxyd) [reply integration_tests/intrinsics_301.f90:50]: i.e. something like:
```f90
findloc(x4, y4, 1)
```

File: src/libasr/pass/intrinsic_array_function_registry.h (hunk 1 above)
Comment (gxyd) [reply src/libasr/pass/intrinsic_array_function_registry.h:3241]: @HarshitaKalani thoughts?

Comment (HarshitaKalani) [reply src/libasr/pass/intrinsic_array_function_registry.h:3241]: I agree completely. I would also like to have a general approach for this. 
Also, the current approach will have high chances of bugs. For example, the current implementation would not handle a case like:
```fortran
program main
    print *, findloc([1, 2, 3], 2, .true., .true.)
end program
```
```console
$ gfortran a.f90 && ./a.out
a.f90:2:35:

    2 |     print *, findloc([1, 2, 3], 2, .true., .true.)
      |                                   1
Error: ‘dim’ argument of ‘findloc’ intrinsic at (1) must be INTEGER
$ lfortran a.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/harshita/Desktop/lfortran/src/bin/lfortran", in _start
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2668, in main
    return main_app(argc, argv);
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2611, in main_app(int, char**)
    err = compile_src_to_object_file(arg_file, tmp_o, false,
...

  File "/home/harshita/Desktop/lfortran/src/libasr/pass/intrinsic_array_function_registry.h", line 3252, in LCompilers::ASRUtils::FindLoc::create_FindLoc(Allocator&, LCompilers::Location const&, LCompilers::Vec<LCompilers::ASR::expr_t*>&, LCompilers::diag::Diagnostics&)
    dim = ASR::down_cast<ASR::IntegerConstant_t>(dim_expr) -> m_n;
AssertFailed: is_a<T>(*f)
```

Comment (certik) [reply src/libasr/pass/intrinsic_array_function_registry.h:3241]: The right design in my opinion is to use the "overload_id" in ASR for this. We discussed exactly this issue for a similar function, I can't remember which one. You decide on the signatures that you will support, let's just say the following:
```
minloc(array) ! overload_id = 0
minloc(array, dim) ! overload_id = 1
minloc(array, dim, mask) ! overload_id = 2
```
And for each case (`overload_id`) all arguments are required and never null (it could be that some arguments have to have their default values specified). So you never write code like this:
```
 if( args[2] && !args[3] && is_logical(*expr_type(args[2])) 
```
Rather, you write code like `if (overload_id == 2) { /* array, dim, mask is present and valid, handle this case */ }`.

Let me know if you have any questions about this, or want to discuss more.

Comment (HarshitaKalani) [reply src/libasr/pass/intrinsic_array_function_registry.h:3241]: Yes, we did it for `minloc` here: https://github.com/lfortran/lfortran/issues/4456. If we follow this, the implementation would be more clean and robust.
One can refer: https://github.com/lfortran/lfortran/pull/4461.

Comment (certik) [reply src/libasr/pass/intrinsic_array_function_registry.h:3241]: Yes, that was it, thanks for finding it. @jinangshah21 go ahead and follow the same design here.

Comment (jinangshah21) [reply src/libasr/pass/intrinsic_array_function_registry.h:3241]: > I agree completely. I would also like to have a general approach for this. Also, the current approach will have high chances of bugs. For example, the current implementation would not handle a case like:
> 
> ```fortran
> program main
>     print *, findloc([1, 2, 3], 2, .true., .true.)
> end program
> ```
> 
> ```
> $ gfortran a.f90 && ./a.out
> a.f90:2:35:
> 
>     2 |     print *, findloc([1, 2, 3], 2, .true., .true.)
>       |                                   1
> Error: ‘dim’ argument of ‘findloc’ intrinsic at (1) must be INTEGER
> $ lfortran a.f90
> Internal Compiler Error: Unhandled exception
> Traceback (most recent call last):
>   Binary file "/home/harshita/Desktop/lfortran/src/bin/lfortran", in _start
>   File "./csu/../csu/libc-start.c", line 392, in __libc_start_main
>   File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main
>   File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2668, in main
>     return main_app(argc, argv);
>   File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2611, in main_app(int, char**)
>     err = compile_src_to_object_file(arg_file, tmp_o, false,
> ...
> 
>   File "/home/harshita/Desktop/lfortran/src/libasr/pass/intrinsic_array_function_registry.h", line 3252, in LCompilers::ASRUtils::FindLoc::create_FindLoc(Allocator&, LCompilers::Location const&, LCompilers::Vec<LCompilers::ASR::expr_t*>&, LCompilers::diag::Diagnostics&)
>     dim = ASR::down_cast<ASR::IntegerConstant_t>(dim_expr) -> m_n;
> AssertFailed: is_a<T>(*f)
> ```

GFortran Gives same error. I had tried all cases with Gfortran, only case with findloc(array, value, mask) was not implemented. So do we have to implement cases that Gfortran not support?

Comment (jinangshah21) [reply src/libasr/pass/intrinsic_array_function_registry.h:3241]: > The right design in my opinion is to use the "overload_id" in ASR for this. We discussed exactly this issue for a similar function, I can't remember which one. You decide on the signatures that you will support, let's just say the following:
> 
> ```
> minloc(array) ! overload_id = 0
> minloc(array, dim) ! overload_id = 1
> minloc(array, dim, mask) ! overload_id = 2
> ```
> 
> And for each case (`overload_id`) all arguments are required and never null (it could be that some arguments have to have their default values specified). So you never write code like this:
> 
> ```
>  if( args[2] && !args[3] && is_logical(*expr_type(args[2])) 
> ```
> 
> Rather, you write code like `if (overload_id == 2) { /* array, dim, mask is present and valid, handle this case */ }`.
> 
> The general design of ASR is that we do not have defaults or optional arguments. Everything is always present and explicit. So there is no branching logic and trying to figure out the defaults, like you discovered in this PR. All these decisions are made by the frontend. Once ASR is constructed, it is already set it stone what exact operations we need to do.
> 
> Let me know if you have any questions about this and if you know how to apply this to this PR, or want to discuss more.

By Checking `if( args[2] && !args[3] && is_logical(*expr_type(args[2])) ` I am differentiating between overload_id for (Array, value, dim)(i.e. 1) and (Array, value, mask)(i.e. 2). So it uses overload_id already.

Comment (certik) [reply src/libasr/pass/intrinsic_array_function_registry.h:3241]: Only do cases that GFortran supports.

I see, this is in the `create` function, which determines the overload_id. In that case this is fine I think!

**Review by certik — APPROVED** [review]
I think this is fine then. It fixes an issue, test is added.

The concern is how to expand this to other functions without repeating too much code.

I would say we can merge it, and then figure out a general solution if there is any.

@gxyd, @HarshitaKalani let me know what you want to do here.

**Review by Pranavchiku — APPROVED** [review]
I think we will always have this problem to adjust variables. The approach uses overload_id just swaps two arguments as one is nullptr and other is not. The only way to generalise this is to create some form of mapping in the frontend for each intrinsic so that we do not have to worry about it in `create_*` function.

**Comment by certik** [comment]
The `create` function is called by the frontend, isn't it? It's not called after ASR is constructed.

**Comment by Pranavchiku** [comment]
Yes, it is called in frontend.

**Comment by gxyd** [comment]
> I would say we can merge it, and then figure out a general solution if there is any.

I agree with this.

> @gxyd, @HarshitaKalani let me know what you want to do here.

We can maybe open a separate issue describing in detail about the general issue.
