### PR TITLE
fix : Handling ArrayItem in ArrayConstructor having Descriptor Array ttype

### LINKED ISSUE #5990: Bug : array as arrayIndex in `arrayItem` in `arrayConstrcutror` fail
MRE
```.f90
program prog
  integer :: i
  integer :: arr(10)
  integer :: arr_indecies(10)
  integer,allocatable :: arr_res(:)
  allocate(arr_res(10))

  do i =1,10
    arr(i) = i
    arr_indecies(i) = i
  end do
  arr_res = [arr(arr_indecies),11] ! <<<<<<<<<<<<<<<< Bug
  print *, arr_res
  do i =1,11
    if (arr_res(i) /= i) error stop
  end do
end program prog
```
I think this due to `implied_do_loop.cpp` pass as the resulting temp array that replaces the `arrayConstructor` has a fixedSize of `2`.
```clj
__libasr__created__var__0__array_constructor_:
  (Variable
      2
      __libasr__created__var__0__array_constructor_
      []
      Local
      ()
      ()
      Default
      (Array
          (Integer 4)
          [((IntegerConstant 1 (Integer 4) Decimal)
          (IntegerConstant 2 (Integer 4) Decimal))]
          FixedSizeArray
      )
      ()
      Source
      Public
      Required
      .false.
      .false.
  ),
```

### PR DESCRIPTION
**Pull request by AnshMehta1**
Fixes #5990 

MRE :- 
```
module a 
  contains 
  function f2() result(res)
    integer(8), allocatable :: res(:)
    allocate(res(10))
    res = [1,2,3,4,5,6,7,8,9,10]
  end function f2
end module a 

program prog
  use a
  integer :: i
  integer :: arr(10)
  integer,allocatable :: arr_res(:)
  do i = 1 , 10
    arr(i) = i+100
  end do

  allocate(arr_res(11))
  arr_res = [arr(f2()),111] ! Error here
  print *, arr_res

end program prog
```

LFortran Output :- 
```
(lf) lordansh@LordAnsh:~/dev/lfort1/lfortran$ lfortran try.f90
101
102
103
104
105
106
107
108
109
110
111
```

### CODE REVIEW

**Comment by kmr-srbh** [comment]
`pass_array_by_data_05.f90` segfaults with the `--std=f23 --fast` option. Could you please look into the issue?

**Comment by AnshMehta1** [comment]
> `pass_array_by_data_05.f90` segfaults with the `--std=f23 --fast` option. Could you please look into the issue?

In my current without this PR , I am getting different outputs on running `pass_array_by_data_05.f90` and sometimes getting error stop. 

```
(lf) lordansh@LordAnsh:~/dev/lfort2/lfortran$ lfortran try.f90 --std=f23 --fast
 3
 6.00000000e+00
(lf) lordansh@LordAnsh:~/dev/lfort2/lfortran$ lfortran try.f90 --std=f23 --fast
 3
 6.34987402e+00
(lf) lordansh@LordAnsh:~/dev/lfort2/lfortran$ lfortran try.f90 --std=f23 --fast
 3
 6.44088361e+24
ERROR STOP
```

**Comment by kmr-srbh** [comment]
Yes, I just noticed the same. The issue is with this test itself. I am opening an issue for it.

**Comment by kmr-srbh** [comment]
Reported at #6038. I am re-triggering the CI. Let's see if it passes. It had passed previously, through the test does not work correctly with `--fast`.

File: integration_tests/arrays_77.f90 [hunk 1]
```diff
@@ -0,0 +1,27 @@
+module a
```
Comment (Pranavchiku) [inline integration_tests/arrays_77.f90:1]:
```suggestion
module a_arrays_77
```

Comment (AnshMehta1) [reply integration_tests/arrays_77.f90:1]: Ok , I will make the changes needed

**Review by Pranavchiku — APPROVED** [review]
