### PR TITLE
fix: inquire(unit, size=) returning 0 instead of actual file size

### LINKED ISSUE #8990: Handle `size` in `inquire` when `unit` is given instead filename
MRE:
```fortran
program test_inquire_size
    implicit none
    integer :: fh
    integer :: length
    character(*), parameter :: test_lines = 'build.f90'
    open(newunit=fh, file="test", access="stream", form='unformatted')
    write(fh) test_lines
    inquire(fh, size=length)
    close(fh)
    print *, "File size =", length, "bytes"
end program test_inquire_size
```

Outputs:
```console
(lf) jinang_shah@JNSLAP:~/Desktop/lfortran$ lfortran b.f90
File size =    0    bytes
(lf) jinang_shah@JNSLAP:~/Desktop/lfortran$ gfortran b.f90 && ./a.out
 File size =           9 bytes
```

### PR DESCRIPTION
**Pull request by opixdown**
## **Issue Fixed**
closes #8990 Handle size in inquire when unit is given instead filename

## **Summary**
This PR fixes the inquire statement to correctly return file size when querying by unit number. Earlier the size parameter was  always returning 0 instead of the actual file size.

## **Reference Code**
```
program test_inquire_size
    implicit none
    integer :: fh
    integer :: length
    character(*), parameter :: test_lines = 'build.f90'
    open(newunit=fh, file="test", access="stream", form='unformatted')
    write(fh) test_lines
    inquire(fh, size=length)
    close(fh)
    print *, "File size =", length, "bytes"
end program test_inquire_size
```

## **Behaviour before PR**
```
(lf) opixdown@Atharvs-MacBook-Air lfortran % lfortran test.f90 
File size =    0    bytes
```

## **Behaviour after PR**
```
(lf) opixdown@Atharvs-MacBook-Air lfortran % lfortran test.f90 
 File size =    9    bytes
(lf) opixdown@Atharvs-MacBook-Air lfortran % gfortran test.f90 && ./a.out
 File size =           9 bytes
```

### CODE REVIEW

**Comment by opixdown** [comment]
I noticed something unusual. When running the test multiple times, lfortran appends to the file instead of overwriting it, while gfortran consistently overwrites:
```
(lf) opixdown@Atharvs-MacBook-Air lfortran % lfortran test.f90
File size =    9    bytes
(lf) opixdown@Atharvs-MacBook-Air lfortran % gfortran test.f90 && ./a.out
 File size =           9 bytes
(lf) opixdown@Atharvs-MacBook-Air lfortran % gfortran test.f90 && ./a.out
 File size =           9 bytes
(lf) opixdown@Atharvs-MacBook-Air lfortran % lfortran test.f90
File size =    18    bytes
(lf) opixdown@Atharvs-MacBook-Air lfortran % lfortran test.f90
File size =    27    bytes
(lf) opixdown@Atharvs-MacBook-Air lfortran % 
```

File: integration_tests/test_inquire_size.f90 [hunk 1]
```diff
@@ -0,0 +1,11 @@
+program test_inquire_size
+    implicit none
+    integer :: fh
+    integer :: length
+    character(*), parameter :: test_lines = 'build.f90'
+    open(newunit=fh, file="test", access="stream", form='unformatted')
+    write(fh) test_lines
+    inquire(fh, size=length)
+    close(fh)
+    print *, "File size =", length, "bytes"
```
Comment (assem2002) [inline integration_tests/test_inquire_size.f90:10]:
```suggestion
    print *, "File size =", length, "bytes"
    if(length /= 9) error stop
```

File: integration_tests/CMakeLists.txt [hunk 2]
```diff
@@ -1980,6 +1980,7 @@ RUN(NAME inquire_01 LABELS gfortran llvm llvm_wasm llvm_wasm_emcc)
 RUN(NAME inquire_02 LABELS gfortran llvm llvm_wasm llvm_wasm_emcc)
 RUN(NAME inquire_03 LABELS gfortran llvm llvm_wasm llvm_wasm_emcc)
 RUN(NAME inquire_04 LABELS gfortran llvm llvm_wasm llvm_wasm_emcc)
+RUN(NAME test_inquire_size LABELS gfortran llvm c)
```
Comment (assem2002) [inline integration_tests/CMakeLists.txt]:
```suggestion
RUN(NAME test_inquire_size LABELS gfortran llvm)
```

**Comment by opixdown** [comment]
Thanks for the suggestions assem.
