### PR TITLE
fix: allocate allocatable members of structs if something is assigned to them

### LINKED ISSUE #8423: Handle structType arguments passing to external function which have array member
MRE:
```fortran
module m_labels
    implicit none

    type :: toml_label
        character(:), allocatable :: source
    end type toml_label

    type :: toml_diagnostic
        type(toml_label), allocatable :: label(:)
    end type toml_diagnostic

end module m_labels


module m_render
    use m_labels
    implicit none

contains

    function render_diagnostic(d) result(out)
        type(toml_diagnostic), intent(in) :: d
        character(:), allocatable :: out
        if (allocated(d%label)) then
            out = "Diagnostic: " // d%label(1)%source
        else
            out = "Empty diagnostic"
        end if
    end function render_diagnostic

end module m_render


program main
    use m_labels
    use m_render
    implicit none

    type(toml_diagnostic) :: diag
    type(toml_label) :: lbl(1)

    lbl(1)%source = "Something went wrong"
    diag%label = lbl

    print *, render_diagnostic(diag)
end program main
```

Outputs: 
```console
(base) jinang_shah@JNSLAP:~/Desktop/lfortran$ gfortran b.f90  && ./a.out
 Diagnostic: Something went wrong
(base) jinang_shah@JNSLAP:~/Desktop/lfortran$ lfortran b.f90 
Runtime Error: Array '' is not allocated.
```

### PR DESCRIPTION
**Pull request by akramhany**
Fixes #8423

### CODE REVIEW

**Review by kmr-srbh — APPROVED** [review]
The changes look good! Previously, the control flow would reach the code in block `else if( is_target_struct && is_value_struct )` for this case and try deep copying without prior allocation, now we allocate the LHS prior to the assignment. Thank you for fixing this!

File: integration_tests/derived_types_78.f90 [hunk 1]
```diff
@@ -0,0 +1,27 @@
+module m_labels
```
Comment (kmr-srbh) [inline integration_tests/derived_types_78.f90]: Please name this module uniquely based on the test name. Something like - `m_labels_derived_types_78`. That will fix the CI failure.

File: integration_tests/derived_types_79.f90 [hunk 2]
```diff
@@ -0,0 +1,46 @@
+module m_labels
```
Comment (kmr-srbh) [inline integration_tests/derived_types_79.f90]: Likewise.
