### PR TITLE
fix: replace Var with ArrayConstant value with appropriate type

### LINKED ISSUE #7188: [stdlib: terminal] Index mismatch in 0-indexed arrays for 1-indexed based values
MRE
```fortran
! SPDX-Identifier: MIT

!> Terminal color and style escape sequences
module stdlib_ansi
    implicit none

    public :: ansi_code

    public :: to_string

    !> Container for terminal escape code
    type :: ansi_code
        !> Style descriptor
        integer(8) :: style = -1_8
        !> Background color descriptor
        integer(8) :: bg = -1_8
        !> Foreground color descriptor
        integer(8) :: fg = -1_8
    end type ansi_code

    character, parameter :: esc = achar(27), chars(0:9) = &
        ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]

    type(ansi_code) :: fg_color_red = ansi_code(fg=3)

    interface to_string
        !> Transform a color code into an actual ANSI escape sequence
        procedure :: to_string_ansi_code
    end interface to_string

contains

    !> Transform a color code into an actual ANSI escape sequence
    pure function to_string_ansi_code(code) result(str)
    type(ansi_code), intent(in) :: code
    character(len=:), allocatable :: str

    str = esc // "[0"  ! Always reset the style

    if (code%style > 0 .and. code%style < 10) str = str // ";" // chars(code%style)
    if (code%fg >= 0 .and. code%fg <= 9) str = str // ";3" // chars(code%fg)
    if (code%bg >= 0 .and. code%bg <= 9) str = str // ";4" // chars(code%bg)
    str = str // "m"
end function to_string_ansi_code


end module stdlib_ansi
```

```fortran
! SPDX-Identifier: MIT
program test_colors
    use stdlib_ansi, only : fg_color_red, to_string
    implicit none

    integer :: stat

    stat = 0

    print *, "Testing: fg_color"

    call test_fg_color(stat)

    if (stat > 0) then
        print *, stat, "test(s) failed!"
        stop 1
    else
        print *, "All tests passed."
    end if

contains

    subroutine test_fg_color(stat)
        integer, intent(inout) :: stat
        character(len=:), allocatable :: str
        integer :: ch

        str = to_string(fg_color_red)
        ch = iachar(str(1:1))

        if (ch /= 27) then
            print *, "FAIL: First character is not ESC (27)"
            stat = stat + 1
            return
        end if

        if (str(2:) /= "[0;33m") then
            print *, "FAIL: Expected '[0;33m' but got '", str(2:), "'"
            stat = stat + 1
            return
        end if

        print *, "PASS: fg_color"
    end subroutine test_fg_color

end program test_colors
```

LFortran
```console
(base) harshil-shah@harshil-shah-HP-Pavilion-Laptop-15-eg2xxx:~/lfortran$ lfortran stdlib_ansi.f90 test_colors.f90
Testing: fg_color
FAIL: Expected '[0;33m' but got '    [0;32m    '
1    test(s) failed!
STOP 1
```

GFortran
```
(base) harshil-shah@harshil-shah-HP-Pavilion-Laptop-15-eg2xxx:~/lfortran$ gfortran stdlib_ansi.f90 test_colors.f90 -o test_colors.out
(base) harshil-shah@harshil-shah-HP-Pavilion-Laptop-15-eg2xxx:~/lfortran$ ./test_colors.out
 Testing: fg_color
 PASS: fg_color
 All tests passed.
```

### PR DESCRIPTION
**Pull request by gxyd**
## Description

Fixes #7188

### CODE REVIEW

File: src/libasr/pass/array_struct_temporary.cpp [hunk 1]
```diff
@@ -2290,6 +2290,17 @@ class ReplaceModuleVarWithValue:
...
+
+        // we replace ttype of ArrayConstant value with, it's declared
+        // ttype, currently this looks like a special case, and this
+        // might actually be needed for other constant value as well
+        // eventually
+        if (ASR::is_a<ASR::ArrayConstant_t>(*value)) {
+            ASR::ArrayConstant_t* arr_const_value =
+                ASR::down_cast<ASR::ArrayConstant_t>(value);
+            arr_const_value->m_type = y->m_type;
+        }
```
Comment (gxyd) [inline src/libasr/pass/array_struct_temporary.cpp:2302]: For the added test case we are replacing it's dimensions from `m_start=1, m_len=10` to `m_start=0, m_len=10`, which is how it's declared in `ints(0:9)` (instead of the default `ints(1:10)`)

File: src/libasr/pass/array_struct_temporary.cpp [hunk 2]
```diff
@@ -2290,6 +2290,17 @@ class ReplaceModuleVarWithValue:
         } else {
             value = y->m_symbolic_value;
         }
+
+        // we replace ttype of ArrayConstant value with, it's declared
+        // ttype, currently this looks like a special case, and this
```
Comment (certik) [inline src/libasr/pass/array_struct_temporary.cpp:2295]:
```suggestion
        // we replace ttype of ArrayConstant value with its declared
        // ttype, currently this looks like a special case, and this
```
?
