### PR TITLE
fix: resolve re-imported symbols correctly

### LINKED ISSUE #10507: Semantic error when renaming a re-imported generic interface
MRE
Module:
```fortran
module submodule_44_mod
   implicit none
   type :: mytype
      integer :: x
   end type mytype

   interface create
      module function create1(a) result(res)
         integer, intent(in) :: a
         type(mytype) :: res
      end function create1

      module function create2(a, b) result(res)
         integer, intent(in) :: a, b
         type(mytype) :: res
      end function create2
   end interface create
end module submodule_44_mod

submodule(submodule_44_mod) submodule_44_sub
   implicit none
contains
   module function create1(a) result(res)
      integer, intent(in) :: a
      type(mytype) :: res
      res%x = a
   end function create1

   module function create2(a, b) result(res)
      integer, intent(in) :: a, b
      type(mytype) :: res
      res%x = a + b
   end function create2
end submodule submodule_44_sub

module submodule_44_reexport
   use submodule_44_mod, only: mytype, create
   implicit none
   private
   public :: mytype, create
end module submodule_44_reexport
```

Program
```fortran
program submodule_44
   ! Test: renaming a re-exported generic interface to match
   ! one of its specific submodule procedure names.
   use submodule_44_reexport, only: mytype, create2 => create
   implicit none
   type(mytype) :: t
   t = create2(1, 2)
   if (t%x /= 3) error stop
   print *, "ok"
end program submodule_44
```

LFortran
```console
(lf) harshil-shah@harshil-shah-HP-Pavilion-Laptop-15-eg2xxx:~/lfortran$ lfortran integration_tests/submodule_44a.f90 
semantic error: Only Subroutine and Function supported in generic procedure
 --> integration_tests/submodule_44a.f90:7:8
  |
7 |    t = create2(1, 2)
  |        ^^^^^^^^^^^^^ 


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

### LINKED ISSUE #10510: Can't find keyword argument of a user-defined derived type constructor
`$ cat mymod.f90 `
```
module somemod

   type :: SomeType
   end type SomeType
   
   interface SomeType
      procedure :: constructor
   end interface SomeType
   
contains
   
   function constructor( ) result( self )
      type(SomeType) :: self
   end function constructor

end module somemod

module mymod

   type :: MyType
   end type MyType
   
   interface MyType
      procedure :: constructor
   end interface MyType
   
contains
   
   function constructor(a) result( self )
      real(8), optional, intent(in) :: a(:)
      type(MyType)                  :: self
   end function constructor
   
end module mymod
```
`$ cat clientmod.f90 `
```
module clientmod
   
   use somemod
   use mymod, only: MyType
   
   type :: ClientType
   end type ClientType
   
   interface ClientType
      procedure :: init
   end interface ClientType
   
contains
   
   function init() result(self)
      type (ClientType) :: self
      real(8) :: arr(6)
      class(SomeType), allocatable :: tmp
      class(MyType),   allocatable :: obj
      allocate(obj, source = MyType(a=arr))
   end function init

end module clientmod
```
`$ lfortran -c --separate-compilation mymod.f90`
`$ lfortran -c --separate-compilation clientmod.f90`
```
semantic error: Keyword argument not found
  --> clientmod.f90:20:30
   |
20 |       allocate(obj, source = MyType(a=arr))
   |                              ^^^^^^^^^^^^^ 'a' keyword argument not found


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

### PR DESCRIPTION
**Pull request by HarshilShah1804**
Fixes #10507
Fixes #10510 
Towards #4748

### CODE REVIEW

**Comment by HarshilShah1804** [comment]
With this, all the tests in the `neural-fortran` package compiles correctly, but gives segfault upon running.
```console
(base) harshil-shah@harshil-shah-HP-Pavilion-Laptop-15-eg2xxx:~/neural-fortran$ fpm test --compiler=lfortran --flag "--cpp --realloc-lhs-arrays"
 + mkdir -p build/dependencies
nf_random.f90                          done.
nf_activation.f90                      done.
nf_parallel.f90                        done.
nf_optimizers.f90                      done.
nf_base_layer.f90                      done.
nf_datasets.f90                        done.
nf_metrics.f90                         done.
nf_datasets_mnist.f90                  done.
nf_io_binary.f90                       done.
tuff.f90                               done.
nf_embedding_layer.f90                 done.
nf_flatten_layer.f90                   done.
nf_reshape3d_layer.f90                 done.
nf_conv2d_layer.f90                    done.
nf_avgpool2d_layer.f90                 done.
nf_avgpool1d_layer.f90                 done.
nf_input3d_layer.f90                   done.
nf_conv1d_layer.f90                    done.
nf_layer.f90                           done.
nf_dense_layer.f90                     done.
nf_linear2d_layer.f90                  done.
nf_input1d_layer.f90                   done.
nf_locally_connected2d_layer.f90       done.
nf_maxpool2d_layer.f90                 done.
nf_input2d_layer.f90                   done.
nf_datasets_submodule.f90              done.
nf_parallel_submodule.f90              done.
nf_datasets_mnist_submodule.f90        done.
nf_dropout_layer.f90                   done.
nf_layernorm.f90                       done.
nf_maxpool1d_layer.f90                 done.
nf_reshape2d_layer.f90                 done.
nf_loss.f90                            done.
nf_io_binary_submodule.f90             done.
nf_layernorm_submodule.f90             done.
nf_dense_layer_submodule.f90           done.
nf_avgpool1d_layer_submodule.f90       done.
nf_locally_connected2d_layer_submodule.done.
nf_linear2d_layer_submodule.f90        done.
nf_dropout_layer_submodule.f90         done.
nf_reshape2d_layer_submodule.f90       done.
nf_input1d_layer_submodule.f90         done.
nf_input2d_layer_submodule.f90         done.
nf_multihead_attention_layer.f90       done.
nf_maxpool2d_layer_submodule.f90       done.
nf_conv1d_layer_submodule.f90          done.
nf_maxpool1d_layer_submodule.f90       done.
nf_network.f90                         done.
nf_reshape3d_layer_submodule.f90       done.
nf_flatten_layer_submodule.f90         done.
nf_input3d_layer_submodule.f90         done.
nf_conv2d_layer_submodule.f90          done.
nf_avgpool2d_layer_submodule.f90       done.
nf_loss_submodule.f90                  done.
nf_embedding_layer_submodule.f90       done.
nf_layer_constructors.f90              done.
test_linear2d_layer.f90                done.
nf.f90                                 done.
nf_multihead_attention_layer_submodule.done.
nf_self_attention_layer.f90            done.
nf_cross_attention_layer.f90           done.
test_embedding_layer.f90               done.
nf_layer_constructors_submodule.f90    done.
nf_network_submodule.f90               done.
nf_layer_submodule.f90                 done.
dense_mnist.f90                        done.
simple.f90                             done.
mha_simple.f90                         done.
cnn_mnist.f90                          done.
cnn_mnist_1d.f90                       done.
quadratic.f90                          done.
sine.f90                               done.
merge_networks.f90                     done.
get_set_network_params.f90             done.
network_parameters.f90                 done.
test_loss.f90                          done.
test_maxpool2d_layer.f90               done.
test_insert_flatten.f90                done.
test_input2d_layer.f90                 done.
test_maxpool1d_layer.f90               done.
test_flatten_layer.f90                 done.
test_avgpool2d_layer.f90               done.
test_layernorm.f90                     done.
test_reshape2d_layer.f90               done.
test_conv2d_layer.f90                  done.
test_dropout_layer.f90                 done.
test_optimizers.f90                    done.
test_input3d_layer.f90                 done.
test_dense_layer.f90                   done.
test_conv1d_network.f90                done.
test_get_set_network_params.f90        done.
test_multihead_attention_layer.f90     done.
test_conv1d_layer.f90                  done.
test_avgpool1d_layer.f90               done.
test_conv2d_network.f90                done.
test_metrics.f90                       done.
test_locally_connected2d_layer.f90     done.
test_reshape_layer.f90                 done.
test_parametric_activation.f90         done.
test_input1d_layer.f90                 done.
test_dense_network.f90                 done.
libneural-fortran.a                    done.
dense_mnist                            done.
simple                                 done.
mha_simple                             done.
cnn_mnist                              done.
cnn_mnist_1d                           done.
quadratic                              done.
sine                                   done.
merge_networks                         done.
get_set_network_params                 done.
network_parameters                     done.
test_loss                              done.
test_maxpool2d_layer                   done.
test_insert_flatten                    done.
test_input2d_layer                     done.
test_maxpool1d_layer                   done.
test_flatten_layer                     done.
test_avgpool2d_layer                   done.
test_layernorm                         done.
test_embedding_layer                   done.
test_reshape2d_layer                   done.
test_conv2d_layer                      done.
test_dropout_layer                     done.
test_linear2d_layer                    done.
test_optimizers                        done.
test_input3d_layer                     done.
test_dense_layer                       done.
test_conv1d_network                    done.
test_get_set_network_params            done.
test_multihead_attention_layer         done.
test_conv1d_layer                      done.
test_avgpool1d_layer                   done.
test_conv2d_network                    done.
test_metrics                           done.
test_locally_connected2d_layer         done.
test_reshape_layer                     done.
test_parametric_activation             done.
test_input1d_layer                     done.
test_dense_network                     done.
[100%] Project compiled successfully.
```

**Comment by jinangshah21** [comment]
Actually I think fix in #10506 is for same issue as this but it just apply fix at else body of same function. I think that fix is better and in this PR also we should use that and also #10510 should be fixed with this change.

Suggestion:
```diff
diff --git a/src/lfortran/semantics/ast_common_visitor.h b/src/lfortran/semantics/ast_common_visitor.h
index 81c518114..03d3a3fcb 100644
--- a/src/lfortran/semantics/ast_common_visitor.h
+++ b/src/lfortran/semantics/ast_common_visitor.h
@@ -17106,6 +17106,16 @@ public:
                     std::string gp_proc_name = ASRUtils::symbol_name(gp->m_procs[i]);
                     ASR::symbol_t* m_proc = current_scope->resolve_symbol(
                         gp_proc_name);
+                    if (m_proc != nullptr) {
+                        // Verify the resolved symbol refers to the same function
+                        // as the one in the source generic procedure, not a
+                        // different function with the same name from another module
+                        ASR::symbol_t* resolved = ASRUtils::symbol_get_past_external(m_proc);
+                        ASR::symbol_t* expected = ASRUtils::symbol_get_past_external(gp_ext->m_procs[i]);
+                        if (resolved != expected) {
+                            m_proc = nullptr;
+                        }
+                    }
                     if( m_proc == nullptr ) {
                         std::string local_sym_ = gp_proc_name + "@" + local_sym;
                         m_proc = current_scope->resolve_symbol(local_sym_);
@@ -17126,6 +17136,16 @@ public:
                     std::string gp_ext_proc_name = ASRUtils::symbol_name(gp_ext->m_procs[i]);
                     ASR::symbol_t* m_proc = current_scope->resolve_symbol(
                         gp_ext_proc_name);
+                    if (m_proc != nullptr) {
+                        // Verify the resolved symbol refers to the same function
+                        // as the one in the source generic procedure, not a
+                        // different function with the same name from another module
+                        ASR::symbol_t* resolved = ASRUtils::symbol_get_past_external(m_proc);
+                        ASR::symbol_t* expected = ASRUtils::symbol_get_past_external(gp_ext->m_procs[i]);
+                        if (resolved != expected) {
+                            m_proc = nullptr;
+                        }
+                    }
                     if( m_proc == nullptr ) {
                         std::string local_sym_ = gp_ext_proc_name + "@" + local_sym;
                         m_proc = current_scope->resolve_symbol(local_sym_);
@@ -17159,6 +17179,16 @@ public:
                     std::string gp_ext_proc_name = ASRUtils::symbol_name(gp_ext->m_procs[i]);
                     ASR::symbol_t* m_proc = current_scope->resolve_symbol(
                         gp_ext_proc_name);
+                    if (m_proc != nullptr) {
+                        // Verify the resolved symbol refers to the same function
+                        // as the one in the source generic procedure, not a
+                        // different function with the same name from another module
+                        ASR::symbol_t* resolved = ASRUtils::symbol_get_past_external(m_proc);
+                        ASR::symbol_t* expected = ASRUtils::symbol_get_past_external(gp_ext->m_procs[i]);
+                        if (resolved != expected) {
+                            m_proc = nullptr;
+                        }
+                    }
                     if( m_proc == nullptr ) {
                         std::string local_sym_ = "@" + gp_ext_proc_name + "@";
                         m_proc = current_scope->resolve_symbol(local_sym_);
```

File: src/lfortran/semantics/ast_common_visitor.h [hunk 1]
```diff
@@ -17294,6 +17106,16 @@ class CommonVisitor : public AST::BaseVisitor<Derived> {
...
                     ASR::symbol_t* m_proc = current_scope->resolve_symbol(
                         gp_proc_name);
+                    // If the resolved symbol is actually a GenericProcedure
+                    // (or ExternalSymbol pointing to one), it means the
+                    // local rename collided with a specific procedure name.
+                    // Treat it as not found and import the actual Function.
+                    if( m_proc != nullptr ) {
+                        ASR::symbol_t* m_proc_underlying = ASRUtils::symbol_get_past_external(m_proc);
+                        if( ASR::is_a<T>(*m_proc_underlying) ) {
+                            m_proc = nullptr;
```
Comment (certik) [inline src/lfortran/semantics/ast_common_visitor.h:17304]: This seems like a very similar fix to the previous PR https://github.com/lfortran/lfortran/pull/10506. Let's merge that one first, then this one (if it is needed).

**Comment by certik** [comment]
@jinangshah21 go ahead and finish the PR.

**Comment by certik** [comment]
The https://github.com/lfortran/lfortran/pull/10506 is now merged. @jinangshah21 what exactly do you recommend we do here? What should be the right fix?

**Comment by jinangshah21** [comment]
I have updated PR with #10510 fix also.
