### PR TITLE
runtime: pre-connect standard Fortran units 5, 6, 0

### LINKED ISSUE #9252: Runtime: pre-connect standard units 5 (stdin) and 6 (stdout)
## Summary

LFortran does not pre-connect Fortran standard units 5 (stdin) and 6 (stdout) as required by the Fortran standard. This causes runtime errors when code uses explicit unit numbers for standard I/O.

## Reproducer

```fortran
program test_unit5
  implicit none
  integer :: x
  write(6,*) "Enter a number:"
  read(5,*) x
  write(6,*) "You entered:", x
end program
```

**Expected**: Program reads from stdin and writes to stdout
**Actual**: Runtime error `Internal Compiler Error: No file found with given unit number 5.`

## Workaround

Using `*` instead of explicit unit numbers works:
```fortran
read(*,*) x    ! Works
write(*,*) x   ! Works
```

## Impact

This blocks running LAPACK test suite which uses:
```fortran
INTEGER, PARAMETER :: NIN = 5, NOUT = 6
READ(NIN, FMT=*) ...
WRITE(NOUT, FMT=*) ...
```

## Proposed Fix

Pre-connect units 5 and 6 at program startup in `src/libasr/runtime/lfortran_intrinsics.c`.

## References

- Fortran 2018 Standard, Section 12.5.3.5: At the beginning of execution of a program, the units identified by the named constants INPUT_UNIT, OUTPUT_UNIT, and ERROR_UNIT are preconnected.
- iso_fortran_env defines input_unit = 5, output_unit = 6, error_unit = 0

### PR DESCRIPTION
**Pull request by krystophny**
## Summary

Pre-connect standard Fortran I/O units at program startup:
- Unit 5: stdin (INPUT_UNIT) - read-only
- Unit 6: stdout (OUTPUT_UNIT) - write-only  
- Unit 0: stderr (ERROR_UNIT) - write-only

The Fortran standard requires INPUT_UNIT, OUTPUT_UNIT, and ERROR_UNIT to be pre-connected, but their actual values are processor-dependent. Units 5/6/0 are the widely-used convention (gfortran, ifort, nvfortran) for legacy compatibility.

## Motivation

Previously only `read(*,*)` and `write(*,*)` worked for stdin/stdout. Code using explicit unit numbers failed:

```fortran
read(5,*) x   ! Failed: "No file found with given unit number 5"
write(6,*) x  ! Failed: "No file found with given unit number 6"
```

This is required for running LAPACK test suite which uses:
```fortran
INTEGER, PARAMETER :: NIN = 5, NOUT = 6
READ(NIN, FMT=*) ...
WRITE(NOUT, FMT=*) ...
```

## Changes

- Add constructor `_lfortran_init_standard_units()` in `lfortran_intrinsics.c` that pre-connects units 5, 6, 0 at program startup
- Update test references for `write_01` and `write_02` (they now correctly get unit 1 from `newunit` since unit 0 is pre-connected to stderr)

## Test Plan

- Added `write_12.f90` integration test that writes to unit 6
- All existing tests pass

Fixes #9252

### CODE REVIEW

**Comment by krystophny** [comment]
Reopening - this is needed for LAPACK test suite execution. The implementation uses __attribute__((constructor)) to properly pre-connect units at startup.

File: integration_tests/write_12.f90
Comment (HarshitaKalani) [inline integration_tests/write_12.f90:1]: Can we make this a bit more robust by adding an error stop check to verify the output? If that’s not easy to do here, we could register it in tests.toml and update the test references so we catch regressions later.

File: integration_tests/CMakeLists.txt [hunk 1]
```diff
@@ -2301,6 +2301,7 @@ RUN(NAME write_08 LABELS gfortran llvm llvm_wasm llvm_wasm_emcc)
 RUN(NAME write_09 LABELS gfortran llvm llvm_wasm llvm_wasm_emcc)
 RUN(NAME write_10 LABELS gfortran llvm llvm_wasm llvm_wasm_emcc)
 RUN(NAME write_11 LABELS gfortran llvm llvm_wasm llvm_wasm_emcc)
+RUN(NAME write_12 LABELS gfortran llvm)
```
Comment (HarshitaKalani) [inline integration_tests/CMakeLists.txt]:
```suggestion
RUN(NAME write_12 LABELS gfortran llvm llvm_wasm llvm_wasm_emcc)
```

Comment (krystophny) [reply integration_tests/CMakeLists.txt]: done!

File: integration_tests/write_12.f90
Comment (krystophny) [reply integration_tests/write_12.f90:1]: done!

Comment (certik) [reply integration_tests/write_12.f90:1]: How is this done? I think we are not verifying the output. You are checking that the string formatting works, but we already know that from other tests. So I would revert 5e314cdf5173533b18ee839614e550f6cda68c01, it's not adding any value. But let's do it later, we need to merge this PR now.

The way to test this is to check that it actually prints to stdout and strderr correctly, via tests/tests.toml with `run=true`. Let's do it in a subsequent PR.
