### PR TITLE
fix: custom operator with the same name as another variable

### LINKED ISSUE #7884: Variable and operator with the same name cause assert failure in custom operator
MRE

julienne_string_m.f90

```fortran
module julienne_string_m
  implicit none
  
  private
  public :: string_t
  public :: operator(.csv.)

  type string_t
    private
    character(len=:), allocatable :: string_
  end type

  interface operator(.csv.)
    module procedure string_csv
  end interface

contains
    
  function string_csv(s) result(res)
    type(string_t), intent(in) :: s
    character(len=100), allocatable :: res

  end function string_csv

end module julienne_string_m
```

julienne_formats_m.f90

```format
module julienne_formats_m
  character(len=*), parameter :: csv = "(*(G0,:,','))" !! comma-separated values
end module julienne_formats_m
```

julienne_m.f90

```fortran
module julienne_m
  use julienne_formats_m, only : csv
  use julienne_string_m, only : operator(.csv.) 
  implicit none
end module julienne_m
```

LFortran
```console
base) harshil-shah@harshil-shah-HP-Pavilion-Laptop-15-eg2xxx:~/lfortran$ lfortran -c julienne_string_m.f90 
(base) harshil-shah@harshil-shah-HP-Pavilion-Laptop-15-eg2xxx:~/lfortran$ lfortran -c julienne_formats_m.f90 
(base) harshil-shah@harshil-shah-HP-Pavilion-Laptop-15-eg2xxx:~/lfortran$ lfortran -c julienne_m.f90 
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/harshil-shah/lfortran/src/bin/lfortran", in _start
  File "./csu/../csu/libc-start.c", line 360, in __libc_start_main
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main
  File "/home/harshil-shah/lfortran/src/bin/lfortran.cpp", line 2729, in main
    return main_app(argc, argv);
  File "/home/harshil-shah/lfortran/src/bin/lfortran.cpp", line 2603, in main_app(int, char**)
    return compile_src_to_object_file(opts.arg_file, outfile, compiler_options.time_report, false,
  File "/home/harshil-shah/lfortran/src/bin/lfortran.cpp", line 1128, in (anonymous namespace)::compile_src_to_object_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, LCompilers::CompilerOptions&, LCompilers::PassManager&, bool)
    result = fe.get_asr2(input, lm, diagnostics);
  File "/home/harshil-shah/lfortran/src/lfortran/fortran_evaluator.cpp", line 276, in LCompilers::FortranEvaluator::get_asr2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::diag::Diagnostics&)
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics, lm);
  File "/home/harshil-shah/lfortran/src/lfortran/fortran_evaluator.cpp", line 298, in LCompilers::FortranEvaluator::get_asr3(LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::LocationManager&)
    compiler_options.symtab_only, compiler_options, lm);
  File "/home/harshil-shah/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 77, in LCompilers::LFortran::ast_to_asr(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::SymbolTable*, bool, LCompilers::CompilerOptions&, LCompilers::LocationManager&)
    entry_function_arguments_mapping, data_structure, lm);
  File "/home/harshil-shah/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 4184, in LCompilers::LFortran::symbol_table_visitor(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::SymbolTable*, LCompilers::CompilerOptions&, std::map<unsigned long, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > > > > >&, std::map<unsigned long, LCompilers::ASR::symbol_t*, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, LCompilers::ASR::symbol_t*> > >&, std::map<unsigned long, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >&, std::map<unsigned long, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >&, std::map<unsigned int, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > > > > >&, std::map<unsigned int, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::symbol_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::symbol_t*> > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::symbol_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::symbol_t*> > > > > >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> > > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> > > > > > > >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<int, std::allocator<int> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<int, std::allocator<int> > > > >&, std::vector<LCompilers::ASR::stmt_t*, std::allocator<LCompilers::ASR::stmt_t*> >&, LCompilers::LocationManager&)
    v.visit_TranslationUnit(ast);
  File "/home/harshil-shah/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 83, in LCompilers::LFortran::SymbolTableVisitor::visit_TranslationUnit(LCompilers::LFortran::AST::TranslationUnit_t const&)
    visit_ast(*x.m_items[i]);
  File "/home/harshil-shah/lfortran/src/lfortran/ast.h", line 4990, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::SymbolTableVisitor>::visit_ast(LCompilers::LFortran::AST::ast_t const&)
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/home/harshil-shah/lfortran/src/lfortran/ast.h", line 4946, in void LCompilers::LFortran::AST::visit_ast_t<LCompilers::LFortran::SymbolTableVisitor>(LCompilers::LFortran::AST::ast_t const&, LCompilers::LFortran::SymbolTableVisitor&)
    case astType::mod: { v.visit_mod((const mod_t &)x); return; }
  File "/home/harshil-shah/lfortran/src/lfortran/ast.h", line 4993, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::SymbolTableVisitor>::visit_mod(LCompilers::LFortran::AST::mod_t const&)
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/home/harshil-shah/lfortran/src/lfortran/ast.h", line 4566, in void LCompilers::LFortran::AST::visit_mod_t<LCompilers::LFortran::SymbolTableVisitor>(LCompilers::LFortran::AST::mod_t const&, LCompilers::LFortran::SymbolTableVisitor&)
    case modType::Module: { v.visit_Module((const Module_t &)x); return; }
  File "/home/harshil-shah/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 389, in LCompilers::LFortran::SymbolTableVisitor::visit_Module(LCompilers::LFortran::AST::Module_t const&)
    visit_ModuleSubmoduleCommon<AST::Module_t, ASR::Module_t>(x);
  File "/home/harshil-shah/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 327, in void LCompilers::LFortran::SymbolTableVisitor::visit_ModuleSubmoduleCommon<LCompilers::LFortran::AST::Module_t, LCompilers::ASR::Module_t>(LCompilers::LFortran::AST::Module_t const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
    visit_unit_decl1(*x.m_use[i]);
  File "/home/harshil-shah/lfortran/src/lfortran/ast.h", line 5002, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::SymbolTableVisitor>::visit_unit_decl1(LCompilers::LFortran::AST::unit_decl1_t const&)
    void visit_unit_decl1(const unit_decl1_t &b) { visit_unit_decl1_t(b, self()); }
  File "/home/harshil-shah/lfortran/src/lfortran/ast.h", line 4587, in void LCompilers::LFortran::AST::visit_unit_decl1_t<LCompilers::LFortran::SymbolTableVisitor>(LCompilers::LFortran::AST::unit_decl1_t const&, LCompilers::LFortran::SymbolTableVisitor&)
    case unit_decl1Type::Use: { v.visit_Use((const Use_t &)x); return; }
  File "/home/harshil-shah/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 3260, in LCompilers::LFortran::SymbolTableVisitor::visit_Use(LCompilers::LFortran::AST::Use_t const&)
    import_symbols_util(m, msym, remote_sym, local_sym,
  File "/home/harshil-shah/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 2912, in LCompilers::LFortran::SymbolTableVisitor::import_symbols_util(LCompilers::ASR::Module_t*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::queue<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::deque<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >&, LCompilers::Location const&)
    process_generic_proc_custom_op<ASR::CustomOperator_t>(local_sym, t,
AssertFailed: ASR::is_a<T>(*gp_sym)
```

### PR DESCRIPTION
**Pull request by akramhany**
Fixes #7884

Also, right now I am using (`~~`) as a symbol to distinct custom operators from other symbols, maybe we need to use something else.

### CODE REVIEW

File: src/lfortran/semantics/ast_common_visitor.h [hunk 1]
```diff
@@ -10608,6 +10613,15 @@ class CommonVisitor : public AST::BaseVisitor<Derived> {
             throw SemanticAbort();
         }
 
+        // If there is a variable with the same name as the operator
+        if (!ASR::is_a<ASR::CustomOperator_t>(*operator_sym)) {
+            diag.add(Diagnostic(
+                "`" + op + "` is not an operator",
+                Level::Error, Stage::Semantic, {Label("", {loc})}
+            ));
+            throw SemanticAbort();
```
Comment (certik) [inline src/lfortran/semantics/ast_common_visitor.h]: Can you add a test for this compiler error?

Comment (akramhany) [reply src/lfortran/semantics/ast_common_visitor.h]: After checking again, I found that with the fix I made this error won't be triggered so I removed it.

Comment (certik) [reply src/lfortran/semantics/ast_common_visitor.h]: That's why we always add a test. :) If it can't be triggered, then even better.

File: src/lfortran/semantics/ast_symboltable_visitor.cpp [hunk 2]
```diff
@@ -3281,6 +3287,11 @@ class SymbolTableVisitor : public CommonVisitor<SymbolTableVisitor> {
                     case AST::use_symbolType::DefinedOperator: {
                         remote_sym = AST::down_cast<AST::DefinedOperator_t>(
                             x.m_symbols[i])->m_opName;
+
+                        // Append "~~" to the begining of any custom defined operator
+                        if (should_change_custom_op_name(remote_sym)) {
+                            remote_sym = "~~" + remote_sym;
+                        }
```
Comment (certik) [inline src/lfortran/semantics/ast_symboltable_visitor.cpp:3294]: You are doing this exact operation 4 times in this PR, let's add it to a function?

File: src/lfortran/semantics/ast_common_visitor.h [hunk 3]
```diff
@@ -11569,6 +11576,17 @@ class CommonVisitor : public AST::BaseVisitor<Derived> {
...
+    // check if we should append "~~" to an operator name
+    bool should_change_custom_op_name(const std::string &op) {
+        static const std::string operator_chars = "+-*/~<=>";
+
+        if (op.find_first_of(operator_chars) != std::string::npos) {
+            return false;
+        }
+
+        return true;
+    }
```
Comment (certik) [inline src/lfortran/semantics/ast_common_visitor.h:11589]: Can you document what the logic is here? If the operator name starts with any of `+-*/~<=>`, then we keep it, otherwise we prepend `~~`?

Or is the logic that the operator must be equal to "+" (or "-", etc.) to avoid prepending `~~`?

When is a user operator equal to `+`? I thought that's not a valid name?

Comment (akramhany) [reply src/lfortran/semantics/ast_common_visitor.h:11589]: I have opened a new PR (#8137) with the mentioned changes, please take a look.
Thanks a lot for the feedback!
