### PR TITLE
Fix crash on deferred type-bound dispatch

### LINKED ISSUE #9978: Indexing of an object array leads to segfault upon method invocation
The following code when compiled with flang-20  prints `shape(b):  2 4`.
`$ cat arrayshape.f90 `
```
module MyTypeMod
   
   type, abstract :: AbsType
   contains
      procedure(alloc), deferred  :: alloc
   end type AbsType

   abstract interface
      subroutine alloc(self,b,n)
         import
         class(AbsType),       intent(in)  :: self
         real(8), allocatable, intent(out) :: b(:,:)
         integer,              intent(in)  :: n
      end subroutine alloc
   end interface
   
   type, extends(AbsType) :: MyType
   contains
      procedure, public  :: alloc => allocation
   end type MyType
   
contains
   
   subroutine allocation(self,b,n)
      class(MyType),        intent(in)  :: self
      real(8), allocatable, intent(out) :: b(:,:)
      integer,              intent(in)  :: n
      allocate( b(2,n) )
   end subroutine allocation
   
end module MyTypeMod


program arrayshape
   
   use MyTypeMod
   
   class(AbsType), allocatable :: objarr(:)
   
   allocate(MyType :: objarr(2))
   objarr = MyType()

   call allocator(objarr(1))
   
contains
   
   subroutine allocator(obj)
      class(AbsType), intent(in)  :: obj
      real(8),        allocatable :: b(:,:)
      call obj%alloc(b,4)
      write(*,*) 'shape(b): ', shape(b)      
   end subroutine allocator

end program arrayshape

```
With LFortran the result is a segfault:
`$ lfortran arrayshape.f90`
`Segmentation fault (core dumped)
`

### PR DESCRIPTION
**Pull request by certik**
The `objarr(1)` was wrapped as `class(AbsType)` with the static abstract vptr, not the element’s runtime vptr.  That made `obj%alloc(...)` resolve to a null slot and crash.

To fix it, we now preserve runtime vptr when creating class views from class-array elements.

Fixes #9978.

### CODE REVIEW

File: src/libasr/codegen/llvm_utils.cpp [hunk 1]
```diff
@@ -8632,9 +8632,19 @@ llvm::Value* LLVMUtils::handle_global_nonallocatable_stringArray(Allocator& al,
...
     
-    llvm::Value* LLVMStruct::create_class_view(ASR::Struct_t* const class_symbol, llvm::Value* const viewed_struct){
+    llvm::Value* LLVMStruct::create_class_view(ASR::Struct_t* const class_symbol,
+            llvm::Value* const viewed_struct, llvm::Value* vptr){
         llvm::Value* const allocated_class_structure = builder->CreateAlloca(llvm_utils->getClassType(class_symbol));
-        store_class_vptr(&class_symbol->base, allocated_class_structure, llvm_utils->module);
+        if (vptr) {
+            if (vptr->getType() != llvm_utils->vptr_type) {
+                vptr = builder->CreateBitCast(vptr, llvm_utils->vptr_type);
+            }
```
Comment (jinangshah21) [inline src/libasr/codegen/llvm_utils.cpp:8641]: This check might not be needed. But it is ok for now.

**Comment by certik** [comment]
I am just going to merge it, since the last test that didn't run yet already passed on the previous commit, so likely it will pass again. If not, we'll have to fix it of course.
