### PR TITLE
Offset data pointer in ``ArrayPhysicalCast``

### LINKED ISSUE #2061: Passing A(:,i) as an argument fails
Here is a minimal example:
```fortran
program test_arrays
real :: B(10,2)
B(:,1) = 1
B(:,2) = 2
print *, mysum(size(B,1), B(:,1))
print *, mysum(size(B,1), B(:,2))

contains

    real function mysum(n, A) result(r)
    integer, intent(in) :: n
    real, intent(in) :: A(n)
    integer :: i
    r = 0
    do i = 1, size(A)
        r = r + A(i)
    end do
    end function

end program
```
This gives:
```console
$ lfortran a.f90 
1.00000000e+01
1.00000000e+01
$ gfortran a.f90 && ./a.out 
   10.0000000    
   20.0000000    
```

Note that this does not happen if the array is declared as `A(:)` instead of `A(n)`. There are other variations of this bug, such as having a function hierarchy, a few accepting `A(:)` and eventually passing to `A(n)`.

### PR DESCRIPTION
**Pull request by czgdp1807**
Closes #2061

### CODE REVIEW

File: src/libasr/codegen/asr_to_llvm.cpp [hunk 1]
```diff
@@ -4356,6 +4356,7 @@ class ASRToLLVMVisitor : public ASR::BaseVisitor<ASRToLLVMVisitor>
                 arg = LLVM::CreateLoad(*builder, arg);
             }
             tmp = LLVM::CreateLoad(*builder, arr_descr->get_pointer_to_data(arg));
+            tmp = llvm_utils->create_ptr_gep(tmp, arr_descr->get_offset(arg));
```
Comment (certik) [inline src/libasr/codegen/asr_to_llvm.cpp:4359]: Awesome, I was hoping the fix is a one liner!

**Comment by certik** [comment]
I tested this PR and I think I get the same first token as gfortran! For the first time. The other tokens are still bad, but I will investigate this.

**Review by certik — APPROVED** [review]
I think this looks great. Is it ok to merge this?

**Comment by certik** [comment]
I think we have it!!!! Without cache:
```
Loading the model...
    done. Time:.687E+01s, Model file version: 1

Model parameters:
n_vocab = 50257
n_ctx   =  1024
n_embd  =   768
n_layer =    12
n_head  =    12

Input text
Alan Turing theorized that computers would one day become very powerful, but even he could not imagine

Encoding: tokenizing input text into tokens (currently slow)...
    done. Time:.372E+00s

Input parameters:
n_seq                =  19
n_tokens_to_generate =  20

Input tokens:
36235 39141 18765 1143 326 9061 561 530 1110 1716 845 3665 11 475 772 339 714 407 5967 


Running model...

Specified width is not enough for the specified number of decimal digits
: No such file or directory
    done. Time:.382E+01s (****x)

Output tokens:
703 484 561 307 1498 284 466 523 13 198 198 1 40 892 326 262 749 1593 1517 318 
```
Agrees with GFortran:
```
Loading the model...
    done. Time:   0.085s, Model file version: 1

Model parameters:
n_vocab = 50257
n_ctx   =  1024
n_embd  =   768
n_layer =    12
n_head  =    12

Input text
Alan Turing theorized that computers would one day become very powerful, but even he could not imagine

Encoding: tokenizing input text into tokens (currently slow)...
    done. Time:   0.197s

Input parameters:
n_seq                =  19
n_tokens_to_generate =  20

Input tokens:
       36235       39141       18765        1143         326        9061         561         530        1110        1716         845        3665          11         475         772         339         714         407        5967


Running model...
At line 335 of file /Users/ondrej/repos/fastGPT/gpt2.f90
Fortran runtime warning: An array temporary was created for argument 'kv_cache' of procedure 'gpt2'

    done. Time:   3.700s (6.42x)

Output tokens:
         703         484         561         307        1498         284         466         523          13         198         198           1          40         892         326         262         749        1593        1517         318
```

**Comment by certik** [comment]
I am just going to merge this. Let me setup testing at the CI.

**Comment by certik** [comment]
I got everything working: https://github.com/lfortran/lfortran/pull/2065
