### PR TITLE
fix: raise semantic error for procedure pointer

### LINKED ISSUE #10131: ICE : Raise sematnic error
```.f90
module mmm
  contains 
  integer function f(x) result(r)
    interface 
      integer function x() 
      end function 
    end interface
    ! r = x + 1
  end function f 
  integer function dummy() result(r)
    r = 42
  end function dummy
end module 

program p
  use mmm
  implicit none
  integer :: res
  procedure(), pointer :: pf
  pf => dummy
  res = f(dummy)
  print *, res
end program 
```

### PR DESCRIPTION
**Pull request by yuvrajsinghgmx**
Closes #10131 

Description for the fix :

`ast_body_visitor` -  Added check for function to subroutine and vice versa
`ast_common_visitor` - Check for `procedure()` without `interface`
`continue_compilation` - add tests

i am not sure about the changes in `continue_compilation` please let me know if any fix is required.

### CODE REVIEW

File: tests/errors/continue_compilation_1.f90
Comment (HarshitaKalani) [inline tests/errors/continue_compilation_1.f90]: You can remove equal number of lines to keep the diff minimal in references.

File: tests/reference/asr-continue_compilation_1-04b6d40.stderr [hunk 1]
```diff
@@ -122,197 +128,203 @@ semantic error: Interface 'missing_global_interface' is referenced but not defin
...
-   --> tests/errors/continue_compilation_1.f90:210:5 - 212:49
+   --> tests/errors/continue_compilation_1.f90:227:5 - 229:49
     |
-210 |        implicit integer(a-f), real(e-z)
+227 |        implicit integer(a-f), real(e-z)
     |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
 ...
     |
-212 |        ! Put declarations below without empty lines
+229 |        ! Put declarations below without empty lines
```
Comment (HarshitaKalani) [inline tests/reference/asr-continue_compilation_1-04b6d40.stderr]: All the lines shifted by 17 lines because of your addition of 17 lines. Follow the comment above to address this.

Comment (yuvrajsinghgmx) [reply tests/reference/asr-continue_compilation_1-04b6d40.stderr]: Done

**Comment by yuvrajsinghgmx** [comment]
I have made the required changes.
Thanks for the review @HarshitaKalani .
