### PR TITLE
Fix : GenericProcedure calls in variable declaration [postpone the `AST::FuncCallOrArray` node instead of the whole `AST::Declaration `node]

### LINKED ISSUE #7095: Bug : genericProcedure call while declaring a returnVar is raising false error
```.f90
module mm
  interface generic
     procedure :: ff
  end interface
  contains

  pure function ff() result(ret)
    integer :: ret
    ret  = 190
  end function

  function foo() result(arr) 
    integer :: arr(generic()) ! >>>>>>>>>>>>>>>>>>>>>>>>> HERE
  end function

end module

program pop
  use mm
  print *, size(foo())
end program pop
```

Current main
```Console
assem@assem-PC:~/Desktop/fortran/compile_gsnap$ lfortran  tt4.f90 
semantic error: Return type not specified
  --> tt4.f90:12:3 - 14:14
   |
12 |      function foo() result(arr) 
   |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^...
...
   |
14 |      end function
   | ...^^^^^^^^^^^^^^ 


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```
Before this commit 023b108f576247b438f3e117f5eda704ee278b50

```Console
assem@assem-PC:~/Desktop/fortran/compile_gsnap$ ../../../LFortranUpStream/lfortran/src/bin/lfortran tt4.f90 
semantic error: Function 'generic' not found (not user defined nor intrinsic)
  --> tt4.f90:13:20
   |
13 |     integer :: arr(generic())
   |                    ^^^^^^^^^ 


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.

```

### PR DESCRIPTION
**Pull request by assem2002**
Fix #7095 
- It's an enhancement to this PR https://github.com/lfortran/lfortran/pull/7081
### What it it fixes : 
GenericProcedure calls while declaring a variable `integer :: ret(genericProcedure())`

### What is the issue ? : 
We used to postpone the evaluation of the whole `AST::Declaration` node till we Evaluate symbolTable of both the Functions and then -> `AST::Interface`.
That led to some `ASR::Function` node being built with incomplete signature, which invoked semantic errors see #7095.

### The Fix :
Just postpone the `AST::FuncCallOrArray` node instead of the whole `AST::Declaration` node, then evaluate the node at the end (after having complete `ASR::Function` + `ASR::GenericProcedure` nodes).

### CODE REVIEW

File: integration_tests/modules_15b.f90 [hunk 1]
```diff
@@ -241,7 +241,7 @@ subroutine sub_int_double_value_name(a, b, r) &
     ! int f_string(char *s)
     integer(c_int) function f_string0(s) result(r) bind(c, name="f_string")
     import :: c_int, c_char
-    character(len=1, kind=c_char), intent(in) :: s(*)
+    character(len=1, kind=c_char), intent(in) :: s
```
Comment (assem2002) [inline integration_tests/modules_15b.f90:244]: the type of this node used to be like this `(String 1 1 () PointerString)` --- with the fix in this PR the type got corrected to an **array of type string** ( I don't know why :) ).

The C function is declared as : 
```C
int f_string(char *s) {
    return strlen(s);
}
```

So I just fixed the test

File: tests/reference/asr-array12-cb81afc.stdout [hunk 2]
```diff
@@ -223,7 +234,12 @@
                                                     ()
                                                     ()
                                                     Default
-                                                    (String 1 1 () PointerString)
+                                                    (Array
+                                                        (String 1 1 () PointerString)
+                                                        [(()
+                                                        ())]
+                                                        StringArraySinglePointer
+                                                    )
```
Comment (assem2002) [inline tests/reference/asr-array12-cb81afc.stdout:242]: That's the correct node. I don't know why exactly it got corrected :)

File: integration_tests/modules_15b.f90 (hunk 1 above)
Comment (assem2002) [reply integration_tests/modules_15b.f90:244]: opened an issue here https://github.com/lfortran/lfortran/issues/7136. Gfortran casts a string to an array of strings if needed, while we don't.
