### PR TITLE
fix: add support for logical to integer cast

### LINKED ISSUE #3436: Logical to integer casting raises semantic error
### Minimal reproducible example:

For the below fortran program:
```f90
program ImplicitLogicalToIntCastExample
    implicit none
    
    logical :: logicalValue
    integer :: integerValue
    
    ! Assign a logical value
    logicalValue = .TRUE.
    
    ! Perform an implicit logical to integer cast
    integerValue = logicalValue
    print *, integerValue

end program ImplicitLogicalToIntCastExample
```

```
>>> gfortran a.f90 -o a.out && ./a.out

   11 |     integerValue = logicalValue
      |                   1
Warning: Extension: Conversion from LOGICAL(4) to INTEGER(4) at (1)
ld: warning: ignoring duplicate libraries: '-lemutls_w', '-lgcc'

1

>>> ./src/bin/lfortran a.f90 -o a.out && ./a.out
semantic error: Type mismatch in assignment, the types must be compatible
  --> a.f90:11:5
   |
11 |     integerValue = logicalValue
   |     ^^^^^^^^^^^^   ^^^^^^^^^^^^ type mismatch (integer and logical)


```

### PR DESCRIPTION
**Pull request by HarshilShah1804**
Fixes #3436

### CODE REVIEW

File: src/lfortran/semantics/asr_implicit_cast_rules.h [hunk 1]
```diff
@@ -561,6 +561,58 @@ class ImplicitCastRules {
...
+                            new_array[i] = data[i] ? 1 : 0;
+                        }
+                        new_data = new_array;
+                    } else if (dest_kind == 1) {
+                        int8_t *new_array = al.allocate<int8_t>(array_size);
+                        for (size_t i = 0; i < array_size; i++) {
+                            new_array[i] = data[i] ? 1 : 0;
+                        }
+                        new_data = new_array;
+                    }
```
Comment (kmr-srbh) [inline src/lfortran/semantics/asr_implicit_cast_rules.h:607]: We can make the if-else blocks only check the kind and allocate the array, then run the loop at the end.

File: integration_tests/integer_to_logical_cast.f90 [hunk 2]
```diff
@@ -0,0 +1,16 @@
...
+    
+    ! Assign a logical value
+    logicalValue = .TRUE.
+    
+    ! Perform an implicit logical to integer cast
+    integerValue = logicalValue
+    print *, integerValue
+
+    if (integerValue /= 1) error stop
+
```
Comment (kmr-srbh) [inline integration_tests/integer_to_logical_cast.f90]: Please add tests for arrays.

File: src/lfortran/semantics/asr_implicit_cast_rules.h (hunk 1 above)
Comment (HarshilShah1804) [reply src/lfortran/semantics/asr_implicit_cast_rules.h:607]: I think it would complicate things up as all the arrays are of different types. Also, we handle every other casting in a similar way. So, I think it's fine.

File: src/lfortran/semantics/ast_body_visitor.cpp [hunk 3]
```diff
@@ -5812,6 +5812,16 @@ class BodyVisitor : public CommonVisitor<BodyVisitor> {
                             array_reshape->m_type = ASRUtils::duplicate_type(al, array_reshape->m_type, &array_reshape_dims, ASR::array_physical_typeType::DescriptorArray,true);
                         }
                     }
+                    if (ASRUtils::is_logical(*value_type) && ASRUtils::is_integer(*target_type)) {
+                        if (!compiler_options.logical_casting) {
+                            diag.add(Diagnostic(
+                                "Implicit casting from LOGICAL to INTEGER is not allowed by default. Use `--logical-casting` flag to enable it.",
```
Comment (kmr-srbh) [inline src/lfortran/semantics/ast_body_visitor.cpp:5837]: Please add an error test for this.
