### PR TITLE
enh: mangle variables and routines declared under intrinsic module

### LINKED ISSUE #7585: duplicate symbols in separate compilation for intrinsic modules
> a.f90

```fortran
module xx
use, intrinsic:: ieee_arithmetic, only: ieee_quiet_nan
contains
subroutine check(x)
real :: x
x = ieee_value(1.0, ieee_quiet_nan)
print *, "x = ", x
end subroutine
end module
```

> b.f90

```fortran
program main
use ieee_arithmetic, only: ieee_quiet_nan
use xx
real :: x
call check(x)
end program
```

```console
% lfortran -c a.f90 --generate-object-code
% lfortran -c b.f90 --generate-object-code
% lfortran a.o b.o --generate-object-code 
duplicate symbol '_ieee_positive_denormal' in:
    /Users/pranavchiku/repos/lfortran/b.o
    /Users/pranavchiku/repos/lfortran/a.o
duplicate symbol '_ieee_negative_denormal' in:
    /Users/pranavchiku/repos/lfortran/b.o
    /Users/pranavchiku/repos/lfortran/a.o
duplicate symbol '_ieee_positive_inf' in:
    /Users/pranavchiku/repos/lfortran/b.o
    /Users/pranavchiku/repos/lfortran/a.o
duplicate symbol '_ieee_negative_normal' in:
    /Users/pranavchiku/repos/lfortran/b.o
    /Users/pranavchiku/repos/lfortran/a.o
duplicate symbol '_ieee_quiet_nan' in:
    /Users/pranavchiku/repos/lfortran/b.o
    /Users/pranavchiku/repos/lfortran/a.o
duplicate symbol '_ieee_positive_normal' in:
    /Users/pranavchiku/repos/lfortran/b.o
    /Users/pranavchiku/repos/lfortran/a.o
duplicate symbol '_ieee_signaling_nan' in:
    /Users/pranavchiku/repos/lfortran/b.o
    /Users/pranavchiku/repos/lfortran/a.o
duplicate symbol '_ieee_positive_zero' in:
    /Users/pranavchiku/repos/lfortran/b.o
    /Users/pranavchiku/repos/lfortran/a.o
duplicate symbol '_ieee_negative_zero' in:
    /Users/pranavchiku/repos/lfortran/b.o
    /Users/pranavchiku/repos/lfortran/a.o
duplicate symbol '_ieee_negative_inf' in:
    /Users/pranavchiku/repos/lfortran/b.o
    /Users/pranavchiku/repos/lfortran/a.o
ld: 10 duplicate symbols
clang: error: linker command failed with exit code 1 (use -v to see invocation)
The command 'clang -o a.out a.o b.o  -L"/Users/pranavchiku/repos/lfortran/src/bin/../runtime" -Wl,-rpath,"/Users/pranavchiku/repos/lfortran/src/bin/../runtime" -llfortran_runtime -lm' failed.
Tip: If there is a linker issue, switch the linker using --linker=<CC> option or create an environment variable `export LFORTRAN_LINKER=<CC>`, where CC is clang or gcc
Also, if required use --linker-path=<PATH>, where PATH has location to look for the linker execuatable
```

### PR DESCRIPTION
**Pull request by Pranavchiku**
Fixes #7585. With this PR we get more packages of stdlib compiled with separate compilation.

### CODE REVIEW

File: src/libasr/pass/unique_symbols.cpp [hunk 1]
```diff
@@ -127,6 +127,13 @@ class SymbolRenameVisitor: public ASR::BaseWalkVisitor<SymbolRenameVisitor> {
             should_mangle = true;
         }
         for (auto &a : x.m_symtab->get_scope()) {
+            if ( intrinsic_module_name_mangling && startswith(x.m_name, "lfortran_intrinsic") ) {
```
Comment (Pranavchiku) [inline src/libasr/pass/unique_symbols.cpp:130]: use `x.m_intrinsic` here and at all places.

```suggestion
            if ( intrinsic_module_name_mangling && x.m_intrinsic ) {
```

Comment (Pranavchiku) [reply src/libasr/pass/unique_symbols.cpp:130]: I've opened https://github.com/lfortran/lfortran/issues/7587 and labelled easy to fix if new contributor wants to pick this up.
