### PR TITLE
Fix missing quotes and apostrophes on output in FORMAT statement

### LINKED ISSUE #9902: FORMAT statement: missing quotes and apostrophes on output
```
program apos_fmt
  implicit none

  print *, '''Hello world!'''
  print *, """Hello world!"""
  write (*,100)
  write (*,101)

100 format ('''Hello world!''')
101 format ("""Hello world!""")

end program
```
```
$ lfortran apos_fmt.f90
'Hello world!'
"Hello world!"
Hello world!
Hello world!
$
``` 
```
$ gfortran apos_fmt.f90
$ ./a.out
 'Hello world!'
 "Hello world!"
'Hello world!'
"Hello world!"
$
```

### PR DESCRIPTION
**Pull request by yuvrajsinghgmx**
Fixes #9902 

Description for the fix : 

1) Remove spaces from raw format string 
2) In case of `' '` this `if (cformat[index+1] == '\'')` , `index += 2` skips the pair.
3) `unescape_quoted_literal` whenever it finds `' ' `  copies only one `'` to the final result and ` "` is copied as it is because it does not match this `'`.

Fix : Comment from PR #9910

### CODE REVIEW

File: src/libasr/codegen/llvm_utils.cpp [hunk 1]
```diff
@@ -8795,7 +8795,7 @@ llvm::Value* LLVMUtils::handle_global_nonallocatable_stringArray(Allocator& al,
             llvm_utils->i8_ptr
         };
         std::vector<llvm::Constant*> type_info_member_values;
-        type_info_member_values.reserve(2); // A type-info object has minimum 1 member.
+        type_info_member_values.reserve(2); // A type-info object has minimum 2 member.
```
Comment (certik) [inline src/libasr/codegen/llvm_utils.cpp]:
```suggestion
        type_info_member_values.reserve(2); // A type-info object has minimum 2 members.
```

File: src/libasr/codegen/llvm_utils.cpp [hunk 2]
```diff
@@ -8926,7 +8926,7 @@ llvm::Value* LLVMUtils::handle_global_nonallocatable_stringArray(Allocator& al,
...
```
Comment (certik) [inline src/libasr/codegen/llvm_utils.cpp]:
```suggestion
        type_info_member_values.reserve(2); // A type-info object has minimum 2 members.
```
