### PR TITLE
fix : allow pointer declaration association with non-parameter target variables

### LINKED ISSUE #7949: bug: initialisation of pointer variable during declaration not allowed
### Minimal Reproducible Example

```fortran
program main

   type :: my_type
      integer :: x
   end type my_type

   type(my_type), target :: my_var
   type(my_type), pointer :: p => my_var
end program main
```

### Output

```console
(lf) saurabhkumar@Mac lfortran % gfortran test.f90 && ./a.out
(lf) saurabhkumar@Mac lfortran % lfortran test.f90
semantic error: Named initialization not supported with: my_var
 --> test.f90:8:4
  |
8 |    type(my_type), pointer :: p => my_var
  |    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

### PR DESCRIPTION
**Pull request by Jatinagarwal24**
fixes #7949 
Derived-type pointer declarations with name initializers (for example, p => my_var) were incorrectly handled as constant/parameter initialization, which produced semantic errors like:

Initialization with non-constant variable is not allowed
Initialization must reduce to a compile time constant
Fix:

Treat name initializers on pointer declarations as pointer association, not parameter-style constant initialization.
Accept variable targets when they have target or pointer attribute.
Validate type compatibility between pointer and target.
Skip compile-time-constant enforcement for valid pointer association initializers.
Add integration regression coverage for declaration-time pointer association.

### CODE REVIEW

File: src/lfortran/semantics/ast_common_visitor.h [hunk 1]
```diff
@@ -7008,6 +7009,45 @@ class CommonVisitor : public AST::BaseVisitor<Derived> {
...
+                                        "Pointer initialization target `" + sym_name + "` is not a variable",
+                                        Level::Error, Stage::Semantic, {
+                                            Label("",{x.base.base.loc})
+                                        }));
+                                    throw SemanticAbort();
+                                }
+                                ASR::Variable_t *var = ASR::down_cast<ASR::Variable_t>(sym_found);
+                                if (!(var->m_target_attr ||
+                                      ASR::is_a<ASR::Pointer_t>(*
+                                        ASRUtils::type_get_past_allocatable(var->m_type)))) {
```
Comment (kmr-srbh) [inline src/lfortran/semantics/ast_common_visitor.h]: Pointer variable can have only a `target` attributed variable as an initialiser. Pointer variables as target are not allowed.

File: src/lfortran/semantics/ast_common_visitor.h [hunk 2]
```diff
@@ -7008,6 +7009,45 @@ class CommonVisitor : public AST::BaseVisitor<Derived> {
...
+                                            Label("",{x.base.base.loc}),
+                                            Label("target declared here", {var->base.base.loc}, false)
+                                        }));
+                                    throw SemanticAbort();
+                                }
+
+                                init_expr = ASRUtils::EXPR(ASR::make_Var_t(al,
+                                    s.m_initializer->base.loc, sym_found));
+                            } else {
+                            // Handle initialization with named parameter constants
```
Comment (jinangshah21) [inline src/lfortran/semantics/ast_common_visitor.h]: Indentation after else is incorrect here.

File: src/lfortran/semantics/ast_common_visitor.h [hunk 3]
```diff
@@ -6998,7 +6998,8 @@ class CommonVisitor : public AST::BaseVisitor<Derived> {
                             }
 
                         } else {
-                            // Handle initialization with named parameter constants
+                            // Handle declaration-time pointer association:
+                            //   type(t), pointer :: p => target_var
```
Comment (jinangshah21) [inline src/lfortran/semantics/ast_common_visitor.h]: Update comment that it initializes both names parameter and pointer association.

File: src/lfortran/semantics/ast_common_visitor.h [hunk 4]
```diff
@@ -7008,6 +7009,45 @@ class CommonVisitor : public AST::BaseVisitor<Derived> {
...
+                                        Level::Error, Stage::Semantic, {
+                                            Label("",{x.base.base.loc}),
+                                            Label("declared here", {var->base.base.loc}, false)
+                                        }));
+                                    throw SemanticAbort();
+                                }
+
+                                ASR::ttype_t* lhs_type = ASRUtils::type_get_past_pointer(type);
+                                ASR::ttype_t* rhs_type = ASRUtils::type_get_past_pointer(var->m_type);
+                                if (!ASRUtils::check_equal_type(lhs_type, rhs_type, nullptr, nullptr)) {
```
Comment (kmr-srbh) [inline src/lfortran/semantics/ast_common_visitor.h]:
```suggestion
                                if (!ASRUtils::check_equal_type(lhs_type, rhs_type, ASRUtils::EXPR(ASR::make_Var_t(al,
                                    variable_added_to_symtab->base.base.loc, &variable_added_to_symtab->base)), ASRUtils::EXPR(ASR::make_Var_t(al,
                                    var->base.base.loc, &var->base)))) {
```

We need to pass the variable expression for checking types of structs and classes.

**Comment by Jatinagarwal24** [comment]
Hi @jinangshah21 , @kmr-srbh I have made the suggested changes pls once check it.

**Comment by Jatinagarwal24** [comment]
Hi @kmr-srbh can you pls run exhaustive tests.
