### PR TITLE
fix: create association for pointer member during replacing `StructConstructor` 

### LINKED ISSUE #8069: Handle Initialization of SIM which is pointer type variable
MRE:
```fortran
module temp
public :: build_target_t
type build_target_ptr
    type(build_target_t), pointer :: ptr => null()
end type build_target_ptr

type build_target_t
end type
end module

program test
use temp
type(build_target_t), pointer :: x
type(build_target_ptr) :: y
y = build_target_ptr(x)
end program  
```

LFortran Error:
```console
code generation error: asr_to_llvm: module failed verification. Error:
Stored value type does not match pointer operand type!
  store %build_target_t %7, %build_target_t** %5, align 1
 %build_target_t*
```

### PR DESCRIPTION
**Pull request by jinangshah21**
Fixes #8069

### CODE REVIEW

File: integration_tests/derived_types_71.f90 [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+end module
+
+program derived_type_71
+    use derived_type_71_mod
+    type(build_target_t), pointer :: x
+    type(build_target_t) :: z
+    type(build_target_ptr) :: y
+
+    z%key = 12
+    x => z
```
Comment (certik) [inline integration_tests/derived_types_71.f90:17]: This fails in GFortran:
```
[ 62%] Linking Fortran executable derived_types_67
/home/runner/work/lfortran/lfortran/integration_tests/derived_types_71.f90:17:9:
[ 62%] Linking Fortran executable derived_types_68

   17 |     x => z
      |         1
Error: Pointer assignment target is neither TARGET nor POINTER at (1)
```
The `z` variable must be declared with `target`.
