### PR TITLE
fix: deallocate string/struct members if rhs member is unallocated

### LINKED ISSUE #9500: Handle struct arrayItem passed in operator overloaded call consisting unallocated string
MRE:
```fortran
module dep_mod
    implicit none

    type :: dep_t
        character(len=:), allocatable :: proj_dir
    contains
        procedure :: equal_dep
        generic   :: operator(==) => equal_dep
    end type dep_t

contains

    logical function equal_dep(lhs, rhs)
        class(dep_t), intent(in) :: lhs, rhs
        
        if (allocated(lhs%proj_dir) .neqv. allocated(rhs%proj_dir)) then
            equal_dep = .false.
        else if (.not. allocated(lhs%proj_dir)) then
            equal_dep = .true.
        else
            equal_dep = lhs%proj_dir == rhs%proj_dir
        end if
    end function equal_dep

end module dep_mod

program test_dep_tree
    use dep_mod
    implicit none

    type(dep_t), allocatable :: d1(:), d2(:)
    integer :: i

    allocate(d1(5), d2(5))

    do i = 1, 3
        d1(i)%proj_dir = "AAA"
        d2(i)%proj_dir = "AAA"
    end do

    do i = 1, size(d1)
        print *, "proj allocated =", allocated(d1(i)%proj_dir), allocated(d2(i)%proj_dir)
        print *, "is dep same =", d1(i) == d2(i)
    end do
end program test_dep_tree
```

Outputs:
```console
(base) jinang_shah@JNSLAP:~/Desktop/lfortran$ gfortran c.f90 && ./a.out
 proj allocated = T T
 is dep same = T
 proj allocated = T T
 is dep same = T
 proj allocated = T T
 is dep same = T
 proj allocated = F F
 is dep same = T
 proj allocated = F F
 is dep same = T
(base) jinang_shah@JNSLAP:~/Desktop/lfortran$ lfortran c.f90
proj allocated =    T    T
is dep same =    T
proj allocated =    T    T
is dep same =    T
proj allocated =    T    T
is dep same =    T
proj allocated =    F    F
is dep same =    F
proj allocated =    F    F
is dep same =    F
```

### PR DESCRIPTION
**Pull request by jinangshah21**
Fixes #9500

### CODE REVIEW

File: src/libasr/codegen/llvm_utils.cpp [hunk 1]
```diff
@@ -9227,11 +9229,23 @@ llvm::Value* LLVMUtils::handle_global_nonallocatable_stringArray(Allocator& al,
                                     llvm_utils->getIntType(4), {}, true)->getPointerTo(), vtable_ptr);
                                 fn = builder->CreateBitCast(fn, fnPtrTy);
                             }
-                        }, [=]() {});
+                        }, [&]() {
+                            if (ASRUtils::is_allocatable(member_type)) {
+                                // If source allocatable struct is not allocated, then
+                                // deallocate the destination allocatable struct
+                                // TODO: Properly Deallocate all members of struct
+                                builder->CreateCall(llvm_utils->_Deallocate(),
```
Comment (jinangshah21) [inline src/libasr/codegen/llvm_utils.cpp:9237]: Here struct members should be correctly deallocated. for this I have opened issue #9511

**Review by certik — APPROVED** [review]
