### PR TITLE
fix: Create temporary for scalar function with lhs array variable is one of its argument

### LINKED ISSUE #5991: (PRIMA) Create temporary for common variable in LHS and RHS and use it in function calls
MRE :
```fortran
program test
    real :: x(4) = [1.0, 2.0, 3.0, 4.0]
    x = x / norm(x)
    print *, x
contains
function norm(vec) result(res)
    implicit none
    real, intent(in) :: vec(:)   
    real :: res                  
    integer :: i                 
    res = 0.0                    
    do i = 1, size(vec)
        res = res + vec(i)**2   
    end do
    res = sqrt(res)             
end function norm
end program
```

GFortran Outptut :  `0.182574183      0.365148365      0.547722518      0.730296731`
LFortran Outptu :  `1.82574183e-01    3.71177405e-01    5.97957253e-01    9.83877778e-01`

### PR DESCRIPTION
**Pull request by jinangshah21**
Fixes #5991

### CODE REVIEW

**Comment by jinangshah21** [comment]
I will solve PRIMA Segfault.

But I don't know why below CI failure happens :
```console
[  9%] Building Fortran object CMakeFiles/types_01_STD_F23.dir/types_01.f90.o
semantic error: No implicit return type available for `res`
  --> /home/runner/work/lfortran/lfortran/integration_tests/functions_30.f90:17:5 - 27:17
   |
17 |        function norm(vec) result(res)
   |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
...
   |
27 |    end function norm
   | ...^^^^^^^^^^^^^^^^^ 


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
make[2]: *** [CMakeFiles/functions_30_STD_F23.dir/build.make:75: CMakeFiles/functions_30_STD_F23.dir/functions_30.f90.o] Error 1 
```

**Comment by jinangshah21** [comment]
For PRIMA with LLVM 19, this is weird segfault :
I had done following workaround before :
```cpp
tmp_cvsabs = matprod(abs(dnew), abs(A(:, iact)))
 cvsabs = tmp_cvsabs + abs(b(iact)) + cviol
```

But now if I do below then Segfault for this PR gets resolved :
```cpp
tmp_cvsabs = matprod(abs(dnew), abs(A(:, iact)))
cvsabs = matprod(abs(dnew), abs(A(:, iact))) + abs(b(iact)) + cviol
```

Also if I remove `tmp_cvsabs` then again it segfaults with this PR.

File: integration_tests/functions_30.f90 [hunk 1]
```diff
@@ -4,10 +4,25 @@ program functions_30
...
+    x = x / norm(x)
+    print *, x
+    if(any(abs(x - [0.182574183, 0.365148365, 0.547722518, 0.730296731]) > 10e-12)) error stop
 contains 
     function max_func(x) result(y)
       real, intent(in) :: x(:)
       real :: y
       y = maxval(x)
     end function
+    function norm(vec) result(res)
```
Comment (kmr-srbh) [inline integration_tests/functions_30.f90:17]: Please prepend `real` here and remove the declaration of `res` to fix the CI failure.

File: integration_tests/functions_30.f90 [hunk 2]
```diff
@@ -4,10 +4,25 @@ program functions_30
     if(maxval([1.0,x]) /= 4.0) error stop
     print *, max_func([1.0,x])
     if(max_func([1.0,x]) /= 4.0) error stop
+    !! Assignment with function on rhs having lhs var in its arg
+    x = x / norm(x)
+    print *, x
+    if(any(abs(x - [0.182574183, 0.365148365, 0.547722518, 0.730296731]) > 10e-12)) error stop
 contains 
     function max_func(x) result(y)
```
Comment (kmr-srbh) [inline integration_tests/functions_30.f90:12]: Likewise.

**Review by kmr-srbh — COMMENTED** [review]
The stated CI failure is due to the use of `--std=f23` flag. You can fix it like this.

**Review by Pranavchiku — CHANGES_REQUESTED** [review]
A way forward will be to investigate where exactly it fails inside matprod or during binary addition of output of matprod and other array.

**Comment by jinangshah21** [comment]
For PRIMA LLVM 19 segfault I have commented a line in `DEBUGGING` block which will not cause any functional change. But because of that llvm 19 was getting segfault.

**Review by Pranavchiku — APPROVED** [review]
Thank you, this is good!
