### PR TITLE
fix: 'intrinsic' attribute refers to intrinsic procedure

### LINKED ISSUE #5857: intrinsic variable conflicts with variable of same name
## Minimal Reproducible Example

For the below Fortran program, extracted from *fman* repository:
```f90

module M_match
   implicit none

   integer,parameter :: byte=kind(1)

   integer(kind=byte),parameter :: LETA=97_byte

   integer(kind=byte),parameter :: CHAR=LETA

contains

   function r2f(ints)
      integer,intent(in)          :: ints(:)
      character(len=size(ints)-1) :: r2f
      integer                     :: i
      intrinsic char
      r2f(i:i)=char(ints(i))
   end function r2f

end module M_match
```

on it's execution with LFortran, gives the below semantic error:
```console
> lfortran --version
LFortran version: 0.42.0-817-g8892f4ab1-dirty
Platform: macOS ARM
LLVM: 11.1.0
Default target: arm64-apple-darwin23.6.0

> lfortran test.f90
semantic error: char was declared as a variable, it can't be called as a function
  --> bootstrap/fman.f90:18:16
   |
18 |       r2f(i:i)=char(ints(i))
   |                ^^^^^^^^^^^^^ help: use the compiler option "--implicit-interface" to use intrinsic functions


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

### PR DESCRIPTION
**Pull request by gxyd**
## Description

earlier 'intrinsic' attribute had almost no effect in ASR creation, this PR makes sure that a declaration like 'intrinsic abs' uses the intrinsic procedure 'abs' even in case of an existing declaration of variable 'abs'

Fixes #5857

### CODE REVIEW

File: src/lfortran/semantics/ast_symboltable_visitor.cpp [hunk 1]
```diff
@@ -103,15 +103,23 @@ class SymbolTableVisitor : public CommonVisitor<SymbolTableVisitor> {
...
         std::map<uint32_t, std::map<std::string, ASR::ttype_t*>> &instantiate_types,
         std::map<uint32_t, std::map<std::string, ASR::symbol_t*>> &instantiate_symbols,
         std::map<std::string, std::map<std::string, std::vector<AST::stmt_t*>>> &entry_functions,
         std::map<std::string, std::vector<int>> &entry_function_arguments_mapping,
         std::vector<ASR::stmt_t*> &data_structure, LCompilers::LocationManager &lm)
-      : CommonVisitor(al, symbol_table, diagnostics, compiler_options, implicit_mapping, common_variables_hash, external_procedures_mapping,
-                      instantiate_types, instantiate_symbols, entry_functions, entry_function_arguments_mapping, data_structure, lm) {}
+      : CommonVisitor(
+            al, symbol_table, diagnostics, compiler_options, implicit_mapping,
+            common_variables_hash, external_procedures_mapping,
```
Comment (gxyd) [inline src/lfortran/semantics/ast_symboltable_visitor.cpp:118]: I also did some formatting of code here, trying to reduce the code line length, that makes it easier to read and understand.

**Comment by gxyd** [comment]
Two things:
1. Either need to fix the *fortran* backend or disable it for the test case
2. appropriate place to use `erase_explicit_intrinsic_procedures` function, which I've added in this PR.

**Comment by gxyd** [comment]
The CI error is because of the output of `fun2` function being:
```f90
integer(4) function fun2() result(i)
    print *, "intrinsic elemental char(65): ", Char(65)
    if (Char(65) /= "A") then
        error stop
    end if
end function fun2
```

and as there is no explicit `intrinsic char`, we get that error because of an existing `char` variable.

**Review by certik — APPROVED** [review]
I think that this is fine. I don't know if this fixes every possible combination, but if we discover further issues, we can improve the logic.
