### PR TITLE
Fix allocatable component struct array

### LINKED ISSUE #9767: Handle struct ArrayItem temporary which has array members in do loop
MRE:
```fortran
module pkg_mod
  implicit none

  type :: variant_t
    integer, allocatable :: executable(:)
  end type variant_t

contains

    subroutine temp_func(src)
        type(variant_t), intent(in) :: src
        print *, allocated(src%executable)
    end subroutine temp_func

end module pkg_mod


program mre_type_bound_proc
    use pkg_mod
    implicit none

    type(variant_t) :: variants_array(2)
    integer :: j
    allocate(variants_array(1)%executable(1))

    variants_array(1)%executable(1) = 1

    do j = 1, size(variants_array)
       call temp_func(variants_array(j))
    end do

end program mre_type_bound_proc
```

Outputs:
```console
(lf) jinang_shah@JNSLAP:~/Desktop/lfortran$ gfortran b.f90 && ./a.out
 T
 F
(lf) jinang_shah@JNSLAP:~/Desktop/lfortran$ lfortran b.f90 --realloc-lhs-arrays
T
T
```

### PR DESCRIPTION
**Pull request by certik**
Fixes #9767.

Merged with main.

### CODE REVIEW

**Comment by jinangshah21** [comment]
Here we need to update reference tests

**Comment by certik** [comment]
I would still like to simplify it, but once the other PRs are in, we can rebase this and see. Possibly we can simplify it in a subsequent PR.

**Comment by certik** [comment]
@jinangshah21 I refactored it a bit. Go ahead and give it a final review.

**Comment by certik** [comment]
It looks like this fix triggers a failure in a 3rd-party app, so we need to create an MRE for it and fix it.

**Comment by certik** [comment]
Here is an MRE:
```fortran
module m_types
  implicit none

  type, abstract :: base_t
  contains
    procedure(load_i), deferred :: load
  end type base_t

  abstract interface
    subroutine load_i(self)
      import :: base_t
      class(base_t), intent(inout) :: self
    end subroutine load_i
  end interface

  type :: srcfile_t
    character(:), allocatable :: file_name
  end type srcfile_t

  type, extends(base_t) :: package_t
    type(srcfile_t), allocatable :: sources(:)
  contains
    procedure :: load => package_load
  end type package_t

contains

  subroutine package_load(self)
    class(package_t), intent(inout) :: self
    if (allocated(self%sources)) deallocate(self%sources)
    allocate(self%sources(1))
    self%sources(1)%file_name = 'file1.f90'
  end subroutine package_load

end module m_types

program crash_mre
  use m_types
  implicit none

  type(package_t) :: pkg
  class(base_t), allocatable :: copy

  allocate(pkg%sources(1))
  pkg%sources(1)%file_name = 'init'

  allocate(copy, mold=pkg)
  call copy%load()

  print *, 'OK'
end program crash_mre
```

**Comment by certik** [comment]
There were two MREs needed, I fixed both. Locally fpm tests pass for me, so we'll see if the CI runs now.

File: integration_tests/allocatable_dummy_descriptor_01.f90 [hunk 1]
```diff
@@ -0,0 +1,239 @@
...
+
+  call pkg%load_from_toml(root)
+
+  if (.not. allocated(pkg%sources)) error stop
+  if (size(pkg%sources) /= 1) error stop
+  if (.not. allocated(pkg%sources(1)%modules_provided)) error stop
+  if (size(pkg%sources(1)%modules_provided) /= 1) error stop
+  if (.not. allocated(pkg%sources(1)%modules_provided(1)%s)) error stop
+  if (pkg%sources(1)%modules_provided(1)%s /= 'm_valnth') error stop
+end program allocatable_dummy_descriptor_01
```
Comment (certik) [inline integration_tests/allocatable_dummy_descriptor_01.f90:239]: Note: this test is too long, I should try to create a shorter MRE.

Comment (certik) [reply integration_tests/allocatable_dummy_descriptor_01.f90:239]: Fixed in https://github.com/lfortran/lfortran/pull/9804.
