### PR TITLE
Bug #5531 - Added conflict diagnostic error message for pointer/allocatable attribute

### LINKED ISSUE #5531: bug: do not allow declaration of `parameter` variables with `allocatable`/`pointer` attribute
### Minimum Reproducible Example

```fortran
program main
   implicit none
   integer, allocatable, parameter :: v=1
end program
```

### Output
```console
(lf) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
; ModuleID = 'LFortran'
source_filename = "LFortran"

define i32 @main(i32 %0, i8** %1) {
.entry:
  call void @_lpython_call_initial_functions(i32 %0, i8** %1)
  %v = alloca i32*, align 8
  store i32* null, i32** %v, align 8
  store i32 1, i32** %v, align 4
  call void @_lpython_free_argv()
  br label %return

return:                                           ; preds = %.entry
  ret i32 0
}

declare void @_lpython_call_initial_functions(i32, i8**)

declare void @_lpython_free_argv()
asr_to_llvm: module failed verification. Error:
Stored value type does not match pointer operand type!
  store i32 1, i32** %v, align 4
 i32*
code generation error: asr_to_llvm: module failed verification. Error:
Stored value type does not match pointer operand type!
  store i32 1, i32** %v, align 4
 i32*


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

### PR DESCRIPTION
**Pull request by dsaw**
Fixes #5531

### CODE REVIEW

File: src/lfortran/semantics/ast_common_visitor.h [hunk 1]
```diff
@@ -2974,9 +2974,6 @@ class CommonVisitor : public AST::BaseVisitor<Derived> {
                                     throw SemanticAbort();
                                 }
                                 // Do nothing for now
-                            } else if (sa->m_attr == AST::simple_attributeType
-                                    ::AttrAllocatable) {
-                                // TODO
```
Comment (kmr-srbh) [inline src/lfortran/semantics/ast_common_visitor.h:2979]: Please undo this change.

File: src/lfortran/semantics/ast_common_visitor.h [hunk 2]
```diff
@@ -3027,6 +3024,30 @@ class CommonVisitor : public AST::BaseVisitor<Derived> {
                             throw SemanticAbort();
                         }
                     }
+                    
+
+                    if (is_allocatable && storage_type == ASR::storage_typeType::Parameter) {
+                        diag.add((Diagnostic( 
+
+                            "`PARAMETER` attribute conflicts with `ALLOCABLE` attribute",
```
Comment (kmr-srbh) [inline src/lfortran/semantics/ast_common_visitor.h:3032]: Please use all lower case for the error message. Also, please correct the spelling for `allocatable`

File: src/lfortran/semantics/ast_common_visitor.h [hunk 3]
```diff
@@ -3027,6 +3024,30 @@ class CommonVisitor : public AST::BaseVisitor<Derived> {
                             throw SemanticAbort();
                         }
                     }
+                    
+
+                    if (is_allocatable && storage_type == ASR::storage_typeType::Parameter) {
+                        diag.add((Diagnostic( 
+
```
Comment (kmr-srbh) [inline src/lfortran/semantics/ast_common_visitor.h:3031]: Please remove this newline.

File: src/lfortran/semantics/ast_common_visitor.h [hunk 4]
```diff
@@ -3027,6 +3024,30 @@ class CommonVisitor : public AST::BaseVisitor<Derived> {
...
+                                Label("",{x.base.base.loc})
+                            }
+                        )));
+                        throw SemanticAbort();
+                    }
+
+                    if (is_pointer && storage_type == ASR::storage_typeType::Parameter) {
+                        diag.add((Diagnostic( 
+
+                            "`PARAMETER` attribute conflicts with `POINTER` attribute",
```
Comment (kmr-srbh) [inline src/lfortran/semantics/ast_common_visitor.h:3043]: Use all lower case.

File: src/lfortran/semantics/ast_common_visitor.h [hunk 5]
```diff
@@ -3027,6 +3024,30 @@ class CommonVisitor : public AST::BaseVisitor<Derived> {
...
+                            Level::Error, Stage::Semantic, {
+                                Label("",{x.base.base.loc})
+                            }
+                        )));
+                        throw SemanticAbort();
+                    }
+
+                    if (is_pointer && storage_type == ASR::storage_typeType::Parameter) {
+                        diag.add((Diagnostic( 
+
```
Comment (kmr-srbh) [inline src/lfortran/semantics/ast_common_visitor.h:3042]: Remove the newline please.

File: tests/reference/run-alloc_attr_disallow-ffd3ec5.stderr [hunk 6]
```diff
@@ -0,0 +1,5 @@
+semantic error: `PARAMETER` attribute conflicts with `ALLOCABLE` attribute
```
Comment (kmr-srbh) [inline tests/reference/run-alloc_attr_disallow-ffd3ec5.stderr:1]: Please push the new references after making the suggested changes.

**Review by kmr-srbh — CHANGES_REQUESTED** [review]

File: src/lfortran/semantics/ast_common_visitor.h (hunk 1 above)
Comment (dsaw) [reply src/lfortran/semantics/ast_common_visitor.h]: done. the if condition was a duplicate with another one above, but I can see it is unnecessary at this time.

File: src/lfortran/semantics/ast_common_visitor.h (hunk 2 above)
Comment (dsaw) [reply src/lfortran/semantics/ast_common_visitor.h]: done

File: src/lfortran/semantics/ast_common_visitor.h (hunk 3 above)
Comment (dsaw) [reply src/lfortran/semantics/ast_common_visitor.h]: done

File: src/lfortran/semantics/ast_common_visitor.h (hunk 4 above)
Comment (dsaw) [reply src/lfortran/semantics/ast_common_visitor.h]: done

File: src/lfortran/semantics/ast_common_visitor.h (hunk 5 above)
Comment (dsaw) [reply src/lfortran/semantics/ast_common_visitor.h]: done

File: tests/reference/run-alloc_attr_disallow-ffd3ec5.stderr (hunk 6 above)
Comment (dsaw) [reply tests/reference/run-alloc_attr_disallow-ffd3ec5.stderr]: done

**Review by kmr-srbh — APPROVED** [review]

File: src/lfortran/semantics/ast_common_visitor.h [hunk 7]
```diff
@@ -3027,6 +3027,28 @@ class CommonVisitor : public AST::BaseVisitor<Derived> {
...
+                    if (is_pointer && storage_type == ASR::storage_typeType::Parameter) {
+                        diag.add((Diagnostic( 
+                            "`parameter` attribute conflicts with `pointer` attribute",
+                            Level::Error, Stage::Semantic, {
+                                Label("",{x.base.base.loc})
+                            }
+                        )));
+                        throw SemanticAbort();
+                    }
```
Comment (kmr-srbh) [inline src/lfortran/semantics/ast_common_visitor.h:3050]: I think it is not efficient to check twice as both `pointer` and `allocatable` cannot appear together. Let's add this to the above `if` block as an `else if` block instead.

Comment (dsaw) [reply src/lfortran/semantics/ast_common_visitor.h:3050]: when I test these conditions as an if else block, the abort isn't reached, probably because the parameter, allocatable and pointer conditions are mutually exclusive. 
Test output diff below for reference:
```
-semantic error: `parameter` attribute conflicts with `allocatable` attribute
- --> tests/./errors/alloc_attr_disallow.f90:4:4
-  |
-4 |    integer, allocatable, parameter :: v=1
-  |    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
+code generation error: asr_to_llvm: module failed verification. Error:
+Stored value type does not match pointer operand type!
+  store i32 1, i32** %v, align 4
+ i32*
```
I think we can test this inside asr_verify or leave it as is.

Comment (kmr-srbh) [reply src/lfortran/semantics/ast_common_visitor.h:3050]: Could you please share the diff of the changes you made?

Comment (dsaw) [reply src/lfortran/semantics/ast_common_visitor.h:3050]:
```
diff --git i/src/lfortran/semantics/ast_common_visitor.h w/src/lfortran/semantics/ast_common_visitor.h
index 655b7d40b..137ee3b3f 100644
--- i/src/lfortran/semantics/ast_common_visitor.h
+++ w/src/lfortran/semantics/ast_common_visitor.h
@@ -2956,9 +2956,27 @@ public:
                             } else if( sa->m_attr == AST::simple_attributeType
                                     ::AttrAllocatable ) {
                                 is_allocatable = true;
+                                if (storage_type == ASR::storage_typeType::Parameter) {
+                                    diag.add((Diagnostic( 
+                                        "`parameter` attribute conflicts with `allocatable` attribute",
+                                        Level::Error, Stage::Semantic, {
+                                            Label("",{x.base.base.loc})
+                                        }
+                                    )));
+                                    throw SemanticAbort();
+                                }
                             } else if (sa->m_attr == AST::simple_attributeType
                                     ::AttrPointer) {
                                 is_pointer = true;
+                                if (storage_type == ASR::storage_typeType::Parameter) {
+                                    diag.add((Diagnostic( 
+                                        "`parameter` attribute conflicts with `pointer` attribute",
+                                        Level::Error, Stage::Semantic, {
+                                            Label("",{x.base.base.loc})
+                                        }
+                                    )));
+                                    throw SemanticAbort();
+                                }
                             } else if (sa->m_attr == AST::simple_attributeType
                                     ::AttrOptional) {
                                 s_presence = ASR::presenceType::Optional;
@@ -3029,26 +3047,6 @@ public:
                     }
                     
 
-                    if (is_allocatable && storage_type == ASR::storage_typeType::Parameter) {
-                        diag.add((Diagnostic( 
-                            "`parameter` attribute conflicts with `allocatable` attribute",
-                            Level::Error, Stage::Semantic, {
-                                Label("",{x.base.base.loc})
-                            }
-                        )));
-                        throw SemanticAbort();
-                    }
-
-                    if (is_pointer && storage_type == ASR::storage_typeType::Parameter) {
-                        diag.add((Diagnostic( 
-                            "`parameter` attribute conflicts with `pointer` attribute",
-                            Level::Error, Stage::Semantic, {
-                                Label("",{x.base.base.loc})
-                            }
-                        )));
-                        throw SemanticAbort();
-                    }
-
                     if (s_intent == ASRUtils::intent_out && value_attr) {
                         diag.add(Diagnostic(
                             "`value` attribute conflicts with `intent(out)` attribute",


```

I also tried adding the both the condition inside the attribute if condition and the same issue persists.

Comment (kmr-srbh) [reply src/lfortran/semantics/ast_common_visitor.h:3050]: I am sorry for the confusion, I meant merging the two `if` block you created into 1 `if - else if` block. Does that work?

Comment (dsaw) [reply src/lfortran/semantics/ast_common_visitor.h]: Oh i see.. updated

File: src/lfortran/semantics/ast_common_visitor.h [hunk 8]
```diff
@@ -3027,6 +3027,27 @@ class CommonVisitor : public AST::BaseVisitor<Derived> {
...
+                    if (is_allocatable && storage_type == ASR::storage_typeType::Parameter) {
+                        diag.add((Diagnostic( 
+                            "`parameter` attribute conflicts with `allocatable` attribute",
+                            Level::Error, Stage::Semantic, {
+                                Label("",{x.base.base.loc})
+                            }
+                        )));
+                        throw SemanticAbort();
+                    }
+                    else if (is_pointer && storage_type == ASR::storage_typeType::Parameter) {
```
Comment (kmr-srbh) [inline src/lfortran/semantics/ast_common_visitor.h:3041]:
```suggestion
                    } else if (is_pointer && storage_type == ASR::storage_typeType::Parameter) {
```

File: tests/tests.toml [hunk 9]
```diff
@@ -733,6 +733,14 @@ llvm = true
 obj = true
 x86 = true
 
+[[test]]
+filename = "./errors/ptr_attr_disallow.f90"
+run = true
+
+[[test]]
+filename = "./errors/alloc_attr_disallow.f90"
+run = true
```
Comment (certik) [inline tests/tests.toml:742]: These should not be run, but "asr".

Second, let's not keep adding new tests like this for each error, because we will have hundreds, possibly thousands, of errors. Rather, just add this error test into our "continue compilation" tests, where it is just one extra line.

This will in addition also test that this error can be recovered from, which we also need to assure.

@dsaw can you please fix that?

Comment (dsaw) [reply tests/tests.toml:742]: sure. seems a PR has been opened for this already. do you have a reference for how to perform the continue compilation tests, if possible?
