### PR TITLE
fix : read an internal file if a substring is involved

### LINKED ISSUE #8582: Reading an internal file fails if a substring is involved
Case 1: reading from a whole character variable into a substring.
Case 2: reading from a substring into a whole character variable.

Program for Case 1:
```
  implicit none ! file substringint1.f90
  character(8):: string = 'abcd', newstring = 'ABCD'
  read(string,"(A)") newstring(5:8)
  print "(A)", newstring
end program
```
Output from gfortran, g95, ifx or AMD flang:
```
ABCDabcd
```
Output from lfortran 0.56.0 is long and ends with
```
code generation error: asr_to_llvm: module failed verification. Error:
Call parameter type does not match function signature!
ptr @string
 i32  call void (i32, ptr, ptr, ptr, i64, ptr, i32, ...) @_lfortran_formatted_read(ptr @string, ptr %2, ptr %3, ptr @0, i64 3, ptr %4, i32 2, ptr %5, i64 4)



Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```
Program for Case 2:
```
  implicit none ! file substringint2.f90
  character(8):: string = 'abcd', newstring = 'ABCD'
  read(string(1:4),"(A)") newstring
  print "(A)", newstring
end program
```
Output from gfortran, g95, ifx or AMD flang:
```
abcd
```
Output from lfortran 0.56.0 is long and ends with
```
code generation error: asr_to_llvm: module failed verification. Error:
Call parameter type does not match function signature!
ptr @string_const
 i32  call void (i32, ptr, ptr, ptr, i64, ptr, i32, ...) @_lfortran_formatted_read(ptr @string_const, ptr %2, ptr %3, ptr @0, i64 3, ptr %4, i32 2, ptr %5, i64 8)



Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

### PR DESCRIPTION
**Pull request by yuvrajsinghgmx**
Closes #8582

### CODE REVIEW

**Comment by yuvrajsinghgmx** [comment]
I have resolved merge conflicts.

**Review by HarshitaKalani — COMMENTED** [review]
The test works for me in main. What is the code addition for? Can you add a test which fails in main and works with the changes in this PR? Mark it as ready for review once done.

**Comment by yuvrajsinghgmx** [comment]
> The test works for me in main. What is the code addition for? Can you add a test which fails in main and works with the changes in this PR? Mark it as ready for review once done.

The test was passing but CI was failing due to `--fast` and the changes are made to fix the same.

**Comment by certik** [comment]
The test passes both with and without `--fast` on Apple M4 on main:
```
(lf) ~/repos/lfortran(main)$ lfortran a.f90
(lf) ~/repos/lfortran(main)$ lfortran a.f90 --fast
(lf) ~/repos/lfortran(main)$
```
Can you show the failure that you are getting with `--fast`?

It seems this is not a good test for the change. 

Update: my bad, it does *not* pass with `--fast`:
```
(lf) ~/repos/lfortran(main)$ lfortran a.f90
(lf) ~/repos/lfortran(main)$ echo $?
0
(lf) ~/repos/lfortran(main)$ lfortran a.f90 --fast
(lf) ~/repos/lfortran(main)$ echo $?
10
```

File: src/libasr/pass/replace_with_compile_time_values.cpp [hunk 1]
```diff
@@ -202,6 +202,47 @@ class ExprVisitor: public ASR::CallReplacerOnExpressionsVisitor<ExprVisitor> {
...
+            this->visit_expr(*xx.m_values[i]);
+            replacer.inside_prohibited_expression = inside_copy;
+        }
+        if (xx.m_fmt) {
+            current_expr = &(xx.m_fmt);
+            replacer.current_expr = current_expr;
+            ASR::CallReplacerOnExpressionsVisitor<ExprVisitor>::visit_expr(**current_expr);
+        }
+        current_expr = current_expr_copy;
+    }
```
Comment (certik) [inline src/libasr/pass/replace_with_compile_time_values.cpp:244]: Can you explain what this part is doing? Is it replacing some arguments to FileRead with their compile-time values?

It seems that is hiding some bug, since things must work both for compile-time and runtime values.

Comment (certik) [reply src/libasr/pass/replace_with_compile_time_values.cpp:244]: I think this was the problem:

The replace_with_compile_time_values optimization pass saw that `newstring(5:8)` had a compile-time value of `""` (from initialization) and replaced the read target with that constant. So instead of reading into the actual newstring substring, the runtime wrote into read-only constant memory, and the original newstring was never modified — causing the subsequent if check to fail.

So this might be a good fix.
