### PR TITLE
Do not reset precedence when cast does not add parentheses

### LINKED ISSUE #1043: Incorrect operator precedence in multiple backends
Note: this is different from #1041. The output of the C backend is generated after #1042 is applied.

Input:

```fortran
subroutine s()
   integer j1
   real*8 pi0(10), pi1(10), amu(10), pii(10), rn
   real*8 Y, QQSCA, QSCA, QQEXT, QEXT, QBACK, XBACK, GSCA

   do j1=1,10
      pi1(j1)=((2.0_8*rn+1.0_8)/(rn))*amu(j1)*pii(j1)-(rn+1.0_8)*pi0(j1)/rn
      pi0(j1)=pii(j1)
   end do

   QQSCA=(2.0/(Y*Y))*QSCA
   QQEXT=(2.0/(Y*Y))*QEXT
   QBACK=(ABS(XBACK))**2
   QBACK=(1.0/(Y*Y))*QBACK
   GSCA=2.0*GSCA/QSCA
end subroutine
```

AST output:

```txt
(TranslationUnit [(Subroutine s [] [] () () [] [] [] [(Declaration (AttrType TypeInteger [] () None) [] [(j1 [] [] () None ())] ()) (Declaration (AttrType TypeReal [(() 8 Value)] () None) [] [(pi0 [(1 10 DimensionExpr)] [] () None ()) (pi1 [(1 10 DimensionExpr)] [] () None ()) (amu [(1 10 DimensionExpr)] [] () None ()) (pii [(1 10 DimensionExpr)] [] () None ()) (rn [] [] () None ())] ()) (Declaration (AttrType TypeReal [(() 8 Value)] () None) [] [(Y [] [] () None ()) (QQSCA [] [] () None ()) (QSCA [] [] () None ()) (QQEXT [] [] () None ()) (QEXT [] [] () None ()) (QBACK [] [] () None ()) (XBACK [] [] () None ()) (GSCA [] [] () None ())] (TriviaNode [] [(EndOfLine) (EndOfLine)]))] [(DoLoop 0 () 0 j1 1 10 () [(= 0 (FuncCallOrArray pi1 [] [(() j1 ())] [] []) (- (* (* (/ (+ (* (Real "2.0_8") rn) (Real "1.0_8")) (Parenthesis rn)) (FuncCallOrArray amu [] [(() j1 ())] [] [])) (FuncCallOrArray pii [] [(() j1 ())] [] [])) (/ (* (+ rn (Real "1.0_8")) (FuncCallOrArray pi0 [] [(() j1 ())] [] [])) rn)) ()) (= 0 (FuncCallOrArray pi0 [] [(() j1 ())] [] []) (FuncCallOrArray pii [] [(() j1 ())] [] []) ())] () (TriviaNode [] [(EndOfLine) (EndOfLine)])) (= 0 QQSCA (* (/ (Real "2.0") (* Y Y)) QSCA) ()) (= 0 QQEXT (* (/ (Real "2.0") (* Y Y)) QEXT) ()) (= 0 QBACK (** (FuncCallOrArray ABS [] [(() XBACK ())] [] []) 2) ()) (= 0 QBACK (* (/ (Real "1.0") (* Y Y)) QBACK) ()) (= 0 GSCA (/ (* (Real "2.0") GSCA) QSCA) ())] [])])
```

ASR Output:

```txt
(TranslationUnit (SymbolTable 1 {iso_c_binding: (IntrinsicModule lfortran_intrinsic_iso_c_binding), iso_fortran_env: (IntrinsicModule lfortran_intrinsic_iso_fortran_env), lfortran_intrinsic_builtin: (IntrinsicModule lfortran_intrinsic_builtin), lfortran_intrinsic_math: (IntrinsicModule lfortran_intrinsic_math), s: (Function (SymbolTable 2 {abs: (ExternalSymbol 2 abs 4 abs lfortran_intrinsic_math [] abs Private), abs@dabs: (ExternalSymbol 2 abs@dabs 4 dabs lfortran_intrinsic_math [] dabs Private), amu: (Variable 2 amu Local () () Default (Real 8 [((IntegerConstant 1 (Integer 4 [])) (IntegerConstant 10 (Integer 4 [])))]) Source Public Required .false.), gsca: (Variable 2 gsca Local () () Default (Real 8 []) Source Public Required .false.), j1: (Variable 2 j1 Local () () Default (Integer 4 []) Source Public Required .false.), pi0: (Variable 2 pi0 Local () () Default (Real 8 [((IntegerConstant 1 (Integer 4 [])) (IntegerConstant 10 (Integer 4 [])))]) Source Public Required .false.), pi1: (Variable 2 pi1 Local () () Default (Real 8 [((IntegerConstant 1 (Integer 4 [])) (IntegerConstant 10 (Integer 4 [])))]) Source Public Required .false.), pii: (Variable 2 pii Local () () Default (Real 8 [((IntegerConstant 1 (Integer 4 [])) (IntegerConstant 10 (Integer 4 [])))]) Source Public Required .false.), qback: (Variable 2 qback Local () () Default (Real 8 []) Source Public Required .false.), qext: (Variable 2 qext Local () () Default (Real 8 []) Source Public Required .false.), qqext: (Variable 2 qqext Local () () Default (Real 8 []) Source Public Required .false.), qqsca: (Variable 2 qqsca Local () () Default (Real 8 []) Source Public Required .false.), qsca: (Variable 2 qsca Local () () Default (Real 8 []) Source Public Required .false.), rn: (Variable 2 rn Local () () Default (Real 8 []) Source Public Required .false.), xback: (Variable 2 xback Local () () Default (Real 8 []) Source Public Required .false.), y: (Variable 2 y Local () () Default (Real 8 []) Source Public Required .false.)}) s [abs@dabs] [] [(DoLoop ((Var 2 j1) (IntegerConstant 1 (Integer 4 [])) (IntegerConstant 10 (Integer 4 [])) ()) [(= (ArrayItem (Var 2 pi1) [(() (Var 2 j1) ())] (Real 8 []) ColMajor ()) (RealBinOp (RealBinOp (RealBinOp (RealBinOp (RealBinOp (RealBinOp (RealConstant 2.000000 (Real 8 [])) Mul (Var 2 rn) (Real 8 []) ()) Add (RealConstant 1.000000 (Real 8 [])) (Real 8 []) ()) Div (Var 2 rn) (Real 8 []) ()) Mul (ArrayItem (Var 2 amu) [(() (Var 2 j1) ())] (Real 8 []) ColMajor ()) (Real 8 []) ()) Mul (ArrayItem (Var 2 pii) [(() (Var 2 j1) ())] (Real 8 []) ColMajor ()) (Real 8 []) ()) Sub (RealBinOp (RealBinOp (RealBinOp (Var 2 rn) Add (RealConstant 1.000000 (Real 8 [])) (Real 8 []) ()) Mul (ArrayItem (Var 2 pi0) [(() (Var 2 j1) ())] (Real 8 []) ColMajor ()) (Real 8 []) ()) Div (Var 2 rn) (Real 8 []) ()) (Real 8 []) ()) ()) (= (ArrayItem (Var 2 pi0) [(() (Var 2 j1) ())] (Real 8 []) ColMajor ()) (ArrayItem (Var 2 pii) [(() (Var 2 j1) ())] (Real 8 []) ColMajor ()) ())]) (= (Var 2 qqsca) (Cast (RealBinOp (RealBinOp (RealConstant 2.000000 (Real 4 [])) Div (Cast (RealBinOp (Var 2 y) Mul (Var 2 y) (Real 8 []) ()) RealToReal (Real 4 []) ()) (Real 4 []) ()) Mul (Cast (Var 2 qsca) RealToReal (Real 4 []) ()) (Real 4 []) ()) RealToReal (Real 8 []) ()) ()) (= (Var 2 qqext) (Cast (RealBinOp (RealBinOp (RealConstant 2.000000 (Real 4 [])) Div (Cast (RealBinOp (Var 2 y) Mul (Var 2 y) (Real 8 []) ()) RealToReal (Real 4 []) ()) (Real 4 []) ()) Mul (Cast (Var 2 qext) RealToReal (Real 4 []) ()) (Real 4 []) ()) RealToReal (Real 8 []) ()) ()) (= (Var 2 qback) (RealBinOp (FunctionCall 2 abs@dabs 2 abs [((Var 2 xback))] (Real 8 []) () ()) Pow (Cast (IntegerConstant 2 (Integer 4 [])) IntegerToReal (Real 8 []) (RealConstant 2.000000 (Real 8 []))) (Real 8 []) ()) ()) (= (Var 2 qback) (Cast (RealBinOp (RealBinOp (RealConstant 1.000000 (Real 4 [])) Div (Cast (RealBinOp (Var 2 y) Mul (Var 2 y) (Real 8 []) ()) RealToReal (Real 4 []) ()) (Real 4 []) ()) Mul (Cast (Var 2 qback) RealToReal (Real 4 []) ()) (Real 4 []) ()) RealToReal (Real 8 []) ()) ()) (= (Var 2 gsca) (Cast (RealBinOp (RealBinOp (RealConstant 2.000000 (Real 4 [])) Mul (Cast (Var 2 gsca) RealToReal (Real 4 []) ()) (Real 4 []) ()) Div (Cast (Var 2 qsca) RealToReal (Real 4 []) ()) (Real 4 []) ()) RealToReal (Real 8 []) ()) ())] () Source Public Implementation () .false. .false. .false. .false. .false. [] [] .false.)}) [])
```

C output:

```c
void s()
{
    struct r64 amu_value;
    struct r64* amu = &amu_value;
    double amu_data[10];
    amu->data = amu_data;
    amu->n_dims = 1;
    amu->dims[0].lower_bound = 1;
    amu->dims[0].length = 10;
    double gsca;
    int32_t j1;
    struct r64 pi0_value;
    struct r64* pi0 = &pi0_value;
    double pi0_data[10];
    pi0->data = pi0_data;
    pi0->n_dims = 1;
    pi0->dims[0].lower_bound = 1;
    pi0->dims[0].length = 10;
    struct r64 pi1_value;
    struct r64* pi1 = &pi1_value;
    double pi1_data[10];
    pi1->data = pi1_data;
    pi1->n_dims = 1;
    pi1->dims[0].lower_bound = 1;
    pi1->dims[0].length = 10;
    struct r64 pii_value;
    struct r64* pii = &pii_value;
    double pii_data[10];
    pii->data = pii_data;
    pii->n_dims = 1;
    pii->dims[0].lower_bound = 1;
    pii->dims[0].length = 10;
    double qback;
    double qext;
    double qqext;
    double qqsca;
    double qsca;
    double rn;
    double xback;
    double y;
    for (j1=1; j1<=10; j1++) {
        pi1->data[(j1 - pi1->dims[0].lower_bound)] = (  2.00000000000000000e+00*rn +   1.00000000000000000e+00)/rn*amu->data[(j1 - amu->dims[0].lower_bound)]*pii->data[(j1 - pii->dims[0].lower_bound)] - (rn +   1.00000000000000000e+00)*pi0->data[(j1 - pi0->dims[0].lower_bound)]/rn;
        pi0->data[(j1 - pi0->dims[0].lower_bound)] = pii->data[(j1 - pii->dims[0].lower_bound)];
    }
    qqsca =   2.00000000000000000e+00/y*y*qsca;
    qqext =   2.00000000000000000e+00/y*y*qext;
    qback = pow(dabs(xback), (double)(2));
    qback =   1.00000000000000000e+00/y*y*qback;
    gsca =   2.00000000000000000e+00*gsca/qsca;
}
```

C++ output (N/A, `code generation error: Intrinsic function 'char' not implemented`)

Julia output:

```julia
function s()
    local amu = Array{Float64, 1}(undef, 10)
    local gsca::Float64 = 0.0
    local j1::Int32 = 0
    local pi0 = Array{Float64, 1}(undef, 10)
    local pi1 = Array{Float64, 1}(undef, 10)
    local pii = Array{Float64, 1}(undef, 10)
    local qback::Float64 = 0.0
    local qext::Float64 = 0.0
    local qqext::Float64 = 0.0
    local qqsca::Float64 = 0.0
    local qsca::Float64 = 0.0
    local rn::Float64 = 0.0
    local xback::Float64 = 0.0
    local y::Float64 = 0.0
    for j1 ∈ 1:10
        pi1[j1] = (  2.00000000000000000e+00 * rn +   1.00000000000000000e+00) / rn * amu[j1] * pii[j1] - (rn +   1.00000000000000000e+00) * pi0[j1] / rn
        pi0[j1] = pii[j1]
    end
    qqsca =   2.00000000000000000e+00 / y * y * qsca
    qqext =   2.00000000000000000e+00 / y * y * qext
    qback = dabs(xback) ^ Float64(2)
    qback =   1.00000000000000000e+00 / y * y * qback
    gsca =   2.00000000000000000e+00 * gsca / qsca
end
```

### PR DESCRIPTION
**Pull request by lucifer1004**
Fix #1043

### CODE REVIEW

File: src/libasr/codegen/asr_to_c_cpp.h [hunk 1]
```diff
@@ -1102,7 +1102,6 @@ R"(#include <stdio.h>
             default : throw CodeGenError("Cast kind " + std::to_string(x.m_kind) + " not implemented",
                 x.base.base.loc);
         }
-        last_expr_precedence = 2;
```
Comment (certik) [inline src/libasr/codegen/asr_to_c_cpp.h:1105]: I think the logic is that every expression node must set a precedence. I think this might introduce bugs. Isn't the issue rather that the following cases must set the precedence differently:
```
            case (ASR::cast_kindType::RealToReal) : {
                // In C++, we do not need to cast float to float explicitly:
                // src = src;
                break;
            }
            case (ASR::cast_kindType::IntegerToInteger) : {
                // In C++, we do not need to cast int <-> long long explicitly:
                // src = src;
                break;
            }
```
Because they do not introduce any output, but cases like 
```
            case (ASR::cast_kindType::LogicalToInteger) : {
                src = "(int)(" + src + ")";
                break;
            }
```
Should set it to 2, as it doesn't need any further parenthesis.

Comment (lucifer1004) [reply src/libasr/codegen/asr_to_c_cpp.h:1105]: You are right, I have made a new commit to handle cases with/without parenthesis separately.

File: src/libasr/codegen/asr_to_c_cpp.h [hunk 2]
```diff
@@ -1044,18 +1050,22 @@ R"(#include <stdio.h>
                     case 8: src = "(double)(" + src + ")"; break;
```
Comment (certik) [inline src/libasr/codegen/asr_to_c_cpp.h:1050]: I can't put the comment there, but I think `IntegerToLogical` should also have last_expr_precedence=2.

Comment (certik) [reply src/libasr/codegen/asr_to_c_cpp.h:1050]: The `LogicalToCharacter` I think might require parentheses, possibly even around "src".

File: src/libasr/codegen/asr_to_c_cpp.h [hunk 3]
```diff
@@ -1005,6 +1007,7 @@ R"(#include <stdio.h>
                 } else {
```
Comment (certik) [inline src/libasr/codegen/asr_to_c_cpp.h:1007]: In IntegerToInteger and RealToReal I would put explicitly:
// last_expr_precedence = last_expr_precedence

To make it clear that we are reusing the last value, just like for "src".

**Review by certik — APPROVED** [review]
Otherwise that looks good, thanks!

File: src/libasr/codegen/asr_to_c_cpp.h (hunk 2 above)
Comment (lucifer1004) [reply src/libasr/codegen/asr_to_c_cpp.h:1050]: > I can't put the comment there, but I think `IntegerToLogical` should also have last_expr_precedence=2.

Yes, I missed that one.

File: src/libasr/codegen/asr_to_c_cpp.h (hunk 3 above)
Comment (lucifer1004) [reply src/libasr/codegen/asr_to_c_cpp.h:1011]: Comments added for all cases where the last value is reused.

File: src/libasr/codegen/asr_to_c_cpp.h (hunk 2 above)
Comment (lucifer1004) [reply src/libasr/codegen/asr_to_c_cpp.h:1056]: - `IntegerToLogical`: fixed.
- `LogicalToCharacter`: parentheses added and precedence set to 2. I did not add parentheses around "src" since the ternary operator should have the lowest precedence.

**Comment by lucifer1004** [comment]
@certik Can I merge this?

**Review by certik — APPROVED** [review]
Yes, go ahead and merge!

**Comment by certik** [comment]
Thanks for fixing it @lucifer1004 !
