### PR TITLE
fix : diagnose interface function/subroutine attribute conflict

### LINKED ISSUE #6281: bug: function/subroutine with same name allowed when declared in different interfaces
### Minimal Reproducible Example

```fortran
module functions_33

implicit none

interface frexp
   function frexp(x,n) result(r)
      real r
      real, intent(in), value :: x
      integer, intent(out) :: n
   end function frexp
end interface frexp

interface frexp_duplicate
   subroutine frexp(x,n)
      real r
      real, intent(in), value :: x
      integer, intent(out) :: n
   end subroutine frexp
end interface

end module functions_33
```

### Output

```console
(lf) saurabh-kumar@Awadh:~/Projects/System/lfortran$ gfortran -c test.f90
test.f90:14:19:

   14 |    subroutine frexp(x,n)
      |                   1
Error: FUNCTION attribute conflicts with SUBROUTINE attribute in ‘frexp’ at (1)
test.f90:15:12:

   15 |       real r
      |            1
Error: Unexpected data declaration statement in INTERFACE block at (1)
test.f90:16:34:

   16 |       real, intent(in), value :: x
      |                                  1
Error: Unexpected data declaration statement in INTERFACE block at (1)
test.f90:17:31:

   17 |       integer, intent(out) :: n
      |                               1
Error: Unexpected data declaration statement in INTERFACE block at (1)
test.f90:18:6:

   18 |    end subroutine frexp
      |      1
Error: Expecting END INTERFACE statement at (1)
(lf) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran -c test.f90
(lf) saurabh-kumar@Awadh:~/Projects/System/lfortran$ 
```

This happens because the subroutine `frexp` is declared with the original name as there is no name conflict with the interface.

### PR DESCRIPTION
**Pull request by Jatinagarwal24**
fixes #6281 
Detect function/subroutine attribute conflict in interface blocks

In ast_symboltable_visitor.cpp
Adds a post-rename symbol-table check in visit_Subroutine (after ~genericprocedure key resolution).
Detects when an existing symbol is actually a function (has return variable) and the new declaration is a subroutine.
Emits a semantic diagnostic:
FUNCTION attribute of '<name>' conflicts with SUBROUTINE attribute
Respects continue-compilation behavior:
Normal mode: throws SemanticAbort.
Continue mode: records error, erases existing symbol, continues.

### CODE REVIEW

**Comment by Jatinagarwal24** [comment]
Hi @certik I think this is good to merge.

File: src/lfortran/semantics/ast_symboltable_visitor.cpp [hunk 1]
```diff
@@ -1425,11 +1425,59 @@ class SymbolTableVisitor : public CommonVisitor<SymbolTableVisitor> {
...
+                current_procedure_args.clear();
+                current_procedure_abi_type = ASR::abiType::Source;
+                current_function_dependencies = current_function_dependencies_copy;
+                in_Subroutine = false;
+                is_template = false;
+                is_global_save_enabled = is_global_save_enabled_copy;
+                return;
+            }
+            throw SemanticAbort();
+        };
```
Comment (kmr-srbh) [inline src/lfortran/semantics/ast_symboltable_visitor.cpp]: We can declare interfaces inside a subroutine and possibly also a template so setting the variables to `false` is not quite right. Also, we should not hardcode the ABI type. Why do we need this? I think we can abort normally like other errors?

File: src/lfortran/semantics/ast_symboltable_visitor.cpp [hunk 2]
```diff
@@ -1425,11 +1425,59 @@ class SymbolTableVisitor : public CommonVisitor<SymbolTableVisitor> {
...
+            if (ASR::is_a<ASR::Function_t>(*f_alt)) {
+                ASR::Function_t* f_alt_fn = ASR::down_cast<ASR::Function_t>(f_alt);
+                if (ASRUtils::get_FunctionType(f_alt_fn)->m_deftype == ASR::deftypeType::Interface &&
+                    f_alt_fn->m_return_var != nullptr) {
+                    std::vector<Location> locs = {f_alt->base.loc};
+                    std::vector<diag::Label> labels;
+                    labels.push_back(diag::Label("", {x.base.base.loc}));
+                    labels.push_back(diag::Label("is already declared as a function here", locs, false));
+                    diag.add(diag::Diagnostic(
+                        "function attribute conflicts with subroutine attribute in '" + sym_name + "'",
```
Comment (kmr-srbh) [inline src/lfortran/semantics/ast_symboltable_visitor.cpp]:
```suggestion
                        "`function` attribute conflicts with `subroutine` attribute in '" + sym_name + "'",
```

Please highlight keywords in error messages.

File: src/lfortran/semantics/ast_symboltable_visitor.cpp [hunk 3]
```diff
@@ -1425,11 +1425,59 @@ class SymbolTableVisitor : public CommonVisitor<SymbolTableVisitor> {
...
+                        diag::Level::Error, diag::Stage::Semantic, labels));
+                    abort_interface_conflict_subroutine();
+                    return;
```
Comment (kmr-srbh) [inline src/lfortran/semantics/ast_symboltable_visitor.cpp]: I think we don't need a `return` here since we throw a `SemanticAbort()` anyways?

**Review by kmr-srbh — CHANGES_REQUESTED** [review]
Please add a small comment (possibly with a small example) stating the case we are throwing an error for since function/function interfaces, subroutine/subroutine interfaces can be of the same name, like:

```fortran
interface frexp
   subroutine frexp(x,n)
      real r
      real, intent(in), value :: x
      integer, intent(out) :: n
   end subroutine frexp
end interface
```

**Comment by Jatinagarwal24** [comment]
Hi, @kmr-srbh I have changed the fix pls once check now.

File: src/lfortran/semantics/ast_symboltable_visitor.cpp [hunk 4]
```diff
@@ -1496,6 +1496,32 @@ class SymbolTableVisitor : public CommonVisitor<SymbolTableVisitor> {
...
+        ASR::symbol_t* existing_sym = parent_scope->get_symbol(sym_name);
+        if (existing_sym != nullptr) {
+            ASR::symbol_t* existing_past_ext = ASRUtils::symbol_get_past_external(existing_sym);
+            if (ASR::is_a<ASR::Function_t>(*existing_past_ext)) {
+                ASR::Function_t* existing_func = ASR::down_cast<ASR::Function_t>(existing_past_ext);
+                if (existing_func->m_return_var != nullptr) {
+                    std::string original_name = to_lower(std::string(x.m_name));
+                    diag.add(diag::Diagnostic(
+                        "FUNCTION attribute of '" + original_name +
+                        "' conflicts with SUBROUTINE attribute",
```
Comment (kmr-srbh) [inline src/lfortran/semantics/ast_symboltable_visitor.cpp]:
```suggestion
                        "`function` attribute of '" + original_name +
                        "' conflicts with `subroutine` attribute",
```

**Review by kmr-srbh — APPROVED** [review]
A small change, otherwise looks good.

**Comment by Jatinagarwal24** [comment]
Hi , @kmr-srbh I think now this is good to merge.

**Comment by kmr-srbh** [comment]
Please resolve the conflicts.

**Comment by kmr-srbh** [comment]
Thanks! This looks good.
