### PR TITLE
enh: add support for passing argument of any type to a polymorphic function parameter

### LINKED ISSUE #5914: Function not found error for a generic function interface
## Minimal Reproducible Example

For the below Fortran code, using a polymorphic type argument in a generic function interface:

```f90

program M_strings
    implicit none
    integer :: valu = 1

    interface str
        procedure str_scalar
    end interface str

    print *, str(valu)

CONTAINS

    function str_scalar(g1)
        class(*), intent(in)  :: g1
        integer :: str_scalar
    end function str_scalar

end program M_strings
```

on it's compilation with LFortran, raises the below semantic error:
```f90
> lfortran --version
LFortran version: 0.43.0-23-gedc44c17d-dirty
Platform: macOS ARM
LLVM: 11.1.0
Default target: arm64-apple-darwin23.6.0

> lfortran test.f90
semantic error: Function 'str' not found (not user defined nor intrinsic)
  --> test.f90:10:14
   |
10 |     print *, str(valu)
   |              ^^^^^^^^^ 


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

I'm aware that we don't support polymorphic type that well in ASR->LLVM, but since this error occurs in AST->ASR, we should probably fix this.

### PR DESCRIPTION
**Pull request by kmr-srbh**
fixes #5914

### CODE REVIEW

File: src/libasr/asr_utils.h [hunk 1]
```diff
@@ -3401,8 +3415,7 @@ inline bool types_equal(ASR::ttype_t *a, ASR::ttype_t *b,
             }
             default : return false;
         }
-    } else if( a->type == ASR::ttypeType::StructType &&
-               b->type == ASR::ttypeType::ClassType ) {
+    } else if (a->type == ASR::ttypeType::StructType && b->type == ASR::ttypeType::ClassType) {
```
Comment (certik) [inline src/libasr/asr_utils.h:3418]: Use `is_a`

File: src/libasr/asr_utils.h [hunk 2]
```diff
@@ -3419,8 +3432,7 @@ inline bool types_equal(ASR::ttype_t *a, ASR::ttype_t *b,
             ASR::Struct_t *b2_type = ASR::down_cast<ASR::Struct_t>(b2_typesym);
             return is_derived_type_similar(a2_type, b2_type);
         }
-    } else if( a->type == ASR::ttypeType::ClassType &&
-               b->type == ASR::ttypeType::StructType ) {
+    } else if (a->type == ASR::ttypeType::ClassType && b->type == ASR::ttypeType::StructType) {
```
Comment (certik) [inline src/libasr/asr_utils.h:3435]: Use `is_a`

**Review by certik — APPROVED** [review]
I think this is good. I left some minor comments that can be fixed in a subsequent PR.
