### PR TITLE
Initial impl. of floating point exception trapping

### LINKED ISSUE #10179: Implement trapping floating point exceptions
When a NaN is created or arithmetic on it happens, stop the code. GFortran and most other compilers can do that. This greatly helps with debugging. Make it optional with a compiler option.

### PR DESCRIPTION
**Pull request by certik**
Add a new --fpe-trap compiler option that enables hardware floating point exception trapping at program startup, similar to GFortran's -ffpe-trap.

The option accepts a comma-separated list of exception types:
  invalid, zero, overflow, underflow, inexact, denormal

Example usage:
  lfortran --fpe-trap invalid,zero,overflow program.f90

Implementation details:
- Add fpe_traps field to CompilerOptions (utils.h)
- Register --fpe-trap CLI option with comma-separated validation
- Add _lfortran_enable_fpe_traps() runtime function that configures hardware FPE traps using a bitmask encoding
- Emit call to the runtime function in LLVM codegen (visit_Program) when --fpe-trap is specified
- Cross-platform support:
  - Linux: feenableexcept() + MXCSR for denormals
  - macOS x86_64: fenv_t manipulation + MXCSR
  - macOS ARM64: FPCR register via inline asm
  - Windows: _controlfp_s()
  - WASM: warning (not supported)

Fixes #10179.

### CODE REVIEW

**Comment by certik** [comment]
See the example `tests/fpe_trap_test.f90` how to use this.

File: src/libasr/runtime/lfortran_intrinsics.c [hunk 1]
```diff
@@ -100,6 +106,7 @@ static int _lfortran_use_runtime_colors = 0;  // disabled by default
 #ifdef HAVE_LFORTRAN_LINK
 // For dl_iterate_phdr() functionality
 #  include <link.h>
+#ifndef _GNU_SOURCE
```
Comment (certik) [inline src/libasr/runtime/lfortran_intrinsics.c:109]: I forgot what this does and why it is needed. Either remove it or document why it is needed and what it does.

Comment (krystophny) [reply src/libasr/runtime/lfortran_intrinsics.c:109]: `_GNU_SOURCE` is needed because `feenableexcept()` is a GNU extension only declared in `<fenv.h>` when that macro is set. The `#ifndef` guard around `dl_phdr_info prevents` duplicate definitions since `<link.h>` already provides them when `_GNU_SOURCE` is active. The cleanest fix is to add `target_compile_definitions(... PRIVATE _GNU_SOURCE)` in CMake for Linux, then delete both the `#define` at the top and the manual `struct/extern`.

**Comment by certik** [comment]
Tests seem to pass, so let's merge this and then we'll improve upon this initial implementation.

File: src/libasr/runtime/lfortran_intrinsics.c (hunk 1 above)
Comment (certik) [reply src/libasr/runtime/lfortran_intrinsics.c:109]: I made this https://github.com/lfortran/lfortran/issues/10214.
