### PR TITLE
throw error when mask is not logical

### LINKED ISSUE #6201: throw error if mask to `sum` is not logical
```fortran
program main
    print *, sum([1, 2, 3], mask = [1, 2, 3])
end program
```
```console
$ gfortran a.f90 && ./a.out
a.f90:11:35:

   11 |     print *, sum([1, 2, 3], mask = [1, 2, 3])
      |                                   1
Error: ‘mask’ argument of ‘sum’ intrinsic at (1) must be LOGICAL
$ lfortran a.f90
6
```

### PR DESCRIPTION
**Pull request by sauravsoni6377**
Fixes  #6201

- Throw error message  mask argument to sum is not logical.

in src/libasr/pass/intrinsic_array_function_registry.h:

`else if (args[2]) {
                if (is_logical(*ASRUtils::expr_type(args[2]))) {
                    mask = args[2];
                } else {
                    diag.add(diag::Diagnostic("'mask' argument of 'sum' intrinsic at (1) must be LOGICAL",
                        diag::Level::Error, diag::Stage::Semantic, {diag::Label("", {loc})}));
                    return nullptr;
                }
    }`

### CODE REVIEW

File: src/libasr/pass/intrinsic_array_function_registry.h [hunk 1]
```diff
@@ -691,8 +691,14 @@ static inline ASR::asr_t* create_ArrIntrinsic(
...
-    } else if (args[2] && is_logical(*ASRUtils::expr_type(args[2]))) {
-                mask = args[2];
+    } else if (args[2]) {
+                if (is_logical(*ASRUtils::expr_type(args[2]))) {
+                    mask = args[2];
+                } else {
+                    diag.add(diag::Diagnostic("'mask' argument of 'sum' intrinsic at (1) must be LOGICAL",
+                        diag::Level::Error, diag::Stage::Semantic, {diag::Label("", {loc})}));
+                    return nullptr;
+                }
```
Comment (kmr-srbh) [inline src/libasr/pass/intrinsic_array_function_registry.h:701]: The `else if` condition checked for `logical` already, so can we add an `else` block and throw this error? I think we are doing the same with the current changes, but with some nesting.

File: src/libasr/pass/intrinsic_array_function_registry.h [hunk 2]
```diff
@@ -691,8 +691,14 @@ static inline ASR::asr_t* create_ArrIntrinsic(
                 args[1]->base.loc);
             return nullptr;
         }
-    } else if (args[2] && is_logical(*ASRUtils::expr_type(args[2]))) {
-                mask = args[2];
+    } else if (args[2]) {
+                if (is_logical(*ASRUtils::expr_type(args[2]))) {
+                    mask = args[2];
+                } else {
+                    diag.add(diag::Diagnostic("'mask' argument of 'sum' intrinsic at (1) must be LOGICAL",
```
Comment (kmr-srbh) [inline src/libasr/pass/intrinsic_array_function_registry.h:698]: Please use all lower-case. Also, do not use the text `"(1)"`. The `Location loc` informs the user of the place of occurrence.

File: tests/reference/run-allocate_01-d7a2337.stderr [hunk 3]
```diff
@@ -0,0 +1,4 @@
+sh: 1: clang: not found
+The command 'clang -o allocate_01.out tests/errors/allocate_01.tmp.o  -L"$DIR/src/bin/../runtime" -Wl,-rpath,"$DIR/src/bin/../runtime" -llfortran_runtime -lm' failed.
+Tip: If there is a linker issue, switch the linker using --linker=<CC> option or create an environment variable `export LFORTRAN_LINKER=<CC>`, where CC is clang or gcc
+Also, if required use --linker-path=<PATH>, where PATH has location to look for the linker execuatable
```
Comment (kmr-srbh) [inline tests/reference/run-allocate_01-d7a2337.stderr:4]: This reference is not required actually. By default, we need `clang` to link the executable. I think we currently do not support using the `--link-with-gcc` when running the reference tests. Please install `clang` and do the following:

1. Pull latest changes from `main`.
2. Do `git checkout main tests/reference/` to reset the test references.
3. Run `./run_tests.py -u` to generate references.
4. Check the references for anomalies like error stacktraces or the one here. Ideally, we should have references for only the semantic error we add here.
5. Push the new references.

File: tests/errors/mask_not_logical.f90 [hunk 4]
```diff
@@ -0,0 +1,3 @@
+program main
+    print *, sum([1, 2, 3], mask = [1, 2, 3])
+end program
```
Comment (kmr-srbh) [inline tests/errors/mask_not_logical.f90:3]: Please add this test case inside `continue_compilation_01.f90`.

**Review by kmr-srbh — CHANGES_REQUESTED** [review]

**Comment by kmr-srbh** [comment]
Please click on "Ready for review" when the PR is ready.

File: src/libasr/pass/intrinsic_array_function_registry.h (hunk 1 above)
Comment (kmr-srbh) [reply src/libasr/pass/intrinsic_array_function_registry.h]: Isn't this nesting doing the same thing as a non-nested `else if` and `else` block?

File: tests/reference/asr-mask_not_logical-1c7b2a8.json [hunk 5]
```diff
@@ -0,0 +1,13 @@
...
+    "infile": "tests/errors/mask_not_logical.f90",
+    "infile_hash": "7c67278ecbb5a744cc477e7bc962e73be7353eb0713848c4091a1ae7",
+    "outfile": null,
+    "outfile_hash": null,
+    "stdout": null,
+    "stdout_hash": null,
+    "stderr": "asr-mask_not_logical-1c7b2a8.stderr",
+    "stderr_hash": "eb2ed7b520d66648e33cae7a992ae6f7659a7254dbdc31db6b8c1030",
+    "returncode": 2
+}
```
[the remark this answers is not in the document]
Comment (sauravsoni6377) [reply tests/reference/asr-mask_not_logical-1c7b2a8.json:13]: okay, i'll do it right now.
