### PR TITLE
enh: reordered checking of arg type in `make_ArraySize_util`

### LINKED ISSUE #5334: (PRIMA) Intrinsic function call in args of function causes error in Arraysize
Towards #4397

MRE : 
```fortran
program main

contains

subroutine trans(A)
real(8), intent(in) :: A(:,:)
print *, matprod(transpose(A))
end subroutine

function matprod(x) result(k)
real(8),intent(in) :: x(:,:)
real(8) :: k(size(x,1))
end function

end program 
```

LFortran Error : 
```console
LCOMPILERS_ASSERT failed: /mnt/c/lfortran/src/libasr/asr_utils.h
function make_ArraySize_t_util(), line number 2625 at
ASR::is_a<ASR::Var_t>(*a_v) || ASR::is_a<ASR::StructInstanceMember_t>(*a_v) || ASR::is_a<ASR::FunctionParam_t>(*a_v)
ERROR MESSAGE:
Found ASR::exprType::5
Traceback (most recent call last):
  Binary file "/mnt/c/lfortran/src/bin/lfortran", in _start
  File "/build/glibc-LcI20x/glibc-2.31/csu/../csu/libc-start.c", line 308, in __libc_start_main
  File "/mnt/c/lfortran/src/bin/lfortran.cpp", line 2679, in main
    return main_app(argc, argv);
  File "/mnt/c/lfortran/src/bin/lfortran.cpp", line 2621, in main_app(int, char**)
    err = compile_src_to_object_file(arg_file, tmp_o, false,
  File "/mnt/c/lfortran/src/bin/lfortran.cpp", line 1002, in (anonymous namespace)::compile_src_to_object_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, LCompilers::CompilerOptions&, LCompilers::PassManager&)
    result = fe.get_asr2(input, lm, diagnostics);
  File "/mnt/c/lfortran/src/lfortran/fortran_evaluator.cpp", line 270, in LCompilers::FortranEvaluator::get_asr2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::diag::Diagnostics&)
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/mnt/c/lfortran/src/lfortran/fortran_evaluator.cpp", line 292, in LCompilers::FortranEvaluator::get_asr3(LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&)
    compiler_options.symtab_only, compiler_options);
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 103, in LCompilers::LFortran::ast_to_asr(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::SymbolTable*, bool, LCompilers::CompilerOptions&)
    instantiate_types, instantiate_symbols, entry_functions, entry_function_arguments_mapping, data_structure);
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 4056, in LCompilers::LFortran::body_visitor(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::ASR::asr_t*, LCompilers::CompilerOptions&, std::map<unsigned long, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > > > > >&, std::map<unsigned long, LCompilers::ASR::symbol_t*, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, LCompilers::ASR::symbol_t*> > >&, std::map<unsigned long, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >&, std::map<unsigned int, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > > > > >&, std::map<unsigned int, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::symbol_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::symbol_t*> > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::symbol_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::symbol_t*> > > > > >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> > > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> > > > > > > >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<int, std::allocator<int> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<int, std::allocator<int> > > > >&, std::vector<LCompilers::ASR::stmt_t*, std::allocator<LCompilers::ASR::stmt_t*> >&)
    b.visit_TranslationUnit(ast);
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 166, in LCompilers::LFortran::BodyVisitor::visit_TranslationUnit(LCompilers::LFortran::AST::TranslationUnit_t const&)
    visit_ast(*x.m_items[i]);
  File "/mnt/c/lfortran/src/lfortran/ast.h", line 4884, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_ast(LCompilers::LFortran::AST::ast_t const&)
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/mnt/c/lfortran/src/lfortran/ast.h", line 4841, in void LCompilers::LFortran::AST::visit_ast_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::ast_t const&, LCompilers::LFortran::BodyVisitor&)
    case astType::mod: { v.visit_mod((const mod_t &)x); return; }
  File "/mnt/c/lfortran/src/lfortran/ast.h", line 4887, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_mod(LCompilers::LFortran::AST::mod_t const&)
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/mnt/c/lfortran/src/lfortran/ast.h", line 4474, in void LCompilers::LFortran::AST::visit_mod_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::mod_t const&, LCompilers::LFortran::BodyVisitor&)
    case modType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1647, in LCompilers::LFortran::BodyVisitor::visit_Program(LCompilers::LFortran::AST::Program_t const&)
    visit_program_unit(*x.m_contains[i]);
  File "/mnt/c/lfortran/src/lfortran/ast.h", line 4892, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_program_unit(LCompilers::LFortran::AST::program_unit_t const&)
    void visit_program_unit(const program_unit_t &b) { visit_program_unit_t(b, self()); }
  File "/mnt/c/lfortran/src/lfortran/ast.h", line 4482, in void LCompilers::LFortran::AST::visit_program_unit_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::program_unit_t const&, LCompilers::LFortran::BodyVisitor&)
    case program_unitType::Subroutine: { v.visit_Subroutine((const Subroutine_t &)x); return; }
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 2049, in LCompilers::LFortran::BodyVisitor::visit_Subroutine(LCompilers::LFortran::AST::Subroutine_t const&)
    transform_stmts(body, x.n_body, x.m_body);
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 121, in LCompilers::LFortran::BodyVisitor::transform_stmts(LCompilers::Vec<LCompilers::ASR::stmt_t*>&, unsigned long, LCompilers::LFortran::AST::stmt_t**)
    this->visit_stmt(*m_body[i]);
  File "/mnt/c/lfortran/src/lfortran/ast.h", line 4930, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_stmt(LCompilers::LFortran::AST::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/mnt/c/lfortran/src/lfortran/ast.h", line 4601, in void LCompilers::LFortran::AST::visit_stmt_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::stmt_t const&, LCompilers::LFortran::BodyVisitor&)
    case stmtType::Print: { v.visit_Print((const Print_t &)x); return; }
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 3279, in LCompilers::LFortran::BodyVisitor::visit_Print(LCompilers::LFortran::AST::Print_t const&)
    this->visit_expr(*x.m_values[i]);
  File "/mnt/c/lfortran/src/lfortran/ast.h", line 4982, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_expr(LCompilers::LFortran::AST::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/mnt/c/lfortran/src/lfortran/ast.h", line 4639, in void LCompilers::LFortran::AST::visit_expr_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::expr_t const&, LCompilers::LFortran::BodyVisitor&)
    case exprType::FuncCallOrArray: { v.visit_FuncCallOrArray((const FuncCallOrArray_t &)x); return; }
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 7330, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::visit_FuncCallOrArray(LCompilers::LFortran::AST::FuncCallOrArray_t const&)
    tmp = create_FunctionCallWithASTNode(x, v, args);
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 5086, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::create_FunctionCallWithASTNode(LCompilers::LFortran::AST::FuncCallOrArray_t const&, LCompilers::ASR::symbol_t*, LCompilers::Vec<LCompilers::ASR::call_arg_t>&, bool)
    return create_Function(x.base.base.loc, args, v);
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 5003, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::create_Function(LCompilers::Location const&, LCompilers::Vec<LCompilers::ASR::call_arg_t>&, LCompilers::ASR::symbol_t*)
    return_type = handle_return_type(return_type, loc, args, func);
  File "/mnt/c/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 4374, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::handle_return_type(LCompilers::ASR::ttype_t*, LCompilers::Location const&, LCompilers::Vec<LCompilers::ASR::call_arg_t>&, LCompilers::ASR::Function_t*)
    return ASRUtils::make_Array_t_util(
  File "/mnt/c/lfortran/src/libasr/asr_utils.h", line 2647, in LCompilers::ASRUtils::make_Array_t_util(Allocator&, LCompilers::Location const&, LCompilers::ASR::ttype_t*, LCompilers::ASR::dimension_t*, unsigned long, LCompilers::ASR::abiType, bool, LCompilers::ASR::array_physical_typeType, bool, bool)    
    m_dims[i].m_length = ASRUtils::EXPR(ASRUtils::make_ArraySize_t_util(
  File "/mnt/c/lfortran/src/libasr/asr_utils.h", line 2625, in LCompilers::ASRUtils::make_ArraySize_t_util(Allocator&, LCompilers::Location const&, LCompilers::ASR::expr_t*, LCompilers::ASR::expr_t*, LCompilers::ASR::ttype_t*, LCompilers::ASR::expr_t*, bool)
    LCOMPILERS_ASSERT_MSG(
  File "/build/glibc-LcI20x/glibc-2.31/stdlib/abort.c", line 79, in abort
  File "/build/glibc-LcI20x/glibc-2.31/signal/../sysdeps/unix/sysv/linux/internal-signals.h", line 86, in raise
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in <invalid>
Abort: Signal SIGABRT (abort) received

Aborted (core dumped)
```

I was working before a week, today I just updated my branch and got this error, so likely this is caused because of some recent PR.

### PR DESCRIPTION
**Pull request by jinangshah21**
Fixes #5334 
Here I haven't changed logic, just reordered checking of arg type as it may be case like `func(abs(A(:,1:2))` where ArraySection is detected after `IntrinsicElementFunction` check.

### CODE REVIEW

**Comment by gxyd** [comment]
I'm sorry, I'm not able to reproduce the linked issue in *main*.

**Comment by jinangshah21** [comment]
> I'm sorry, I'm not able to reproduce the linked issue in _main_.

Check https://github.com/lfortran/lfortran/issues/5334#issuecomment-2468742181 which is just one step more than original MRE.
Original MRE was solved by #5346

File: integration_tests/interface_13.f90 [hunk 1]
```diff
@@ -1,33 +1,33 @@
...
+        res = 123 .mul. 456
+        if (res /= 56088) error stop
+    end subroutine compute
+end module
+
+program interface_13
+    use interface_13_module_2
+    implicit none
+    call compute()
+end program interface_13
```
Comment (certik) [inline integration_tests/interface_13.f90:33]: What are the changes in this file? Let's not do white space changes in a PR that fixes things, send it as a separate PR.

**Comment by certik** [comment]
So the reordering makes it compute the dimensions correctly? Can you post an ASR before and after this PR, just for the expression involved? That way we can check that the new way is correct.

File: integration_tests/interface_13.f90 (hunk 1 above)
Comment (jinangshah21) [reply integration_tests/interface_13.f90:33]: I didn't changed anything in this file. This is not related to this PR.

Comment (certik) [reply integration_tests/interface_13.f90:33]: Then remove unrelated changes. :)

**Comment by jinangshah21** [comment]
> So the reordering makes it compute the dimensions correctly? Can you post an ASR before and after this PR, just for the expression involved? That way we can check that the new way is correct.

Previously it was not generating ASR. Basically we have to do `size(abs(A(:,1:x))` so in `make_ArraySize_util_t` size will get `IntrinsicElementalFunction` as argument and inside it we have `ArraySection`. What `make_ArraySize_util_t` does is it checks of argument is ArraySection first then it checks for `IntrinsicElementalFunction`. From `IntrinsicElementalFunction` check we will get ArraySection which we have to process further but ArraySection check is done before so it gives : 
```
function make_ArraySize_t_util(), line number 2637 at
ASR::is_a<ASR::Var_t>(*a_v) || ASR::is_a<ASR::StructInstanceMember_t>(*a_v) || ASR::is_a<ASR::FunctionParam_t>(*a_v)
ERROR MESSAGE:
Found ASR::exprType::67  !!ArraySection
```

**Comment by jinangshah21** [comment]
> So the reordering makes it compute the dimensions correctly? Can you post an ASR before and after this PR, just for the expression involved? That way we can check that the new way is correct.

Not issue of dimensions. But we want `IntrinsicElementalFunction --> ArraySection --> Array`

**Review by certik — APPROVED** [review]
I think it's fine, it fixes an issue. If the fix is incorrect, we can later rework it.

CC @czgdp1807, if you see a problem here, let me know.

**Comment by Pranavchiku** [comment]
The issue is still there, this PR compiles it but later example segfaults.

So if we create a full example:

```fortran
program arrays_58

real :: A(2,2) = reshape([1.0,2.0,3.0,4.0], [2,2])
call trans(A)
print *, A
if ( any(abs( A - 12.91 ) > 1e-8) ) error stop 
contains

subroutine trans(A)
real, intent(inout) :: A(:, :)
A = matprod(transpose(A))
end subroutine

function matprod(x) result(k)
real,intent(in) :: x(:,:)
real :: k(size(x, 1), size(x, 2))
k = 12.91
end function

end program
```

This does not work.

**Comment by certik** [comment]
Feel free to revert this PR if needed.

**Comment by Pranavchiku** [comment]
I think it is fine it just rearranges some if statement without hindering code flow.

**Comment by jinangshah21** [comment]
> The issue is still there, this PR compiles it but later example segfaults.
> 
> So if we create a full example:
> 
> ```fortran
> program arrays_58
> 
> real :: A(2,2) = reshape([1.0,2.0,3.0,4.0], [2,2])
> call trans(A)
> print *, A
> if ( any(abs( A - 12.91 ) > 1e-8) ) error stop 
> contains
> 
> subroutine trans(A)
> real, intent(inout) :: A(:, :)
> A = matprod(transpose(A))
> end subroutine
> 
> function matprod(x) result(k)
> real,intent(in) :: x(:,:)
> real :: k(size(x, 1), size(x, 2))
> k = 12.91
> end function
> 
> end program
> ```
> 
> This does not work.

It is working on my local.

**Comment by Pranavchiku** [comment]
Can you show the output of `pass_fortran_15_intrinsic_function.f90` after `--dump-all-passes-fortran`?

**Comment by jinangshah21** [comment]
> Can you show the output of `pass_fortran_15_intrinsic_function.f90` after `--dump-all-passes-fortran`?

```fortran
! Fortran code after applying the pass: intrinsic_function
program arrays_58
implicit none
integer(4) :: __1_t
integer(4) :: __1_v
integer(4) :: __2_t
integer(4) :: __2_v
real(4), dimension(2, 2) :: __libasr__created__var__1__real_bin_op_res
real(4), dimension(2, 2) :: __libasr__created__var__2__elemental_func_call_res
logical(4), dimension(2, 2) :: __libasr__created__var__3__real_comp_op_res
real(4) :: __libasr_created_scalar_auxiliary_variable
real(4) :: __libasr_created_scalar_auxiliary_variable1
real(4), dimension(2, 2), save :: a = reshape([1.00000000e+00, 2.00000000e+00, 3.00000000e+00, 4.00000000e+00], [2, 2])
call trans(a)
print *, a
__libasr_created_scalar_auxiliary_variable = 1.29100000e+01
__1_v = lbound(a, 1)
do __1_t = lbound(__libasr__created__var__1__real_bin_op_res, 1), ubound(__libasr__created__var__1__real_bin_op_res, 1)
    __2_v = lbound(a, 2)
    do __2_t = lbound(__libasr__created__var__1__real_bin_op_res, 2), ubound(__libasr__created__var__1__real_bin_op_res,&
         2)
        __libasr__created__var__1__real_bin_op_res(__1_t, __2_t) = a(__1_v,&
         __2_v) - __libasr_created_scalar_auxiliary_variable
        __2_v = __2_v + 1
    end do
    __1_v = __1_v + 1
end do
__1_v = lbound(__libasr__created__var__1__real_bin_op_res, 1)
do __1_t = lbound(__libasr__created__var__2__elemental_func_call_res, 1),&
         ubound(__libasr__created__var__2__elemental_func_call_res, 1)
    __2_v = lbound(__libasr__created__var__1__real_bin_op_res, 1)
    do __2_t = lbound(__libasr__created__var__2__elemental_func_call_res, 2),&
         ubound(__libasr__created__var__2__elemental_func_call_res, 2)
        __libasr__created__var__2__elemental_func_call_res(__1_t,&
         __2_t) = _lcompilers_abs_f32(__libasr__created__var__1__real_bin_op_res(__1_v, __2_v))
        __2_v = __2_v + 1
    end do
    __1_v = __1_v + 1
end do
__libasr_created_scalar_auxiliary_variable1 = 1.00000000e-08
__1_v = lbound(__libasr__created__var__2__elemental_func_call_res, 1)
do __1_t = lbound(__libasr__created__var__3__real_comp_op_res, 1), ubound(__libasr__created__var__3__real_comp_op_res,&
         1)
    __2_v = lbound(__libasr__created__var__2__elemental_func_call_res, 2)
    do __2_t = lbound(__libasr__created__var__3__real_comp_op_res, 2),&
         ubound(__libasr__created__var__3__real_comp_op_res, 2)
        __libasr__created__var__3__real_comp_op_res(__1_t,&
         __2_t) = __libasr__created__var__2__elemental_func_call_res(__1_v,&
         __2_v) > __libasr_created_scalar_auxiliary_variable1
        __2_v = __2_v + 1
    end do
    __1_v = __1_v + 1
end do
if (Any_4_2_0(__libasr__created__var__3__real_comp_op_res)) then
    error stop
end if

contains

subroutine matprod(x, k)
    integer(4) :: __1_t
    integer(4) :: __2_t
    real(4), dimension(:, :), intent(in) :: x
    real(4), dimension(size(x, 1), size(x, 2)), intent(out) :: k
    do __1_t = lbound(k, 1), ubound(k, 1)
        do __2_t = lbound(k, 2), ubound(k, 2)
            k(__1_t, __2_t) = 1.29100000e+01
        end do
    end do
end subroutine matprod

subroutine trans(a)
    integer(4) :: __1_t
    integer(4) :: __1_v
    integer(4) :: __2_t
    integer(4) :: __2_v
    real(4), dimension(:, :), pointer :: __libasr__created__var__0__array_section_pointer_
    real(4), dimension(:, :), allocatable :: __libasr__created__var__0__func_call_res
    real(4), dimension(:, :), allocatable :: __libasr__created__var__0__lcompilers_transpose_res
    real(4), dimension(:, :), intent(inout) :: a
    integer(4), parameter :: x = 2
    deallocate(__libasr__created__var__0__func_call_res)
    allocate(__libasr__created__var__0__func_call_res((ubound(a, 1) - lbound(a, 1))/1 + 1, (x - 1)/1 + 1))
__libasr__created__var__0__array_section_pointer_ => a(lbound(a, 1):ubound(a, 1), 1:x)
    allocate(__libasr__created__var__0__lcompilers_transpose_res(size(__libasr__created__var__0__array_section_pointer_,&
         2), size(__libasr__created__var__0__array_section_pointer_, 1)))
    call _lcompilers_transpose(__libasr__created__var__0__array_section_pointer_,&
         __libasr__created__var__0__lcompilers_transpose_res)
    call matprod(__libasr__created__var__0__lcompilers_transpose_res, __libasr__created__var__0__func_call_res)
    __1_v = lbound(__libasr__created__var__0__func_call_res, 1)
    do __1_t = lbound(a, 1), ubound(a, 1)
        __2_v = lbound(__libasr__created__var__0__func_call_res, 2)
        do __2_t = lbound(a, 2), ubound(a, 2)
            a(__1_t, __2_t) = __libasr__created__var__0__func_call_res(__1_v, __2_v)
            __2_v = __2_v + 1
        end do
        __1_v = __1_v + 1
    end do
end subroutine trans

logical(4) function Any_4_2_0(mask)
    integer(4) :: __1_i
    integer(4) :: __2_i
    logical(4), dimension(:, :), intent(in) :: mask
    Any_4_2_0 = .false.
    do __1_i = lbound(mask, 1), ubound(mask, 1)
        do __2_i = lbound(mask, 2), ubound(mask, 2)
            Any_4_2_0 = Any_4_2_0 .or. mask(__1_i, __2_i)
        end do
    end do
end function Any_4_2_0

real(4) function _lcompilers_abs_f32(x)
    real(4), intent(in) :: x
    if (x >= 0.00000000e+00) then
        _lcompilers_abs_f32 = x
    else
        _lcompilers_abs_f32 = -x
    end if
end function _lcompilers_abs_f32

subroutine _lcompilers_transpose(matrix_a_t, result)
    integer(4) :: i
    integer(4) :: j
    real(4), dimension(:, :), pointer, intent(in) :: matrix_a_t
    real(4), dimension(:, :), intent(out) :: result
    do i = lbound(matrix_a_t, 1), ubound(matrix_a_t, 1)
        do j = lbound(matrix_a_t, 2), ubound(matrix_a_t, 2)
            result(j, i) = matrix_a_t(i, j)
        end do
    end do
    return
end subroutine _lcompilers_transpose

end program arrays_58
```

**Comment by Pranavchiku** [comment]
For me it is:

```fortran
! Fortran code after applying the pass: intrinsic_function
program arrays_58
implicit none
integer(4) :: __1_t
integer(4) :: __1_v
integer(4) :: __2_t
integer(4) :: __2_v
real(4), dimension(2, 2) :: __libasr__created__var__0__real_bin_op_res
real(4), dimension(2, 2) :: __libasr__created__var__1__elemental_func_call_res
logical(4), dimension(2, 2) :: __libasr__created__var__2__real_comp_op_res
real(4) :: __libasr_created_scalar_auxiliary_variable
real(4) :: __libasr_created_scalar_auxiliary_variable1
real(4), dimension(2, 2), save :: a = reshape([1.00000000e+00, 2.00000000e+00, 3.00000000e+00, 4.00000000e+00], [2, 2])
call trans(a)
print *, a
__libasr_created_scalar_auxiliary_variable = 1.29100000e+01
__1_v = lbound(a, 1)
do __1_t = lbound(__libasr__created__var__0__real_bin_op_res, 1), ubound(__libasr__created__var__0__real_bin_op_res, 1)
    __2_v = lbound(a, 2)
    do __2_t = lbound(__libasr__created__var__0__real_bin_op_res, 2), ubound(__libasr__created__var__0__real_bin_op_res,&
         2)
        __libasr__created__var__0__real_bin_op_res(__1_t, __2_t) = a(__1_v,&
         __2_v) - __libasr_created_scalar_auxiliary_variable
        __2_v = __2_v + 1
    end do
    __1_v = __1_v + 1
end do
__1_v = lbound(__libasr__created__var__0__real_bin_op_res, 1)
do __1_t = lbound(__libasr__created__var__1__elemental_func_call_res, 1),&
         ubound(__libasr__created__var__1__elemental_func_call_res, 1)
    __2_v = lbound(__libasr__created__var__0__real_bin_op_res, 1)
    do __2_t = lbound(__libasr__created__var__1__elemental_func_call_res, 2),&
         ubound(__libasr__created__var__1__elemental_func_call_res, 2)
        __libasr__created__var__1__elemental_func_call_res(__1_t,&
         __2_t) = _lcompilers_abs_f32(__libasr__created__var__0__real_bin_op_res(__1_v, __2_v))
        __2_v = __2_v + 1
    end do
    __1_v = __1_v + 1
end do
__libasr_created_scalar_auxiliary_variable1 = 1.00000000e-08
__1_v = lbound(__libasr__created__var__1__elemental_func_call_res, 1)
do __1_t = lbound(__libasr__created__var__2__real_comp_op_res, 1), ubound(__libasr__created__var__2__real_comp_op_res,&
         1)
    __2_v = lbound(__libasr__created__var__1__elemental_func_call_res, 2)
    do __2_t = lbound(__libasr__created__var__2__real_comp_op_res, 2),&
         ubound(__libasr__created__var__2__real_comp_op_res, 2)
        __libasr__created__var__2__real_comp_op_res(__1_t,&
         __2_t) = __libasr__created__var__1__elemental_func_call_res(__1_v,&
         __2_v) > __libasr_created_scalar_auxiliary_variable1
        __2_v = __2_v + 1
    end do
    __1_v = __1_v + 1
end do
if (Any_4_2_0(__libasr__created__var__2__real_comp_op_res)) then
    error stop
end if

contains

subroutine matprod(x, k)
    integer(4) :: __1_t
    integer(4) :: __2_t
    real(4), dimension(:, :), intent(in) :: x
    real(4), dimension(size(x, 1), size(x, 2)), intent(out) :: k
    do __1_t = lbound(k, 1), ubound(k, 1)
        do __2_t = lbound(k, 2), ubound(k, 2)
            k(__1_t, __2_t) = 1.29100000e+01
        end do
    end do
end subroutine matprod

subroutine trans(a)
    integer(4) :: __1_t
    integer(4) :: __1_v
    integer(4) :: __2_t
    integer(4) :: __2_v
    real(4), dimension(:, :), intent(inout) :: a
    real(4), dimension(size(a, 1), size(a, 2)) :: __libasr__created__var__0__func_call_res
    real(4), dimension(:, :), allocatable :: __libasr__created__var__0__lcompilers_transpose_res
    call _lcompilers_transpose(a, __libasr__created__var__0__lcompilers_transpose_res)
    call matprod(__libasr__created__var__0__lcompilers_transpose_res, __libasr__created__var__0__func_call_res)
    __1_v = lbound(__libasr__created__var__0__func_call_res, 1)
    do __1_t = lbound(a, 1), ubound(a, 1)
        __2_v = lbound(__libasr__created__var__0__func_call_res, 2)
        do __2_t = lbound(a, 2), ubound(a, 2)
            a(__1_t, __2_t) = __libasr__created__var__0__func_call_res(__1_v, __2_v)
            __2_v = __2_v + 1
        end do
        __1_v = __1_v + 1
    end do
end subroutine trans

logical(4) function Any_4_2_0(mask)
    integer(4) :: __1_i
    integer(4) :: __2_i
    logical(4), dimension(:, :), intent(in) :: mask
    Any_4_2_0 = .false.
    do __1_i = lbound(mask, 1), ubound(mask, 1)
        do __2_i = lbound(mask, 2), ubound(mask, 2)
            Any_4_2_0 = Any_4_2_0 .or. mask(__1_i, __2_i)
        end do
    end do
end function Any_4_2_0

real(4) function _lcompilers_abs_f32(x)
    real(4), intent(in) :: x
    if (x >= 0.00000000e+00) then
        _lcompilers_abs_f32 = x
    else
        _lcompilers_abs_f32 = -x
    end if
end function _lcompilers_abs_f32

subroutine _lcompilers_transpose(matrix_a_t, result)
    integer(4) :: i
    integer(4) :: j
    real(4), dimension(:, :), intent(in) :: matrix_a_t
    real(4), dimension(:, :), intent(out) :: result
    do i = lbound(matrix_a_t, 1), ubound(matrix_a_t, 1)
        do j = lbound(matrix_a_t, 2), ubound(matrix_a_t, 2)
            result(j, i) = matrix_a_t(i, j)
        end do
    end do
    return
end subroutine _lcompilers_transpose

end program arrays_58
```

**Comment by Pranavchiku** [comment]
In mac we do not have:

```fortran
    deallocate(__libasr__created__var__0__func_call_res)
    allocate(__libasr__created__var__0__func_call_res((ubound(a, 1) - lbound(a, 1))/1 + 1, (x - 1)/1 + 1))
__libasr__created__var__0__array_section_pointer_ => a(lbound(a, 1):ubound(a, 1), 1:x)
    allocate(__libasr__created__var__0__lcompilers_transpose_res(size(__libasr__created__var__0__array_section_pointer_,&
         2), size(__libasr__created__var__0__array_section_pointer_, 1)))
```

This is weird, we need to investigate this divergence.

**Comment by jinangshah21** [comment]
> In mac we do not have:
> 
> ```fortran
>     deallocate(__libasr__created__var__0__func_call_res)
>     allocate(__libasr__created__var__0__func_call_res((ubound(a, 1) - lbound(a, 1))/1 + 1, (x - 1)/1 + 1))
> __libasr__created__var__0__array_section_pointer_ => a(lbound(a, 1):ubound(a, 1), 1:x)
>     allocate(__libasr__created__var__0__lcompilers_transpose_res(size(__libasr__created__var__0__array_section_pointer_,&
>          2), size(__libasr__created__var__0__array_section_pointer_, 1)))
> ```
> 
> This is weird, we need to investigate this divergence.

First I posted wrong code, now it is corrected.

**Comment by jinangshah21** [comment]
`allocate(__libasr__created__var__0__lcompilers_transpose_res(size(a, 2), size(a, 1)))`  this is not present in yours.

**Comment by HarshitaKalani** [comment]
This segfaults for me on latest main, fortran dump of `intrinsic_function` pass:
```fortran
! Fortran code after applying the pass: intrinsic_function
program arrays_58
implicit none
integer(4) :: __1_t
integer(4) :: __1_v
integer(4) :: __2_t
integer(4) :: __2_v
real(4), dimension(2, 2) :: __libasr__created__var__0__real_bin_op_res
real(4), dimension(2, 2) :: __libasr__created__var__1__elemental_func_call_res
logical(4), dimension(2, 2) :: __libasr__created__var__2__real_comp_op_res
real(4) :: __libasr_created_scalar_auxiliary_variable
real(4) :: __libasr_created_scalar_auxiliary_variable1
real(4), dimension(2, 2), save :: a = reshape([1.00000000e+00, 2.00000000e+00, 3.00000000e+00, 4.00000000e+00], [2, 2])
call trans(a)
print *, a
__libasr_created_scalar_auxiliary_variable = 1.29100000e+01
__1_v = lbound(a, 1)
do __1_t = lbound(__libasr__created__var__0__real_bin_op_res, 1), ubound(__libasr__created__var__0__real_bin_op_res, 1)
    __2_v = lbound(a, 2)
    do __2_t = lbound(__libasr__created__var__0__real_bin_op_res, 2), ubound(__libasr__created__var__0__real_bin_op_res,&
         2)
        __libasr__created__var__0__real_bin_op_res(__1_t, __2_t) = a(__1_v,&
         __2_v) - __libasr_created_scalar_auxiliary_variable
        __2_v = __2_v + 1
    end do
    __1_v = __1_v + 1
end do
__1_v = lbound(__libasr__created__var__0__real_bin_op_res, 1)
do __1_t = lbound(__libasr__created__var__1__elemental_func_call_res, 1),&
         ubound(__libasr__created__var__1__elemental_func_call_res, 1)
    __2_v = lbound(__libasr__created__var__0__real_bin_op_res, 1)
    do __2_t = lbound(__libasr__created__var__1__elemental_func_call_res, 2),&
         ubound(__libasr__created__var__1__elemental_func_call_res, 2)
        __libasr__created__var__1__elemental_func_call_res(__1_t,&
         __2_t) = _lcompilers_abs_f32(__libasr__created__var__0__real_bin_op_res(__1_v, __2_v))
        __2_v = __2_v + 1
    end do
    __1_v = __1_v + 1
end do
__libasr_created_scalar_auxiliary_variable1 = 1.00000000e-08
__1_v = lbound(__libasr__created__var__1__elemental_func_call_res, 1)
do __1_t = lbound(__libasr__created__var__2__real_comp_op_res, 1), ubound(__libasr__created__var__2__real_comp_op_res,&
         1)
    __2_v = lbound(__libasr__created__var__1__elemental_func_call_res, 2)
    do __2_t = lbound(__libasr__created__var__2__real_comp_op_res, 2),&
         ubound(__libasr__created__var__2__real_comp_op_res, 2)
        __libasr__created__var__2__real_comp_op_res(__1_t,&
         __2_t) = __libasr__created__var__1__elemental_func_call_res(__1_v,&
         __2_v) > __libasr_created_scalar_auxiliary_variable1
        __2_v = __2_v + 1
    end do
    __1_v = __1_v + 1
end do
if (Any_4_2_0(__libasr__created__var__2__real_comp_op_res)) then
    error stop
end if

contains

subroutine matprod(x, k)
    integer(4) :: __1_t
    integer(4) :: __2_t
    real(4), dimension(:, :), intent(in) :: x
    real(4), dimension(size(x, 1), size(x, 2)), intent(out) :: k
    do __1_t = lbound(k, 1), ubound(k, 1)
        do __2_t = lbound(k, 2), ubound(k, 2)
            k(__1_t, __2_t) = 1.29100000e+01
        end do
    end do
end subroutine matprod

subroutine trans(a)
    integer(4) :: __1_t
    integer(4) :: __1_v
    integer(4) :: __2_t
    integer(4) :: __2_v
    real(4), dimension(:, :), intent(inout) :: a
    real(4), dimension(size(a, 1), size(a, 2)) :: __libasr__created__var__0__func_call_res
    real(4), dimension(:, :), allocatable :: __libasr__created__var__0__lcompilers_transpose_res
    call _lcompilers_transpose(a, __libasr__created__var__0__lcompilers_transpose_res)
    call matprod(__libasr__created__var__0__lcompilers_transpose_res, __libasr__created__var__0__func_call_res)
    __1_v = lbound(__libasr__created__var__0__func_call_res, 1)
    do __1_t = lbound(a, 1), ubound(a, 1)
        __2_v = lbound(__libasr__created__var__0__func_call_res, 2)
        do __2_t = lbound(a, 2), ubound(a, 2)
            a(__1_t, __2_t) = __libasr__created__var__0__func_call_res(__1_v, __2_v)
            __2_v = __2_v + 1
        end do
        __1_v = __1_v + 1
    end do
end subroutine trans

logical(4) function Any_4_2_0(mask)
    integer(4) :: __1_i
    integer(4) :: __2_i
    logical(4), dimension(:, :), intent(in) :: mask
    Any_4_2_0 = .false.
    do __1_i = lbound(mask, 1), ubound(mask, 1)
        do __2_i = lbound(mask, 2), ubound(mask, 2)
            Any_4_2_0 = Any_4_2_0 .or. mask(__1_i, __2_i)
        end do
    end do
end function Any_4_2_0

real(4) function _lcompilers_abs_f32(x)
    real(4), intent(in) :: x
    if (x >= 0.00000000e+00) then
        _lcompilers_abs_f32 = x
    else
        _lcompilers_abs_f32 = -x
    end if
end function _lcompilers_abs_f32

subroutine _lcompilers_transpose(matrix_a_t, result)
    integer(4) :: i
    integer(4) :: j
    real(4), dimension(:, :), intent(in) :: matrix_a_t
    real(4), dimension(:, :), intent(out) :: result
    do i = lbound(matrix_a_t, 1), ubound(matrix_a_t, 1)
        do j = lbound(matrix_a_t, 2), ubound(matrix_a_t, 2)
            result(j, i) = matrix_a_t(i, j)
        end do
    end do
    return
end subroutine _lcompilers_transpose

end program arrays_58

```

**Comment by jinangshah21** [comment]
Ok I am checking rebuilding it.

**Comment by jinangshah21** [comment]
Sorry, my mistake. It is giving segfault. 
Also It gives segfaults for this : 
```
program arrays_58

real :: A(2,2) = reshape([1.0,2.0,3.0,4.0], [2,2])
call trans(A)
print *, A
contains

subroutine trans(A)
real, intent(inout) :: A(:, :)
A = transpose(A)
end subroutine

end program
```
