### PR TITLE
fix: ICE when using len on a character array component accessed via class 

### LINKED ISSUE #10747: ICE when using len on a character array component accessed via class
While compiling the mglet-base codebase dependancies module with LFortran, an Internal Compiler Error occurs in src/ib/topol_mod.F90.

## **MRE**
```
module topol_mod
    implicit none
    type :: topol_t
        character(len=256), allocatable :: geometries(:)
    end type topol_t

contains

    subroutine init(this)
        class(topol_t), intent(inout) :: this
        integer :: j
        j = 1
        allocate(this%geometries(1))
        this%geometries(j) = repeat(" ", len(this%geometries(j)))
    end subroutine init
end module topol_mod

program test_topol

    use topol_mod
    implicit none
    type(topol_t) :: topo
    call init(topo)
    print *, "Length:", len(topo%geometries(1))
    print *, "Content:", "'" // topo%geometries(1) // "'"

end program test_topol

```
## Output With Lfortran
```
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/opixdown/lfortran/src/bin/lfortran.cpp", line 2809
    LCompilers::print_stack_on_segfault();
  File "/Users/opixdown/lfortran/src/bin/lfortran.cpp", line 2736
    err = compile_src_to_object_file(arg_file, tmp_o, compiler_options.time_report, false,
.
.
.
  File "/Users/opixdown/lfortran/src/libasr/asr.h", line 41
    LCOMPILERS_ASSERT(is_a<T>(*f));
AssertFailed: is_a<T>(*f)
```
## Output With Gfortran
```
(lf) opixdown@Atharvs-MacBook-Air lfortran % gfortran t.f90 && ./a.out 
 Length:         256
 Content:'                                                                                                                                                                                                             
                                                   '
(lf) opixdown@Atharvs-MacBook-Air lfortran % 
```

### PR DESCRIPTION
**Pull request by opixdown**
fix #10747

### CODE REVIEW

File: src/lfortran/semantics/ast_common_visitor.h [hunk 1]
```diff
@@ -11936,22 +11936,40 @@ class CommonVisitor : public AST::BaseVisitor<Derived> {
...
         } else if(ASR::is_a<ASR::ArrayItem_t>(*v)) {
             ASR::ArrayItem_t* arr_item = ASR::down_cast<ASR::ArrayItem_t>(v);
-            ASR::Var_t* arr_var = ASR::down_cast<ASR::Var_t>(arr_item->m_v);
-            ASR::symbol_t* arr_sym = arr_var->m_v;
-            ASR::Array_t* arr = ASR::down_cast<ASR::Array_t>(ASRUtils::type_get_past_allocatable_pointer(ASRUtils::symbol_type(arr_sym)));
-            ASR::String_t* str = ASR::down_cast<ASR::String_t>(arr->m_type);
-            int length;
-            len_compiletime = ASRUtils::extract_value(str->m_len, length) ? make_ConstantWithType(
-                make_IntegerConstant_t, length, type, loc) : nullptr;
+                if (ASR::is_a<ASR::Var_t>(*arr_item->m_v)) {
```
Comment (certik) [inline src/lfortran/semantics/ast_common_visitor.h:11939]: Incorrect indentation

**Review by certik — APPROVED** [review]

**Comment by certik** [comment]
To save CI, just let this PR finish the full CI, if it works we'll merge and you fix it in subsequent PR.

**Comment by opixdown** [comment]
> To save CI, just let this PR finish the full CI, if it works we'll merge and you fix it in subsequent PR.

Apologies for the error, i’ll fix it soon

File: integration_tests/CMakeLists.txt [hunk 2]
```diff
@@ -2782,6 +2782,7 @@ RUN(NAME class_140 LABELS gfortran llvm)
 RUN(NAME class_141 LABELS gfortran llvm)
 RUN(NAME class_142 LABELS gfortran llvm)
 RUN(NAME class_143 LABELS gfortran llvm)
+RUN(NAME class_144 LABELS gfortran llvm)
```
Comment (HarshitaKalani) [inline integration_tests/CMakeLists.txt:2785]:
```suggestion
RUN(NAME class_144 LABELS gfortran llvm llvm_wasm llvm_wasm_emcc)
```
Can we also add wasm label with this?
