### PR TITLE
tests: consolidate tests of pr 10467

### LINKED ISSUE #10634: consolidate tests
@opixdown Can you please consolidate the tests in a subsequent PR? Ensure that the consolidated test fails before this PR was merged and works now.

_Originally posted by @certik in https://github.com/lfortran/lfortran/issues/10467#issuecomment-4040384766_

### PR DESCRIPTION
**Pull request by opixdown**
fixes #10634

### CODE REVIEW

File: integration_tests/struct_type_12.f90 [hunk 1]
```diff
@@ -1,15 +1,63 @@
-module test_struct_kind_shadow_int
+module test_shadow_int
```
Comment (certik) [inline integration_tests/struct_type_12.f90]: Put the test name into the module name, to avoid conflicts with other tests running in parallel.

File: integration_tests/struct_type_12.f90 [hunk 2]
```diff
@@ -1,15 +1,62 @@
 module test_struct_kind_shadow_int
```
Comment (HarshitaKalani) [inline integration_tests/struct_type_12.f90]:
```suggestion
module struct_type_12_int_module
```

File: integration_tests/struct_type_12.f90 [hunk 3]
```diff
@@ -1,15 +1,62 @@
...
     implicit none
     integer, parameter :: k = 4
-    type ty
+    type ty_int
         integer(k) :: k = 42_k
     end type
 end module
 
+module test_struct_kind_shadow_complex
```
Comment (HarshitaKalani) [inline integration_tests/struct_type_12.f90]:
```suggestion
module struct_type_12_complex_module
```

Comment (HarshitaKalani) [reply integration_tests/struct_type_12.f90]: Same for other module names please.

File: integration_tests/struct_type_12.f90 [hunk 4]
```diff
@@ -1,15 +1,62 @@
...
+
+module test_struct_kind_shadow_real
+    implicit none
+    integer, parameter :: q = selected_real_kind(10)
+    type ty_real
+        real(q) :: q = 1._q
+    end type
+end module
+
 program test
```
Comment (HarshitaKalani) [inline integration_tests/struct_type_12.f90]:
```suggestion
program struct_type_12
```

File: integration_tests/struct_type_12.f90 [hunk 5]
```diff
@@ -1,15 +1,62 @@
...
+    type(ty_real)    :: t_real
+
+    if (t_int%k /= 42) error stop "integer kind shadow: value incorrect"
+    if (real(t_complex%q) /= 1.0 .or. aimag(t_complex%q) /= 2.0) &
+        error stop "complex kind shadow: value incorrect"
+    if (t_char%c /= 'hello') error stop "char kind shadow: value incorrect"
+    if (.not. t_logical%l)   error stop "logical kind shadow: value incorrect"
+    if (t_real%q /= 1.0)     error stop "real kind shadow: value incorrect"
+    print *, "all tests passed"
 end program test
```
Comment (HarshitaKalani) [inline integration_tests/struct_type_12.f90]:
```suggestion
end program struct_type_12
```

**Comment by opixdown** [comment]
> It would be better this way I think. Can you please address these comments? Thanks!

@HarshitaKalani  done, i have updated the test as suggested
