### PR TITLE
Fix allocatable string assignments

### LINKED ISSUE #1407: bug in implicit LHS string allocate
```fortran
program allocate_05
character(len=:), allocatable :: string
character(len=3) :: num
string = num
end program
```
This gives:
```console
$ lfortran integration_tests/allocate_05.f90      
a.out(5351,0x100498580) malloc: *** error for object 0x100207f7c: pointer being freed was not allocated
a.out(5351,0x100498580) malloc: *** set a breakpoint in malloc_error_break to debug
```
The issue comes from:
```console
$ lfortran integration_tests/allocate_05.f90 --show-llvm
; ModuleID = 'LFortran'
source_filename = "LFortran"

@0 = private unnamed_addr constant [4 x i8] c"   \00", align 1

define i32 @main(i32 %0, i8** %1) {
.entry:
  call void @_lpython_set_argv(i32 %0, i8** %1)
  %num = alloca i8*, align 8
  store i8* getelementptr inbounds ([4 x i8], [4 x i8]* @0, i32 0, i32 0), i8** %num, align 8
  %string = alloca i8*, align 8
  store i8* null, i8** %string, align 8
  %2 = load i8*, i8** %num, align 8
  store i8* %2, i8** %string, align 8
  %3 = load i8*, i8** %string, align 8
  call void (i8*, ...) @_lfortran_free(i8* %3)
  ret i32 0
}

declare void @_lpython_set_argv(i32, i8**)

declare void @_lfortran_free(i8*, ...)
```
the line:
```llvm
  call void (i8*, ...) @_lfortran_free(i8* %3)
```
where `string` is freed, but it points to the global string which cannot be freed.

The solution is to make a copy of the string on the line `string = num` (first allocating `string` to the right size). Then everything should work.

### PR DESCRIPTION
**Pull request by Smit-create**
Fixes #1407

### CODE REVIEW

File: integration_tests/allocate_05.f90 [hunk 1]
```diff
@@ -5,7 +5,7 @@ program allocate_05
     character(len=3) :: num
     allocate(character(len=3)::string)
     num = "abc"
-    string(:) = num
+    string = num
```
Comment (certik) [inline integration_tests/allocate_05.f90:8]: Shouldn't we test both?

Comment (Smit-create) [reply integration_tests/allocate_05.f90:8]: Thanks, done!

**Review by czgdp1807 — APPROVED** [review]

**Review by certik — APPROVED** [review]
Thanks!
