### PR TITLE
fix: Throw error when assigning derived type to base type variable

### LINKED ISSUE #7534: bug: throw error for derived to base class variable assignment
### Minimal Reproducible Example

```fortran
program main
    implicit none

    type :: Base
        integer :: x
    end type

    type, extends(Base) :: Derived
        real :: r
    end type

    type(Base) :: base_var
    type(Derived) :: derived_var

    base_var = derived_var
end program main
```

### Output

```console
(lf) saurabhkumar@Mac lfortran % gfortran test.f90 && ./a.out
test.f90:15:15:

   15 |     base_var = derived_var
      |               1
Error: Cannot convert TYPE(derived) to TYPE(base) at (1)
(lf) saurabhkumar@Mac lfortran % lfortran test.f90           
Assertion failed: (PointeeType == cast<PointerType>(Ptr->getType()->getScalarType())->getElementType()), function Create, file Instructions.h, line 941.
Traceback (most recent call last):
  File "/Users/saurabhkumar/OpenSource/lfortran/src/bin/lfortran.cpp", line 2726
    LCompilers::print_stack_on_segfault();
  File "/Users/saurabhkumar/OpenSource/lfortran/src/bin/lfortran.cpp", line 2653
    err = compile_src_to_object_file(arg_file, tmp_o, compiler_options.time_report, false,
  File "/Users/saurabhkumar/OpenSource/lfortran/src/bin/lfortran.cpp", line 1185
    std::cerr << diagnostics.render(lm, compiler_options);
  File "/Users/saurabhkumar/OpenSource/lfortran/src/lfortran/fortran_evaluator.cpp", line 394
    if (res.ok) {
  File "/Users/saurabhkumar/OpenSource/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 11681
    v.visit_asr((ASR::asr_t&)asr);
  File "/Users/saurabhkumar/OpenSource/lfortran/src/libasr/asr_base_visitor.h", line 342
    void visit_asr(const asr_t &b) { visit_asr_t(b, self()); }
  File "/Users/saurabhkumar/OpenSource/lfortran/src/libasr/asr_base_visitor.h", line 317
    case asrType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/Users/saurabhkumar/OpenSource/lfortran/src/libasr/asr_base_visitor.h", line 343
    void visit_unit(const unit_t &b) { visit_unit_t(b, self()); }
  File "/Users/saurabhkumar/OpenSource/lfortran/src/libasr/asr_base_visitor.h", line 22
    case unitType::TranslationUnit: { v.visit_TranslationUnit((const TranslationUnit_t &)x); return; }
  File "/Users/saurabhkumar/OpenSource/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 1014
    visit_symbol(*item.second);
  File "/Users/saurabhkumar/OpenSource/lfortran/src/libasr/asr_base_visitor.h", line 345
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/Users/saurabhkumar/OpenSource/lfortran/src/libasr/asr_base_visitor.h", line 30
    case symbolType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/Users/saurabhkumar/OpenSource/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3569
    this->visit_stmt(*x.m_body[i]);
  File "/Users/saurabhkumar/OpenSource/lfortran/src/libasr/asr_base_visitor.h", line 361
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/saurabhkumar/OpenSource/lfortran/src/libasr/asr_base_visitor.h", line 54
    case stmtType::Assign: { v.visit_Assign((const Assign_t &)x); return; }
  File "/Users/saurabhkumar/OpenSource/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5567
    asr_target_type, module.get(), name2memidx);
  File "/Users/saurabhkumar/OpenSource/lfortran/src/libasr/codegen/llvm_utils.cpp", line 2202
    src_member = create_gep2(name2dertype[der_type_name], src, mem_idx);
  File "/Users/saurabhkumar/OpenSource/lfortran/src/libasr/codegen/llvm_utils.cpp", line 1514
    return LLVMUtils::CreateGEP2(t, ds, idx_vec);
  File "/Users/saurabhkumar/OpenSource/lfortran/src/libasr/codegen/llvm_utils.cpp", line 1703
    return builder->CreateGEP(t, x, idx);
  File "/Users/saurabhkumar/miniconda3/envs/lf/include/llvm/IR/IRBuilder.h", line 1773
    return Insert(GetElementPtrInst::Create(Ty, Ptr, IdxList), Name);
  File "/Users/saurabhkumar/miniconda3/envs/lf/include/llvm/IR/Instructions.h", line 942
    return new (Values) GetElementPtrInst(PointeeType, Ptr, IdxList, Values,
  Binary file "/usr/lib/system/libsystem_c.dylib", local address: 0x18037aeeb
  Binary file "/usr/lib/system/libsystem_c.dylib", local address: 0x18037bc5f
  Binary file "/usr/lib/system/libsystem_pthread.dylib", local address: 0x18047288b
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x1804ac623
Abort: Signal SIGABRT (abort) received

zsh: abort      lfortran test.f90
```

### PR DESCRIPTION
**Pull request by Jatinagarwal24**
fixes #7534

### CODE REVIEW

File: tests/errors/continue_compilation_3.f90 [hunk 1]
```diff
@@ -203,6 +213,8 @@ program continue_compilation_3
     print *, ['c', 'o', 'd', 'e'] .or. ['m', 'a', 's']
     print *, ["welcome", "to", "lf"] .and. "contributors"  !even size diff of array element must be caught
     call ss("hello")
+    !derived_to_base_assignment
+base_var = derived_var   ! <<<<<< ERROR - Cannot convert TYPE(derived) to TYPE(base)
```
Comment (certik) [inline tests/errors/continue_compilation_3.f90]: Put them into continue_compilation_1 and read the documentation there about removing empty lines, to keep the diff minimal.

File: src/lfortran/semantics/ast_body_visitor.cpp [hunk 2]
```diff
@@ -4932,6 +4932,22 @@ class BodyVisitor : public CommonVisitor<BodyVisitor> {
                     );
                     throw SemanticAbort();
             }
+
+            // Check for strict type equality for non-polymorphic derived types
+            if (ASRUtils::is_struct(*target_type) && !ASRUtils::is_class_type(target_type)) {
+                if (ASRUtils::is_struct(*value_type)) {
```
Comment (Pranavchiku) [inline src/lfortran/semantics/ast_body_visitor.cpp]:
```suggestion
            if (ASRUtils::is_struct(*target_type) && !ASRUtils::is_class_type(target_type) && ASRUtils::is_struct(*value_type)) {
```

**Comment by certik** [comment]
That looks pretty good, now let's run all tests.
