### PR TITLE
fix: use a temporary buffer with `fgets()` for formatted read

### LINKED ISSUE #5576: Reading more than 2 lines from a file fails
MRE:
```fortran
program file_read
implicit none
integer :: i
character(len=10) :: tmp
integer :: u
open(newunit=u, file="input.txt", status='old')
do i = 1, 3
    read(u, '(A)') tmp
    print *, i, tmp
end do
close(u)
end program
```
with `input.txt`:
```
xx
yy
zz
```
Behaves like this:
```console
$ gfortran a.f90 && ./a.out
           1 xx        
           2 yy        
           3 zz        
$ lfortran a.f90 
1    xx
2    yy
3    
```
The first two lines are read correctly, but the last line fails.

### PR DESCRIPTION
**Pull request by kmr-srbh**
fixes #5576 and https://github.com/lfortran/lfortran/issues/5545#issuecomment-2513454447.

### CODE REVIEW

File: src/libasr/runtime/lfortran_intrinsics.c [hunk 1]
```diff
@@ -3320,10 +3320,19 @@ LFORTRAN_API void _lfortran_formatted_read(int32_t unit_num, int32_t* iostat, in
...
+        char *tmp_buffer = (char*)malloc((n + 1) * sizeof(char));
+        *iostat = !(fscanf(stdin, "%s", tmp_buffer) == 1);
+        size_t input_length = strlen(tmp_buffer);
+        strcpy(*arg, tmp_buffer);
+        while (input_length < n) {
+            strncat(*arg, &SPACE, 1);
+            input_length++;
+        }
+        (*arg)[n] = '\0';
+
```
Comment (certik) [inline src/libasr/runtime/lfortran_intrinsics.c:3335]: Should we free `tmp_buffer` here?

**Review by certik — APPROVED** [review]
I think this looks great, thanks for fixing it!

Let's merge it, and we can improve upon this with subsequent PRs, such as fix any memory leaks if there are any.

**Comment by certik** [comment]
CI must be fixed.

**Comment by kmr-srbh** [comment]
Yes this CI failure is due to handling of `iostat`. There is some issue. I will look into it.

File: src/libasr/runtime/lfortran_intrinsics.c (hunk 1 above)
Comment (kmr-srbh) [reply src/libasr/runtime/lfortran_intrinsics.c:3335]: Ah, yes. Adding it.

**Comment by kmr-srbh** [comment]
Will finish this PR for `"(a)"` format specifier today. We can later look into supporting the other format specifiers in subsequent PRs if it is high priority.

**Comment by certik** [comment]
`(A)` is good for now.

File: src/libasr/runtime/lfortran_intrinsics.c [hunk 2]
```diff
@@ -3319,30 +3319,69 @@ LFORTRAN_API void _lfortran_formatted_read(int32_t unit_num, int32_t* iostat, in
...
+            (buffer)[strcspn(buffer, "\n")] = 0;
+
+            size_t input_length = strlen(buffer);
+            *chunk = input_length;
+            while (input_length < n) {
+                strncat(buffer, &SPACE, 1);
+                input_length++;
+            }
+            strcpy(*arg, buffer);
```
Comment (gxyd) [inline src/libasr/runtime/lfortran_intrinsics.c:3347]: I see that `*arg` is allocate above as `*arg = (char*)malloc(n * sizeof(char));`, while buffer is `char *buffer = (char*)malloc((n + 1) * sizeof(char));`

and the syntax for `strcpy` says:
```c
char *strcpy(char *dest, const char *src)
```

It probably maybe wrong to copy size `n + 1` (`buffer`) to size `n` (`*arg`)

File: src/libasr/runtime/lfortran_intrinsics.c [hunk 3]
```diff
@@ -3319,30 +3319,69 @@ LFORTRAN_API void _lfortran_formatted_read(int32_t unit_num, int32_t* iostat, in
...
+            } else {
+                *iostat = 0;
+            }
+
+            (buffer)[strcspn(buffer, "\n")] = 0;
+
+            size_t input_length = strlen(buffer);
+            *chunk = input_length;
+            while (input_length < n) {
+                strncat(buffer, &SPACE, 1);
```
Comment (gxyd) [inline src/libasr/runtime/lfortran_intrinsics.c:3344]: I'm looking at the documentation for `strncat` https://en.cppreference.com/w/c/string/byte/strncat, it says:
```
Return value
1) returns a copy of dest
2) returns zero on success, returns non-zero on error. Also, on error, writes zero to dest[0] (unless dest is a null pointer or destsz is zero or greater than RSIZE_MAX).
```

which makes me think that this isn't an efficient way of padding spaces. Why don't we simply use a `for loop` and assign the remaining character of `buffer` as `buffer[i] = ' ';` I think that would be more efficient than using `strncat`

File: src/libasr/runtime/lfortran_intrinsics.c [hunk 4]
```diff
@@ -3319,30 +3319,69 @@ LFORTRAN_API void _lfortran_formatted_read(int32_t unit_num, int32_t* iostat, in
 
     int n = strlen(*arg);
     *arg = (char*)malloc(n * sizeof(char));
+    const char SPACE = ' ';
```
Comment (gxyd) [inline src/libasr/runtime/lfortran_intrinsics.c:3322]: could you please help me understand, that if this function `_lfortran_formatted_read` is run for every line we encounter?

e.g. for
```
xx
yy
zz
```
so this function `_lfortran_formatted_read` will be run three times?

File: src/libasr/runtime/lfortran_intrinsics.c [hunk 5]
```diff
@@ -3319,30 +3319,69 @@ LFORTRAN_API void _lfortran_formatted_read(int32_t unit_num, int32_t* iostat, in
...
+        } else {
+            if (streql(buffer, "\n")) {
+                *iostat = -2;
+            } else {
+                *iostat = 0;
+            }
+
+            (buffer)[strcspn(buffer, "\n")] = 0;
+
+            size_t input_length = strlen(buffer);
```
Comment (gxyd) [inline src/libasr/runtime/lfortran_intrinsics.c:3341]: since we already used `strcspn` above to find the character where the first `\n` occurs, we can find `input_length` from that?

**Review by gxyd — COMMENTED** [review]
I left a few comments, every time I read C code, it usually takes me a long time to review it, because of not so ease with debugging. I'm sure that I haven't reviewed it carefully, but left a few comments we can think about.

**Review by certik — APPROVED** [review]
I think it's good enough to merge, since it fixes a bug that now works. However, let's improve the code based on @gxyd's suggestions in subsequent PRs.
