### PR TITLE
fix: support CONTIGUOUS attribute in variable declarations

### LINKED ISSUE #10587: Semantic error: "Attribute declaration not supported" for CONTIGUOUS attribute
MRE 
```
program expr2
	implicit none
	character(len=1) :: nml(1)
	double precision :: nmv(1)

	call eval_equation("x", nml, nmv)

contains

	subroutine eval_equation(ln, nml, nmv)
		character(*), intent(in) :: ln
		character(*), dimension(:), intent(in) :: nml
		double precision, dimension(:), intent(inout) :: nmv
		contiguous :: nml, nmv
	end subroutine eval_equation

end program expr2
```
LFortran 
```
(lf) root@LAPTOP-8SLTQKJO:~/lfortran# lfortran examples/expr2.f90 
semantic error: Attribute declaration not supported
  --> examples/expr2.f90:14:3
   |
14 |   contiguous :: nml, nmv
   |   ^^^^^^^^^^^^^^^^^^^^^^ 


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```
Gfortran
```
(lf) root@LAPTOP-8SLTQKJO:~/lfortran# gfortran examples/expr2.f90 && ./a.out 

```

### PR DESCRIPTION
**Pull request by Jatinagarwal24**
fix #10587

### CODE REVIEW

**Comment by Jatinagarwal24** [comment]
Hi,@certik pls review this.

File: src/lfortran/semantics/ast_common_visitor.h [hunk 1]
```diff
@@ -4748,6 +4748,30 @@ class CommonVisitor : public AST::BaseVisitor<Derived> {
...
+                                    ASR::symbol_t* sym_past_external =
+                                        ASRUtils::symbol_get_past_external(sym_);
+                                    if (!ASR::is_a<ASR::Variable_t>(*sym_past_external)) {
+                                        diag.add(Diagnostic(
+                                            "Contiguous attribute can only be applied to variables",
+                                            Level::Error, Stage::Semantic, {
+                                                Label("", {x.m_syms[i].loc})
+                                            }));
+                                        throw SemanticAbort();
+                                    }
```
Comment (HarshitaKalani) [inline src/lfortran/semantics/ast_common_visitor.h:4806]: Can we please add tests for these two errors in the continue_compilation_*.f90 file?

Comment (Jatinagarwal24) [reply src/lfortran/semantics/ast_common_visitor.h:4806]: I have added two tests in continue_compilation file.Thanks!

**Comment by certik** [comment]
I think that's fine. Please rebase.
