### PR TITLE
Fix `sqrt(epsilon(1._dp))`

### LINKED ISSUE #1122: sqrt(epsilon(1._dp)) does not work
This:
```fortran
program test
integer, parameter :: dp = kind(0.d0)
real(dp) :: tol
tol = sqrt(epsilon(1._dp))
print *, tol
end
```
Gives:
```console
$ gfortran a.f90 && ./a.out 
   1.4901161193847656E-008
$ lfortran a.f90 
1.49166814624004135e-154
```

### PR DESCRIPTION
**Pull request by Pranavchiku**
Fixes #1122.
With this, we get [`minpack/example_lmdif1`](https://github.com/certik/minpack/blob/scipy21/examples/example_lmdif1.f90) aligned with GFortran by every bit.

Clean PR for #1176.

### CODE REVIEW

File: integration_tests/intrinsics_34.f90 [hunk 1]
```diff
@@ -1,6 +1,13 @@
...
+    real(dp) :: y = 2.33
     print *, epsilon(x)
     print *, epsilon(y)
-end program
\ No newline at end of file
+    print *, epsilon(1._dp) ** 0.5 !Part of Minpack
+
+    ! Below numbers are corresponding output of gfortran and not magic numbers.
+    if (abs(epsilon(x) - 1.19209290E-07) > 1e-7) error stop
+    if (abs(epsilon(y) - 2.2204460492503131E-016) > 1e-15) error stop
```
Comment (certik) [inline integration_tests/intrinsics_34.f90:11]:
```suggestion
    if (abs(epsilon(y) - 2.2204460492503131E-016_dp) > 1e-15_dp) error stop
```

**Review by certik — APPROVED** [review]
Otherwise this is good, after you merge the suggestions and regenerate reference tests, this can be merged.

**Comment by certik** [comment]
Thanks for fixing it!
