### PR TITLE
Modify return type for `BinOp` after `where` pass itemize the array

### LINKED ISSUE #5433: (PRIMA) RealBinOp in max intrinsic in where clause causes error
Towards #4397 

MRE:

```fortran
program main
real :: A(4)
call temp(A)

contains
subroutine temp(A)
real, intent(in) :: A(:)
real :: xbdi(size(A))
real :: ssq(size(A))
where (xbdi == 0) ssq = max(0.0, ssq - xbdi)
end subroutine

end program
```

LFortran Error :
```console
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/mnt/c/lfortran/src/bin/lfortran", in _start
  File "/build/glibc-LcI20x/glibc-2.31/csu/../csu/libc-start.c", line 308, in __libc_start_main
  File "/mnt/c/lfortran/src/bin/lfortran.cpp", line 2688, in main
    return main_app(argc, argv);
  File "/mnt/c/lfortran/src/bin/lfortran.cpp", line 2630, in main_app(int, char**)
    err = compile_src_to_object_file(arg_file, tmp_o, false,
  File "/mnt/c/lfortran/src/bin/lfortran.cpp", line 1045, in (anonymous namespace)::compile_src_to_object_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, LCompilers::CompilerOptions&, LCompilers::PassManager&)
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/mnt/c/lfortran/src/lfortran/fortran_evaluator.cpp", line 382, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 10372, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    v.visit_asr((ASR::asr_t&)asr);
  File "/mnt/c/lfortran/src/libasr/../libasr/asr.h", line 5186, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_asr(LCompilers::ASR::asr_t const&)
    void visit_asr(const asr_t &b) { visit_asr_t(b, self()); }
  File "/mnt/c/lfortran/src/libasr/../libasr/asr.h", line 5162, in void LCompilers::ASR::visit_asr_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::asr_t const&, LCompilers::ASRToLLVMVisitor&)
    case asrType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/mnt/c/lfortran/src/libasr/../libasr/asr.h", line 5187, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_unit(LCompilers::ASR::unit_t const&)
    void visit_unit(const unit_t &b) { visit_unit_t(b, self()); }
  File "/mnt/c/lfortran/src/libasr/../libasr/asr.h", line 4892, in void LCompilers::ASR::visit_unit_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::unit_t const&, LCompilers::ASRToLLVMVisitor&)
    case unitType::TranslationUnit: { v.visit_TranslationUnit((const TranslationUnit_t &)x); return; }
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 988, in LCompilers::ASRToLLVMVisitor::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    visit_symbol(*item.second);
  File "/mnt/c/lfortran/src/libasr/../libasr/asr.h", line 5189, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/mnt/c/lfortran/src/libasr/../libasr/asr.h", line 4900, in void LCompilers::ASR::visit_symbol_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::symbol_t const&, LCompilers::ASRToLLVMVisitor&)
    case symbolType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3253, in LCompilers::ASRToLLVMVisitor::visit_Program(LCompilers::ASR::Program_t const&)
    visit_procedures(x);
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4288, in void LCompilers::ASRToLLVMVisitor::visit_procedures<LCompilers::ASR::Program_t>(LCompilers::ASR::Program_t const&)
    visit_Function(*s);
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4044, in LCompilers::ASRToLLVMVisitor::visit_Function(LCompilers::ASR::Function_t const&)
    generate_function(x);
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4240, in LCompilers::ASRToLLVMVisitor::generate_function(LCompilers::ASR::Function_t const&)
    this->visit_stmt(*x.m_body[i]);
  File "/mnt/c/lfortran/src/libasr/../libasr/asr.h", line 5206, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/mnt/c/lfortran/src/libasr/../libasr/asr.h", line 4955, in void LCompilers::ASR::visit_stmt_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::stmt_t const&, LCompilers::ASRToLLVMVisitor&)
    case stmtType::WhileLoop: { v.visit_WhileLoop((const WhileLoop_t &)x); return; }
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 6063, in LCompilers::ASRToLLVMVisitor::visit_WhileLoop(LCompilers::ASR::WhileLoop_t const&)
    create_loop(x.m_name, [=]() {
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 321, in void LCompilers::ASRToLLVMVisitor::create_loop<LCompilers::ASRToLLVMVisitor::visit_WhileLoop(LCompilers::ASR::WhileLoop_t const&)::'lambda'(), LCompilers::ASRToLLVMVisitor::visit_WhileLoop(LCompilers::ASR::WhileLoop_t const&)::'lambda0'()>(char*, LCompilers::ASRToLLVMVisitor::visit_WhileLoop(LCompilers::ASR::WhileLoop_t const&)::'lambda'(), LCompilers::ASRToLLVMVisitor::visit_WhileLoop(LCompilers::ASR::WhileLoop_t const&)::'lambda0'())
    loop_body();
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 6069, in LCompilers::ASRToLLVMVisitor::visit_WhileLoop(LCompilers::ASR::WhileLoop_t const&)::'lambda0'()::operator()() const
    this->visit_stmt(*x.m_body[i]);
  File "/mnt/c/lfortran/src/libasr/../libasr/asr.h", line 5206, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/mnt/c/lfortran/src/libasr/../libasr/asr.h", line 4938, in void LCompilers::ASR::visit_stmt_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::stmt_t const&, LCompilers::ASRToLLVMVisitor&)
    case stmtType::If: { v.visit_If((const If_t &)x); return; }
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 6023, in LCompilers::ASRToLLVMVisitor::visit_If(LCompilers::ASR::If_t const&)
    llvm_utils->create_if_else(tmp, [&]() {
  File "/mnt/c/lfortran/src/libasr/../libasr/codegen/llvm_utils.h", line 400, in void LCompilers::LLVMUtils::create_if_else<LCompilers::ASRToLLVMVisitor::visit_If(LCompilers::ASR::If_t const&)::'lambda'(), LCompilers::ASRToLLVMVisitor::visit_If(LCompilers::ASR::If_t const&)::'lambda0'()>(llvm::Value*, LCompilers::ASRToLLVMVisitor::visit_If(LCompilers::ASR::If_t const&)::'lambda'(), LCompilers::ASRToLLVMVisitor::visit_If(LCompilers::ASR::If_t const&)::'lambda0'())
    if_block();
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 6025, in LCompilers::ASRToLLVMVisitor::visit_If(LCompilers::ASR::If_t const&)::'lambda'()::operator()() const
    this->visit_stmt(*x.m_body[i]);
  File "/mnt/c/lfortran/src/libasr/../libasr/asr.h", line 5206, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/mnt/c/lfortran/src/libasr/../libasr/asr.h", line 4955, in void LCompilers::ASR::visit_stmt_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::stmt_t const&, LCompilers::ASRToLLVMVisitor&)
    case stmtType::WhileLoop: { v.visit_WhileLoop((const WhileLoop_t &)x); return; }
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 6063, in LCompilers::ASRToLLVMVisitor::visit_WhileLoop(LCompilers::ASR::WhileLoop_t const&)
    create_loop(x.m_name, [=]() {
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 321, in void LCompilers::ASRToLLVMVisitor::create_loop<LCompilers::ASRToLLVMVisitor::visit_WhileLoop(LCompilers::ASR::WhileLoop_t const&)::'lambda'(), LCompilers::ASRToLLVMVisitor::visit_WhileLoop(LCompilers::ASR::WhileLoop_t const&)::'lambda0'()>(char*, LCompilers::ASRToLLVMVisitor::visit_WhileLoop(LCompilers::ASR::WhileLoop_t const&)::'lambda'(), LCompilers::ASRToLLVMVisitor::visit_WhileLoop(LCompilers::ASR::WhileLoop_t const&)::'lambda0'())
    loop_body();
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 6069, in LCompilers::ASRToLLVMVisitor::visit_WhileLoop(LCompilers::ASR::WhileLoop_t const&)::'lambda0'()::operator()() const
    this->visit_stmt(*x.m_body[i]);
  File "/mnt/c/lfortran/src/libasr/../libasr/asr.h", line 5206, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/mnt/c/lfortran/src/libasr/../libasr/asr.h", line 4926, in void LCompilers::ASR::visit_stmt_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::stmt_t const&, LCompilers::ASRToLLVMVisitor&)
    case stmtType::Assignment: { v.visit_Assignment((const Assignment_t &)x); return; }
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5134, in LCompilers::ASRToLLVMVisitor::visit_Assignment(LCompilers::ASR::Assignment_t const&)
    this->visit_expr_wrapper(m_value, true);
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5539, in LCompilers::ASRToLLVMVisitor::visit_expr_wrapper(LCompilers::ASR::expr_t*, bool)
    this->visit_expr(*x);
  File "/mnt/c/lfortran/src/libasr/../libasr/asr.h", line 5254, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_expr(LCompilers::ASR::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/mnt/c/lfortran/src/libasr/../libasr/asr.h", line 4980, in void LCompilers::ASR::visit_expr_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::expr_t const&, LCompilers::ASRToLLVMVisitor&)
    case exprType::FunctionCall: { v.visit_FunctionCall((const FunctionCall_t &)x); return; }
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9936, in LCompilers::ASRToLLVMVisitor::visit_FunctionCall(LCompilers::ASR::FunctionCall_t const&)
    std::vector<llvm::Value *> args2 = convert_call_args(x, is_method);
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 8858, in std::vector<llvm::Value*, std::allocator<llvm::Value*> > LCompilers::ASRToLLVMVisitor::convert_call_args<LCompilers::ASR::FunctionCall_t>(LCompilers::ASR::FunctionCall_t const&, bool)
    this->visit_expr_wrapper(x.m_args[i].m_value);
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5539, in LCompilers::ASRToLLVMVisitor::visit_expr_wrapper(LCompilers::ASR::expr_t*, bool)
    this->visit_expr(*x);
  File "/mnt/c/lfortran/src/libasr/../libasr/asr.h", line 5254, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_expr(LCompilers::ASR::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/mnt/c/lfortran/src/libasr/../libasr/asr.h", line 5043, in void LCompilers::ASR::visit_expr_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::expr_t const&, LCompilers::ASRToLLVMVisitor&)
    case exprType::ArrayItem: { v.visit_ArrayItem((const ArrayItem_t &)x); return; }
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2374, in LCompilers::ASRToLLVMVisitor::visit_ArrayItem(LCompilers::ASR::ArrayItem_t const&)
    bool is_bindc_array = ASRUtils::expr_abi(x.m_v) == ASR::abiType::BindC;
LCompilersException: Cannot extract the ABI of f32[:] expression.
```

### PR DESCRIPTION
**Pull request by assem2002**
Fixes #5433
It changes the ASR for the example `where (xbdi == 0) ssq = max(0, ssq - xbdi)` from 
```Clojure
(IntegerBinOp
    (ArrayItem
        (Var 3 ssq)
        [(()
        (Var 3 __1_k)
        ())]
        (Integer 4)
        RowMajor
        ()
    )
    Sub
    (ArrayItem
        (Var 3 xbdi)
        [(()
        (Var 3 __1_k)
        ())]
        (Integer 4)
        RowMajor
        ()
    )
    (Array
        (Integer 4)
        [((IntegerConstant 1 (Integer 4) Decimal)
        (ArraySize
            (Var 3 a)
            ()
            (Integer 4)
            ()
        ))]
        PointerToDataArray
    )
    ()
)
```
To
```Clojure
(IntegerBinOp
    (ArrayItem
        (Var 3 ssq)
        [(()
        (Var 3 __1_k)
        ())]
        (Integer 4)
        RowMajor
        ()
    )
    Sub
    (ArrayItem
        (Var 3 xbdi)
        [(()
        (Var 3 __1_k)
        ())]
        (Integer 4)
        RowMajor
        ()
    )
    (Integer 4)  ;; HERE IS THE CHANGE
    ()
)
```

### CODE REVIEW

**Comment by assem2002** [comment]
I think `abs` doesn't work for that for some reason. We just have to make sure we skip it in `where` pass as we already do, but it seems something happen for `abs`

File: src/libasr/pass/where.cpp [hunk 1]
```diff
@@ -85,8 +85,13 @@ class ReplaceVar : public ASR::BaseExprReplacer<ReplaceVar>
         this->replace_expr(x->m_right); \
         ASR::expr_t* right = *current_expr; \
         current_expr = current_expr_copy; \
+        ASR::ttype_t* return_type;\
+        /* Both sides are primtives, OR one side is primitve and the other is ArrayBroadCast, OR both arrays*/ \
+        bool return_is_primitve =!ASRUtils::is_array(ASRUtils::expr_type(x->m_left)) || \
```
Comment (assem2002) [inline src/libasr/pass/where.cpp:90]: Should we change that to "scalar"?

File: integration_tests/where_14.f90 [hunk 2]
```diff
@@ -0,0 +1,16 @@
...
+    call temp(A)
+    
+    contains
+    subroutine temp(A)
+    real, intent(in) :: A(:)
+    integer :: xbdi(size(A))
+    integer :: ssq(size(A))
+    xbdi = [212334,0,212121,0]
+    ssq = [1,10,1,-1]
+    where (xbdi == 0) ssq = max(0, ssq - xbdi)
```
Comment (gxyd) [inline integration_tests/where_14.f90:12]: Can we also add test cases for `ssq - 2` and `2 - ssq` (i.e. one item being scalar and the other is array/non-primitive)?

Comment (gxyd) [reply integration_tests/where_14.f90:12]: Does this test case already pass with `--experimental-simplifier` flag? Maybe put the changes in this PR under `if (!experimental_simplifier) { ... / changes here / } `

Why do they pass on `--experimental-simplifier`? (a brief understanding here would be nice)

File: src/libasr/pass/where.cpp (hunk 1 above)
Comment (gxyd) [reply src/libasr/pass/where.cpp:90]: In this context, I think either is fine, I'm happy with *primitive*.

**Comment by gxyd** [comment]
The current failure in job *build-and-push-image* is unrelated to this PR, and will vanish once *main* is merged, so that's allright.

File: src/libasr/pass/where.cpp [hunk 3]
```diff
@@ -85,8 +85,13 @@ class ReplaceVar : public ASR::BaseExprReplacer<ReplaceVar>
         this->replace_expr(x->m_right); \
         ASR::expr_t* right = *current_expr; \
         current_expr = current_expr_copy; \
+        ASR::ttype_t* return_type;\
+        /* Both sides are primtives, OR one side is primitve and the other is ArrayBroadCast, OR both arrays*/ \
```
Comment (certik) [inline src/libasr/pass/where.cpp:89]:
```suggestion
        /* Both sides are primitives, OR one side is primitive and the other is ArrayBroadCast, OR both arrays*/ \
```

**Review by certik — APPROVED** [review]
I think this is fine.

File: integration_tests/where_14.f90 (hunk 2 above)
Comment (assem2002) [reply integration_tests/where_14.f90:12]: Yeah that's great question. The test provided doesn't work on main because `where`  pass creates a wrong return type for `BinOp` which is `Array` though that `where` pass has done its job on itemizing the arrays, and then `array_op` sees the `BinOp` as `array` expression then it tries to loop on it and for sure I can't see what it tries to do as the final ASR is meaningless.
On the other hand `--experimental-simplifier` doesn't depend on `where` pass to itemize the array so the return type of `BinOp` is correct so all of that mess I mentioned above doesn't occur.

Comment (assem2002) [reply integration_tests/where_14.f90:12]: I'll push cases with `ssq -2 ` and `2 - ssq`

**Review by certik — APPROVED** [review]
