### PR TITLE
fix: handle lone `logical` array in `WHERE` clause

### LINKED ISSUE #4316: Support implicit comparison for logical arrays in `where`
MRE

```fortran
program name
    implicit none
    logical :: a(5)
    integer  :: b(5)
    b = -1
    a = [.true., .false., .true., .false., .true.]
    where(a) b = 12121
    print *, b  
   !Expected Result >>  ( 12121          -1       12121          -1       12121 )
end program name

```
if we use `where(a .eqv. .TRUE.) b = 12121`, It works fine

### PR DESCRIPTION
**Pull request by kmr-srbh**
fixes #4316 

```fortran
program name
   implicit none
   logical :: a(5)
   integer  :: b(5)
   a = [.true., .false., .true., .false., .true.]
   where(a) b = 12121
   print *, b
end program name
```
is transformed to
```fortran
program name
implicit none
integer(4) :: __1_k
logical(4), dimension(5) :: __libasr__created__var__0__array_constant_
logical(4), dimension(5) :: a
integer(4), dimension(5) :: b
__1_k = lbound(__libasr__created__var__0__array_constant_, 1)
__libasr__created__var__0__array_constant_(__1_k) = .true.
__1_k = __1_k + 1
__libasr__created__var__0__array_constant_(__1_k) = .false.
__1_k = __1_k + 1
__libasr__created__var__0__array_constant_(__1_k) = .true.
__1_k = __1_k + 1
__libasr__created__var__0__array_constant_(__1_k) = .false.
__1_k = __1_k + 1
__libasr__created__var__0__array_constant_(__1_k) = .true.
__1_k = __1_k + 1
a = __libasr__created__var__0__array_constant_
do __1_k = lbound(a, 1), ubound(a, 1), 1
    if (a(__1_k) .eqv. .true.) then
        b(__1_k) = 12121
    end if
end do
print *, b
end program name
```
in the `where` pass.

### Output
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
12121 873032432 12121 -231447168 12121 
```

### CODE REVIEW

File: src/libasr/pass/where.cpp [hunk 1]
```diff
@@ -258,6 +263,9 @@ class WhereVisitor : public PassUtils::PassVisitor<WhereVisitor>
         } else if (log_bin_op) {
             test_new = ASRUtils::EXPR(ASR::make_LogicalBinOp_t(al, loc, is_left_array ? left_array : left, log_bin_op->m_op,
                         is_right_array?right_array:right, logical_type, nullptr));
+        } else if (ASR::is_a<ASR::ArrayItem_t>(*test)) {
```
Comment (certik) [inline src/libasr/pass/where.cpp:266]: Add an assert here that the type of `test` is logical? This should be caught by verify() of course, but just for documenting the flow, that a single variable in a condition must be logical and we assume it is.

**Comment by certik** [comment]
Add a test.

File: src/libasr/pass/where.cpp (hunk 1 above)
Comment (kmr-srbh) [reply src/libasr/pass/where.cpp:266]: We handle this case inside `visit_Where`:
```c++
} else if (ASRUtils::is_array(ASRUtils::expr_type(test))) {
    if (ASR::is_a<ASR::Logical_t>(*ASRUtils::type_get_past_array(ASRUtils::expr_type((test))))) {
        left = test;
        is_array = true;
    } else {
        throw LCompilersException("'where' clause requires a logical array");
    }
}
```
```fortran
program name
   implicit none
   integer :: a(5)
   integer  :: b(5)
   a = [1, 2, 3, 4, 5]
   where(a) b = 12121
   print *, b
end program name
```
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 360, in __libc_start_main_impl()
  File "./csu/../sysdeps/x86/libc-start.c", line 58, in __libc_start_call_main()
  File "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran.cpp", line 2481, in main()
    return main_app(argc, argv);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran.cpp", line 2442, in main_app(int, char**)
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran.cpp", line 954, in compile_to_object_file()
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/fortran_evaluator.cpp", line 363, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9967, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/pass/pass_manager.h", line 315, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/pass/pass_manager.h", line 169, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    _passes_db[passes[i]](al, *asr, pass_options);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/pass/where.cpp", line 432, in LCompilers::pass_replace_where(Allocator&, LCompilers::ASR::TranslationUnit_t&, LCompilers::PassOptions const&)
    v.visit_TranslationUnit(unit);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 40665, in LCompilers::ASR::ASRPassBaseWalkVisitor<LCompilers::WhereVisitor>::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    this->visit_symbol(*a.second);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 5157, in LCompilers::ASR::BaseVisitor<LCompilers::WhereVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 4869, in visit_symbol_t<LCompilers::WhereVisitor>()
    case symbolType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/pass/pass_utils.h", line 305, in LCompilers::PassUtils::PassVisitor<LCompilers::WhereVisitor>::visit_Program(LCompilers::ASR::Program_t const&)
    transform_stmts(xx.m_body, xx.n_body);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/pass/pass_utils.h", line 280, in LCompilers::PassUtils::PassVisitor<LCompilers::WhereVisitor>::transform_stmts(LCompilers::ASR::stmt_t**&, unsigned long&)
    self().visit_stmt(*m_body[i]);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 5174, in LCompilers::ASR::BaseVisitor<LCompilers::WhereVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 4923, in visit_stmt_t<LCompilers::WhereVisitor>()
    case stmtType::Where: { v.visit_Where((const Where_t &)x); return; }
LCompilersException: 'where' clause requires a logical array
```

Comment (kmr-srbh) [reply src/libasr/pass/where.cpp:266]: We are currently using `LCompilersException` for error here, I will replace them with a semantic error.

Comment (certik) [reply src/libasr/pass/where.cpp:266]: Yes, `throw LCompilersException("'where' clause requires a logical array");` is perfect here.

This is in a pass, we do not give semantic errors in the pass, only internal compiler errors `LCompilersException` which means it's a bug in LFortran that we have to fix, like above.

All semantic errors must be checked and reported in AST->ASR. So above this error must be caught already in AST->ASR.

**Comment by certik** [comment]
A test must be added.

File: src/libasr/pass/where.cpp (hunk 1 above)
Comment (kmr-srbh) [reply src/libasr/pass/where.cpp:266]: I have added the semantic error at the required place in the AST -> ASR conversion. Is the above exception still required?

Comment (certik) [reply src/libasr/pass/where.cpp:266]: Yes, as a check it's good to keep it.

File: integration_tests/where_08.f90 [hunk 2]
```diff
@@ -0,0 +1,34 @@
+program main
```
Comment (Pranavchiku) [inline integration_tests/where_08.f90:1]:
```suggestion
program where_08
```

File: src/libasr/pass/where.cpp [hunk 3]
```diff
@@ -220,31 +221,35 @@ class WhereVisitor : public PassUtils::PassVisitor<WhereVisitor>
             log_bin_op = ASR::down_cast<ASR::LogicalBinOp_t>(test);
             left = log_bin_op->m_left;
             right = log_bin_op->m_right;
+        } else if (ASR::is_a<ASR::ArrayItem_t>(*test)) {
+            is_single_operand = true;
```
Comment (Pranavchiku) [inline src/libasr/pass/where.cpp:225]: Why would it be an array item? Shouldn't it be just a `var`?

**Review by Pranavchiku — COMMENTED** [review]
Instead of doing it this way, I will prefer to create `LogicalBinOp` ( before line 212 ) and assign it to test if it is a single operand. This way we need no consequent changes and everything will be handled automatically.

This can also be handled in frontend ( AST -> ASR )

File: src/libasr/pass/where.cpp (hunk 3 above)
Comment (kmr-srbh) [reply src/libasr/pass/where.cpp:225]: As we are dealing with an array here, we try to use one element at a time for checking the condition. We construct this on line 403 when the operand is a single array.

**Comment by kmr-srbh** [comment]
>  I will prefer to create LogicalBinOp

This is a good simplification. I will change this implementation to use it. :+1:

File: src/lfortran/semantics/ast_body_visitor.cpp [hunk 4]
```diff
@@ -3218,6 +3218,17 @@ class BodyVisitor : public CommonVisitor<BodyVisitor> {
         Vec<ASR::stmt_t*> orelse;
         orelse.reserve(al, x.n_orelse);
         transform_stmts(orelse, x.n_orelse, x.m_orelse);
+        if (ASRUtils::is_array(ASRUtils::expr_type(test))) {
+            if (!ASR::is_a<ASR::Logical_t>(*ASRUtils::type_get_past_array(ASRUtils::expr_type((test))))) {
+                throw SemanticError("'where' clause requires a logical array", test->base.loc);
+            } else {
+                ASR::expr_t* logical_true = ASRUtils::EXPR(
```
Comment (Pranavchiku) [inline src/lfortran/semantics/ast_body_visitor.cpp:3225]: Awesome, this is what I had in my mind! Just check why CI fails and then I'll review in detail.

Comment (kmr-srbh) [reply src/lfortran/semantics/ast_body_visitor.cpp:3225]: There is a minor issue here. I am fixing it now.

File: src/lfortran/semantics/ast_body_visitor.cpp [hunk 5]
```diff
@@ -3218,6 +3218,22 @@ class BodyVisitor : public CommonVisitor<BodyVisitor> {
...
+                    *ASRUtils::type_get_past_array(ASRUtils::expr_type((test))))) {
+                throw SemanticError("'where' clause requires a logical array", test->base.loc);
+            } else {
+                ASR::expr_t* logical_true = ASRUtils::EXPR(
+                                                ASR::make_LogicalConstant_t(al, x.base.base.loc, true,
+                                                ASRUtils::TYPE(ASR::make_Logical_t(al, x.base.base.loc, 4))));
+                test = ASRUtils::EXPR(ASR::make_LogicalBinOp_t(al, x.base.base.loc, test,
+                            ASR::logicalbinopType::Eqv, logical_true, ASRUtils::expr_type(test), nullptr));
+            }
+        }
```
Comment (certik) [inline src/lfortran/semantics/ast_body_visitor.cpp:3236]: The logic doesn't seem right. Let's say I have a complex array. Then it seems it will go into the "else" branch here, and tries to compare it to logical True? That seems wrong.

Also, what if it is not an array --- shouldn't it fail then?

Instead, why not compare the type itself of the array element? 

I like to do the non-failing mode first in these nested ifs, like this:

```
if (ASRUtils::is_array(ASRUtils::expr_type(test)) {
    if (array_element_ttype(test) == logical) {
        if (logical op) {
            // already in the right format (maybe later we can insert more nested ifs here with more checks)
        } else {
            // explicitly compare against True
        }
    } else {
        error "the first array argument to `where` must be of type logical"
    }
} else {
    error "the argument to `where` must be an array"
}
```

**Comment by kmr-srbh** [comment]
> What is the actual problem we are trying to fix?

The issue in question occurs when we pass a single logical array to `where`. It is semantically correct and GFortran handles it like:
```c++
int i = 0;
while (1) {
    if (logical_array[i]) {
        // do work
    }
}
```

We attempt to construct the same here by checking strictly for the case where we have a standalone logical array.

**Comment by certik** [comment]
The general solution is this: https://github.com/lfortran/lfortran/issues/4330, until then a simple fix like in this PR is good enough to unblock us, so go ahead and finish it as cleanly as we can for now, and we'll merge it.

File: src/lfortran/semantics/ast_body_visitor.cpp (hunk 5 above)
Comment (Pranavchiku) [reply src/lfortran/semantics/ast_body_visitor.cpp:3236]: > Let's say I have a complex array

I think we cannot have it, it should throw an error. @kmr-srbh can you please check and revert if gfortran throws an error or not. By the change you did, we will throw an error for sure.

Comment (kmr-srbh) [reply src/lfortran/semantics/ast_body_visitor.cpp:3236]: GFortran throws an error and we do so too. We test it here - https://github.com/lfortran/lfortran/pull/4320/files#diff-a07067ee3d9cce4783c7a91018d10ef98a00c204321fed16955a53b9e81e96cf.

Comment (Pranavchiku) [reply src/lfortran/semantics/ast_body_visitor.cpp:3236]: In latest main we have no type checking for `test`, with this PR as we are handling types, we shall do it in non-failing mode as Ondrej suggested above.

Comment (Pranavchiku) [reply src/lfortran/semantics/ast_body_visitor.cpp:3236]: > should necessarily always be a logical array.

You are correct, this is what we expect it to be, but end user may write code like `where(.true.)` and in this case type of test will be a logical scalar and it is when we need to throw an error. We cannot certainly say that user will write code correctly, but we need to be certain that we pass a LogicalArray to our ASR passes to make its implementation simple.

Comment (Pranavchiku) [reply src/lfortran/semantics/ast_body_visitor.cpp:3236]: You may refer code block present in https://github.com/lfortran/lfortran/pull/4320/files#r1647528202 and try to understand how your current implementation and that differs.

**Review by Pranavchiku — COMMENTED** [review]
left a few comments on a thread above

File: src/lfortran/semantics/ast_body_visitor.cpp [hunk 6]
```diff
@@ -3218,6 +3218,26 @@ class BodyVisitor : public CommonVisitor<BodyVisitor> {
...
```
Comment (certik) [inline src/lfortran/semantics/ast_body_visitor.cpp:3240]: Let's write this as:
```
if (ASRUtils::is_array(ASRUtils::expr_type(test)) {
    if (array_element_ttype(test) == logical) {
        if  (!ASR::is_a<ASR::IntegerCompare_t>(*test) 
            && !ASR::is_a<ASR::RealCompare_t>(*test)
            && !ASR::is_a<ASR::LogicalBinOp_t>(*test)) {
            // Rewrite into a form "X == true"
                ASR::expr_t* logical_true = ASRUtils::EXPR(
kmr-srbh marked this conversation as resolved.
                                                ASR::make_LogicalConstant_t(al, x.base.base.loc, true,
                                                ASRUtils::TYPE(ASR::make_Logical_t(al, x.base.base.loc, 4))));
                test = ASRUtils::EXPR(ASR::make_LogicalBinOp_t(al, x.base.base.loc, test,
                            ASR::logicalbinopType::Eqv, logical_true, ASRUtils::expr_type(test), nullptr));
        }
    } else {
        error "the first array argument to `where` must be of type logical"
    }
} else {
    error "the argument to `where` must be an array"
}
```

**Review by certik — APPROVED** [review]
I think this looks great now!
