### PR TITLE
Fix #6052: nested_vars pass assigning to intent(in) variables

### LINKED ISSUE #6052: assigning to intent(in) variable by nested vars pass
```fortran
subroutine add(x, y)
    implicit none
    real, intent(in) :: x, y
    print *, x + y
    call add2()
    contains
        subroutine add2()
            implicit none
            print *, x + y + 2
        end subroutine
end subroutine

program main
    implicit none
    call add(1.0, 2.0)
end program
```

```console
% lfortran c.f90
ASR verify pass error: Assignment target `x` with intent `IN` not allowed
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2738
    LCompilers::print_stack_on_segfault();
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2679
    err = compile_src_to_object_file(arg_file, tmp_o, false,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 1052
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 382
    compiler_options, run_fn, infile);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 10496
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 403
    apply_passes(al, asr, _passes_with_experimental_simplifier, pass_options, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 184
    throw LCompilersException("Verify failed in the pass: "
LCompilersException: Verify failed in the pass: nested_vars
```

Bumped to this while debugging #5957

### PR DESCRIPTION
**Pull request by PrakharGoyal28**
Closes #6052
Converts variables with intent(in) to intent(inout) before creating synchronization assignments in the nested_vars pass.
This prevents ASR verification errors like
Assignment target 'x' with intent IN not allowed

### CODE REVIEW

File: src/libasr/pass/nested_vars.cpp [hunk 1]
```diff
@@ -791,6 +791,17 @@ private :
                         } else if (is_procedure_variable) {
                             body.push_back(al, ASRUtils::STMT(ASR::make_Associate_t(al, t->base.loc, target, val)));
                         } else {
+                            if (ASR::is_a<ASR::Var_t>(*val)) {
```
Comment (AnshMehta1) [inline src/libasr/pass/nested_vars.cpp]: I don't think this change is required anymore for fixing this issue as the MRE works correctly with latest main.

File: tests/errors/a.f90 [hunk 2]
```diff
@@ -0,0 +1,16 @@
+subroutine add(x, y)
```
Comment (AnshMehta1) [inline tests/errors/a.f90]: This test should be added as an integration test with error stop conditions rather than adding it in errors directory.

File: integration_tests/internal_subr_host_vars_01.f90 [hunk 3]
```diff
@@ -0,0 +1,26 @@
+! Verify host association for internal subroutines and enforce via error stop
+subroutine add(x, y)
+    implicit none
+    real, intent(in) :: x, y
+    real :: s
+
+    s = x + y
+    if (abs(s - (x + y)) > 1.0e-6) error stop "host add: s mismatch"
```
Comment (AnshMehta1) [inline integration_tests/internal_subr_host_vars_01.f90]: Test must be intended to validate the value of `x + y`.  Add something like `if ( s /= 3.0) error stop`. Don't add any message after error, just a normal error stop is enough.

```suggestion
    if (s /= 3.0) error stop

File: integration_tests/internal_subr_host_vars_01.f90 [hunk 4]
```diff
@@ -0,0 +1,26 @@
...
+
+contains
+
+    subroutine add2()
+        implicit none
+        real :: t
+        ! add2 should be able to see x, y from the host
+        t = x + y + 2.0
+        if (abs(t - (x + y + 2.0)) > 1.0e-6) error stop "host add2: t mismatch"
```
Comment (AnshMehta1) [inline integration_tests/internal_subr_host_vars_01.f90]:
```suggestion
        if (t /= 5.0) error stop

File: integration_tests/internal_subr_host_vars_01.f90 (hunk 3 above)
Comment (PrakharGoyal28) [reply integration_tests/internal_subr_host_vars_01.f90]: Got it

File: integration_tests/internal_subr_host_vars_01.f90 [hunk 5]
```diff
@@ -0,0 +1,26 @@
...
+        real :: t
+        ! add2 should be able to see x, y from the host
+        t = x + y + 2.0
+        if (t /= 5.0) error stop
+    end subroutine add2
+
+end subroutine add
+
+
+program main
```
Comment (AnshMehta1) [inline integration_tests/internal_subr_host_vars_01.f90]: Also, always use program name as file name .
```suggestion
program internal_subr_host_vars_01

File: integration_tests/internal_subr_host_vars_01.f90 [hunk 6]
```diff
@@ -0,0 +1,26 @@
...
+        if (t /= 5.0) error stop
+    end subroutine add2
+
+end subroutine add
+
+
+program internal_subr_host_vars_01
+    implicit none
+    call add(1.0, 2.0)
+end program main
```
Comment (AnshMehta1) [inline integration_tests/internal_subr_host_vars_01.f90]: This should not be main as program name is not main.
```suggestion 
end program internal_subr_host_vars_01

**Review by AnshMehta1 — APPROVED** [review]
Looks fine to me. Thanks
