### PR TITLE
Restrict assignment of do loop variable in do loop body.

### LINKED ISSUE #1342: Lfortran allows redefinition of loop variable unlike Gfortran
```
program for_loop_example
  implicit none
  integer :: i

  do i = 1, 10
    write(*,*) i
    i=i+1
  end do

end program for_loop_example
```
Such an increment is not allowed inside the loop in ` Gfortran`
```
(lf) faze-geek@DESKTOP-497JDCU:~/lfortran/lfortran$ gfortran try.f90  && ./a.out
try.f90:7:9:

    5 |   do i = 1, 10
      |              2
    6 |     write(*,*) i
    7 |     i=i+1
      |         1
Error: Variable ‘i’ at (1) cannot be redefined inside loop beginning at (2)

(lf) faze-geek@DESKTOP-497JDCU:~/lfortran/lfortran$ ./src/bin/lfortran try.f90
1
3
5
7
9
```

### PR DESCRIPTION
**Pull request by Pranavchiku**
Fixes #1342.

### CODE REVIEW

File: src/lfortran/semantics/ast_body_visitor.cpp [hunk 1]
```diff
@@ -2117,6 +2117,23 @@ class BodyVisitor : public CommonVisitor<BodyVisitor> {
...
+                ASR::stmt_t* stmt = body[i];
+                if (stmt->type == ASR::stmtType::Assignment) {
+                    ASR::Assignment_t* assign = ASR::down_cast<ASR::Assignment_t>(stmt);
+                    ASR::expr_t* target = assign->m_target;
+                    if (target->type == ASR::exprType::Var) {
+                        ASR::Var_t* var = ASR::down_cast<ASR::Var_t>(target);
+                        if (var->m_v->type == ASR::symbolType::Variable) {
+                            ASR::Variable_t* target_var = ASR::down_cast<ASR::Variable_t>(var->m_v);
+                            if (to_lower(x.m_var) == std::string(target_var->m_name)) {
+                                throw SemanticError("Do loop: assignment to loop variable `" + std::string(target_var->m_name) +"` is not allowed", assign->base.base.loc);
```
Comment (certik) [inline src/lfortran/semantics/ast_body_visitor.cpp:2131]: I would highlight just the target variable:
```suggestion
                                throw SemanticError("Assignment to loop variable `" + std::string(target_var->m_name) +"` is not allowed in a do loop", target_var->base.base.loc);
```

File: src/lfortran/semantics/ast_body_visitor.cpp [hunk 2]
```diff
@@ -2117,6 +2117,23 @@ class BodyVisitor : public CommonVisitor<BodyVisitor> {
...
+            for (size_t i = 0; i < body.size(); i++) {
+                ASR::stmt_t* stmt = body[i];
+                if (stmt->type == ASR::stmtType::Assignment) {
+                    ASR::Assignment_t* assign = ASR::down_cast<ASR::Assignment_t>(stmt);
+                    ASR::expr_t* target = assign->m_target;
+                    if (target->type == ASR::exprType::Var) {
+                        ASR::Var_t* var = ASR::down_cast<ASR::Var_t>(target);
+                        if (var->m_v->type == ASR::symbolType::Variable) {
+                            ASR::Variable_t* target_var = ASR::down_cast<ASR::Variable_t>(var->m_v);
+                            if (to_lower(x.m_var) == std::string(target_var->m_name)) {
```
Comment (certik) [inline src/lfortran/semantics/ast_body_visitor.cpp:2130]: Use `var` -> m_v and directly compare the pointer with `target_var`. If it is the same pointer, it's the same variable, otherwise it is not. We should not use a string comparison, as it is fragile.

**Comment by Pranavchiku** [comment]
This method does not for nested do loop, I have an approach for that which goes as follows:
* Keep an array of do loop variables -> `do_loop_vars`
* If in `do_loop_body` we find another do loop recursively call the function by pushing the do_loop_var of parent loop in the array
* Check if `assignment->m_target` is present in `do_loop_vars`.

**Comment by Pranavchiku** [comment]
We should throw error here as well right?
```fortran
    do i = 1, 10
        do j = 1, 3
            i = i + 1
        end do
    end do
```

File: src/lfortran/semantics/ast_body_visitor.cpp [hunk 3]
```diff
@@ -2117,6 +2117,21 @@ class BodyVisitor : public CommonVisitor<BodyVisitor> {
...
         if (head.m_v != nullptr) {
+            // iterate over body and for every assignment check target, if it is equal to head.m_v, throw error
+            for (size_t i = 0; i < body.size(); i++) {
+                ASR::stmt_t* stmt = body[i];
+                if (stmt->type == ASR::stmtType::Assignment) {
+                    ASR::Assignment_t* assign = ASR::down_cast<ASR::Assignment_t>(stmt);
+                    ASR::expr_t* target = assign->m_target;
+                    if (target->type == ASR::exprType::Var) {
+                        ASR::Var_t* var1 = ASR::down_cast<ASR::Var_t>(target);
+                        ASR::symbol_t* loop_var_sym = current_scope->resolve_symbol(to_lower(x.m_var));
```
Comment (certik) [inline src/lfortran/semantics/ast_body_visitor.cpp:2128]: I think `var` already contains this information, so you can just extract it instead of doing another lookup.

**Comment by certik** [comment]
This is a good prototype.

There is an issue of performance also, this approach I think will be quite slow, compared to the alternative: You can maintain a stack of loop variables, and then in visit_Assignment, just check that we are not assigning to a variable that is a loop variable. In a way, we are turning on a temporary read-only mode for those variables, restricted to the scope of the loop.

File: src/lfortran/semantics/ast_body_visitor.cpp [hunk 4]
```diff
@@ -2117,6 +2117,21 @@ class BodyVisitor : public CommonVisitor<BodyVisitor> {
         head.m_end = end;
         head.m_increment = increment;
         if (head.m_v != nullptr) {
+            // iterate over body and for every assignment check target, if it is equal to head.m_v, throw error
+            for (size_t i = 0; i < body.size(); i++) {
+                ASR::stmt_t* stmt = body[i];
```
Comment (czgdp1807) [inline src/lfortran/semantics/ast_body_visitor.cpp:2122]: I guess iterating over the whole set of statements might not be the most efficient approach. Its clean but not the most efficient. The error should be thrown as soon as we notice that `head.m_v` is assignment's target. Here the error is thrown once the do loop is fully created.

We just need to add a class member like, `current_loop_variable` and set it to `head.m_v` before starting to visit `AST` statements of the do loop. When you enter `visit_Assignment` just check if the target is the same as `current_loop_variable`. If so raise an error right there.

**Review by czgdp1807 — CHANGES_REQUESTED** [review]

File: src/lfortran/semantics/ast_body_visitor.cpp (hunk 4 above)
Comment (czgdp1807) [reply src/lfortran/semantics/ast_body_visitor.cpp:2122]: Or if you don't want to do it right now, that's also okay. Just add a `TODO` comment that there is a better approach which doesn't require us to wait for the whole do loop to be created before throwing the error.

File: src/lfortran/semantics/ast_body_visitor.cpp (hunk 3 above)
Comment (Pranavchiku) [reply src/lfortran/semantics/ast_body_visitor.cpp:2128]: Okay yes! Thanks for pointing this out.

File: src/lfortran/semantics/ast_body_visitor.cpp (hunk 4 above)
Comment (Pranavchiku) [reply src/lfortran/semantics/ast_body_visitor.cpp:2122]: Let me try to do that, if it takes more time, we can finish this PR and I will just add a `TODO` comment.

**Comment by Pranavchiku** [comment]
I am using `std::vector<ASR::symbol_t*> do_loop_variables` as a stack, and as suggested on visiting Assignment checking if target is present in do_loop_variables, then throwing an error.
It works for nested do loops as well.

**Review by czgdp1807 — APPROVED** [review]
LGTM.

File: src/lfortran/semantics/ast_body_visitor.cpp (hunk 4 above)
Comment (certik) [reply src/lfortran/semantics/ast_body_visitor.cpp]: The `current_loop_variable` must be `current_loop_variables` and be a stack, so that nested loops also work.

File: src/lfortran/semantics/ast_body_visitor.cpp [hunk 5]
```diff
@@ -1611,6 +1612,19 @@ class BodyVisitor : public CommonVisitor<BodyVisitor> {
...
         ASR::expr_t *value = ASRUtils::EXPR(tmp);
         ASR::stmt_t *overloaded_stmt = nullptr;
+        if (target->type == ASR::exprType::Var) {
+            ASR::Var_t *var = ASR::down_cast<ASR::Var_t>(target);
+            ASR::symbol_t *sym = var->m_v;
+            std::string var_name;
+            if (sym->type == ASR::symbolType::Variable) {
+                ASR::Variable_t *v = ASR::down_cast<ASR::Variable_t>(sym);
+                var_name = std::string(v->m_name);
+            }
```
Comment (certik) [inline src/lfortran/semantics/ast_body_visitor.cpp:1622]: Move this inside the next if statement, for performance.

Comment (certik) [reply src/lfortran/semantics/ast_body_visitor.cpp:1622]: Also it MUST be a variable, since it would be present in a loop variable, so you can just cast it.

File: src/lfortran/semantics/ast_body_visitor.cpp [hunk 6]
```diff
@@ -2108,6 +2122,11 @@ class BodyVisitor : public CommonVisitor<BodyVisitor> {
             increment = nullptr;
         }
 
+        if (var && var->type == ASR::exprType::Var) {
```
Comment (certik) [inline src/lfortran/semantics/ast_body_visitor.cpp:2125]: I think it must be a variable, doesn't it?
```suggestion
        if (var) {
```
That way we get an assert failure if it isn't, which signals a bug in our compiler, instead of ignoring it.

**Comment by certik** [comment]
I think this is the right approach, thanks!

I left some comments to simplify / refactor the code.

File: src/lfortran/semantics/ast_body_visitor.cpp (hunk 6 above)
Comment (Pranavchiku) [reply src/lfortran/semantics/ast_body_visitor.cpp:2125]: > I think it must be a variable, doesn't it?

I guess yes, to assure it I kept the condition for `var->type`.

File: src/lfortran/semantics/ast_body_visitor.cpp (hunk 5 above)
Comment (Pranavchiku) [reply src/lfortran/semantics/ast_body_visitor.cpp:1622]: > Also it MUST be a variable, since it would be present in a loop variable, so you can just cast it.

There might be a chance that it is a Var and not present in loop variable hence not (Variable_t) which will cause Internal Compiler Error: Unhandled exception, I came across this in `integration_tests/modules_27_module2.f90` hence keeping the check for variable.

Comment (czgdp1807) [reply src/lfortran/semantics/ast_body_visitor.cpp]: That's true. But can use anything other than a variable in Fortran's do loop? I think if `var` is not `nullptr` then it must be always a `Var` in Fortran. If not then throw a `SemanticError`.

Comment (Pranavchiku) [reply src/lfortran/semantics/ast_body_visitor.cpp]: If I got you correctly, that is why we removed check `var->type == ASR::exprType::Var` from `visit_DoLoop`.

Comment (Pranavchiku) [reply src/lfortran/semantics/ast_body_visitor.cpp]: Aah got it, let me just update it, if it is present in do_loop_variables, then we can directly cast it to `Variable_t` and get `var_name`.

Comment (Pranavchiku) [reply src/lfortran/semantics/ast_body_visitor.cpp]: Done :)

Comment (certik) [reply src/lfortran/semantics/ast_body_visitor.cpp]: The point is that we never want to have branches in the code where we just ignore something. Either give a compiler error, or directly cast it.

**Comment by certik** [comment]
Next time please polish the history or squash it.

**Comment by Pranavchiku** [comment]
Sincere apologies for poor commit history, will take care of it.

**Comment by certik** [comment]
No worries!
