### PR TITLE
semantics: reject non-variable actuals for INTENT(OUT/INOUT) dummies (fixes #4611)

### LINKED ISSUE #4611: bug: subroutine accepts non-variable argument to parameter of `INTENT(INOUT`
### Minimal Reproducible Example

```fortran
PROGRAM main

   IMPLICIT NONE

   CALL sub ( 1 )

CONTAINS

   SUBROUTINE sub ( i )

      INTEGER, INTENT(INOUT) :: i

      PRINT *, i

   END SUBROUTINE sub

END PROGRAM main
```

#### GFortran

```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ gfortran ./examples/example.f90 && ./a.out
./examples/example.f90:5:14:

    5 |    CALL sub ( 1 )
      |              1
Error: Non-variable expression in variable definition context (actual argument to INTENT = OUT/INOUT) at (1)
```

#### LFortran

```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
1
```

### PR DESCRIPTION
**Pull request by krystophny**
Reject non-variable actuals for `INTENT(OUT/INOUT)` dummy arguments.

Semantics
- Use `ASRUtils::is_variable()` to allow assignable entities only.

Test
- `integration_tests/intent_out_nonvariable_01.f90` marked FAIL to ensure compile-time rejection.

### CODE REVIEW

File: src/libasr/asr_utils.h [hunk 1]
```diff
@@ -6458,6 +6458,22 @@ inline void check_simple_intent_mismatch(diag::Diagnostics &diag, ASR::Function_
...
+                if (!ASRUtils::is_variable(passed_arg_expr)) {
+                    diag.add(diag::Diagnostic(
+                        "Non-variable actual argument passed to a dummy argument with INTENT("
+                        + std::string(callee_param->m_intent == ASR::intentType::Out ? "OUT" : "INOUT") + ")",
+                        diag::Level::Error, diag::Stage::Semantic,
+                        { diag::Label("", { passed_arg_expr ? passed_arg_expr->base.loc : f->base.base.loc }) }));
+                    throw SemanticAbort();
+                }
+            }
+        }
```
Comment (certik) [inline src/libasr/asr_utils.h:6524]: Add a test for this error message, per https://github.com/lfortran/lfortran/pull/8509#discussion_r2314427023.

File: integration_tests/CMakeLists.txt [hunk 2]
```diff
@@ -402,6 +402,9 @@ RUN(NAME expr_18 LABELS gfortran llvm llvm_wasm llvm_wasm_emcc wasm c fortran)
 RUN(NAME expr_19 LABELS gfortran llvm llvm_wasm llvm_wasm_emcc wasm c)
 RUN(NAME expr_20 LABELS gfortran llvm llvm_wasm llvm_wasm_emcc wasm c fortran)
 
+# Semantics: reject non-variable actual for INTENT(OUT/INOUT) (issue #4611)
+RUN(NAME intent_out_nonvariable_01 FAIL LABELS gfortran llvm)
```
Comment (certik) [inline integration_tests/CMakeLists.txt]: Move this test for an error message into `tests/errors/continue_compilation_1.f90`.

**Comment by krystophny** [comment]
## Test Consolidation and Verification

I've merged the duplicate tests `intent_out_01.f90` and `intent_out_nonvariable_01.f90` into a single test `intent_04.f90` as they were identical except for the program name.

### Test Status
- The test is properly registered in CMakeLists.txt with the `FAIL` flag
- GFortran correctly rejects the code with: "Non-variable expression in variable definition context (actual argument to INTENT = OUT/INOUT)"
- LFortran currently compiles it without error (which is the bug this PR aims to fix)

### Test Code
```fortran
program intent_04
    implicit none
    call set_to_one(1)
contains
    subroutine set_to_one(x)
        integer, intent(out) :: x
        x = 1
    end subroutine set_to_one
end program
```

This test will ensure that once the fix is implemented, LFortran will properly reject passing non-variable expressions (like literal constants) to subroutine parameters with `intent(out)` or `intent(inout)`.

**Comment by krystophny** [comment]
## Error Test Cases Added

I've also added test cases to `tests/errors/continue_compilation_1.f90` as suggested by certik. The test includes:

### New subroutines added:
```fortran
subroutine intent_out_test(x)
    integer, intent(out) :: x
    x = 42
end subroutine intent_out_test

subroutine intent_inout_test(y)
    integer, intent(inout) :: y
    y = y + 1
end subroutine intent_inout_test
```

### Test calls that should trigger errors:
```fortran
! Test non-variable expressions with intent(out) and intent(inout)
call intent_out_test(1)      ! Error: literal constant with intent(out)
call intent_out_test(x + 1)  ! Error: expression with intent(out)
call intent_inout_test(2)    ! Error: literal constant with intent(inout)
call intent_inout_test(x * 2)! Error: expression with intent(inout)
```

These will produce appropriate semantic errors once the check for non-variable actuals with INTENT(OUT/INOUT) is implemented. The test references have been updated accordingly.

**Comment by krystophny** [comment]
## Implementation Complete ✅

The fix has been implemented and tested successfully. 

### Changes Made:
1. **Modified `check_simple_intent_mismatch()`** in `src/libasr/asr_utils.h` to detect non-variable expressions passed to INTENT(OUT/INOUT) parameters
2. **Added error tests** to `tests/errors/continue_compilation_1.f90` (as suggested by certik)
3. **Removed** the integration test (moved to error tests, not copied)

### Verification:
- ✅ LFortran now correctly rejects literals passed to intent(out) parameters
- ✅ LFortran now correctly rejects expressions passed to intent(out) parameters  
- ✅ LFortran now correctly rejects literals passed to intent(inout) parameters
- ✅ LFortran now correctly rejects expressions passed to intent(inout) parameters

The error message matches GFortran's style:
```
semantic error: Non-variable expression in variable definition context 
(actual argument to INTENT = OUT/INOUT)
```

The implementation is minimal and focused, adding just the necessary check in the existing intent validation function.

File: tests/errors/continue_compilation_1.f90 [hunk 3]
```diff
@@ -329,6 +339,12 @@ program continue_compilation_1
     call logger % add_log_file(filename=filename)
     call logger % add_log_file()
 
+    ! Test non-variable expressions with intent(out) and intent(inout)
+    call intent_out_test(1)  ! Error: literal constant with intent(out)
+    call intent_out_test(x + 1)  ! Error: expression with intent(out)
+    call intent_inout_test(2)  ! Error: literal constant with intent(inout)
+    call intent_inout_test(x * 2)  ! Error: expression with intent(inout)
+
```
Comment (certik) [inline tests/errors/continue_compilation_1.f90]: Put these at the very end of this file, so that the output diff is small.

**Comment by certik** [comment]
You need to update reference results.

**Comment by krystophny** [comment]
> You need to update reference results.

done!

File: tests/errors/continue_compilation_1.f90 [hunk 4]
```diff
@@ -57,6 +57,16 @@ subroutine s(c) bind(c)
...
+    subroutine intent_out_test(x)
+        integer, intent(out) :: x
+        x = 42
+    end subroutine intent_out_test
+
+    subroutine intent_inout_test(y)
+        integer, intent(inout) :: y
+        y = y + 1
+    end subroutine intent_inout_test
+
```
Comment (certik) [inline tests/errors/continue_compilation_1.f90]: You have to follow the instructions in the file: https://github.com/krystophny/lfortran/blob/8c89518fdbdd307a7a7e115dbb7b9bc102a8edf8/tests/errors/continue_compilation_1.f90#L1.

Comment (krystophny) [reply tests/errors/continue_compilation_1.f90]: sorry about that, there are no lines left to remove under the module. what to do? start a new file?

Comment (krystophny) [reply tests/errors/continue_compilation_1.f90]: OK, moved to `tests/errors/continue_compilation_3.f90` now where there was still space.

File: src/libasr/asr_utils.h [hunk 5]
```diff
@@ -6458,6 +6458,73 @@ inline void check_simple_intent_mismatch(diag::Diagnostics &diag, ASR::Function_
...
+                                    ASR::FunctionCall_t* func_call = ASR::down_cast<ASR::FunctionCall_t>(passed_arg_expr);
+                                    if (func_call->m_name) {
+                                        ASR::symbol_t* func_sym = func_call->m_name;
+                                        if (ASR::is_a<ASR::Function_t>(*func_sym)) {
+                                            ASR::Function_t* func = ASR::down_cast<ASR::Function_t>(func_sym);
+                                            std::string func_name = func->m_name;
+                                            // Allow list access functions that return modifiable references
+                                            if (func_name == "_lfortran_get_item") {
+                                                is_valid_variable = true;
+                                            }
```
Comment (certik) [inline src/libasr/asr_utils.h:6501]: We need to figure out what is going on here, as we should not have anything front-end (LFortran) related in libasr like this.

File: src/libasr/asr_utils.h [hunk 6]
```diff
@@ -6458,6 +6458,73 @@ inline void check_simple_intent_mismatch(diag::Diagnostics &diag, ASR::Function_
...
+                                }
+                                default:
+                                    is_valid_variable = false;
+                                    break;
+                            }
+                            
+                            if (!is_valid_variable) {
+                                diag.add(diag::Diagnostic(
+                                    "Non-variable expression in variable definition context "
+                                    "(actual argument to INTENT = OUT/INOUT)",
```
Comment (certik) [inline src/libasr/asr_utils.h:6514]: We use lowercase in error messages.

File: tests/errors/continue_compilation_3.f90 [hunk 7]
```diff
@@ -65,10 +65,10 @@ program continue_compilation_3
...
     integer(8) :: merge_k = 8
 
-
-
-
-
+    call intent_out_test(1)  ! Error: literal constant with intent(out)
+    call intent_out_test(x + 1)  ! Error: expression with intent(out)
+    call intent_inout_test(2)  ! Error: literal constant with intent(inout)
+    call intent_inout_test(x * 2)  ! Error: expression with intent(inout)
```
Comment (certik) [inline tests/errors/continue_compilation_3.f90:71]: Let's also add a check for `intent_out_test((x))`, which makes `x` an expression and so should be rejected. Check with other compilers that that's the case.
