### PR TITLE
check array rank and dimensions before assignment

### LINKED ISSUE #3517: Different shape array assignment shouldn't work
```bash
> cat a.f90
program main
    implicit none
    integer :: arr1(1)
    integer :: arr2(3)

    arr2 = (/1, 2, 3/)
    arr1 = arr2
    print *, arr1
end program

> ./src/bin/lfortran a.f90
1

> gfortran a.f90

    7 |     arr1 = arr2
      |    1
Error: Different shape for array assignment at (1) on dimension 1 (1 and 3)
```

Same happens for when `arr1` has bigger size than `arr2`

### PR DESCRIPTION
**Pull request by gxyd**
Fixes #3517

### CODE REVIEW

**Comment by gxyd** [comment]
I don't fully understand how the below program is valid:
```f90
integer function a(n,m)
implicit real (n)
implicit integer (m)
implicit real*8 (k)
integer :: X(m), Y(m)
n = 5
m = 8
X = [1,2,3,4,5]
end function
```

since we first assign `m` as 8 and then the size of `X` (which when initialized as set to m) is 5. This is a test-case in out test-suite.

**Comment by certik** [comment]
That program is invalid. Needs to be fixed.

**Comment by gxyd** [comment]
The failing test from `pack` (i.e.)
```bash
semantic error: Dimensions not equal
 --> /home/runner/work/lfortran/lfortran/integration_tests/array_01_pack.f90:4:3
  |
4 |   p = pack(m, m /= 0)
  |   ^^^^^^^^^^^^^^^^^^^ 
```

would be there because of an issue in `pack` https://github.com/lfortran/lfortran/issues/3155#issuecomment-1960063872

**Comment by gxyd** [comment]
I will put in some more work on this, before someone can review this.

**Comment by gxyd** [comment]
Currently the failing test is:
```
semantic error: Different shape for array assignment on dimension 1(5 and 2)
  --> /home/runner/work/lfortran/lfortran/integration_tests/intrinsics_51.f90:29:1
   |
29 | cr = sin([[1., 2., 3.], [4., 5.]])
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
```

as `cr` is already declared to be of size '5', while we currently don't return `sin([[1., 2., 3.], [4., 5.]])` of size '5' (It's a separate bug I believe). I guess this MR has nothing wrong on that part.

**Comment by gxyd** [comment]
This is ready for a review now, let me know how to handle the failing test (if you have any opinion on that).

File: integration_tests/valid_array_assignment_same_length_different_start.f90 [hunk 1]
```diff
@@ -0,0 +1,13 @@
+program valid_array_assignment_same_length_different_start
+    ! array with size 3 and start index 2
+    integer :: arr1(2:4)
+    ! array with size 3 and start index 1
+    integer :: arr2(1:3)
+    arr1 = (/1, 2, 3/)
```
Comment (certik) [inline integration_tests/valid_array_assignment_same_length_different_start.f90:6]:
```suggestion
    arr1 = [1, 2, 3]
```

File: tests/errors/incompatible_dimension_assignment_arr1.f90 [hunk 2]
```diff
@@ -0,0 +1,8 @@
+program incompatible_ranks_allocatable_arr2
+    implicit none
+    ! constant array of size 1
+    integer :: arr1(1)
+    ! arr1 (which is of size 1) is being assigned
+    ! an array of size 3
+    arr1 = (/1, 2, 3/)
```
Comment (certik) [inline tests/errors/incompatible_dimension_assignment_arr1.f90:7]:
```suggestion
    arr1 = [1, 2, 3]
```

File: tests/errors/incompatible_ranks_allocatable_arr1.f90 [hunk 3]
```diff
@@ -0,0 +1,9 @@
+program incompatible_ranks_allocatable_arr1
+    implicit none
+    ! allocatable array of rank 2
+    integer, allocatable :: arr1(:, :)
+
+    ! RHS is a constant array of rank 1
+    ! incompatible assignment
+    arr1 = (/1, 2, 3/)
```
Comment (certik) [inline tests/errors/incompatible_ranks_allocatable_arr1.f90:8]:
```suggestion
    arr1 = [1, 2, 3]
```

**Comment by certik** [comment]
If your PR uncovered a bug, then comment out the failing lines in tests, and ensure everything passes.

Then we'll decide what to do next.

File: integration_tests/valid_array_assignment_same_length_different_start.f90 (hunk 1 above)
Comment (gxyd) [reply integration_tests/valid_array_assignment_same_length_different_start.f90]: Ah, so it seems like `[1, 2, 3` is a more modern syntax for arrays followed by Fortran.

**Comment by gxyd** [comment]
I've commented out the failing test (which needs a change). Could you please help me understand the failing test?

**Comment by certik** [comment]
The Windows error is real:
```console
D:\a\lfortran\lfortran\lfortran-0.33.1-532-gccc42db11\src\lfortran\semantics\ast_body_visitor.cpp(2273): error C2146: syntax error: missing ')' before identifier 'and'
D:\a\lfortran\lfortran\lfortran-0.33.1-532-gccc42db11\src\lfortran\semantics\ast_body_visitor.cpp(2273): error C2065: 'and': undeclared identifier
D:\a\lfortran\lfortran\lfortran-0.33.1-532-gccc42db11\src\lfortran\semantics\ast_body_visitor.cpp(2273): error C2146: syntax error: missing ';' before identifier 'dim_b_int'
D:\a\lfortran\lfortran\lfortran-0.33.1-532-gccc42db11\src\lfortran\semantics\ast_body_visitor.cpp(2273): error C2059: syntax error: ')'
```

File: src/lfortran/semantics/ast_body_visitor.cpp [hunk 4]
```diff
@@ -2226,6 +2226,61 @@ class BodyVisitor : public CommonVisitor<BodyVisitor> {
...
+                    int dim_a_int {-1};
+                    int dim_b_int {-1};
+                    // 'm_length' isn't assigned for allocatable arrays
+                    // let them be valid for now atleast
+                    if (!(dim_a.m_length && dim_b.m_length)) {
+                        continue;
+                    }
+                    ASRUtils::extract_value(ASRUtils::expr_value(dim_a.m_length), dim_a_int);
+                    ASRUtils::extract_value(ASRUtils::expr_value(dim_b.m_length), dim_b_int);
+                    if (dim_a_int > 0 and dim_b_int > 0 && dim_a_int != dim_b_int) {
```
Comment (certik) [inline src/lfortran/semantics/ast_body_visitor.cpp:2273]: To fix the Windows error:
```suggestion
                    if (dim_a_int > 0 && dim_b_int > 0 && dim_a_int != dim_b_int) {
```

File: integration_tests/intrinsics_51.f90 [hunk 5]
```diff
@@ -25,12 +25,12 @@ program intrinsics_51
...
-print *, "cr: ", cr
-do i = lbound(cr, 1), ubound(cr, 1)
-    if( abs(cr(i) - sin(real(i))) > 1e-6 ) error stop
-end do
+!print *, [[1., 2., 3.], [4., 5.]]
+!cr = sin([[1., 2., 3.], [4., 5.]])
+!print *, "cr: ", cr
+!do i = lbound(cr, 1), ubound(cr, 1)
+!    if( abs(cr(i) - sin(real(i))) > 1e-6 ) error stop
+!end do
```
Comment (certik) [inline integration_tests/intrinsics_51.f90:33]: @Pranavchiku can you please have a look at this test and see why it fails? There might be a bug.

Comment (Pranavchiku) [reply integration_tests/intrinsics_51.f90:33]: MRE:

```fortran
program intrinsics_51
    implicit none
    real :: cr(5)
    
    cr = sin([[1., 2., 3.], [4., 5.]])
    print *, "cr: ", cr
end program
```

```console
% lfortran b.f90 --show-stacktrace
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2391
    LCompilers::print_stack_on_segfault();
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2355
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 907
    result = fe.get_asr2(input, lm, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 253
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 275
    compiler_options.symtab_only, compiler_options);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 127
    if (res.ok) {
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 3445
    b.is_body_visitor = true;
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 143
    visit_ast(*x.m_items[i]);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4848
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4804
    case astType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4851
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4438
    case modType::BlockData: { v.visit_BlockData((const BlockData_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1510
    transform_stmts(body, x.n_body, x.m_body);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 114
    this->visit_stmt(*m_body[i]);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4894
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4540
    case stmtType::Assign: { v.visit_Assign((const Assign_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 2385
    check_ArrayAssignmentCompatibility(target, value, x);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 2277
    std::to_string(dim_b_int) + ")", x.base.base.loc);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/semantic_exception.h", line 20
    { }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/semantic_exception.h", line 17
    : d{diag::Diagnostic(msg, diag::Level::Error, diag::Stage::Semantic, {
semantic error: Different shape for array assignment on dimension 1(5 and 2)
 --> b.f90:5:5
  |
5 |     cr = sin([[1., 2., 3.], [4., 5.]])
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 


Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

Comment (certik) [reply integration_tests/intrinsics_51.f90:33]: Yes, but the issue is that the RHS should be length 5, not 2. I think this is the case in master as well. So that's the bug.

Comment (Pranavchiku) [reply integration_tests/intrinsics_51.f90:33]:
```
(IntrinsicScalarFunction
                            Sin
                            [(ArrayPhysicalCast
                                (ArrayConstant
                                    [(ArrayConstant
                                        [(RealConstant
                                            1.000000
                                            (Real 4)
                                        )
                                        (RealConstant
                                            2.000000
                                            (Real 4)
                                        )
                                        (RealConstant
                                            3.000000
                                            (Real 4)
                                        )]
                                        (Array
                                            (Real 4)
                                            [((IntegerConstant 1 (Integer 4))
                                            (IntegerConstant 3 (Integer 4)))]
                                            FixedSizeArray
                                        )
                                        ColMajor
                                    )
                                    (ArrayConstant
                                        [(RealConstant
                                            4.000000
                                            (Real 4)
                                        )
                                        (RealConstant
                                            5.000000
                                            (Real 4)
                                        )]
                                        (Array
                                            (Real 4)
                                            [((IntegerConstant 1 (Integer 4))
                                            (IntegerConstant 2 (Integer 4)))]
                                            FixedSizeArray
                                        )
                                        ColMajor
                                    )]
                                    (Array
                                        (Real 4)
                                        [((IntegerConstant 1 (Integer 4))
                                        (IntegerConstant 2 (Integer 4)))]
                                        FixedSizeArray
                                    )
                                    ColMajor
                                )
                                FixedSizeArray
                                DescriptorArray
                                (Array
                                    (Real 4)
                                    [((IntegerConstant 1 (Integer 4))
                                    (IntegerConstant 2 (Integer 4)))]
                                    DescriptorArray
                                )
                                ()
                            )]
                            0
                            (Array
                                (Real 4)
                                [((IntegerConstant 1 (Integer 4))
                                (IntegerConstant 2 (Integer 4)))]
                                FixedSizeArray
                            )
                            () --------------------------------------> This should have value, but it does not have
                        )
```

I faced the same in #3485.

Comment (Pranavchiku) [reply integration_tests/intrinsics_51.f90:33]: The trouble is `eval_Sin` is not functioning properly. It should evaluate `cr = sin([[1., 2., 3.], [4., 5.]])` the RHS but is not doing.

Comment (Pranavchiku) [reply integration_tests/intrinsics_51.f90:33]: Opened #3559, will resolve it soon.

Comment (certik) [reply integration_tests/intrinsics_51.f90:33]: Awesome, thanks @Pranavchiku !

Comment (gxyd) [reply integration_tests/intrinsics_51.f90:33]: Yes, I understood the bug, I have been (if possible) looking to make a change to the test case functionality, so that this MR can move forward without necessarily needing the bug to be fixed.

Comment (certik) [reply integration_tests/intrinsics_51.f90:33]: Can you change it to something like:
```
a = [[1., 2., 3.], [4., 5.]]
!print *, a
!cr = sin(a)
```
As well as
```
cr = sin([1., 2., 3., 4., 5.])
```
That will test both compile time and runtime and hopefully it works.

Comment (Pranavchiku) [reply integration_tests/intrinsics_51.f90:33]: @gxyd to make tests pass you just have to skip if value is an IntrinsicElementalFunction or IntrinsicArrayFunction and add a TODO to remove this later

Comment (gxyd) [reply integration_tests/intrinsics_51.f90:33]: Seems like there is another issue:
```bash
> cat b.f90
program main
    implicit none
    print *, "rank is:", rank([[1., 2., 3.], [4., 5.]])
    print *, "shape is:", shape([[1., 2., 3.], [4., 5.]])
end program

> lfortran b.f90
rank is: 1
shape is: 2 

> gfortran b.f90 -o b.out && ./b.out
 rank is:           1
 shape is:           5
```

Comment (gxyd) [reply integration_tests/intrinsics_51.f90:33]: I can't look into the issue in detail right now, but I'll once I get my monitor back on Saturday (my eyes aren't liking it right now).

**Comment by gxyd** [comment]
I don't understand this new CI error, it's origination from stdlib, I don't understand how stdlib is used in LFortran repo.

**Comment by certik** [comment]
The CI downloads stdlib and compiles it. It fails. It means your new checks uncovered some issues there, that are not caught by our integration tests. We need to understand the issue and write a dedicated integration test for it, and fix it. We can also report it as an issue (to fix later) and workaround the problem in stdlib.

**Comment by gxyd** [comment]
> It means your new checks uncovered some issues there

"there" as in "within stdlib"?

**Comment by certik** [comment]
Since stdlib compiles with gfortran, the bug is not in stdlib, it's a bug in LFortran, that is either introduced by this PR, or it has always been in LFortran and only uncovered by this PR's stricter checks.

**Comment by gxyd** [comment]
I see the stacktrace to have

```bash
semantic error: Different shape for array assignment on dimension 1(4 and 16)
   --> /home/runner/work/lfortran/lfortran/stdlib/test/linalg/test_linalg.f90:267:9
    |
267 |         c = pack(a, mask)
    |         ^^^^^^^^^^^^^^^^^ 

```

which repository contains the file: "test_linalg"? I don't see it on our repo, nor in stdlib.

This PR highlighted (was already known) the issue with `pack` (as seen in one of the modified integration tests), probably could be similar here.

**Comment by certik** [comment]
See here, which sets up the stdlib at the CI. You can follow the same steps to reproduce this locally:

https://github.com/lfortran/lfortran/blob/a9e968bfa290b7a0d901c13591992ea5169689ca/.github/workflows/CI.yml#L646

There is a link to check out the exact git repository and branch and a hash.

**Comment by Pranavchiku** [comment]
If `pack` is a blocker, let me know, I'll try to remove the TODO, but that will need to have intrinsic `count` ( https://gcc.gnu.org/onlinedocs/gfortran/COUNT.html ).

**Comment by certik** [comment]
We can workaround this in stdlib for now, and open up an issue for pack and reference it from there. I think that would be fine.

**Comment by Pranavchiku** [comment]
I am working on implementation of `count`, will be done by EOD. Then it will be a small change in `pack` intrinsic.

**Comment by Pranavchiku** [comment]
I have fix for pack almost ready, there are a few cases that fail, will get it done by tomorrow. I am sorry for making you wait to merge this PR.

**Comment by gxyd** [comment]
> I am sorry for making you wait to merge this PR.

Don't worry about that. I'm glad that we are doing things the right way.

**Comment by Pranavchiku** [comment]
I have made progress on it, will open PR soon.

**Comment by Pranavchiku** [comment]
With #3605, for `p = pack(m, m/=0)`, node looks like:

```
                    (Assignment
                        (Var 2 p)
                        (IntrinsicArrayFunction
                            Pack
                            [(ArrayPhysicalCast
                                (Var 2 m)
                                FixedSizeArray
                                DescriptorArray
                                (Array
                                    (Integer 4)
                                    [((IntegerConstant 1 (Integer 4))
                                    (IntegerConstant 6 (Integer 4)))]
                                    DescriptorArray
                                )
                                ()
                            )
                            (ArrayPhysicalCast
                                (IntegerCompare
                                    (Var 2 m)
                                    NotEq
                                    (IntegerConstant 0 (Integer 4))
                                    (Array
                                        (Logical 4)
                                        [((IntegerConstant 1 (Integer 4))
                                        (IntegerConstant 6 (Integer 4)))]
                                        FixedSizeArray
                                    )
                                    ()
                                )
                                FixedSizeArray
                                DescriptorArray
                                (Array
                                    (Logical 4)
                                    [((IntegerConstant 1 (Integer 4))
                                    (IntegerConstant 6 (Integer 4)))]
                                    DescriptorArray
                                )
                                ()
                            )]
                            2
                            (Array
                                (Integer 4)
                                [((IntegerConstant 1 (Integer 4))
                                (IntrinsicArrayFunction
                                    Count
                                    [(ArrayPhysicalCast
                                        (IntegerCompare
                                            (Var 2 m)
                                            NotEq
                                            (IntegerConstant 0 (Integer 4))
                                            (Array
                                                (Logical 4)
                                                [((IntegerConstant 1 (Integer 4))
                                                (IntegerConstant 6 (Integer 4)))]
                                                FixedSizeArray
                                            )
                                            ()
                                        )
                                        FixedSizeArray
                                        DescriptorArray
                                        (Array
                                            (Logical 4)
                                            [((IntegerConstant 1 (Integer 4))
                                            (IntegerConstant 6 (Integer 4)))]
                                            DescriptorArray
                                        )
                                        ()
                                    )]
                                    0
                                    (Integer 4)
                                    ()
                                ))]
                                DescriptorArray
                            )
                            ()
                        )
                        ()
                    )
```

**Comment by Pranavchiku** [comment]
@gxyd it is merged, I am sorry for delaying this PR. You may rebase it as instructed at #3589 and see if CI works now.

File: src/lfortran/semantics/ast_body_visitor.cpp [hunk 6]
```diff
@@ -2226,6 +2226,63 @@ class BodyVisitor : public CommonVisitor<BodyVisitor> {
...
+     * - they have the same rank and
+     * - (if applicable) dimensions.
+     * and throws a semantic error if otherwise
+     */
+    void check_ArrayAssignmentCompatibility(ASR::expr_t* target, ASR::expr_t* value, const AST::Assignment_t &x) {
+        ASR::ttype_t *target_type = ASRUtils::type_get_past_allocatable(ASRUtils::expr_type(target));
+        ASR::ttype_t *value_type = ASRUtils::type_get_past_allocatable(ASRUtils::expr_type(value));
+        // we don't want to check by "check_equal_type" because we want to allow
+        // real :: x(4); x = [1, 2, 3, 4] to be a valid assignment (as RHS is "integer array")
+        // TODO: the only reason to not do this check for "reshape" is because
```
Comment (gxyd) [inline src/lfortran/semantics/ast_body_visitor.cpp:2242]: I would like to maybe figure out how to fix this error in another issue, I see there are few open issues for "reshape", but I definitely think that this should  be made to work.

**Review by certik — APPROVED** [review]
I think this looks good to merge.
