### PR TITLE
fix: check if a `Var_t` expression is a `Variable_t` before down casting

### LINKED ISSUE #4202: bug: when checking for loop variables in an implied do loop, check if a `Var_t` expression is a `Variable_t` before down casting
### Minimum Reproducible Example

```fortran
MODULE solvar_module
   REAL, DIMENSION(10) :: fixup_counter
END MODULE

PROGRAM test
   USE solvar_module
   IMPLICIT NONE

   INTEGER :: n

   PRINT *, (fixup_counter(n),n=1,4)
END PROGRAM test
```
### Output
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 360, in __libc_start_main_impl()
  File "./csu/../sysdeps/x86/libc-start.c", line 58, in __libc_start_call_main()
  File "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran.cpp", line 2481, in main()
    return main_app(argc, argv);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran.cpp", line 2442, in main_app(int, char**)
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran.cpp", line 912, in compile_to_object_file()
    result = fe.get_asr2(input, lm, diagnostics);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/fortran_evaluator.cpp", line 256, in LCompilers::FortranEvaluator::get_asr2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::diag::Diagnostics&)
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/fortran_evaluator.cpp", line 278, in LCompilers::FortranEvaluator::get_asr3(LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&)
    compiler_options.symtab_only, compiler_options);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 106, in LCompilers::LFortran::ast_to_asr(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::SymbolTable*, bool, LCompilers::CompilerOptions&)
    instantiate_types, instantiate_symbols, entry_functions, entry_function_arguments_mapping, data_structure);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 3729, in LCompilers::LFortran::body_visitor(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::ASR::asr_t*, LCompilers::CompilerOptions&, std::map<unsigned long, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > > > > >&, std::map<unsigned long, LCompilers::ASR::symbol_t*, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, LCompilers::ASR::symbol_t*> > >&, std::map<unsigned long, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >&, std::map<unsigned int, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > > > > >&, std::map<unsigned int, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::symbol_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::symbol_t*> > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::symbol_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::symbol_t*> > > > > >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> > > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> > > > > > > >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<int, std::allocator<int> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<int, std::allocator<int> > > > >&, std::vector<LCompilers::ASR::stmt_t*, std::allocator<LCompilers::ASR::stmt_t*> >&)
    b.visit_TranslationUnit(ast);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 144, in LCompilers::LFortran::BodyVisitor::visit_TranslationUnit(LCompilers::LFortran::AST::TranslationUnit_t const&)
    visit_ast(*x.m_items[i]);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/ast.h", line 4878, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_ast(LCompilers::LFortran::AST::ast_t const&)
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/ast.h", line 4835, in visit_ast_t<LCompilers::LFortran::BodyVisitor>()
    case astType::mod: { v.visit_mod((const mod_t &)x); return; }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/ast.h", line 4881, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_mod(LCompilers::LFortran::AST::mod_t const&)
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/ast.h", line 4468, in visit_mod_t<LCompilers::LFortran::BodyVisitor>()
    case modType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1569, in LCompilers::LFortran::BodyVisitor::visit_Program(LCompilers::LFortran::AST::Program_t const&)
    transform_stmts(body, x.n_body, x.m_body);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 115, in LCompilers::LFortran::BodyVisitor::transform_stmts(LCompilers::Vec<LCompilers::ASR::stmt_t*>&, unsigned long, LCompilers::LFortran::AST::stmt_t**)
    this->visit_stmt(*m_body[i]);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/ast.h", line 4924, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_stmt(LCompilers::LFortran::AST::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/ast.h", line 4595, in visit_stmt_t<LCompilers::LFortran::BodyVisitor>()
    case stmtType::Print: { v.visit_Print((const Print_t &)x); return; }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 3088, in LCompilers::LFortran::BodyVisitor::visit_Print(LCompilers::LFortran::AST::Print_t const&)
    visit_expr(*x.m_values[i]);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/ast.h", line 4976, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_expr(LCompilers::LFortran::AST::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/ast.h", line 4636, in visit_expr_t<LCompilers::LFortran::BodyVisitor>()
    case exprType::ImpliedDoLoop: { v.visit_ImpliedDoLoop((const ImpliedDoLoop_t &)x); return; }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 6260, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::visit_ImpliedDoLoop(LCompilers::LFortran::AST::ImpliedDoLoop_t const&)
    bool is_compiletime = is_compiletime_implied_do_loop(idl, loop_vars);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 5964, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::is_compiletime_implied_do_loop(LCompilers::ASR::ImpliedDoLoop_t*, std::vector<LCompilers::ASR::symbol_t*, std::allocator<LCompilers::ASR::symbol_t*> >&)
    if (!contains_loop_vars(expr, loop_vars)) {
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 5944, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::contains_loop_vars(LCompilers::ASR::expr_t*, std::vector<LCompilers::ASR::symbol_t*, std::allocator<LCompilers::ASR::symbol_t*> >&)
    visitor.visit_expr(*expr);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/asr.h", line 5218, in LCompilers::ASR::BaseVisitor<LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::contains_loop_vars(LCompilers::ASR::expr_t*, std::vector<LCompilers::ASR::symbol_t*, std::allocator<LCompilers::ASR::symbol_t*> >&)::ImpliedDoLoopValuesVisitor>::visit_expr(LCompilers::ASR::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/asr.h", line 5007, in visit_expr_t<LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::contains_loop_vars(LCompilers::ASR::expr_t*, std::vector<LCompilers::ASR::symbol_t*, std::allocator<LCompilers::ASR::symbol_t*> >&)::ImpliedDoLoopValuesVisitor>()
    case exprType::ArrayItem: { v.visit_ArrayItem((const ArrayItem_t &)x); return; }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/asr.h", line 6274, in LCompilers::ASR::BaseWalkVisitor<LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::contains_loop_vars(LCompilers::ASR::expr_t*, std::vector<LCompilers::ASR::symbol_t*, std::allocator<LCompilers::ASR::symbol_t*> >&)::ImpliedDoLoopValuesVisitor>::visit_ArrayItem(LCompilers::ASR::ArrayItem_t const&)
    self().visit_expr(*x.m_v);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/asr.h", line 5218, in LCompilers::ASR::BaseVisitor<LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::contains_loop_vars(LCompilers::ASR::expr_t*, std::vector<LCompilers::ASR::symbol_t*, std::allocator<LCompilers::ASR::symbol_t*> >&)::ImpliedDoLoopValuesVisitor>::visit_expr(LCompilers::ASR::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/asr.h", line 5003, in visit_expr_t<LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::contains_loop_vars(LCompilers::ASR::expr_t*, std::vector<LCompilers::ASR::symbol_t*, std::allocator<LCompilers::ASR::symbol_t*> >&)::ImpliedDoLoopValuesVisitor>()
    case exprType::Var: { v.visit_Var((const Var_t &)x); return; }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 5910, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::contains_loop_vars(LCompilers::ASR::expr_t*, std::vector<LCompilers::ASR::symbol_t*, std::allocator<LCompilers::ASR::symbol_t*> >&)::ImpliedDoLoopValuesVisitor::visit_Var(LCompilers::ASR::Var_t const&)
    ASR::Variable_t* var = ASR::down_cast<ASR::Variable_t>(sym);
AssertFailed: is_a<T>(*f)
```

This bug was caught when compiling file `inner.f90` of the SNAP package.

### PR DESCRIPTION
**Pull request by kmr-srbh**
fixes #4202 

```fortran
MODULE solvar_module
   REAL, DIMENSION(10) :: fixup_counter
END MODULE

PROGRAM test
   USE solvar_module
   IMPLICIT NONE

   INTEGER :: n

   PRINT *, (fixup_counter(n),n=1,4)
END PROGRAM test
```
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00 
```

### CODE REVIEW

**Comment by kmr-srbh** [comment]
With the known issues commented out, we are now able to completely compile SNAP, but do not get the message " Aww SNAP. Program failed. Try again." to print to stdout. I think we are near completion?

```console
(base) saurabh-kumar@Awadh:~/Projects/Packages/SNAP/src$ make
lfortran  -c global.f90
lfortran  -c sn.f90
lfortran  -c data.f90
lfortran  -c geom.f90
lfortran  -c control.f90
cpp -P  time.0.F90 >time.f90
lfortran  -c time.f90
warning: Assuming implicit save attribute for variable declaration
  --> time.f90:60:25
   |
60 |     CHARACTER(LEN=1) :: star='*'
   |                         ^^^^^^^^ help: add explicit save attribute or initialize in a separate statement


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
cpp -P  plib.0.F90 >plib.f90
lfortran  -c plib.f90
lfortran  -c mms.f90
warning: Assuming implicit save attribute for variable declaration
   --> mms.f90:522:25
    |
522 |     CHARACTER(LEN=1) :: star='*'
    |                         ^^^^^^^^ help: add explicit save attribute or initialize in a separate statement


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
lfortran  -c solvar.f90
lfortran  -c dealloc.f90
lfortran  -c utils.f90
warning: Argument `access` isn't supported yet
   --> utils.f90:123:5 - 124:39
    |
123 |        OPEN( UNIT=funit, FILE=tname, STATUS=fstat, ACCESS='SEQUENTIAL',   &
    |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
...
    |
124 |              ACTION=faction, IOSTAT=ierr )
    | ...^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ignored for now

warning: Argument `action` isn't supported yet
   --> utils.f90:123:5 - 124:39
    |
123 |        OPEN( UNIT=funit, FILE=tname, STATUS=fstat, ACCESS='SEQUENTIAL',   &
    |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
...
    |
124 |              ACTION=faction, IOSTAT=ierr )
    | ...^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ignored for now

warning: Argument `iostat` isn't supported yet
   --> utils.f90:123:5 - 124:39
    |
123 |        OPEN( UNIT=funit, FILE=tname, STATUS=fstat, ACCESS='SEQUENTIAL',   &
    |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
...
    |
124 |              ACTION=faction, IOSTAT=ierr )
    | ...^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ignored for now


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
lfortran  -c version.f90
lfortran  -c input.f90
warning: Assuming implicit save attribute for variable declaration
   --> input.f90:120:25
    |
120 |     CHARACTER(LEN=1) :: star='*'
    |                         ^^^^^^^^ help: add explicit save attribute or initialize in a separate statement


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
lfortran  -c setup.f90
warning: Assuming implicit save attribute for variable declaration
   --> setup.f90:751:25
    |
751 |     CHARACTER(LEN=1) :: star='*'
    |                         ^^^^^^^^ help: add explicit save attribute or initialize in a separate statement

warning: Assuming implicit save attribute for variable declaration
   --> setup.f90:916:26
    |
916 |     CHARACTER(LEN=16) :: fn='slgg'
    |                          ^^^^^^^^^ help: add explicit save attribute or initialize in a separate statement

warning: Assuming implicit save attribute for variable declaration
   --> setup.f90:918:37
    |
918 |     INTEGER(i_knd) :: l, g1, g2, n, fu=15
    |                                     ^^^^^ help: add explicit save attribute or initialize in a separate statement


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
lfortran  -c output.f90
warning: Assuming implicit save attribute for variable declaration
  --> output.f90:54:25
   |
54 |     CHARACTER(LEN=1) :: star='*'
   |                         ^^^^^^^^ help: add explicit save attribute or initialize in a separate statement

warning: Assuming implicit save attribute for variable declaration
   --> output.f90:259:26
    |
259 |     CHARACTER(LEN=16) :: fn='flux'
    |                          ^^^^^^^^^ help: add explicit save attribute or initialize in a separate statement

warning: Assuming implicit save attribute for variable declaration
   --> output.f90:263:44
    |
263 |     INTEGER(i_knd) :: i, j, k, g, l, ierr, fu=16, mtag, jp, jlb, jub,  &
    |                                            ^^^^^ help: add explicit save attribute or initialize in a separate statement


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
lfortran  -c snap_main.f90
lfortran  -c expxs.f90
lfortran  -c thrd_comm.f90
lfortran  -c dim1_sweep.f90
lfortran  -c dim3_sweep.f90
lfortran  -c mkba_sweep.f90
lfortran  -c octsweep.f90
lfortran  -c sweep.f90
warning: Assuming implicit save attribute for variable declaration
  --> sweep.f90:67:7
   |
67 |       dummy(2)=(/0, 0/)
   |       ^^^^^^^^^^^^^^^^^ help: add explicit save attribute or initialize in a separate statement


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
lfortran  -c inner.f90
lfortran  -c outer.f90
lfortran  -c analyze.f90
lfortran  -c translv.f90
warning: Assuming implicit save attribute for variable declaration
  --> translv.f90:55:23
   |
55 |   CHARACTER(LEN=1) :: star='*'
   |                       ^^^^^^^^ help: add explicit save attribute or initialize in a separate statement


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
lfortran   -o gsnap global.o snap_main.o utils.o version.o plib.o geom.o sn.o data.o control.o input.o setup.o dealloc.o translv.o solvar.o outer.o expxs.o inner.o sweep.o octsweep.o dim1_sweep.o dim3_sweep.o output.o time.o mms.o analyze.o thrd_comm.o mkba_sweep.o
(base) saurabh-kumar@Awadh:~/Projects/Packages/SNAP/src$ ./gsnap
(base) saurabh-kumar@Awadh:~/Projects/Packages/SNAP/src$ 
```

**Comment by kmr-srbh** [comment]
I feel there might be some more issues due to the commented out code. We need to fix the left-over issues to have a look again.

**Comment by certik** [comment]
Add a test for this fix.

Great job!

Roughly speaking, here are the steps:

1. Parse everything to AST
2. Raise everything to ASR with workarounds
3. Lower everything to LLVM with workarounds
4. Compile all LLVM to machine code, link everything, with workaorunds
5. Make it run currently (with workarounds), side by side with GFortran, first on some small subset, then expand the subset to the usable size that we decide we want to support (for SNAP it should run some examples, ideally all, without MPI)
6. Remove as many workarounds as we can

It looks like you finished 4. That's a big deal, thank you!

Now we need to work on 5. That might take several weeks as well, but once it runs well, the we are very close. The 6. is the last step, we have well defined issues that we just have to fix, and remove as many workarounds as we can.

File: src/lfortran/semantics/ast_common_visitor.h [hunk 1]
```diff
@@ -5906,8 +5906,10 @@ class CommonVisitor : public AST::BaseVisitor<Derived> {
                     contain_loop_vars &= true;
                     return;
                 }
-                ASR::Variable_t* var = ASR::down_cast<ASR::Variable_t>(sym);
-                contain_loop_vars &= ASRUtils::is_value_constant(var->m_value);
+                if (ASR::is_a<ASR::Variable_t>(*sym)) {
+                    ASR::Variable_t* var = ASR::down_cast<ASR::Variable_t>(sym);
+                    contain_loop_vars &= ASRUtils::is_value_constant(var->m_value);
+                }
```
Comment (Pranavchiku) [inline src/lfortran/semantics/ast_common_visitor.h:5912]: What will it be if not a `Variable`? Like what it is in this case?

Comment (Pranavchiku) [reply src/lfortran/semantics/ast_common_visitor.h:5912]: Check it will be an `ExternalSymbol`, if that is the case you need to somehow `symbol_get_past_external` and then this won't be correct fix.

**Review by Pranavchiku — CHANGES_REQUESTED** [review]
left question and comment above

File: src/lfortran/semantics/ast_common_visitor.h (hunk 1 above)
Comment (kmr-srbh) [reply src/lfortran/semantics/ast_common_visitor.h:5912]: You are right. We can do `symbol_get_past_external` as stated by you.

**Comment by certik** [comment]
Let's add a test that fails in master, but works in this PR.

**Review by Pranavchiku — CHANGES_REQUESTED** [review]
changes look good to me, I'll wait for a test before approving. Always remember to add a test preferably an integration test in PR that is fixed with the patch you submitted.

File: integration_tests/implied_do_loops5.f90 [hunk 2]
```diff
@@ -0,0 +1,12 @@
...
+   INTEGER, DIMENSION(10) :: fixup_counter
+END MODULE implied_do_loops5
+
+PROGRAM test
+   USE implied_do_loops5
+   IMPLICIT NONE
+
+   INTEGER :: n
+
+   PRINT *, (fixup_counter(n) + n, n=1, 4)
```
Comment (Pranavchiku) [inline integration_tests/implied_do_loops5.f90:11]: please add `if() error stop` condition to test actual value.

**Review by Pranavchiku — CHANGES_REQUESTED** [review]
minor comment.

**Review by certik — APPROVED** [review]
I think this looks good now.

File: src/lfortran/semantics/ast_common_visitor.h [hunk 3]
```diff
@@ -6017,7 +6018,8 @@ class CommonVisitor : public AST::BaseVisitor<Derived> {
                 // check if loop_var_index is valid
                 if (loop_var_index >= (int) loop_vars.size()) {
                     // this is compiletime value
-                    ASR::Variable_t* var = ASR::down_cast<ASR::Variable_t>(x.m_v);
+                    ASR::Variable_t* var = ASR::down_cast<ASR::Variable_t>(
+                                                ASRUtils::symbol_get_past_external(x.m_v));
```
Comment (certik) [inline src/lfortran/semantics/ast_common_visitor.h:6022]: I think this part is not tested, correct? Does the correspond to `n` being in the other module?

File: integration_tests/implied_do_loops5.f90 (hunk 2 above)
Comment (kmr-srbh) [reply integration_tests/implied_do_loops5.f90:11]: I saw that none of the other implied do loop tests have this.

File: src/lfortran/semantics/ast_common_visitor.h (hunk 3 above)
Comment (Pranavchiku) [reply src/lfortran/semantics/ast_common_visitor.h:6022]: > Does the correspond to `n` being in the other module?

yes

Comment (kmr-srbh) [reply src/lfortran/semantics/ast_common_visitor.h:6022]: I am adding a test case for this. Moving `n` to the module, works. Is that right?

Comment (certik) [reply src/lfortran/semantics/ast_common_visitor.h:6022]: I think so.

File: integration_tests/implied_do_loops5.f90 (hunk 2 above)
Comment (certik) [reply integration_tests/implied_do_loops5.f90:11]: You can print it like this, and then assign it to an array, and test the result in the array. It's good to do, then the test is robust.

File: integration_tests/implied_do_loops5.f90 [hunk 4]
```diff
@@ -1,12 +1,16 @@
...
    INTEGER :: n
 END MODULE implied_do_loops5
 
 PROGRAM test
    USE implied_do_loops5
    IMPLICIT NONE
+   INTEGER, DIMENSION(5) :: result_array
 
+   PRINT *, (fixup_counter(n) + n, n = 1, 5)
+   result_array = (/ (fixup_counter(n) + n, n = 1, 5) /)
```
Comment (Pranavchiku) [inline integration_tests/implied_do_loops5.f90:12]:
```suggestion
   result_array = [(fixup_counter(n) + n, n = 1, 5)]
```

File: integration_tests/implied_do_loops5.f90 [hunk 5]
```diff
@@ -0,0 +1,16 @@
+MODULE implied_do_loops5
+   INTEGER, DIMENSION(5) :: fixup_counter
+   INTEGER :: n
+END MODULE implied_do_loops5
+
+PROGRAM test
+   USE implied_do_loops5
```
Comment (Pranavchiku) [inline integration_tests/implied_do_loops5.f90:7]:
```suggestion
MODULE module_implied_do_loops5
   INTEGER, DIMENSION(5) :: fixup_counter
   INTEGER :: n
END MODULE implied_do_loops5

PROGRAM implied_do_loops5
   USE module_implied_do_loops5
```

File: integration_tests/implied_do_loops5.f90 [hunk 6]
```diff
@@ -0,0 +1,16 @@
...
+   IMPLICIT NONE
+   INTEGER, DIMENSION(5) :: result_array
+
+   PRINT *, (fixup_counter(n) + n, n = 1, 5)
+   result_array = [(fixup_counter(n) + n, n = 1, 5)]
+
+   if (all(result_array /= [1, 2, 3, 4, 5])) ERROR STOP
+
+END PROGRAM test
```
Comment (Pranavchiku) [inline integration_tests/implied_do_loops5.f90:16]:
```suggestion
END PROGRAM implied_do_loops5
```

**Review by Pranavchiku — APPROVED** [review]
