### PR TITLE
Fix : Check open and FileWrite format match

### LINKED ISSUE #8989: Handle `filewrite` where format is not provided
MRE:
```fortran
program minimal_test
    implicit none

    character(len=*), parameter :: temp_file = "_lfortran_temporary_file_329372"
    character(len=*), parameter :: test_line = "HelloWorld!"
    integer :: unit, ios

    open(newunit=unit, file=temp_file)
    write(unit, iostat=ios) test_line
    close(unit)

end program minimal_test
```

### PR DESCRIPTION
**Pull request by assem2002**
#closes #8989
Fix : Check Open Format ('formatted' OR 'unformatted') against Write format ('(I0)' OR '*' OR NONE)

# Changes
- Don't pass any formatting if node `FileWrite.is_formatted` == FALSE.
- Check at runtime the formatting match for FileWrite and opened filed using `is_write_and_open_format_match`
- If `iostat` provided and mismatch occur, Don't exit program and just report error code the `iostat` variable.

### CODE REVIEW

File: src/libasr/runtime/lfortran_intrinsics.c [hunk 1]
```diff
@@ -5184,17 +5184,42 @@ LFORTRAN_API char* _lpython_read(int64_t fd, int64_t n)
...
+    if(!is_write_and_open_format_match(unit_file_bin, format_data)){
+        if(iostat) {
+            *iostat = 5001;
+            return;
+        } else {
+            fprintf(stderr, "Runtime Error: Format mismatch between"
+                "OPEN statement and WRITE statement on unit %d.\n", unit_num);
+            exit(1);
+        }
+    }
```
Comment (certik) [inline src/libasr/runtime/lfortran_intrinsics.c:5217]: Let's add a test `run = true` in `tests/errors` for this error, to ensure it works.

Comment (certik) [reply src/libasr/runtime/lfortran_intrinsics.c:5217]: (I see that you are testing the `then` branch, but let's also test this `else` branch, and ensure the error looks good.)

**Comment by assem2002** [comment]
Thanks. Will add a test shortly.
