### PR TITLE
Fix: validate deferred length consistency for allocatable character dummy arguments

### LINKED ISSUE #6776: Error : Report error for not matching string array types
MRE 
```.f90
program test
  character(2):: x(200)
  character(:),allocatable:: y(:)
  call ss(x)   ! <<<<<<<<<<<<<<<<<< ERROR
  ! call ss(y) ! <<<<<<<<<<<<<<<<<< This works
  contains 
  subroutine ss (xx)
    character(:), allocatable :: xx(:)  
    xx(1) = "AB"
  end subroutine 
end program test
```
```console
code generation error: asr_to_llvm: module failed verification. Error:
Stored value type does not match pointer operand type!
  store [3 x i8]* %9, i8*** %10, align 8
 i8**Call parameter type does not match function signature!
  %array_descriptor = alloca %array, align 8
 %array**  call void @ss(%array* %array_descriptor)



Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
assem@assem-PC:~/Desktop/fortran/compile_gsnap$ gfortran tt7.f90 
tt7.f90:16:10:

   16 |   call ss(x)   ! <<<<<<<<<<<<<<<<<< ERROR
      |          1
Error: Actual argument at (1) to allocatable or pointer dummy argument ‘xx’ must have a deferred length type parameter if and only if the dummy has one
assem@assem-PC:~/Desktop/fortran/compile_gsnap$ 

```

### PR DESCRIPTION
**Pull request by Jatinagarwal24**
Fixes #6776

### CODE REVIEW

File: tests/errors/continue_compilation_3.f90 [hunk 1]
```diff
@@ -34,10 +34,10 @@ subroutine assumed_rank(x)
         print *, (x /= [1, 2])
     end subroutine assumed_rank
 
-
-
-
-
+    subroutine ss(x)
+        character(:), allocatable :: x
+        x(1) = "AB"
```
Comment (certik) [inline tests/errors/continue_compilation_3.f90]: Can you write `x(1) = "AB"` ? The `x` is not an array, so this doesn't work, right?

I asked Grok, it agrees: https://grok.com/share/bGVnYWN5_891c27b5-c2ea-4dd8-a8c8-038a61d96d89 and provides examples of what you maybe intended to do here, so pick one of those.

File: tests/reference/asr-continue_compilation_3-435a232.stderr [hunk 2]
```diff
@@ -439,6 +439,12 @@ semantic error: Different `character` lengths 7 and 2 in array constructor
 204 |     print *, ["welcome", "to", "lf"] .and. "contributors"  !even size diff of array element must be caught
     |                          ^^^^ 
 
+semantic error: Actual argument to allocatable or pointer dummy argument must have a deferred length type parameter if and only if the dummy has one
+   --> tests/errors/continue_compilation_3.f90:205:13
+    |
+205 |     call ss("hello")
+    |             ^^^^^^^ type mismatch at this call
```
Comment (certik) [inline tests/reference/asr-continue_compilation_3-435a232.stderr]: Let's improve the error message. After reading it it's not clear what I am supposed to do as a user to fix it.

Rather, let's say something like "cannot pass unallocatable string to allocatable argument" (or whatever the actual problem is) as the error description. Then the hint by the label should say "make this expression allocatable" (if this is the right fix).

**Comment by certik** [comment]
After you fix it, go ahead and click on "Ready for review".

**Comment by Jatinagarwal24** [comment]
Hi,@certik 
Can you pls review this.
