### PR TITLE
Delay handling for type-bound member calls

### LINKED ISSUE #2882: Deferred type-bound procedure is not recognized
This is another bug regarding type-bound procedures. In the following code, `obj` is reported by LFortran as having no type-bound procedure named `nelements` (both ifort and gfortran compile this code correctly):
```
module test_method

   type, abstract :: abstract_type
   contains
      procedure(nelements), deferred :: nelements
   end type abstract_type

   abstract interface
      pure function nelements(self) result(n)
         import; implicit none
         class(abstract_type), intent(in) :: self
         integer                          :: n
      end function nelements
   end interface
  
   type :: Wrapper
      private
      class(abstract_type), allocatable :: obj 
   contains
      procedure :: caller
   end type Wrapper
   
contains

   subroutine caller(self)
      class(Wrapper), intent(in) :: self      
      real(8), dimension(self%obj%nelements()) :: a
   end subroutine caller

end module test_method
```
Here's LFortran's output:
```
semantic error: Variable 'obj' doesn't have any member named, 'nelements'.
  --> test.f90:27:26
   |
27 |       real(8), dimension(self%obj%nelements()) :: a
   |                          ^^^^^^^^^^^^^^^^^^^^ 

```

### PR DESCRIPTION
**Pull request by certik**
Fixes #2882.

### CODE REVIEW

**Comment by certik** [comment]
This is similar to https://github.com/lfortran/lfortran/pull/7713. @kmr-srbh can you please review this PR, since you worked on this issue before?

File: src/lfortran/semantics/ast_common_visitor.h [hunk 1]
```diff
@@ -2538,6 +2538,15 @@ class CommonVisitor : public AST::BaseVisitor<Derived> {
...
 
+    bool is_type_bound_func_call_without_args(AST::expr_t* expr) {
+        if (!AST::is_a<AST::FuncCallOrArray_t>(*expr)) {
+            return false;
+        }
+        AST::FuncCallOrArray_t* call = AST::down_cast<AST::FuncCallOrArray_t>(expr);
+        return call->n_member > 0 && call->n_args == 0 &&
+               call->n_subargs == 0 && call->n_keywords == 0;
+    }
+
```
Comment (kmr-srbh) [inline src/lfortran/semantics/ast_common_visitor.h]: We can pass arguments in the function call while setting the dimensions. This can be handled in a different PR.

File: src/lfortran/semantics/ast_symboltable_visitor.cpp [hunk 2]
```diff
@@ -2855,13 +2855,47 @@ class SymbolTableVisitor : public CommonVisitor<SymbolTableVisitor> {
...
+                                break;
+                            }
+                        }
+                        if (!is_dt_dependency) {
+                            filtered_dep.push_back(al, var_dep.p[i]);
+                        }
+                    }
+                    var_dep = filtered_dep;
+                }
+            }
```
Comment (kmr-srbh) [inline src/lfortran/semantics/ast_symboltable_visitor.cpp]: This is not quite right. Please use the change in https://github.com/lfortran/lfortran/pull/7713/changes#r2799210889 to fix the ASR verify failure.

File: src/lfortran/semantics/ast_symboltable_visitor.cpp [hunk 3]
```diff
@@ -2855,13 +2855,47 @@ class SymbolTableVisitor : public CommonVisitor<SymbolTableVisitor> {
...
+            if (current_scope->asr_owner &&
+                ASR::is_a<ASR::symbol_t>(*current_scope->asr_owner)) {
+                asr_owner_sym = ASR::down_cast<ASR::symbol_t>(current_scope->asr_owner);
+            }
+            if (asr_owner_sym &&
+                current_scope->get_counter() != ASRUtils::symbol_parent_symtab(func_call->m_name)->get_counter() &&
+                !ASR::is_a<ASR::ExternalSymbol_t>(*func_call->m_name) &&
+                !ASR::is_a<ASR::Variable_t>(*func_call->m_name)) {
+                func_dep.push_back(al, ASRUtils::symbol_name(func_call->m_name));
+            }
```
Comment (kmr-srbh) [inline src/lfortran/semantics/ast_symboltable_visitor.cpp]: We can remove this by using https://github.com/lfortran/lfortran/pull/10009/changes#r2799213079.

File: src/libasr/pass/pass_utils.h [hunk 4]
```diff
@@ -544,7 +544,23 @@ namespace LCompilers {
...
+                    }
+                    if (x.m_dt) {
+                        bool fill_variable_dependencies_copy = fill_variable_dependencies;
+                        if (fill_variable_dependencies) {
+                            fill_variable_dependencies = false;
+                        }
+                        visit_expr(*x.m_dt);
+                        fill_variable_dependencies = fill_variable_dependencies_copy;
+                    }
+                    visit_ttype(*x.m_type);
```
Comment (kmr-srbh) [inline src/libasr/pass/pass_utils.h]: Same here.

File: src/lfortran/semantics/ast_symboltable_visitor.cpp (hunk 2 above)
Comment (kmr-srbh) [inline src/lfortran/semantics/ast_symboltable_visitor.cpp]: I meant this selection in https://github.com/lfortran/lfortran/pull/10009/changes#r2799213079.

**Comment by certik** [comment]
I pushed in a patch that simplifies the diff. Can you please review the diff now?

File: src/lfortran/semantics/ast_common_visitor.h (hunk 1 above)
Comment (certik) [reply src/lfortran/semantics/ast_common_visitor.h]: > We can pass arguments in the function call while setting the dimensions.

I don't understand what you mean by this. Can you give me an example?

Comment (kmr-srbh) [reply src/lfortran/semantics/ast_common_visitor.h]: We can have array declarations like `real(8), dimension(self%obj%nelements(20)) :: a` where we are passing `20` to `nelements()`.

File: src/lfortran/semantics/ast_symboltable_visitor.cpp (hunk 2 above)
Comment (certik) [reply src/lfortran/semantics/ast_symboltable_visitor.cpp]: This code is gone.

Comment (certik) [reply src/lfortran/semantics/ast_symboltable_visitor.cpp]: This code is gone.

File: src/libasr/pass/pass_utils.h (hunk 4 above)
Comment (certik) [reply src/libasr/pass/pass_utils.h]: This code is gone.

File: src/lfortran/semantics/ast_symboltable_visitor.cpp (hunk 3 above)
Comment (certik) [reply src/lfortran/semantics/ast_symboltable_visitor.cpp]: Are you thinking of the following patch:
```diff
--- a/src/lfortran/semantics/ast_symboltable_visitor.cpp
+++ b/src/lfortran/semantics/ast_symboltable_visitor.cpp
@@ -2861,17 +2861,7 @@ public:
             // Add called function as dependency to the owning-function's scope
             SetChar func_dep;
             func_dep.from_pointer_n_copy(al, func->m_dependencies, func->n_dependencies);
-            ASR::symbol_t* asr_owner_sym = nullptr;
-            if (current_scope->asr_owner &&
-                ASR::is_a<ASR::symbol_t>(*current_scope->asr_owner)) {
-                asr_owner_sym = ASR::down_cast<ASR::symbol_t>(current_scope->asr_owner);
-            }
-            if (asr_owner_sym &&
-                current_scope->get_counter() != ASRUtils::symbol_parent_symtab(func_call->m_name)->get_counter() &&
-                !ASR::is_a<ASR::ExternalSymbol_t>(*func_call->m_name) &&
-                !ASR::is_a<ASR::Variable_t>(*func_call->m_name)) {
-                func_dep.push_back(al, ASRUtils::symbol_name(func_call->m_name));
-            }
+            func_dep.push_back(al, ASRUtils::symbol_name(func_call->m_name));
             func->m_dependencies = func_dep.p;
             func->n_dependencies = func_dep.n;

diff --git a/src/libasr/asr_verify.cpp b/src/libasr/asr_verify.cpp
index 6e8286239..b5dfa97a2 100644
--- a/src/libasr/asr_verify.cpp
+++ b/src/libasr/asr_verify.cpp
@@ -1189,6 +1189,9 @@ public:
         require(x.m_name,
             "FunctionCall::m_name must be present");
         variable_dependencies.push_back(std::string(ASRUtils::symbol_name(x.m_name)));
+        if (x.m_dt && ASR::is_a<ASR::StructInstanceMember_t>(*x.m_dt)) {
+            visit_expr(*x.m_dt);
+        }
         ASR::symbol_t* asr_owner_sym = nullptr;
         if(current_symtab->asr_owner &&  ASR::is_a<ASR::symbol_t>(*current_symtab->asr_owner) ) {
             asr_owner_sym = ASR::down_cast<ASR::symbol_t>(current_symtab->asr_owner);
```
For this I get:
```console
(lf) ~/repos/lfortran(df1)$ lfortran integration_tests/class_109.f90
ASR verify pass error: Variable a depends on self but isn't found in its dependency list.
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/src/bin/lfortran.cpp", line 2805
    LCompilers::print_stack_on_segfault();
  File "/Users/ondrej/repos/lfortran/src/bin/lfortran.cpp", line 2732
    err = compile_src_to_object_file(arg_file, tmp_o, compiler_options.time_report, false,
  File "/Users/ondrej/repos/lfortran/src/bin/lfortran.cpp", line 1193
    t2 = std::chrono::high_resolution_clock::now();
  File "/Users/ondrej/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 276
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics, lm);
  File "/Users/ondrej/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 298
    compiler_options.symtab_only, compiler_options, lm);
  File "/Users/ondrej/repos/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 81
    if (res.ok) {
  File "/Users/ondrej/repos/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 4816
    v.visit_TranslationUnit(ast);
  File "/Users/ondrej/repos/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 89
    visit_ast(*x.m_items[i]);
  File "/Users/ondrej/repos/lfortran/src/lfortran/ast.h", line 5018
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/src/lfortran/ast.h", line 4973
    case astType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/src/lfortran/ast.h", line 5021
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/src/lfortran/ast.h", line 4595
    case modType::BlockData: { v.visit_BlockData((const BlockData_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 483
    visit_unit_decl1(*x.m_use[i]);
  File "/Users/ondrej/repos/lfortran/src/lfortran/ast.h", line 5030
    void visit_unit_decl1(const unit_decl1_t &b) { visit_unit_decl1_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/src/lfortran/ast.h", line 4614
    case unit_decl1Type::Use: { v.visit_Use((const Use_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 3692
    ASRUtils::fix_translation_unit(al, tu, tu_symtab, true);
  File "/Users/ondrej/repos/lfortran/src/libasr/asr_utils.cpp", line 959
    throw LCompilersException("Verify failed");
LCompilersException: Verify failed
```

File: src/lfortran/semantics/ast_common_visitor.h (hunk 1 above)
Comment (certik) [reply src/lfortran/semantics/ast_common_visitor.h]: I see. I fixed this in 88a2920e50d65f97684831db449e5026d2b32ea3.

File: src/lfortran/semantics/ast_symboltable_visitor.cpp (hunk 3 above)
Comment (certik) [reply src/lfortran/semantics/ast_symboltable_visitor.cpp]: I figured it out: 284326f81df1a4dbc8aa63ae8732922214eb513f.

**Comment by certik** [comment]
Ready.
