### PR TITLE
fix : Correct m-type of StructInstanceMember to get rid of Allocatable when field is not Allocatable

### LINKED ISSUE #6735: `findloc` intrinsic function is not working properly ( Giving ASR verify pass error )
Towards #5629 

MRE :- 

```.f90
program test
    implicit none

    type :: stone
        integer :: value = 0 
    end type stone

    type(stone),dimension(:),allocatable :: s
    integer :: val , iloc

    allocate(s(0))
    val = 1
    iloc = findloc(s%value, val, dim=1)

    print * , iloc
end program
```

Gfortran Output :- 

```console
(lf) lordansh@LordAnsh:~/dev/lfort1/lfortran$ gfortran try2.f90 && ./a.out
           0
```

LFortran Error :- 

```console
(lf) lordansh@LordAnsh:~/dev/lfort1/lfortran$ lfortran try2.f90
ASR verify pass error: FunctionCall::m_name _lcompilers_findloc must be returning a non-void value.
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/lordansh/dev/lfort1/lfortran/src/bin/lfortran", in _start
  File "./csu/../csu/libc-start.c", line 360, in __libc_start_main
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main
  File "/home/lordansh/dev/lfort1/lfortran/src/bin/lfortran.cpp", line 2690, in main
    return main_app(argc, argv);
  File "/home/lordansh/dev/lfort1/lfortran/src/bin/lfortran.cpp", line 2618, in main_app(int, char**)
    err = compile_src_to_object_file(arg_file, tmp_o, compiler_options.time_report, false,
  File "/home/lordansh/dev/lfort1/lfortran/src/bin/lfortran.cpp", line 1165, in (anonymous namespace)::compile_src_to_object_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, LCompilers::CompilerOptions&, LCompilers::PassManager&)
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/home/lordansh/dev/lfort1/lfortran/src/lfortran/fortran_evaluator.cpp", line 382, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/home/lordansh/dev/lfort1/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 10893, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/home/lordansh/dev/lfort1/lfortran/src/libasr/pass/pass_manager.h", line 310, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    apply_passes(al, asr, _passes, pass_options, diagnostics);
LCompilersException: Verify failed in the pass: intrinsic_function
```

### PR DESCRIPTION
**Pull request by AnshMehta1**
Towards #5629 
fix #6735 

MRE :- 
```.f90
program test
  implicit none

  type :: stone
      integer :: value = 0
  end type stone

  type(stone),dimension(:),allocatable :: s

  allocate(s(2))
  print*, s%value
end program
```

LFortran Output :- 
```console
(lf) lordansh@LordAnsh:~/dev/lfort4/lfortran$ lfortran try.f90
0    0
```

Corrected ASR :- 
```console
[(StructInstanceMember
    (Var 2 s)
    2 1_stone_value
    (Array
        (Integer 4)
        [(()
        ())]
        DescriptorArray
    )
    ()
)]

```

### CODE REVIEW

File: src/lfortran/semantics/ast_common_visitor.h [hunk 1]
```diff
@@ -10166,7 +10166,11 @@ class CommonVisitor : public AST::BaseVisitor<Derived> {
                 }
                 if(ASR::is_a<ASR::Allocatable_t>(*array_type)){
                     ASR::down_cast<ASR::Array_t>((ASR::down_cast<ASR::Allocatable_t>(array_type))->m_type)->m_type = ASRUtils::type_get_past_array(ASRUtils::type_get_past_allocatable(tmp2->m_type));
-                    tmp2->m_type = array_type;
+                    if (ASR::down_cast<ASR::Variable_t>(ASR::down_cast<ASR::ExternalSymbol_t>(tmp2->m_m)->m_external)->m_type->type == ASR::ttypeType::Allocatable) {
```
Comment (gxyd) [inline src/lfortran/semantics/ast_common_visitor.h:10169]: Two things:
* First, I would try to simply use `ASRUtils::is_allocatable(ASRUtils::EXPR(tmp))`, because this is what I expect it would do as well (I might be wrong), and if possible assign `ASR::expr_t* some_appropriate_expr_name = ASRUtils::EXPR(tmp)` and then do it, so it's easy to understand what's `tmp` referring to.
* secondly, if the above doesn't work, atleast we shouldn't use ` .... ->type == ASR::ttypeType::Allocatable`, I would instead use `ASR::is_a<ASR::Allocatable_t>(ASRUtils::expr_type(...))`

File: integration_tests/intrinsics_371.f90 [hunk 2]
```diff
@@ -0,0 +1,18 @@
...
+    implicit none
+
+    type :: stone
+        integer :: value = 0 
+    end type stone
+
+    type(stone),dimension(:),allocatable :: s
+    integer :: val , iloc
+
+    allocate(s(0))
```
Comment (gxyd) [inline integration_tests/intrinsics_371.f90:11]: `allocate(s(0))`, what does that mean?

File: integration_tests/intrinsics_371.f90 [hunk 3]
```diff
@@ -0,0 +1,18 @@
...
+    val = 1
+
+    iloc = findloc(s%value, val, dim=1)
+
+    print * , iloc
+    if (iloc /= 0) error stop
```
Comment (gxyd) [inline integration_tests/intrinsics_371.f90:17]: `iloc` being `0` means that the element isn't found? (I'm sorry, I'm not really good with remembering the details of intrinsics)

File: integration_tests/intrinsics_371.f90 (hunk 2 above)
Comment (gxyd) [reply integration_tests/intrinsics_371.f90:11]: Is that exactly how it was in the AoC-2024's code?

**Review by gxyd — COMMENTED** [review]
The ASR change, does look good to me, left some comments to consider though.

File: integration_tests/intrinsics_371.f90 (hunk 2 above)
Comment (AnshMehta1) [reply integration_tests/intrinsics_371.f90:11]: Yes , AoC-2024 uses this . 
image
image

Comment (AnshMehta1) [reply integration_tests/intrinsics_371.f90:11]: It uses some sort of do-loop starting with allocate(s(0)) case.

File: integration_tests/intrinsics_371.f90 (hunk 3 above)
Comment (AnshMehta1) [reply integration_tests/intrinsics_371.f90:17]: Ya , it means that value we are searching is not found .

File: src/lfortran/semantics/ast_common_visitor.h (hunk 1 above)
Comment (AnshMehta1) [reply src/lfortran/semantics/ast_common_visitor.h]: Made the changes . Didn't do this part `ASR::expr_t* some_appropriate_expr_name = ASRUtils::EXPR(tmp)` as few lines above , we have this code which gives reference to tmp
image

File: integration_tests/intrinsics_371.f90 (hunk 2 above)
Comment (HarshitaKalani) [reply integration_tests/intrinsics_371.f90:11]: Yes, that's correct. When we just wish to allocate the array but of 0 size.

File: src/lfortran/semantics/ast_common_visitor.h [hunk 4]
```diff
@@ -10166,7 +10166,11 @@ class CommonVisitor : public AST::BaseVisitor<Derived> {
                 }
                 if(ASR::is_a<ASR::Allocatable_t>(*array_type)){
                     ASR::down_cast<ASR::Array_t>((ASR::down_cast<ASR::Allocatable_t>(array_type))->m_type)->m_type = ASRUtils::type_get_past_array(ASRUtils::type_get_past_allocatable(tmp2->m_type));
-                    tmp2->m_type = array_type;
+                    if (ASRUtils::is_allocatable(ASRUtils::EXPR(tmp))) {
+                        tmp2->m_type = array_type;
+                    } else {
+                        tmp2->m_type = ASRUtils::type_get_past_allocatable(array_type);
+                    }
```
Comment (HarshitaKalani) [inline src/lfortran/semantics/ast_common_visitor.h:10173]:
```suggestion
                   tmp2->m_type = ASRUtils::type_get_past_allocatable(array_type);
```
You don't need the if-else condition I believe. The function type_get_past_allocatable already does that.

**Review by HarshitaKalani — COMMENTED** [review]
Suggested a minor change. Otherwise looks good.

File: src/lfortran/semantics/ast_common_visitor.h (hunk 4 above)
Comment (AnshMehta1) [reply src/lfortran/semantics/ast_common_visitor.h:10173]: Actually , array-type initially is allocatable . We need to do `ASRUtils::type_get_past_allocatable(array_type)` to get rid of allocatable only in the case when `ASRUtils::EXPR(tmp)` is not allocatable .

Comment (HarshitaKalani) [reply src/lfortran/semantics/ast_common_visitor.h:10173]: Oh I see. Yep, this is good then.

**Review by HarshitaKalani — APPROVED** [review]
