### PR TITLE
enh: add support for handling `ASR::ClassProcedure_t` for functions with string parameters

### LINKED ISSUE #5734: bug: `ClassProcedure_t` not handled for `Function_t` with `String_t` parameters
### Minimal Reproducible Example

```fortran
module aoc_utilities

   type,public :: clock
        private
        integer :: begin, end, rate
    contains
        procedure,public :: toc => clock_end
    end type clock

    type(clock),public :: clk

    contains

    subroutine clock_end(me, case_str)
      class(clock),intent(inout) :: me
      character(len=*),intent(in) :: case_str
      print *, case_str
  end subroutine clock_end

end module aoc_utilities


program main

   use aoc_utilities
   call clk%toc("5")

end program main
```

### Output

```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ gfortran test.f90 && ./a.out
 5
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran test.f90
code generation error: ICE: expected func_subrout->type == ASR::symbolType::Function.


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

### PR DESCRIPTION
**Pull request by kmr-srbh**
fixes #5734

### CODE REVIEW

**Comment by kmr-srbh** [comment]
The CI failure is unexpected here. The added test runs correctly on my system.

```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran test.f90
5
6
```

**Comment by kmr-srbh** [comment]
Here is the cause of the failure - #5741. We can either wait until it's fixed, or comment out the failing case and merge this if the changes look good.

**Comment by kmr-srbh** [comment]
@jinangshah21 I am commenting out the test case related to #5741. If this PR is merged before you push a fix, please uncomment the test case.

**Comment by jinangshah21** [comment]
> @jinangshah21 I am commenting out the test case related to #5741. If this PR is merged before you push a fix, please uncomment the test case.

I had pushed fix for #5741 at #5758.

**Comment by kmr-srbh** [comment]
Thanks Jinang! That would be helpful.

File: src/libasr/codegen/asr_to_llvm.cpp [hunk 1]
```diff
@@ -8986,6 +8986,19 @@ class ASRToLLVMVisitor : public ASR::BaseVisitor<ASRToLLVMVisitor>
                         if( func_subrout->type == ASR::symbolType::Function ) {
                             ASR::Function_t* func = down_cast<ASR::Function_t>(func_subrout);
                             orig_arg = ASRUtils::EXPR2VAR(func->m_args[i]);
+                        } else if (func_subrout->type == ASR::symbolType::ClassProcedure) {
+                            ASR::ClassProcedure_t* class_proc = down_cast<ASR::ClassProcedure_t>(func_subrout);
+                            ASR::symbol_t* func_sym = class_proc->m_proc;
+                            if (func_sym->type == ASR::symbolType::Function) {
```
Comment (certik) [inline src/libasr/codegen/asr_to_llvm.cpp:8992]:
```suggestion
                            if (ASR::is_a<ASR::Function_t>(*func_sym)) {
```
And the same everywhere else around here.

If you could please fix that in the next PR, that would be great.

File: src/libasr/codegen/asr_to_llvm.cpp [hunk 2]
```diff
@@ -8986,6 +8986,19 @@ class ASRToLLVMVisitor : public ASR::BaseVisitor<ASRToLLVMVisitor>
...
+                                ASR::Function_t* func = down_cast<ASR::Function_t>(func_sym);
+                                orig_arg = EXPR2VAR(func->m_args[i]);
+                            } else {
+                                LCOMPILERS_ASSERT(false)
```
Comment (certik) [inline src/libasr/codegen/asr_to_llvm.cpp:8996]: Is this a temporary thing until we implement it, or it can never be anything else?

Let's add a comment here.

**Review by certik — APPROVED** [review]

File: src/libasr/codegen/asr_to_llvm.cpp (hunk 2 above)
Comment (kmr-srbh) [reply src/libasr/codegen/asr_to_llvm.cpp:8996]: I followed this from an implementation which was used elsewhere in the code. Can a `procedure` be used in other ways than those we check for? Else I think we never probably reach the `else` block.
