### PR TITLE
fix: add support for substrings inside write statements

### LINKED ISSUE #7787: Bug writing part of a character string
This standard-conforming program tests writing to part of a character string because #3811 and #7775 revealed a problem in reading from one.
```
! file writepartstring.f90
  character(10):: string = 'ABCDEFGHIJ'
  write(string(1:4),'(A)') 'abcd'
  write( *,'(A)') string
end program
```
Output from lfortran 0.53.0 with or without --std=f23
```
Segmentation fault (core dumped)
```
Output from 4 other compilers, which is correct
```
abcdEFGHIJ
````

### LINKED ISSUE #8369: Handle string section in write arg
MRE:
```fortran 
program m
   implicit none
   character(len=5) :: local
   write(local(1:),'(a)') "Hello"
   print *, local
end program m
```

Outputs:
```console
(base) jinang_shah@JNSLAP:~/Desktop/lfortran$ gfortran b.f90 && ./a.out
 Hello
(base) jinang_shah@JNSLAP:~/Desktop/lfortran$ lfortran b.f90 

(base) jinang_shah@JNSLAP:~/Desktop/lfortran$ 
```

### PR DESCRIPTION
**Pull request by YashNagda17**
Fixes #7787 & Fixes #8369
Add support for writing into StringSections inside write statements by marking them as assignment targets.

### CODE REVIEW

**Review by jinangshah21 — APPROVED** [review]
I think this is fine!

File: src/libasr/pass/replace_with_compile_time_values.cpp [hunk 1]
```diff
@@ -145,6 +145,63 @@ class ExprVisitor: public ASR::CallReplacerOnExpressionsVisitor<ExprVisitor> {
         current_expr = current_expr_copy;
     }
 
+        void visit_FileWrite(const ASR::FileWrite_t& x) {
+        // Don't replace string write targets as compile-time constants
+        ASR::FileWrite_t& xx = const_cast<ASR::FileWrite_t&>(x);
```
Comment (certik) [inline src/libasr/pass/replace_with_compile_time_values.cpp:150]: The indentation is invalid
