### PR TITLE
FIX: Missing dependency in ASR

### LINKED ISSUE #3504: Missing dependency in ASR
```fortran
pure function my_merge(val1, val2, mask) result(merged_value)
  integer, intent(in) :: val1, val2
  logical, intent(in) :: mask
  integer :: merged_value

  if (mask) then
    merged_value = val1
  else
    merged_value = val2
  end if

end function my_merge


program main
contains
function mean_2_cdp_cdp(x, dim, mask) result(res)
  complex, intent(in) :: x(:,:)
  integer, intent(in) :: dim
  logical, intent(in), optional :: mask
  complex :: res(my_merge(size(x, 1), size(x, 2), mask=1<dim))

  interface
    pure function my_merge(val1, val2, mask) result(merged_value2)
      integer, intent(in) :: val1, val2
      logical, intent(in) :: mask
      integer :: merged_value2
    end function my_merge
  end interface

end function mean_2_cdp_cdp
end program

```

```console
% lfortran a.f90 --show-asr
ASR verify pass error: Function mean_2_cdp_cdp depends on my_merge but isn't found in its dependency list.
  --> a.f90:17:1 - 31:28
   |
17 |    function mean_2_cdp_cdp(x, dim, mask) result(res)
   |    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
...
   |
31 |    end function mean_2_cdp_cdp
   | ...^^^^^^^^^^^^^^^^^^^^^^^^^^^^ failed here


Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

### PR DESCRIPTION
**Pull request by Pranavchiku**
Fixes #3504

### CODE REVIEW

**Comment by Pranavchiku** [comment]
Example that fails:

```fortran
module stdlib_string_type
    implicit none

    !> String type holding an arbitrary sequence of characters.
    type :: string_type
        ! Use the sequence statement below as a hack to prevent extending this type.
        ! It is not used for storage association.
        sequence
        private
        character(len=:), allocatable :: raw
    end type string_type

    !> Assign a character sequence to a string.
    interface assignment(=)
        module procedure :: assign_string_char
    end interface assignment(=)
contains

    !> Assign a character sequence to a string.
    elemental subroutine assign_string_char(lhs, rhs)
        type(string_type), intent(inout) :: lhs
        character(len=*), intent(in) :: rhs
        lhs%raw = rhs
    end subroutine assign_string_char


    !> Returns the character sequence hold by the string without trailing spaces.
    elemental function trim_string(string) result(trimmed_string)
        type(string_type), intent(in) :: string
        type(string_type) :: trimmed_string

        trimmed_string = trim(maybe(string))

    end function trim_string

    !> Safely return the character sequences represented by the string
    pure function maybe(string) result(maybe_string)
        implicit none
        type(string_type), intent(in) :: string
        character(len=5) :: maybe_string
    end function maybe


end module stdlib_string_type

```

**Comment by Pranavchiku** [comment]
I have made progress on this, will push changes once every case works.

**Comment by certik** [comment]
@Shaikh-Ubaid or @czgdp1807 can you please review it? I think it looks good at first sight, but this requires more thorough review.

File: integration_tests/functions_21.f90 [hunk 1]
```diff
@@ -0,0 +1,42 @@
+pure integer function my_merge(val1, val2, mask) result(merged_value)
```
Comment (Shaikh-Ubaid) [inline integration_tests/functions_21.f90:1]: Is this test case added only to test "Missing dependency in ASR"? 
- If so, then I think a smaller test case is possible. See https://github.com/lfortran/lfortran/issues/3504#issuecomment-1964524631. Let's use the smaller one here.
- If not, what other things apart from "Missing dependency in ASR" does this example test?

File: integration_tests/functions_22.f90 [hunk 2]
```diff
@@ -0,0 +1,40 @@
+pure integer function fn1(A) result(r)
```
Comment (Shaikh-Ubaid) [inline integration_tests/functions_22.f90:1]: I am confused what specific bug this example tests?

I checked this test locally and it seems to work for me for `gfortran` and `lfortran`.

```console
% cat examples/expr2.f90              
pure integer function fn1(A) result(r)
implicit none
real, intent(in) :: A(:,:)
r = minval(shape(A))
end function

subroutine diag_rsp_mat(A, res)
implicit none
interface
    pure integer function fn1(B)
    implicit none
    real, intent(in) :: B(:,:)
    end function
end interface
real, intent(in) :: A(:,:)
real, intent(out) :: res(fn1(A))
print *, shape(res), fn1(A)
if (fn1(A) /= 5) error stop
end subroutine diag_rsp_mat

program functions_22
implicit none
real :: A(5, 5)
real :: res(5)
integer :: result
interface
    subroutine diag_rsp_mat(A, res)
    implicit none
    interface
        pure integer function fn1(C)
        implicit none
        real, intent(in) :: C(:,:)
        end function
    end interface
    real, intent(in) :: A(:,:)
    real, intent(out) :: res(fn1(A))
    end subroutine diag_rsp_mat
end interface
call diag_rsp_mat(A, res)
end program
% gfortran examples/expr2.f90         
examples/expr2.f90:10:29:

   10 |     pure integer function fn1(B)
      |                             1
Warning: Interface mismatch in global procedure 'fn1' at (1): Shape mismatch in argument 'b'
examples/expr2.f90:30:33:

   30 |         pure integer function fn1(C)
      |                                 1
Warning: Interface mismatch in global procedure 'fn1' at (1): Shape mismatch in argument 'c'
% ./a.out 
           5           5
% lfortran_in_main examples/expr2.f90  
5 
5
```

@Pranavchiku could you clarify?

File: integration_tests/functions_21.f90 (hunk 1 above)
Comment (Pranavchiku) [reply integration_tests/functions_21.f90:1]: No. It tests two things:
- Missing dependency
- Improvement in `function_call_in_declaration` pass
- Miscellaneous requirement, as it is fully functional test taken from `stdlib_stats`

File: integration_tests/functions_22.f90 (hunk 2 above)
Comment (Pranavchiku) [reply integration_tests/functions_22.f90:1]: comment above.

Comment (Pranavchiku) [reply integration_tests/functions_22.f90:1]: This is taken from https://github.com/lfortran/lfortran/pull/3388.

File: integration_tests/functions_21.f90 (hunk 1 above)
Comment (Shaikh-Ubaid) [reply integration_tests/functions_21.f90:1]: Ok, good. In future, I would suggest adding concise test for each individual bug fixed (if the bugs can be isolated). For example, in the above case one for Missing dependency and one for the Improvement in the pass, assuming they can be isolated.

For "Miscellaneous requirement, as it is fully functional test taken from stdlib_stats", I am unsure if it is a good idea to add it here since it would already be tested as part of `stdlib_stats`. Thus seems redundant. Since, it is added now, I think it is fine.

Comment (Pranavchiku) [reply integration_tests/functions_21.f90:1]: Yes, I'll take care :)

**Review by Shaikh-Ubaid — APPROVED** [review]
It looks good to me. Thanks for this! Great work @Pranavchiku!

File: src/lfortran/semantics/ast_common_visitor.h [hunk 3]
```diff
@@ -4039,6 +4042,11 @@ class CommonVisitor : public AST::BaseVisitor<Derived> {
         if (ASRUtils::symbol_parent_symtab(v)->get_counter() != current_scope->get_counter()) {
             ADD_ASR_DEPENDENCIES(current_scope, v, current_function_dependencies);
         }
+        if (_processing_dimensions && _declaring_variable &&
+            ASRUtils::symbol_parent_symtab(v)->get_counter() != current_scope->get_counter() &&
+            !ASR::is_a<ASR::ExternalSymbol_t>(*v)) {
+            current_function_dependencies.push_back(al, ASRUtils::symbol_name(v));
+        }
```
Comment (Shaikh-Ubaid) [inline src/lfortran/semantics/ast_common_visitor.h:4049]: After another look at this, it seems like this can be moved into `ADD_ASR_DEPENDENCIES`?

File: integration_tests/functions_22.f90 (hunk 2 above)
Comment (certik) [reply integration_tests/functions_22.f90:1]: What is the shape mismatch that GFortran warns about? It seems in both cases it is `real, intent(in) :: B(:,:)`. Just the name of the argument changes, but that should be irrelevant.

**Comment by certik** [comment]
Can you explain with words what specific bug this is fixing? 

Using an interface inside a function?

File: src/lfortran/semantics/ast_common_visitor.h [hunk 4]
```diff
@@ -808,6 +808,7 @@ class CommonVisitor : public AST::BaseVisitor<Derived> {
     bool in_Subroutine = false;
     bool is_common_variable = false;
     bool _processing_dimensions = false;
+    bool _declaring_variable = false;
```
Comment (certik) [inline src/lfortran/semantics/ast_common_visitor.h:811]: Can you explain what the purpose is of this variable?

File: integration_tests/functions_22.f90 (hunk 2 above)
Comment (Pranavchiku) [reply integration_tests/functions_22.f90:1]: I am not sure, took the code from https://github.com/lfortran/lfortran/pull/3388#issuecomment-1937357128.

File: src/lfortran/semantics/ast_common_visitor.h (hunk 4 above)
Comment (Pranavchiku) [reply src/lfortran/semantics/ast_common_visitor.h:811]: When we look this `complex :: res(my_merge(size(x, 1), size(x, 2), mask=1<dim))`, where `res` is `ReturnVar`, LFortran does not add `my_merge` to dependency list of function but it does depend on it. 

This results in ASRVerify error (https://github.com/lfortran/lfortran/issues/3504#issue-2152144674). Also the current `ADD_ASR_DEPENDENCIES` do not add `my_merge` into it, so to ensure that we are currently declaring variable and then if we create a function call while processing dimensions the function name must be appended to function dependencies.

File: src/lfortran/semantics/ast_common_visitor.h (hunk 3 above)
Comment (Pranavchiku) [reply src/lfortran/semantics/ast_common_visitor.h:4049]: Yes, this can be done, we'll just have to pass the two variables to it and those shall have default values. To avoid default values I decided to not merge both.

**Review by czgdp1807 — COMMENTED** [review]
I fixed this exact same issue in one of my open PRs. Could you please tell for which module you are adding this fix?

**Review by czgdp1807 — COMMENTED** [review]
I see this is for stats module. I faced the same issue and I added the fix in https://github.com/lfortran/lfortran/pull/3459/files. Check ``asr_utils.cpp`` in that PR. Let me try the same thing on the tests you added in this PR. Please DO NOT merge this before till then.

**Comment by Pranavchiku** [comment]
You may then need to cherry-pick https://github.com/lfortran/lfortran/pull/3519/commits/0035d6675e4b5f945abfdc3230cd9dc68cd193ba to make it fully work.

**Comment by czgdp1807** [comment]
Sure. I will start the work right away and update here.

**Comment by Pranavchiku** [comment]
Also, I have plans to refactor that pass almost ready ( a small request to cherry-pick it ), else I'll have to change the refactored code. I am sorry for inconvenience.

**Review by czgdp1807 — APPROVED** [review]

**Comment by czgdp1807** [comment]
I think this is fine.
