### PR TITLE
fix: semantic error for invalid keyword argument

### LINKED ISSUE #3207: error not issued on bad open statement
I saw this while exploring the code for issue  #3205 dealing with end of file detection. I tried adding end= to the open statement (change the code for #3205 to ```open (77, *, file='numbers', end=200)``` and recompile).

gfortran reports a syntax error, lfortran does not. 

```
(lf) troi ~/projects/fortran $ gfortran iotest.f90
iotest.f90:7:26:

    7 | open (77, file='numbers', end=200, err=100)
      |                          1
Error: Syntax error in OPEN statement at (1)
```

### PR DESCRIPTION
**Pull request by gxyd**
Fixes #3207

### CODE REVIEW

File: src/lfortran/parser/semantics.h [hunk 1]
```diff
@@ -1010,6 +1012,11 @@ void extract_args1(Allocator &al,
             LCOMPILERS_ASSERT(item.kw.m_value != nullptr);
             kw.loc = item.kw.loc;
             kw.m_value = item.kw.m_value;
+            std::string arg_str(item.kw.m_arg);
+            std::transform(arg_str.begin(), arg_str.end(), arg_str.begin(), ::toupper);
+            if (std::find(acceptable_args.begin(), acceptable_args.end(), arg_str) == acceptable_args.end()) {
+                throw LCompilers::LFortran::parser_local::ParserError("Unsupported keyword argument: " + arg_str, l);
+            }
```
Comment (certik) [inline src/lfortran/parser/semantics.h:1019]: I think this will slow down regular parsing.

Instead, why not just parse every argument into AST (I think it already happens like that) and then in AST->ASR figure out if we have any extra keyword arguments? All these semantic checks conceptually belong into the semantic phase (AST->ASR), not parsing (src->AST).

Comment (gxyd) [reply src/lfortran/parser/semantics.h:1019]: > I think this will slow down regular parsing. Instead, why not just parse every argument into AST (I think it already happens like that) and then in AST->ASR figure out if we have any extra keyword arguments?

This makes sense from "speed point of view". (I've a question) Isn't the general idea to detect these kind of extra kwargs at "parser level", so we can throw "Syntax error" because if we wait till ASR then we can only throw "Semantic erorr" (I also noticed that GFortran raises "Syntax erorr")?

Comment (gxyd) [reply src/lfortran/parser/semantics.h:1019]: > All these semantic checks conceptually belong into the semantic phase (AST->ASR), not parsing (src->AST)

On second thought, maybe you are right that it actually should be a part of "semantic phase". I'll work on it to make the necessary changes.

**Comment by certik** [comment]
Argument and keyword argument checking belongs into semantic phase. Parsing checks general syntax, but doesn't care about the number of arguments, their types, their names, keyword argument names, etc.

You *can* do more semantic checks during parsing, as well as restrict various combinations with parsing rules. But often times there is some compilation speed penalty, like in the above.

File: src/lfortran/semantics/ast_body_visitor.cpp [hunk 2]
```diff
@@ -273,6 +273,12 @@ class BodyVisitor : public CommonVisitor<BodyVisitor> {
                 if (!ASRUtils::is_character(*a_form_type)) {
                         throw SemanticError("`form` must be of type, Character or CharacterPointer", x.base.base.loc);
                 }
+            } else {
+                const std::unordered_set<std::string> unsupported_args {"iostat", "iomsg", "err", "blank", "access", \
+                                                                            "recl", "fileopt", "action", "position"};
+                if (unsupported_args.find(m_arg_str) == unsupported_args.end()) {
+                    throw SemanticError("invalid argument: `" + m_arg_str + "` supplied", x.base.base.loc);
+                }
```
Comment (certik) [inline src/lfortran/semantics/ast_body_visitor.cpp:281]: Why not just:
```suggestion
                throw SemanticError("invalid argument: `" + m_arg_str + "` supplied", x.base.base.loc);
```

File: src/lfortran/semantics/ast_body_visitor.cpp [hunk 3]
```diff
@@ -679,12 +691,14 @@ class BodyVisitor : public CommonVisitor<BodyVisitor> {
...
-                    throw SemanticError(m_arg_string + " has already been specified.", x.base.base.loc);
+                std::string m_arg_str = to_lower(std::string(x.m_kwargs[i].m_arg));
+                if( args[argname2idx[m_arg_str]] ) {
+                    throw SemanticError(m_arg_str + " has already been specified.", x.base.base.loc);
+                } else if (argname2idx.find(m_arg_str) == argname2idx.end()) {
+                    throw SemanticError("invalid argument: `" + m_arg_str + "` supplied", x.base.base.loc);
                 }
                 visit_expr(*x.m_kwargs[i].m_value);
-                args[argname2idx[m_arg_string]] = ASRUtils::EXPR(tmp);
+                args[argname2idx[m_arg_str]] = ASRUtils::EXPR(tmp);
```
Comment (certik) [inline src/lfortran/semantics/ast_body_visitor.cpp:701]: I think this change is not tested yet. Make sure both error messages are tested in tests (one of them might be already).

**Review by certik — COMMENTED** [review]
Left some comments for improvement. Otherwise this looks great! I think this is a lot simpler and faster than the previous parsing approach.

File: src/lfortran/semantics/ast_body_visitor.cpp (hunk 2 above)
Comment (gxyd) [reply src/lfortran/semantics/ast_body_visitor.cpp:281]: If I do that then unsupported kwargs like `action, blank, recl` (i.e. the ones mentioned in `unsupported_args`) would raise a Semantic Error, which they shouldn't, right?

This made question for why `FileOpen` doesn't have `action, blank, recl` etc. in it's definition in ASR.asdl? defined here: https://github.com/lfortran/lfortran/blob/main/src/libasr/ASR.asdl#L48

File: src/lfortran/semantics/ast_body_visitor.cpp (hunk 3 above)
Comment (gxyd) [reply src/lfortran/semantics/ast_body_visitor.cpp:701]: fair enough, I'll test this.

File: src/lfortran/semantics/ast_body_visitor.cpp (hunk 2 above)
Comment (certik) [reply src/lfortran/semantics/ast_body_visitor.cpp:281]: I see. Then do something like:
```suggestion
                const std::unordered_set<std::string> unsupported_args {"iostat", "iomsg", "err", "blank", "access", \
                                                                            "recl", "fileopt", "action", "position"};
                if (unsupported_args.find(m_arg_str) == unsupported_args.end()) {
                    throw SemanticError("Invalid argument: `" + m_arg_str + "` supplied", x.base.base.loc);
                } else {
                    throw SemanticError("Argument: `" + m_arg_str + "` not implemented yet", x.base.base.loc);
                }
```
And add tests for both cases.

**Comment by gxyd** [comment]
@certik , I've tried to resolve your comments, please take a relook:
* What's the process on "resolving conversation" in LFortran (would the reviewer do it or reviewee do it?)
* As I'm getting comfortable with C++, let me know if there is any possible improvement that I can do (I would like make good habits for that)
* Please let me (or you can also do) squash the commits (into one) when it's about to be merged 😄

File: src/lfortran/semantics/ast_body_visitor.cpp (hunk 2 above)
Comment (gxyd) [reply src/lfortran/semantics/ast_body_visitor.cpp]: Do you think we should just raise a warning instead of an error? I mean, for someone who already uses these kwargs, their code would break and also would need changes in our test-suite (many instance of use of "access" and "action".

File: src/lfortran/semantics/ast_body_visitor.cpp [hunk 4]
```diff
@@ -273,6 +273,14 @@ class BodyVisitor : public CommonVisitor<BodyVisitor> {
                 if (!ASRUtils::is_character(*a_form_type)) {
                         throw SemanticError("`form` must be of type, Character or CharacterPointer", x.base.base.loc);
                 }
+            } else {
+                const std::unordered_set<std::string> unsupported_args {"iostat", "iomsg", "err", "blank", "access", \
+                                                                            "recl", "fileopt", "action", "position"};
+                if (unsupported_args.find(m_arg_str) == unsupported_args.end()) {
+                    throw SemanticError("invalid argument: `" + m_arg_str + "` supplied", x.base.base.loc);
```
Comment (certik) [inline src/lfortran/semantics/ast_body_visitor.cpp:280]:
```suggestion
                    throw SemanticError("Invalid argument: `" + m_arg_str + "` supplied", x.base.base.loc);
```

File: src/lfortran/semantics/ast_body_visitor.cpp [hunk 5]
```diff
@@ -273,6 +273,14 @@ class BodyVisitor : public CommonVisitor<BodyVisitor> {
...
+                } else {
+                    throw SemanticError("Argument: `" + m_arg_str + "` not implemented yet", x.base.base.loc);
```
Comment (certik) [inline src/lfortran/semantics/ast_body_visitor.cpp:282]:
```suggestion
                    throw SemanticError("Argument `" + m_arg_str + "` not implemented yet", x.base.base.loc);
```

File: src/lfortran/semantics/ast_body_visitor.cpp [hunk 6]
```diff
@@ -355,6 +364,8 @@ class BodyVisitor : public CommonVisitor<BodyVisitor> {
                 }
                 this->visit_expr(*kwarg.m_value);
                 a_err = ASRUtils::EXPR(tmp);
+            } else {
+                throw SemanticError("invalid argument: `" + m_arg_str + "` supplied", x.base.base.loc);
```
Comment (certik) [inline src/lfortran/semantics/ast_body_visitor.cpp:368]:
```suggestion
                throw SemanticError("invalid argument `" + m_arg_str + "` supplied", x.base.base.loc);
```

File: src/lfortran/semantics/ast_body_visitor.cpp [hunk 7]
```diff
@@ -679,12 +693,14 @@ class BodyVisitor : public CommonVisitor<BodyVisitor> {
 
         for( size_t i = 0; i < x.n_kwargs; i++ ) {
             if( x.m_kwargs[i].m_value ) {
-                std::string m_arg_string = to_lower(std::string(x.m_kwargs[i].m_arg));
-                if( args[argname2idx[m_arg_string]] ) {
-                    throw SemanticError(m_arg_string + " has already been specified.", x.base.base.loc);
+                std::string m_arg_str = to_lower(std::string(x.m_kwargs[i].m_arg));
+                if (argname2idx.find(m_arg_str) == argname2idx.end()) {
+                    throw SemanticError("invalid argument: `" + m_arg_str + "` supplied", x.base.base.loc);
```
Comment (certik) [inline src/lfortran/semantics/ast_body_visitor.cpp:698]:
```suggestion
                    throw SemanticError("Invalid argument `" + m_arg_str + "` supplied", x.base.base.loc);
```

**Comment by certik** [comment]
You can turn some of the errors into warnings, and append "ignored for now" into the warning, to make it clear that the argument is ignored.

**Comment by gxyd** [comment]
@certik this is ready for a review

File: src/lfortran/semantics/ast_body_visitor.cpp [hunk 8]
```diff
@@ -273,6 +273,18 @@ class BodyVisitor : public CommonVisitor<BodyVisitor> {
...
                 }
+            } else {
+                const std::unordered_set<std::string> unsupported_args {"iostat", "iomsg", "err", "blank", "access", \
+                                                                            "recl", "fileopt", "action", "position"};
+                if (unsupported_args.find(m_arg_str) == unsupported_args.end()) {
+                    throw SemanticError("Invalid argument `" + m_arg_str + "` supplied", x.base.base.loc);
+                } else {
+                    diag.semantic_warning_label(
+                        "Argument `" + m_arg_str + "` isn't supported yet",
+                        {x.base.base.loc},
```
Comment (certik) [inline src/lfortran/semantics/ast_body_visitor.cpp:284]: Let's use something like:
```suggestion
                        {kwarg.base.base.loc},
```
So that it highlights exactly the argument that we need, instead of the whole thing.

If this works, then the same for all the other errors.

Comment (gxyd) [reply src/lfortran/semantics/ast_body_visitor.cpp:284]: when I try `kwarg.loc`, I get:
```bash
(lf1)  ✘ gxyd@Gauravs-MacBook-Air  ~/OpenSource/lfortran   invalid_kwarg-3207 ±  ./src/bin/lfortran tests/warnings/open_notimplemented_kwarg1.f90
warning: Argument `action` isn't supported yet
 --> tests/warnings/open_notimplemented_kwarg1.f90:1:1
  |
1 | PROGRAM open_notimplemented_kwargs
  | ^ ignored for now

```

I noted the same issue somewhere else as well, which I believe is incorrect. I believe kwarg's aren't being assigned `loc` correctly (they are just set to `0, 0` for first, last)

Comment (gxyd) [reply src/lfortran/semantics/ast_body_visitor.cpp:284]: I'm looking at `asdl_cpp.py` for where to assign `loc` for kwargs correctly.

Comment (certik) [reply src/lfortran/semantics/ast_body_visitor.cpp:284]: Ok, keep the original code for now, let's merge this PR and fix it up later.

Can you open up an issue for the kward loc problem?

File: tests/warnings/file_01_data.txt [hunk 9]
```diff
@@ -0,0 +1,4 @@
+10130
+c
+4.20
+9223372036854775804
```
Comment (certik) [inline tests/warnings/file_01_data.txt:4]: This file is not needed. We only test ASR, not actually reading from a file.

File: integration_tests/test_backspace_01.f90 [hunk 10]
```diff
@@ -3,7 +3,7 @@ program test_backspace_01
     implicit none
     character(80) :: line
     integer :: u = 10
-    open(10, file='file_01_data.txt', status='old', action='read')
+    open(10, file='file_01_data.txt', status='old')
```
Comment (certik) [inline integration_tests/test_backspace_01.f90:6]: This is now ignored with a warning, so let's revert this change.

**Comment by certik** [comment]
Left two comments, otherwise ok.

File: integration_tests/test_backspace_01.f90 (hunk 10 above)
Comment (gxyd) [reply integration_tests/test_backspace_01.f90]: I'm ok with it either way, so I've made the requested change :)

File: tests/warnings/file_01_data.txt (hunk 9 above)
Comment (gxyd) [reply tests/warnings/file_01_data.txt]: Ah yes, you are right about that. Will keep in mind going forward 👍

File: src/lfortran/semantics/ast_body_visitor.cpp (hunk 8 above)
Comment (gxyd) [reply src/lfortran/semantics/ast_body_visitor.cpp:284]: Done, I've opened an isssue here: https://github.com/lfortran/lfortran/issues/3295

**Comment by gxyd** [comment]
Resolved all comments and opened a separate issue for `kwarg.loc` bug as well.

**Review by certik — APPROVED** [review]

**Comment by gxyd** [comment]
@certik , do you know why the build failed here? (Or just needs a restart?)

**Comment by certik** [comment]
The CI failure is due to https://github.com/lfortran/lfortran/issues/3211
