### PR TITLE
fix: allow "variable" as "iostat" and "iomsg" value

### LINKED ISSUE #3947: array element disallowed as iostat value
Every other compiler I tried allowed the variable after ```iostat=``` in a ```read``` statement to be an element of an integer array but lfortran said it was not an integer. #3936 also involved ```iostat=``` but no array, and the error messages from lfortran are quite different. The program
```
 program iostatarray
  integer, parameter:: sp = kind(1e0), dp = kind(1d0)
  integer ios(2)
  real(sp) xsp
  real(dp) xdp
  character(3):: cx = '666'
  read(cx,*,iostat=ios(1)) xsp
  if(ios(1)/=0)print *, 'Error in read(cx,*,iostat=ios(1)) xsp'
  print *,'xsp =',xsp
  read(cx,*,iostat=ios(2)) xdp
  if(ios(2)/=0)print *, 'Error in read(cx,*,iostat=ios(2)) xdp'
  print *,'xdp =',xdp
end program iostatarray
```
gave this output in my Ubuntu 22.04 Linux system:
```
semantic error: `iostat` must be of type, Integer
 --> iostatarray.f90:7:3
  |
7 |   read(cx,*,iostat=ios(1)) xsp
  |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 


Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

### PR DESCRIPTION
**Pull request by gxyd**
"variable" is as defined in the 2023 FORTRAN documentation as (R907)

Fixes #3947

### CODE REVIEW

**Review by Shaikh-Ubaid — APPROVED** [review]
Shared one comment. Rest looks good. Great work! I think the PR makes `iostat` and `iomsg` much more robust. Thanks for this @gxyd!

File: src/libasr/asr_utils.h [hunk 1]
```diff
@@ -984,6 +984,47 @@ static inline bool all_args_have_value(const Vec<ASR::expr_t*> &args) {
...
+        case ASR::exprType::ArrayItem: {
+            ASR::ArrayItem_t* a_item = ASR::down_cast<ASR::ArrayItem_t>(a_value);
+            ASR::expr_t* array_expr = a_item->m_v;
+            ASR::Variable_t* array_var = ASRUtils::EXPR2VAR(array_expr);
+            // a constant array's item isn't a "variable"
+            return array_var->m_storage != ASR::storage_typeType::Parameter;
+        }
+        case ASR::exprType::StringItem:
+        case ASR::exprType::StringSection:
+        case ASR::exprType::Var:
```
[the remark this answers is not in the document]
Comment (gxyd) [reply src/libasr/asr_utils.h]: Right, I've fixed this as well and added a test case for it as well.

File: tests/errors/tmp.txt
Comment (gxyd) [inline tests/errors/tmp.txt:1]: @Shaikh-Ubaid as this doesn't go un-noticed explicitly commenting here, I added this file for test purposes, let me know if there is a cleaner way, without needing to have a `.txt` file for it.

Comment (gxyd) [reply tests/errors/tmp.txt:1]: I've actually made some changes in tests, so that we don't need tmp.txt anymore, let me know if that looks good or having a tmp.txt file and testing via it

Comment (Shaikh-Ubaid) [reply tests/errors/tmp.txt:1]: Thanks. The updated approach is better. One less file to commit :)

**Review by Shaikh-Ubaid — APPROVED** [review]

**Comment by Shaikh-Ubaid** [comment]
It looks like my commit suggestion failed the CI.

File: src/libasr/asr_utils.h [hunk 2]
```diff
@@ -984,6 +984,54 @@ static inline bool all_args_have_value(const Vec<ASR::expr_t*> &args) {
...
+            ASR::ArrayItem_t* a_item = ASR::down_cast<ASR::ArrayItem_t>(a_value);
+            ASR::expr_t* array_expr = a_item->m_v;
+            ASR::Variable_t* array_var = ASRUtils::EXPR2VAR(array_expr);
+            // a constant array's item isn't a "variable"
+            return array_var->m_storage != ASR::storage_typeType::Parameter;
+        }
+        case ASR::exprType::Var: {
+            ASR::Var_t* var_t = ASR::down_cast<ASR::Var_t>(a_value);
+            if (ASR::is_a<ASR::Variable_t>(*ASRUtils::symbol_get_past_external(var_t->m_v))) {
+                ASR::Variable_t* variable_t = ASRUtils::EXPR2VAR(var_t->m_v);
```
Comment (Shaikh-Ubaid) [inline src/libasr/asr_utils.h:1018]:
```suggestion
                ASR::Variable_t* variable_t = ASRUtils::EXPR2VAR(a_value);
```

Comment (gxyd) [reply src/libasr/asr_utils.h]: I think we simply do:
```diff
diff --git a/src/libasr/asr_utils.h b/src/libasr/asr_utils.h
index 3374c1101..c1fde28fd 100644
--- a/src/libasr/asr_utils.h
+++ b/src/libasr/asr_utils.h
@@ -1013,12 +1013,8 @@ static inline bool is_variable(ASR::expr_t* a_value) {
             return array_var->m_storage != ASR::storage_typeType::Parameter;
         }
         case ASR::exprType::Var: {
-            ASR::Var_t* var_t = ASR::down_cast<ASR::Var_t>(a_value);
-            if (ASR::is_a<ASR::Variable_t>(*ASRUtils::symbol_get_past_external(var_t->m_v))) {
-                ASR::Variable_t* variable_t = ASRUtils::EXPR2VAR(var_t->m_v);
-                return variable_t->m_storage != ASR::storage_typeType::Parameter;
-            }
-            return true;
+            ASR::Variable_t* variable_t = ASRUtils::EXPR2VAR(a_value);
+            return variable_t->m_storage != ASR::storage_typeType::Parameter;
         }
         case ASR::exprType::StringItem:
         case ASR::exprType::StringSection:
```

Comment (Shaikh-Ubaid) [reply src/libasr/asr_utils.h]: If you are interested, you can also rebase and squash appropriate commits to clean the history. Or we can also squash merge this if you would like.

Comment (Shaikh-Ubaid) [reply src/libasr/asr_utils.h]: >I think we can simply do:

Yes, make the change!

Comment (gxyd) [reply src/libasr/asr_utils.h]: Yes, I'll push a commit. I got to know from certik regarding this `Var` & `Variable` confusion. That underlying every `Var` is always a `Variable` (could be an external), I'll keep that in mind going forward.

File: src/libasr/asr_utils.h [hunk 3]
```diff
@@ -984,6 +984,50 @@ static inline bool all_args_have_value(const Vec<ASR::expr_t*> &args) {
...
 
+/*
+See section 9.2 Variable from J3 SD-007r1.pdf for what a "Variable" is
+
+Below is an example verbatim from the document.
+For example, given the declarations:
+
+```
+    CHARACTER (10) A, B (10)
+    TYPE (PERSON) P ! See 7.5.2.1, NOTE
```
Comment (Shaikh-Ubaid) [inline src/libasr/asr_utils.h:995]: I just noticed this. I am unsure if taking an example from a document affects copyright. @certik could you share your opinion on this?

Comment (gxyd) [reply src/libasr/asr_utils.h:995]: Good point. Linking here the document from which I got this sample code from: https://j3-fortran.org/doc/year/23/23-007r1.pdf. I can just mention the link to the document and I think that would suffice as well. The only reason I included the example was, so that the dev doesn't have to go out of the way to the document to understand it's purpose, having an in-house example makes things relatively easy.

Comment (certik) [reply src/libasr/asr_utils.h:995]: I think verbatim copying might be problematic. Let's create our own examples and describe things using our own words.

Comment (gxyd) [reply src/libasr/asr_utils.h]: Alright, I've updated it to have a simpler explanation in my own words and example declarations different from the ones defined in the document. Let me know if it looks good (ofcourse we'll to squash the commits if things look good)

Comment (gxyd) [reply src/libasr/asr_utils.h]: I'm curious though @certik if we can reference the document i.e. point to certain sections of the document without any copright issue e.g. reference "9.2 Variable" of J3 document? in our documentation?

Comment (certik) [reply src/libasr/asr_utils.h]: It's a gray area, for example I believe the GFortran documentation copies examples verbatim from the standard, including some of the words. There is also such a thing as *fair use*:

> Under the fair use doctrine of the U.S. copyright statute, it is permissible to use limited portions of a work including quotes, for purposes such as commentary, criticism, news reporting, and scholarly reports.

I am not an expert, so the best is to stay clear and explain things using our own terms, then there is no issue.

**Review by certik — APPROVED** [review]

File: src/libasr/asr_utils.h [hunk 4]
```diff
@@ -984,6 +984,51 @@ static inline bool all_args_have_value(const Vec<ASR::expr_t*> &args) {
...
+    TYPE (EMPLOYEE) e
+        INTEGER age
+    END TYPE EMPLOYEE
+```
+
+then 'x', 'y', 'y(1)', 'y(1:2)', 'e % age' are all variables, while 'i' isn't
+
+TODO: this definitely needs some extensions to include others as "variable"'s
+*/
+static inline bool is_variable(ASR::expr_t* a_value) {
```
Comment (certik) [inline src/libasr/asr_utils.h:1004]: Anything in `libasr` should have nothing to do with Fortran. So we need to figure out rules that make sense to do in ASR, in a language-independent manner. It doesn't matter what Fortran (or Python or C) does. Until then, the above provides a motivation where we are coming from so it's fine, but it's necessarily temporary until we figure out a proper, language-independent, design.

Comment (gxyd) [reply src/libasr/asr_utils.h:1004]: Understood. I should've used better documentation for it, because the current actual definition of `is_variable` would make it language independent, as I can imagine `x, y(1) etc.` to remain classified as "variable" independent of language.
