### PR TITLE
throw error when shape argument in reshape in not fixed size array

### LINKED ISSUE #6437: throw error in reshape if `shape` argument is not a FixedSizeArray
MRE
```fortran
program reshape_dynamic
    implicit none
    integer, allocatable ::  shape_(:)
    integer, dimension(2, 3) :: matrix

    integer, dimension(4) :: source = [1, 2, 3, 4]
    
    allocate(shape_(2))
    shape_ = [2, 3]
    matrix = reshape(source, shape_, pad=[0])

    deallocate(shape_)
end program reshape_dynamic
```

GFortran throws error for shape_ not being an array of constant size
```bash
gfortran a.f90 && ./a.out
   47 |     matrix = reshape(source, shape_, pad=[0])
      |                             1
Error: ‘shape’ argument of ‘reshape’ intrinsic at (1) must be an array of constant size
```

LFortran does not give error here.
```bash
lfortran a.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/harshil-shah/lfortran/src/bin/lfortran", in _start
  File "./csu/../csu/libc-start.c", line 360, in __libc_start_main
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main
  File "/home/harshil-shah/lfortran/src/bin/lfortran.cpp", line 2769, in main
    return main_app(argc, argv);
  File "/home/harshil-shah/lfortran/src/bin/lfortran.cpp", line 2707, in main_app(int, char**)
    err = compile_src_to_object_file(arg_file, tmp_o, false,
  File "/home/harshil-shah/lfortran/src/bin/lfortran.cpp", line 1008, in (anonymous namespace)::compile_src_to_object_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, LCompilers::CompilerOptions&, LCompilers::PassManager&)
    result = fe.get_asr2(input, lm, diagnostics);
  File "/home/harshil-shah/lfortran/src/lfortran/fortran_evaluator.cpp", line 275, in LCompilers::FortranEvaluator::get_asr2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::diag::Diagnostics&)
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics, lm);
  File "/home/harshil-shah/lfortran/src/lfortran/fortran_evaluator.cpp", line 297, in LCompilers::FortranEvaluator::get_asr3(LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::LocationManager&)
    compiler_options.symtab_only, compiler_options, lm);
  File "/home/harshil-shah/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 111, in LCompilers::LFortran::ast_to_asr(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::SymbolTable*, bool, LCompilers::CompilerOptions&, LCompilers::LocationManager&)
    );
  File "/home/harshil-shah/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 4751, in LCompilers::LFortran::body_visitor(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::ASR::asr_t*, LCompilers::CompilerOptions&, std::map<unsigned long, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > > > > >&, std::map<unsigned long, LCompilers::ASR::symbol_t*, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, LCompilers::ASR::symbol_t*> > >&, std::map<unsigned long, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >&, std::map<unsigned long, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >&, std::map<unsigned int, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > > > > >&, std::map<unsigned int, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::symbol_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::symbol_t*> > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::symbol_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::symbol_t*> > > > > >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> > > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> > > > > > > >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<int, std::allocator<int> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<int, std::allocator<int> > > > >&, std::vector<LCompilers::ASR::stmt_t*, std::allocator<LCompilers::ASR::stmt_t*> >&, LCompilers::LocationManager&)
    b.visit_TranslationUnit(ast);
  File "/home/harshil-shah/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 163, in LCompilers::LFortran::BodyVisitor::visit_TranslationUnit(LCompilers::LFortran::AST::TranslationUnit_t const&)
    visit_ast(*x.m_items[i]);
  File "/home/harshil-shah/lfortran/src/lfortran/ast.h", line 4969, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_ast(LCompilers::LFortran::AST::ast_t const&)
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/home/harshil-shah/lfortran/src/lfortran/ast.h", line 4925, in void LCompilers::LFortran::AST::visit_ast_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::ast_t const&, LCompilers::LFortran::BodyVisitor&)
    case astType::mod: { v.visit_mod((const mod_t &)x); return; }
  File "/home/harshil-shah/lfortran/src/lfortran/ast.h", line 4972, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_mod(LCompilers::LFortran::AST::mod_t const&)
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/home/harshil-shah/lfortran/src/lfortran/ast.h", line 4549, in void LCompilers::LFortran::AST::visit_mod_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::mod_t const&, LCompilers::LFortran::BodyVisitor&)
    case modType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/home/harshil-shah/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1990, in LCompilers::LFortran::BodyVisitor::visit_Program(LCompilers::LFortran::AST::Program_t const&)
    transform_stmts(body, x.n_body, x.m_body);
  File "/home/harshil-shah/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 125, in LCompilers::LFortran::BodyVisitor::transform_stmts(LCompilers::Vec<LCompilers::ASR::stmt_t*>&, unsigned long, LCompilers::LFortran::AST::stmt_t**)
    this->visit_stmt(*m_body[i]);
  File "/home/harshil-shah/lfortran/src/lfortran/ast.h", line 5017, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_stmt(LCompilers::LFortran::AST::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/harshil-shah/lfortran/src/lfortran/ast.h", line 4659, in void LCompilers::LFortran::AST::visit_stmt_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::stmt_t const&, LCompilers::LFortran::BodyVisitor&)
    case stmtType::Assignment: { v.visit_Assignment((const Assignment_t &)x); return; }
  File "/home/harshil-shah/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 2866, in LCompilers::LFortran::BodyVisitor::visit_Assignment(LCompilers::LFortran::AST::Assignment_t const&)
    this->visit_expr(*x.m_value);
  File "/home/harshil-shah/lfortran/src/lfortran/ast.h", line 5069, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_expr(LCompilers::LFortran::AST::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/home/harshil-shah/lfortran/src/lfortran/ast.h", line 4722, in void LCompilers::LFortran::AST::visit_expr_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::expr_t const&, LCompilers::LFortran::BodyVisitor&)
    case exprType::FuncCallOrArray: { v.visit_FuncCallOrArray((const FuncCallOrArray_t &)x); return; }
  File "/home/harshil-shah/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 7976, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::visit_FuncCallOrArray(LCompilers::LFortran::AST::FuncCallOrArray_t const&)
    v = intrinsic_as_node(x, is_function);
  File "/home/harshil-shah/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 7358, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::intrinsic_as_node(LCompilers::LFortran::AST::FuncCallOrArray_t const&, bool&)
    tmp = create_ArrayReshape(x);
  File "/home/harshil-shah/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 6488, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::create_ArrayReshape(LCompilers::LFortran::AST::FuncCallOrArray_t const&)
    ASR::Array_t* newshape_array_type = ASR::down_cast<ASR::Array_t>(ASRUtils::expr_type(newshape));
AssertFailed: is_a<T>(*f)
```

### PR DESCRIPTION
**Pull request by galactus3050**
Fixes #6437

### CODE REVIEW

**Comment by galactus3050** [comment]
I believe the failure is unrelated to my PR. Please review

File: tests/errors/continue_compilation_1.f90 [hunk 1]
```diff
@@ -199,4 +199,14 @@ subroutine my_func(x, y)
     print *, iparity(["a", "b"])
     print *, parity(["a", "b"])
 
+    integer, allocatable ::  shape_(:)
```
Comment (gxyd) [inline tests/errors/continue_compilation_1.f90:202]: I'm not really happy with having these declarations here (GFortran doesn't even allow them), they should raise an error of their own to not allow declarations after statements, currently LFortran doesn't raise an error for these (which is an open issue), ideally we should move these declarations to the top maybe?

File: src/lfortran/semantics/ast_common_visitor.h [hunk 2]
```diff
@@ -6502,7 +6502,13 @@ class CommonVisitor : public AST::BaseVisitor<Derived> {
         }
         ASR::array_physical_typeType array_physical_type = ASRUtils::extract_physical_type(
                                                             ASRUtils::expr_type(array));
-
+        ASR::ttype_t* shape_type = ASRUtils::expr_type(newshape);
```
Comment (gxyd) [inline src/lfortran/semantics/ast_common_visitor.h:6505]: The fix here looks good to me.

File: tests/errors/continue_compilation_1.f90 [hunk 3]
```diff
@@ -10,8 +10,44 @@ program continue_compilation_1
...
+
+
+
+
+
+
+
+
+
+
```
Comment (HarshitaKalani) [inline tests/errors/continue_compilation_1.f90:50]: Can you please remove these blank lines?

File: tests/errors/continue_compilation_1.f90 [hunk 4]
```diff
@@ -10,8 +10,44 @@ program continue_compilation_1
     integer, parameter :: i1 = 2
     character(len=5) :: string = "hello"
 	character(len=1) :: set(2) = ["l", "h"]
```
Comment (HarshitaKalani) [inline tests/errors/continue_compilation_1.f90:12]:
```suggestion
character(len=1) :: set(2) = ["l", "h"]
```

File: tests/errors/continue_compilation_1.f90 (hunk 3 above)
Comment (HarshitaKalani) [reply tests/errors/continue_compilation_1.f90:50]: Oh I see, this is addressing: https://github.com/lfortran/lfortran/pull/6441#discussion_r1975693431.
It's fine.

**Review by HarshitaKalani — APPROVED** [review]
Looks good.
