### PR TITLE
CPP: add `#elif` handling

### LINKED ISSUE #3202: Preprocessor incomplete?
Related to #2492.

Our preprocessor seems incomplete, `#elif` gets ignored, e.g.
```f90
print *, __LFORTRAN__
#ifdef __GNU__
#elif defined(__LFORTRAN__)
print *, __LFORTRAN__
#endif
```

And it cannot process CMake's compiler test file [CMakeFortranCompilerId.F]:(https://github.com/lfortran/lfortran/files/14056118/CMakeFortranCompilerId.F.zip)

```
lfortran --cpp CMakeFortranCompilerId.F
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/usr/bin/lfortran", in _start()
  Binary file "/lib64/libc.so.6", in __libc_start_main_alias_2()
  Binary file "/lib64/libc.so.6", in __libc_start_call_main()
  Binary file "/usr/bin/lfortran", in main()
  Binary file "/usr/bin/lfortran", in main_app(int, char**)
  Binary file "/usr/bin/lfortran", in _get_rpath_from_linker_flags(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, LCompilers::CompilerOptions&)
  Binary file "/usr/bin/lfortran", in LCompilers::FortranEvaluator::get_asr2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::diag::Diagnostics&)
  Binary file "/usr/bin/lfortran", in LCompilers::FortranEvaluator::get_ast2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::diag::Diagnostics&)
  Binary file "/usr/bin/lfortran", in LCompilers::LFortran::CPreprocessor::run(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::LocationManager&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::LFortran::CPPMacro, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::LFortran::CPPMacro> > >&) const
  Binary file "/usr/bin/lfortran", in LCompilers::LFortran::get_next_token(unsigned char*&, LCompilers::LFortran::CPPTokenType&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)
  Binary file "/usr/bin/lfortran", in LCompilers::LFortran::get_next_token(unsigned char*&, LCompilers::LFortran::CPPTokenType&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)
  Binary file "/usr/bin/lfortran", in LCompilers::LFortran::get_next_token(unsigned char*&, LCompilers::LFortran::CPPTokenType&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)
  Binary file "/usr/bin/lfortran", in LCompilers::LFortran::get_next_token(unsigned char*&, LCompilers::LFortran::CPPTokenType&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)
  Binary file "/usr/bin/lfortran", in LCompilers::LFortran::get_next_token(unsigned char*&, LCompilers::LFortran::CPPTokenType&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)
  Binary file "/usr/bin/lfortran", in LCompilers::LFortran::get_next_token(unsigned char*&, LCompilers::LFortran::CPPTokenType&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)
  Binary file "/usr/bin/lfortran", in LCompilers::LFortran::get_next_token(unsigned char*&, LCompilers::LFortran::CPPTokenType&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)
  Binary file "/usr/bin/lfortran", in LCompilers::LFortran::get_next_token(unsigned char*&, LCompilers::LFortran::CPPTokenType&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)
  Binary file "/usr/bin/lfortran", in LCompilers::LFortran::get_next_token(unsigned char*&, LCompilers::LFortran::CPPTokenType&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)
  Binary file "/usr/bin/lfortran", in LCompilers::LFortran::get_next_token(unsigned char*&, LCompilers::LFortran::CPPTokenType&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)
  Binary file "/usr/bin/lfortran", in LCompilers::LFortran::get_next_token(unsigned char*&, LCompilers::LFortran::CPPTokenType&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)
  Binary file "/usr/bin/lfortran", in LCompilers::LFortran::get_next_token(unsigned char*&, LCompilers::LFortran::CPPTokenType&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)
  Binary file "/usr/bin/lfortran", in LCompilers::LFortran::get_next_token(unsigned char*&, LCompilers::LFortran::CPPTokenType&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)
  Binary file "/usr/bin/lfortran", in LCompilers::LFortran::get_next_token(unsigned char*&, LCompilers::LFortran::CPPTokenType&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)
  Binary file "/usr/bin/lfortran", in LCompilers::LFortran::get_next_token(unsigned char*&, LCompilers::LFortran::CPPTokenType&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)
  Binary file "/usr/bin/lfortran", in LCompilers::LFortran::get_next_token(unsigned char*&, LCompilers::LFortran::CPPTokenType&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)
LCompilersException: Unknown token: %
```

### PR DESCRIPTION
**Pull request by certik**
Towards #3202.

### CODE REVIEW

File: build0.sh [hunk 1]
```diff
@@ -16,8 +16,9 @@ python src/libasr/wasm_instructions_visitor.py
 python src/libasr/intrinsic_func_registry_util_gen.py
 
 # Generate the tokenizer and parser
-(cd src/lfortran/parser && re2c -W -b tokenizer.re -o tokenizer.cpp)
-(cd src/lfortran/parser && re2c -W -b preprocessor.re -o preprocessor.cpp)
+(cd src/lfortran && re2c -W -b parser/tokenizer.re -o parser/tokenizer.cpp)
+(cd src/lfortran && re2c -W -b parser/preprocessor.re -o parser/preprocessor.cpp)
+(cd src/lfortran && re2c -W -b parser/preprocessor.re -o parser/preprocessor.cpp)
```
Comment (junghans) [inline build0.sh:21]: Do you purposely run the last line twice?

Comment (certik) [reply build0.sh:21]: Great catch!

**Comment by certik** [comment]
The failure is unrelated.
