### PR TITLE
fix: get correct struct symbol from implied do loop

### LINKED ISSUE #8183: add m_type_declaration for arrayconstructor temporary in implied do loop
MRE:
```fortran
program temp 
type :: my_type
  integer :: a
end type 
integer :: i
type(my_type) :: arr(3)
    arr = [(my_type(i),i=1,3)]
end program
```

LFortran Error:
```console
(lf) jinang_shah@JNSLAP:~/Desktop/lfortran$ lfortran c.f90
ASR verify pass error: Variable __libasr__created__var__0__array_constructor_ of type StructType must have a type declaration.
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/jinang_shah/Desktop/lfortran/src/bin/lfortran", in _start
  File "./csu/../csu/libc-start.c", line 360, in __libc_start_main
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main
  File "/home/jinang_shah/Desktop/lfortran/src/bin/lfortran.cpp", line 2729, in main
    return main_app(argc, argv);
  File "/home/jinang_shah/Desktop/lfortran/src/bin/lfortran.cpp", line 2653, in main_app(int, char**)
    err = compile_src_to_object_file(arg_file, tmp_o, compiler_options.time_report, false,
  File "/home/jinang_shah/Desktop/lfortran/src/bin/lfortran.cpp", line 1184, in (anonymous namespace)::compile_src_to_object_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, LCompilers::CompilerOptions&, LCompilers::PassManager&, bool)
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile, &time_opt);
  File "/home/jinang_shah/Desktop/lfortran/src/lfortran/fortran_evaluator.cpp", line 393, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int*)
    compiler_options, run_fn, "", infile);
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 12725, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/home/jinang_shah/Desktop/lfortran/src/libasr/pass/pass_manager.h", line 318, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    apply_passes(al, asr, _passes, pass_options, diagnostics, cummulative_time_taken_by_passes_in_microseconds);
LCompilersException: Verify failed in the pass: implied_do_loops
```

### PR DESCRIPTION
**Pull request by jinangshah21**
Fixes #8183

### CODE REVIEW

File: src/libasr/asr_utils.cpp [hunk 1]
```diff
@@ -194,9 +194,11 @@ ASR::symbol_t* get_struct_sym_from_struct_expr(ASR::expr_t* expression)
                 // If `func_call->m_dt` is not null, it means that the function call
                 // is returning a struct type.
                 return ASRUtils::symbol_get_past_external(ASRUtils::get_struct_sym_from_struct_expr(func_call->m_dt));
-            } else {
+            } else if (ASR::is_a<ASR::Function_t>(*ASRUtils::symbol_get_past_external(func_call->m_name))) {
                 ASR::Function_t* func = ASR::down_cast<ASR::Function_t>(ASRUtils::symbol_get_past_external(func_call->m_name));
                 return ASRUtils::symbol_get_past_external(ASRUtils::get_struct_sym_from_struct_expr(func->m_return_var));
+            } else {
+                return nullptr;
```
Comment (Pranavchiku) [inline src/libasr/asr_utils.cpp:201]: This can be anything other than `ASR::Function_t`, maybe `StructMethodDeclaration` or `Variable` (procedure), let's throw an error with type information.
