### PR TITLE
enh: openmp pass to handle pragma inside do loop

### LINKED ISSUE #4388: OpenMP example
Here is a fixed up OpenMP example from https://fortran-lang.discourse.group/t/openmp-code-implementation-in-gfortran-and-intel/8256:
```fortran
program openmp_test
    implicit none

    !=============

    integer ( kind = 4 ), parameter :: Nx = 100
    integer ( kind = 4 ), parameter :: Ny = 100
    real ( kind = 8 )               :: dx = 0.03
    real ( kind = 8 )               :: dy = 0.03

    !=============

    integer (kind = 4 ) :: nsteps = 1000
    integer (kind = 4 ) :: nprint = 100
    integer (kind = 4 ) :: tsteps
    real ( kind = 8 )   :: dtime  = 1.0e-4

    !===============

    real ( kind = 8 )   :: tau   = 0.0003
    real ( kind = 8 )   :: epsilonb = 0.01
    real ( kind = 8 )   :: kappa = 1.8
    real ( kind = 8 )   :: delta = 0.02
    real ( kind = 8 )   :: aniso = 6.0
    real ( kind = 8 )   :: alpha = 0.9
    real ( kind = 8 )   :: gama  = 10.0
    real ( kind = 8 )   :: teq   = 1.0
    real ( kind = 8 )   :: theta0= 0.2
    real ( kind = 8 )   :: seed  = 5.0

    real ( kind = 8 )   :: pix   = 4.0*atan(1.0)

    !===============

    real ( kind = 8 ) , dimension( Nx, Ny ) :: phi, tempr
    real ( kind = 8 ) , dimension( Nx, Ny ) :: lap_phi, lap_tempr
    real ( kind = 8 ) , dimension( Nx, Ny ) :: phidx, phidy
    real ( kind = 8 ) , dimension( Nx, Ny ) :: epsil, epsilon_deriv
    real ( kind = 8 )                       :: phi_old, term1, term2
    real ( kind = 8 )                       :: theta, m
    integer ( kind = 4 )                    :: i, j, ip, im, jp, jm



    !============================================================




    phi = 0.0
    tempr = 0.0

    do i = 1, Nx
        do j = 1, Ny
            if ( (i - Nx/2.0)*(i - Nx/2.0) + (j - Ny/2.0)*(j - Ny/2.0)&
            & < seed ) then
                phi(i,j) = 1.0
            end if
        end do
    end do




    !============================================================



    time_loop: do tsteps = 1, nsteps


        !$omp parallel do private(i,j,ip,im,jp,jm,theta)

        do j = 1, Ny
            do i =1, Nx

                jp = j + 1
                jm = j - 1

                ip = i + 1
                im = i - 1

                if ( im == 0 ) im = Nx
                if ( ip == ( Nx + 1) ) ip = 1
                if ( jm == 0 ) jm = Ny
                if ( jp == ( Ny + 1) ) jp = 1

                !=====

                lap_phi(i,j) = ( phi(ip,j) + phi(im,j) + phi(i,jm) + phi(i,jp)&
                & - 4.0*phi(i,j)) / ( dx*dy )
                lap_tempr(i,j) = ( tempr(ip,j) + tempr(im,j) + tempr(i,jm) + &
                & tempr(i,jp) - 4.0*tempr(i,j)) / ( dx*dy )

                !======

                phidx(i,j) = ( phi(ip,j) - phi(im,j) ) / dx
                phidy(i,j) = ( phi(i,jp) - phi(i,jm) ) / dy

                !======

                theta  = atan2( phidy(i,j),phidx(i,j) )

                !======

                epsil(i,j) = epsilonb*( 1.0 + delta*cos(aniso*&
                & ( theta - theta0 ) ) )
                epsilon_deriv(i,j) = -epsilonb*aniso*delta*sin&
                & ( aniso*( theta - theta0 ) )

            end do
        end do

        !$omp end parallel do


        !$omp parallel do private(i,j,ip,im,jp,jm,phi_old,term1,term2,tempr)

        do j = 1, Ny
            do i =1, Nx

                jp = j + 1
                jm = j - 1

                ip = i + 1
                im = i - 1

                if ( im == 0 ) im = Nx
                if ( ip == ( Nx + 1) ) ip = 1
                if ( jm == 0 ) jm = Ny
                if ( jp == ( Ny + 1) ) jp = 1

                phi_old = phi(i,j)

                !========

                term1 = ( epsil(i,jp)*epsilon_deriv(i,jp)*phidx(i,jp)&
                & - epsil(i,jm)*epsilon_deriv(i,jm)*phidx(i,jm) ) / dy
                term2 = -( epsil(ip,j)*epsilon_deriv(ip,j)*phidy(ip,j)&
                & - epsil(im,j)*epsilon_deriv(im,j)*phidy(im,j) ) / dx

                !========

                m = alpha/pix*atan( gama*( teq - tempr(i,j) ) )

                !========

                phi(i,j) = phi(i,j) + ( dtime/tau )*( term1 + term2 +&
                & epsil(i,j)**2*lap_phi(i,j) ) + &
                & phi_old*( 1.0 - phi_old )*( phi_old -0.5 + m )
                tempr(i,j) = tempr(i,j) + dtime*lap_tempr(i,j) &
                & + kappa*( phi(i,j) - phi_old )

            end do
        end do
        !$omp end parallel do


        ! print steps

        if ( mod( tsteps, nprint ) .eq. 0 ) print *, 'Done steps  =  ', tsteps



    end do time_loop


    !============================================================================
    ! output file

    open ( 1, file = "phi.dat" )
    do i = 1, Nx
        write( 1, 10 ) ( phi(i,j),j = 1, Ny )
    end do
    10 FORMAT(1000000F10.6)
    close( 1 )



end program openmp_test
```

It almost works with LFortran:
```console
$ lfortran -o xx a.f90
$ ./xx
Done steps  =   100
Done steps  =   200
Done steps  =   300
Done steps  =   400
Done steps  =   500
Done steps  =   600
Done steps  =   700
Done steps  =   800
Done steps  =   900
Done steps  =   1000
[HANG]
```

Let's report an MRE for the hang. Then apply this patch:
```fortran
    print *, phi(:2,:2)
!    open ( 1, file = "phi.dat" )
!    do i = 1, Nx
!        write( 1, 10 ) ( phi(i,j),j = 1, Ny )
!    end do
!    10 FORMAT(1000000F10.6)
!    close( 1 )
```
In serial it agrees with GFortran:
```console
$ lfortran a.f90
style suggestion: Use '==' instead of '.eq.'
   --> a.f90:161:36
    |
161 |         if ( mod( tsteps, nprint ) .eq. 0 ) print *, 'Done steps  =  ', tsteps
    |                                    ^^^^ help: write this as '=='


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
Done steps  =   100
Done steps  =   200
Done steps  =   300
Done steps  =   400
Done steps  =   500
Done steps  =   600
Done steps  =   700
Done steps  =   800
Done steps  =   900
Done steps  =   1000
8.12009330895841880e-23 5.29391098848010228e-23
3.57480498898115721e-22 1.20244514143295107e-22

$ gfortran a.f90 && ./a.out
 Done steps  =           100
 Done steps  =           200
 Done steps  =           300
 Done steps  =           400
 Done steps  =           500
 Done steps  =           600
 Done steps  =           700
 Done steps  =           800
 Done steps  =           900
 Done steps  =          1000
   8.1213034304693946E-023   3.5747701553385965E-022   5.2941999399679490E-023   1.2024184771981686E-022
```
We print the array as matrix, GFortran prints in column-major order, but the elements agree to about 6 significant digits.

With OpenMP:
```console
$ gfortran -fopenmp a.f90 && ./a.out
 Done steps  =           100
 Done steps  =           200
 Done steps  =           300
 Done steps  =           400
 Done steps  =           500
 Done steps  =           600
 Done steps  =           700
 Done steps  =           800
 Done steps  =           900
 Done steps  =          1000
   1.3566926973936031E-023   1.8500023055360351E-023   1.8546499641547335E-023   7.7407243664235237E-023
$ lfortran --openmp a.f90
style suggestion: Use '==' instead of '.eq.'
   --> a.f90:161:36
    |
161 |         if ( mod( tsteps, nprint ) .eq. 0 ) print *, 'Done steps  =  ', tsteps
    |                                    ^^^^ help: write this as '=='


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
ASR verify pass error: ASR verify: The symbol table was found and the symbol in it shares the name, but is not equal to `sym`

ASR verify pass error: Var::m_v `phi` cannot point outside of its symbol table
Internal Compiler Error: Unhandled exception
```

The GFortran results change, so probably the code is not quite correct.  And LFortran gives an internal compiler error, which we should report as MRE and fix.

### PR DESCRIPTION
**Pull request by Pranavchiku**
Fixes #4388. Towads #3777. With this PR we get it working.
> Serial

```console
% gfortran b.f90 && ./a.out 
 Done steps  =           100
 Done steps  =           200
 Done steps  =           300
 Done steps  =           400
 Done steps  =           500
 Done steps  =           600
 Done steps  =           700
 Done steps  =           800
 Done steps  =           900
 Done steps  =          1000
   8.1156792211894978E-023   3.5746070221702888E-022   5.2919810042527039E-023   1.2024036703484373E-022

% lfortran b.f90 
style suggestion: Use '==' instead of '.eq.'
   --> b.f90:161:36
    |
161 |         if ( mod( tsteps, nprint ) .eq. 0 ) print *, 'Done steps  =  ', tsteps
    |                                    ^^^^ help: write this as '=='


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
Done steps  =   100
Done steps  =   200
Done steps  =   300
Done steps  =   400
Done steps  =   500
Done steps  =   600
Done steps  =   700
Done steps  =   800
Done steps  =   900
Done steps  =   1000
8.11890548559992338e-23 5.29347833517143053e-23 
3.57477363872004304e-22 1.20244357112337166e-22 

```

> openmp

```console
% lfortran b.f90 --openmp --openmp-lib-dir=$CONDA_PREFIX/lib       
style suggestion: Use '==' instead of '.eq.'
   --> b.f90:161:36
    |
161 |         if ( mod( tsteps, nprint ) .eq. 0 ) print *, 'Done steps  =  ', tsteps
    |                                    ^^^^ help: write this as '=='


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
Done steps  =   100
Done steps  =   200
Done steps  =   300
Done steps  =   400
Done steps  =   500
Done steps  =   600
Done steps  =   700
Done steps  =   800
Done steps  =   900
Done steps  =   1000
8.11890548559992338e-23 5.29347833517143053e-23 
3.57477363872004304e-22 1.20244357112337166e-22 

% gfortran b.f90 -fopenmp && ./a.out
 Done steps  =           100
 Done steps  =           200
 Done steps  =           300
 Done steps  =           400
 Done steps  =           500
 Done steps  =           600
 Done steps  =           700
 Done steps  =           800
 Done steps  =           900
 Done steps  =          1000
  0.57349606629159489       0.56949953099083217       0.56946976603681299       0.56929291068471366 
```

### CODE REVIEW

File: src/libasr/pass/openmp.cpp [hunk 1]
```diff
@@ -1306,10 +1333,14 @@ class DoConcurrentVisitor :
             pass_result.push_back(al, ASRUtils::STMT(ASR::make_SubroutineCall_t(al, x.base.base.loc, current_scope->get_symbol("gomp_parallel"), nullptr,
                                 call_args.p, call_args.n, nullptr)));
 
-            // update all reduction variables in statements after this.
-            ReductionVariableVisitor rvv(al, current_scope, ASRUtils::symbol_name(thread_data_sym), data_expr, reduction_variables);
-            for (size_t i = current_stmt_index + 1; i < current_n_body; i++) {
-                rvv.visit_stmt(*current_m_body[i]);
```
Comment (Pranavchiku) [inline src/libasr/pass/openmp.cpp:1312]: In subsequent PRs we can remover `ReductionVariableVisitor` OR maybe keep it in case we come across where we need it.

**Comment by Pranavchiku** [comment]
Once this PR is merged, we shall make a new release `v0.37.0`.

**Comment by certik** [comment]
Go ahead and make a release.
