### PR TITLE
Refined Rank mismatch error

### LINKED ISSUE #6576: bug: Incorrect initialization of rank mismatched arrays
MRE
```fortran
program main
    integer, dimension(3, 2) :: a = [1, 2, 3, 4, 5, 6]
end program
```
Lfortran
```console
(lf) harshil-shah@harshil-shah-HP-Pavilion-Laptop-15-eg2xxx:~/lfortran$ lfortran --version
LFortran version: 0.48.0-21-g019b6c7c7
Platform: Linux
LLVM: 11.0.1
Default target: x86_64-unknown-linux-gnu
(lf) harshil-shah@harshil-shah-HP-Pavilion-Laptop-15-eg2xxx:~/lfortran$ lfortran a.f90

```

Gfortran
```console
(lf) harshil-shah@harshil-shah-HP-Pavilion-Laptop-15-eg2xxx:~/lfortran$ gfortran a.f90 && ./a.out
examples/expr2.f90:2:33:

    2 |     integer, dimension(3, 2) :: a = [1, 2, 3, 4, 5, 6]
      |                                 1
Error: Incompatible ranks 2 and 1 in assignment at (1)
```

### PR DESCRIPTION
**Pull request by rahulrangers**
fixes #6576
Improving PR #6581

- Highlights **only the RHS initializer** in the error (previously, the entire line was highlighted)
- Displays the **actual ranks** of both the LHS and RHS in the error message

### CODE REVIEW

File: src/lfortran/semantics/ast_common_visitor.h [hunk 1]
```diff
@@ -4132,10 +4132,12 @@ class CommonVisitor : public AST::BaseVisitor<Derived> {
                         ASR::Array_t* rhs_array
                             = ASR::down_cast<ASR::Array_t>(ASRUtils::expr_type(tmp_init));
                         if (lhs_array->n_dims != rhs_array->n_dims) {
-                            diag.add(Diagnostic("Incompatible ranks in assignment",
+                            diag.add(Diagnostic(
+                                "Incompatible ranks `"+ std::to_string(lhs_array->n_dims) + "` and `"
+                                                                  + std::to_string(rhs_array->n_dims) + "` in assignment",
```
Comment (kmr-srbh) [inline src/lfortran/semantics/ast_common_visitor.h]:
```suggestion
                                "Incompatible ranks "+ std::to_string(lhs_array->n_dims) + " and "
                                                                  + std::to_string(rhs_array->n_dims) + " in assignment",
```

Let's not use backticks for numbers. We use them for highlighting symbol names like variables.

File: tests/reference/asr-continue_compilation_2-a6145a1.stderr [hunk 2]
```diff
@@ -242,11 +242,11 @@ semantic error: Keyword argument not found
...
     |                                 ^^^^^^^^^^^^^^^^^^^^ 'mykeyword' keyword argument not found
 
-semantic error: Incompatible ranks in assignment
-   --> tests/errors/continue_compilation_2.f90:199:5
+semantic error: Incompatible ranks `2` and `1` in assignment
+   --> tests/errors/continue_compilation_2.f90:199:36
     |
 199 |     integer, dimension(3,2) :: m = [ 1, 0, 0, 2, 4, 6 ]
-    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
+    |                                    ^^^^^^^^^^^^^^^^^^^^
```
Comment (kmr-srbh) [inline tests/reference/asr-continue_compilation_2-a6145a1.stderr]: After making the above change, you will need to push the new references.

**Review by kmr-srbh — DISMISSED** [review]
The changes are correct. Please make the requested changes and we can merge this.

**Comment by kmr-srbh** [comment]
Thanks!
