### PR TITLE
enh: point to array descriptor of pointer to array when allocating after nullifying it

### LINKED ISSUE #4466: bug: allocation after nullifying results in segmentation fault
**MRE**
```Fortran 
program name
    integer , dimension(:), pointer :: ptr
    nullify(ptr)
    allocate(ptr(10))
end program name
```

### PR DESCRIPTION
**Pull request by kmr-srbh**
fixes #4466 

This PR is an improved version of #4508 building upon the provided suggestion.

### CODE REVIEW

File: src/libasr/codegen/asr_to_llvm.cpp [hunk 1]
```diff
@@ -1032,6 +1032,21 @@ class ASRToLLVMVisitor : public ASR::BaseVisitor<ASRToLLVMVisitor>
...
+                            llvm::Type::getInt32Ty(context))),
+                    [&]() {
+                        llvm::Type* type = llvm_utils->get_type_from_ttype_t_util(
+                            ASRUtils::type_get_past_pointer(ASRUtils::type_get_past_allocatable(
+                                ASRUtils::expr_type(tmp_expr))), module.get());
+                        llvm::Value* ptr_ = builder->CreateAlloca(type, nullptr);
+                        arr_descr->fill_dimension_descriptor(ptr_, n_dims);
+                        LLVM::CreateStore(*builder, ptr_, x_arr);
+                    },
+                    []() {});
```
Comment (certik) [inline src/libasr/codegen/asr_to_llvm.cpp:1049]: This looks much simpler than the last PR. This if statement implements the steps outlined in https://github.com/lfortran/lfortran/pull/4508#discussion_r1677172066.

@czgdp1807, does this look good to you?

**Review by czgdp1807 — APPROVED** [review]
For now this is fine.
