### PR TITLE
fix : Do not return from instantiate function and populate llvm_symtab_fn for class interfaces

### LINKED ISSUE #7270: [stdlib:hashmaps] Calling type-bound procedure declared via module and implemented in submodule is causing `code generation error`
MRE :- 
```.f90
module stdlib_hashmaps
    implicit none
    private

    public ::  open_hashmap_type

    type :: open_hashmap_type
    contains
        procedure :: map_entry => map_open_entry
    end type open_hashmap_type

    interface
        module subroutine map_open_entry(map, key)
            class(open_hashmap_type), intent(inout) :: map
            integer, intent(in) :: key
        end subroutine map_open_entry
    end interface
    
end module stdlib_hashmaps

submodule(stdlib_hashmaps) stdlib_hashmap_open
    implicit none
contains

    module subroutine map_open_entry(map, key)
        class(open_hashmap_type), intent(inout) :: map
        integer, intent(in) :: key
    end subroutine map_open_entry

end submodule stdlib_hashmap_open

program main
    use stdlib_hashmaps, only : open_hashmap_type

    implicit none

    type(open_hashmap_type)   :: map
    integer :: key
    call map % map_entry( key )

end program
```

LFortran CodeGen Error :- 
```console
(lf) lordansh@LordAnsh:~/dev/lfort4/lfortran$ lfortran test.f90
code generation error: Subroutine code not generated for 'map_open_entry'


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

MRE works well with gfortran .

### PR DESCRIPTION
**Pull request by AnshMehta1**
Towards #536 
Fixes #7270
Addresses https://github.com/lfortran/lfortran/pull/8010#pullrequestreview-3004223332

### CODE REVIEW

File: src/libasr/codegen/asr_to_llvm.cpp [hunk 1]
```diff
@@ -4668,7 +4668,7 @@ class ASRToLLVMVisitor : public ASR::BaseVisitor<ASRToLLVMVisitor>
             F = llvm_symtab_fn[h];
         } else {
             llvm::FunctionType* function_type = llvm_utils->get_function_type(x, module.get());
-            if( ASRUtils::get_FunctionType(x)->m_deftype == ASR::deftypeType::Interface ) {
+            if( ASRUtils::get_FunctionType(x)->m_deftype == ASR::deftypeType::Interface && !ASRUtils::get_FunctionType(x)->m_module ) {
```
Comment (Pranavchiku) [inline src/libasr/codegen/asr_to_llvm.cpp:4671]: Ahh I see, you are handling cases for class. PR name suggests that we generate object code for `module ` interfaces.

Comment (AnshMehta1) [reply src/libasr/codegen/asr_to_llvm.cpp:4671]: Ya, I named it generally, like whenever we have module interfaces, then we don't return from instantiate function. Will change the name.
