### PR TITLE
fix: handle copy of arrays offsets inside deepcopy for structs

### LINKED ISSUE #11244: fix: Copy of struct fails after calling multiple copies
Towards #11144 

Here, MRE is intentionally kept bigger with many fields, similar to the original bug. Here, reducing any struct field makes the MRE pass in main, so testing with struct fields is important.

MRE:
```fortran
program copy_mre
  implicit none
  integer, parameter :: dp=kind(0.d0), nslots=100, s=200, n=80, m=1000

  type :: var_t
    character(len=n) :: var_name=""
    character(len=s) :: description=""
    integer :: var_type=0
    character(len=m) :: stored_data=""
    real(dp), allocatable :: real_data(:)
    character(len=s), allocatable :: char_data(:)
  end type

  type :: cfg_t
    integer :: num_vars=0
    type(var_t), allocatable :: vars(:)
  end type

  type(cfg_t) :: cfg

  call init(cfg)
  call probe(cfg, "Copy 1")  ! When this line is commented, code works fine

  deallocate(cfg%vars(1)%real_data)
  allocate(cfg%vars(1)%real_data(2))
  cfg%vars(1)%real_data = [1.0_dp, 2.0_dp]
  cfg%vars(2)%char_data(1) = "J."
  cfg%vars(3)%char_data = [character(len=s) :: "H.J.", "Teunissen"]
  cfg%vars(4)%char_data(1) = "another_file"

  call probe(cfg, "Copy 2")

contains

  subroutine init(cfg)
    type(cfg_t), intent(out) :: cfg
    allocate(cfg%vars(nslots))
    cfg%num_vars = 4

    cfg%vars(1)%var_name = "author%fav_reals"
    cfg%vars(1)%description = "favorite reals"
    cfg%vars(1)%var_type = 2
    allocate(cfg%vars(1)%real_data(3))
    cfg%vars(1)%real_data = [1.337_dp, 13.37_dp, 133.7_dp]

    cfg%vars(2)%var_name = "author_name%first"
    cfg%vars(2)%description = "first name"
    cfg%vars(2)%var_type = 3
    allocate(cfg%vars(2)%char_data(1))
    cfg%vars(2)%char_data(1) = "jannis"

    cfg%vars(3)%var_name = "author_name%full"
    cfg%vars(3)%description = "full name"
    cfg%vars(3)%var_type = 3
    allocate(cfg%vars(3)%char_data(2))
    cfg%vars(3)%char_data = [character(len=s) :: "Jannis", "Teunissen"]

    cfg%vars(4)%var_name = "filename"
    cfg%vars(4)%description = "filename"
    cfg%vars(4)%var_type = 3
    allocate(cfg%vars(4)%char_data(1))
    cfg%vars(4)%char_data(1) = "this/is/a/filename"
  end subroutine

  subroutine probe(src, label)
    type(cfg_t), intent(in) :: src
    character(len=*), intent(in) :: label
    type(cfg_t) :: dst

    print *, "---- ", trim(label), " PRE-COPY ----"
    print *, "first    = '", trim(src%vars(2)%char_data(1)), "'"
    print *, "filename = '", trim(src%vars(4)%char_data(1)), "'"

    dst = src

    print *, "---- ", trim(label), " POST-COPY ----"
    print *, "first    = '", trim(dst%vars(2)%char_data(1)), "'"
    print *, "filename = '", trim(dst%vars(4)%char_data(1)), "'"
  end subroutine

end program
```

Main:
```bash

$ lfortran a.f90
---- Copy 1 PRE-COPY ----
first    = 'jannis'
filename = 'this/is/a/filename'
---- Copy 1 POST-COPY ----
first    = 'jannis'
filename = 'this/is/a/filename'
---- Copy 2 PRE-COPY ----
first    = 'J.'
filename = 'another_file'
---- Copy 2 POST-COPY ----
first    = 'J.'
filename = ' �'

$ gfortran a.f90 & ./a.out
[1]+  Done                    gfortran a.f90
[1] 72249
 ---- Copy 1 PRE-COPY ----
 first    = 'jannis'
 filename = 'this/is/a/filename'
 ---- Copy 1 POST-COPY ----
 first    = 'jannis'
 filename = 'this/is/a/filename'
 ---- Copy 2 PRE-COPY ----
 first    = 'J.'
 filename = 'another_file'
 ---- Copy 2 POST-COPY ----
 first    = 'J.'
 filename = 'another_file'
```

### PR DESCRIPTION
**Pull request by YashNagda17**
Towards #11144 
Fixes #11244

Issue: Current design didn't copy the array offset inside deepcopies of structs.
This caused arrays to have garbage-values.

fix: Instead of manually copying all the metadata, reuse the backend array api `fill_array_details`,
to handle the copy operation correctly, which handles offsets as well.

### CODE REVIEW

**Review by certik — APPROVED** [review]

File: integration_tests/allocatable_component_struct_array_02.f90 [hunk 1]
```diff
@@ -0,0 +1,181 @@
...
+    end if
+    if (trim(dst%vars(4)%char_data(1)) /= "another_file") then
+      print *, "FAIL copy2: vars(4)%char_data(1): ", trim(dst%vars(4)%char_data(1))
+      error stop
+    end if
+
+    print *, "All Copy 2 Tests Passed"
+  end subroutine
+
+end program allocatable_component_struct_array_02
```
Comment (certik) [inline integration_tests/allocatable_component_struct_array_02.f90:181]: I think all these tests are not needed, next time I think it's better to just put in the MRE, so minimal tests that exercise the new code change. But it's fine for now, so I merged it.
