### PR TITLE
Fix doloop with variable increment

### LINKED ISSUE #946: LLVM: do loop with a skip and continue inside fails
Here is a minimal reproducible example:
```fortran
subroutine f()
integer :: i, n
do i = 1, 10, n
    100 continue
end do
end subroutine
```
Which fails. If you remove `100 continue`, or if you remove `, n`, it will work. Here is the failure:
```console
$ lfortran --show-llvm a.f90 
; ModuleID = 'LFortran'
source_filename = "LFortran"

define void @f() {
.entry:
  %i = alloca i32, align 4
  %n = alloca i32, align 4
  %0 = load i32, i32* %n, align 4
  %1 = icmp sgt i32 %0, 0
  br i1 %1, label %then, label %else

then:                                             ; preds = %.entry
  %2 = load i32, i32* %n, align 4
  %3 = sub i32 1, %2
  store i32 %3, i32* %i, align 4
  br label %loop.head

loop.head:                                        ; preds = %goto_target3, %then
  %4 = load i32, i32* %i, align 4
  %5 = load i32, i32* %n, align 4
  %6 = add i32 %4, %5
  %7 = icmp sle i32 %6, 10
  br i1 %7, label %loop.body, label %loop.end

loop.body:                                        ; preds = %loop.head
  %8 = load i32, i32* %i, align 4
  %9 = load i32, i32* %n, align 4
  %10 = add i32 %8, %9
  store i32 %10, i32* %i, align 4
  br label %goto_target3

goto_target3:                                     ; preds = %loop.body2, %loop.body
  br label %loop.head
  br label %loop.head1

loop.end4:                                        ; preds = %loop.head1
  br label %ifcont

ifcont:                                           ; preds = %loop.end4, %loop.end
  br label %return

return:                                           ; preds = %ifcont
  ret void
}
lfortran(79209,0x108308580) malloc: *** error for object 0x60000293ce40: pointer being freed was not allocated
lfortran(79209,0x108308580) malloc: *** set a breakpoint in malloc_error_break to debug
Traceback (most recent call last):
  Binary file "/usr/lib/system/libsystem_malloc.dylib", local address: 0x180121fa7
  Binary file "/usr/lib/system/libsystem_malloc.dylib", local address: 0x18013305f
  Binary file "/usr/lib/system/libsystem_malloc.dylib", local address: 0x18012fa1b
  Binary file "/usr/lib/system/libsystem_c.dylib", local address: 0x18024a313
  Binary file "/usr/lib/system/libsystem_pthread.dylib", local address: 0x18030ceaf
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x1803244e3
Abort: Signal SIGABRT (abort) received

zsh: abort      lfortran --show-llvm a.f90
```

It is not clear if the issue is with continue, or with the do loop.

### PR DESCRIPTION
**Pull request by Smit-create**
#512 
Fixes #946

### CODE REVIEW

File: src/libasr/pass/pass_utils.cpp [hunk 1]
```diff
@@ -646,50 +646,78 @@ namespace LFortran {
...
+
                     if (not_constant_inc) {
-                        ASR::ttype_t *int_type = LFortran::ASRUtils::TYPE(ASR::make_Integer_t(al,
-                                    loc, 4, nullptr, 0));
+                        ASR::expr_t *target = loop.m_head.m_v;
+                        int a_kind = ASRUtils::extract_kind_from_ttype_t(ASRUtils::expr_type(target));
+                        ASR::ttype_t *int_type = LFortran::ASRUtils::TYPE(ASR::make_Integer_t(al, loc, a_kind, nullptr, 0));
+
                         ASR::ttype_t *log_type = ASRUtils::TYPE(
                             ASR::make_Logical_t(al, loc, 1, nullptr, 0));
```
Comment (certik) [inline src/libasr/pass/pass_utils.cpp:661]: We use `logical(4)` as the default logical:
```suggestion
                            ASR::make_Logical_t(al, loc, 4, nullptr, 0));
```
That will cleanup the diffs in the tests as well.

**Comment by certik** [comment]
Awesome, thanks a lot for this! Go ahead and apply the above change and update tests. I will then carefully review that loops with constant skips work as before (unchanged).

**Comment by certik** [comment]
I think that this looks great. Let me test it with Minpack first to see if it fixes the issue.

**Comment by certik** [comment]
With this fix, Minpack must be taking some different path in the source base, because it started to work! The enorm doesn't work, which I know about, but I the algorithm must somehow converge anyway:
```console
Computed:
-5.70654512542618897e-01
-6.81628341216289013e-01
-7.01732451306508187e-01
-7.04212939735556764e-01
-7.01369048406216167e-01
-6.91865644625619836e-01
-6.65792012683941503e-01
-5.96034200634259048e-01
-4.16412062945815342e-01

Reference:
-5.70654499999999953e-01 -6.81628299999999965e-01 -7.01732499999999981e-01 -7.04212900000000031e-01 -7.01369000000000020e-01 -6.91865599999999970e-01 -6.65792000000000050e-01 -5.96034199999999958e-01 -4.16412100000000007e-01
```
