### PR TITLE
mangle intrinsic function with hash of asr owner

### LINKED ISSUE #2340: duplicate symbol '__lcompilers_abs_f64_' when trying to generate a shared library using clang
> a.f90

```fortran
subroutine a()
double precision :: x
x = -1.0D0
x = abs(x)
end subroutine
```

> b.f90

```fortran
subroutine b()
double precision :: x, y
x = -1.0D0
y = abs(x)
end subroutine
```

```console
% lfortran a.f90 -o a1.o -c --all-mangling --mangle-underscore --generate-object-code
% lfortran b.f90 -o a2.o -c --rtlib --all-mangling --mangle-underscore --generate-object-code
% clang -shared -fPIC -o lib.so a1.o a2.o -L/Users/pranavchiku/repos/lfortran/src/runtime -llfortran_runtime
duplicate symbol '__lcompilers_abs_f64_' in:
    a1.o
    a2.o
ld: 1 duplicate symbol for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### PR DESCRIPTION
**Pull request by Pranavchiku**
Fixes #2340

### CODE REVIEW

File: src/libasr/pass/unique_symbols.cpp [hunk 1]
```diff
@@ -52,12 +58,21 @@ class SymbolRenameVisitor: public ASR::BaseWalkVisitor<SymbolRenameVisitor> {
...
         if (startswith(curr_name, "_lpython") || startswith(curr_name, "_lfortran") ) {
             return curr_name;
+        } else if (startswith(curr_name, "_lcompilers_")) {
+            // mangle intrinsic functions
+            if (current_scope) {
+                uint64_t hash = get_hash(current_scope->asr_owner);
+                return module_name + curr_name + "_" + std::to_string(hash) + "_" + lcompilers_unique_ID;
+            } else {
+                return module_name + curr_name + "_" + lcompilers_unique_ID;
+            }
```
Comment (Smit-create) [inline src/libasr/pass/unique_symbols.cpp:68]:
```suggestion
        } else if (startswith(curr_name, "_lcompilers_") && current_scope) {
                // mangle intrinsic functions
                uint64_t hash = get_hash(current_scope->asr_owner);
                return module_name + curr_name + "_" + std::to_string(hash) + "_" + lcompilers_unique_ID;
```

**Review by certik — APPROVED** [review]
I think this is fine. @Smit-create is this ok with you?

**Review by czgdp1807 — APPROVED** [review]
