### PR TITLE
Get log(x) working in the C backend

### LINKED ISSUE #1746: Get `log(x)` working with C and C++ backends
```fortran
program simple
implicit none
real :: A, B
B = 2.0D0
A = log(B) ! It works with sin(B).
print *, A
end program simple
```
Currently in C:
```console
$ lfortran --show-c a.f90  
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 1914
    return emit_c(arg_file, compiler_options);
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 711
    LCompilers::Result<std::string> cpp = fe.get_c(input, lm, diagnostics, 1);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 456
    return get_c2(*asr.result, diagnostics, default_lower_bound);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 467
    return asr_to_c(al, asr, diagnostics, compiler_options,
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_c.cpp", line 1344
    v.visit_asr((ASR::asr_t &)asr);
  File "../libasr/asr.h", line 4775
  File "../libasr/asr.h", line 4751
  File "../libasr/asr.h", line 4776
  File "../libasr/asr.h", line 4496
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_c.cpp", line 713
    if( ASRUtils::get_body_size(mod) != 0 ) {
  File "../libasr/asr.h", line 4778
  File "../libasr/asr.h", line 4505
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_c.cpp", line 822
    ASR::Function_t *s = ASR::down_cast<ASR::Function_t>(sym);
  File "../libasr/codegen/asr_to_c_cpp.h", line 598
  File "../libasr/asr.h", line 4793
  File "../libasr/asr.h", line 4527
  File "../libasr/codegen/asr_to_c_cpp.h", line 840
  File "../libasr/asr.h", line 4839
  File "../libasr/asr.h", line 4672
  File "../libasr/asr.h", line 4935
LCompilersException: visit_IntrinsicFunctionSqrt() not implemented
```
And C++:
```console
$ lfortran --show-cpp a.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 1911
    return emit_cpp(arg_file, compiler_options);
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 687
    LCompilers::Result<std::string> cpp = fe.get_cpp(input, lm, diagnostics, 1);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 431
    return get_cpp2(*asr.result, diagnostics, default_lower_bound);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 442
    return asr_to_cpp(al, asr, diagnostics, compiler_options,
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_cpp.cpp", line 750
    v.visit_asr((ASR::asr_t &)asr);
  File "../libasr/asr.h", line 4775
  File "../libasr/asr.h", line 4751
  File "../libasr/asr.h", line 4776
  File "../libasr/asr.h", line 4496
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_cpp.cpp", line 457
    ASR::symbol_t *mod = x.m_global_scope->get_symbol(item);
  File "../libasr/asr.h", line 4778
  File "../libasr/asr.h", line 4505
  File "../libasr/codegen/asr_to_c_cpp.h", line 246
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_cpp.cpp", line 367
    this->visit_expr(*v.m_symbolic_value);
  File "../libasr/asr.h", line 4839
  File "../libasr/asr.h", line 4582
  File "../libasr/asr.h", line 4845
LCompilersException: visit_StructTypeConstructor() not implemented
```

### PR DESCRIPTION
**Pull request by certik**
Fixes #1746.

### CODE REVIEW

**Comment by certik** [comment]
We need to enable the C backend in the lfortran driver and add tests.

For now, here is how to test it:
```console
$ cd integration_tests
$ lfortran intrinsics_17.f90 --show-c > x.c
$ clang -I../src/libasr/runtime x.c -ferror-limit=1 -L../src/runtime -llfortran_runtime -Wl,-rpath -Wl,../src/runtime
$ ./a.out
4.481689
4.481689
0.405465
0.405465
0.966105
0.966105
0.540420
0.540420
$ lfortran intrinsics_17.f90
4.48168898e+00
4.48168907033806452e+00
4.05465096e-01
4.05465108108164385e-01
9.66105163e-01
9.66105146475310761e-01
5.40419519e-01
5.40419500270584163e-01
```

**Comment by certik** [comment]
We should test this in LPython to make sure all the C tests still pass.

**Comment by Smit-create** [comment]
Thanks, @certik. I'll try this diff with `lpython` and see if everything works fine.

File: src/libasr/codegen/asr_to_c_cpp.h [hunk 1]
```diff
@@ -1710,6 +1738,33 @@ R"(#include <stdio.h>
...
 
+    void visit_ComplexConstructor(const ASR::ComplexConstructor_t &x) {
+        self().visit_expr(*x.m_re);
+        std::string re = std::move(src);
+        self().visit_expr(*x.m_im);
+        std::string im = std::move(src);
+        src = "CMPLX(" + re + "," + im + ")";
+    }
+
+    void visit_StructTypeConstructor(const ASR::StructTypeConstructor_t &x) {
```
Comment (Shaikh-Ubaid) [inline src/libasr/codegen/asr_to_c_cpp.h:1749]: It seems another approach in place of implementing these visitor functions could be to utilize the default ASR->ASR passes. LPython C Backend utilizes it.

https://github.com/lcompilers/lpython/blob/cbda4d864016cda8d920773ac31aad52c2a955f4/src/bin/lpython.cpp#L337-L344

I think we can/should utilize the ASR->ASR passes in the LFortran C Backend as well. I think the above application of passes in LPython can be moved to `asr_to_c()`, that way it could/will be shared with both LPython and LFortran. Using the ASR->ASR passes, I think we might not need to implement `visit_StructTypeConstructor()` and  `visit_IntrinsicFunctionSqrt()` at the moment.

File: src/libasr/codegen/asr_to_c.cpp [hunk 2]
```diff
@@ -779,6 +790,12 @@ R"(
     }
 
     void visit_Module(const ASR::Module_t &x) {
+        if (startswith(x.m_name, "lfortran_intrinsic_")) {
+            intrinsic_module = true;
+        } else {
+            intrinsic_module = false;
+        }
```
Comment (Shaikh-Ubaid) [inline src/libasr/codegen/asr_to_c.cpp:797]:
```suggestion
        intrinsic_module = x.m_intrinsic;
```
I think here we can also utilize the `x.m_intrinsic` data member of `Module_t`.

File: src/libasr/codegen/asr_to_c_cpp.h (hunk 1 above)
Comment (certik) [reply src/libasr/codegen/asr_to_c_cpp.h:1749]: I see. Yes, we can do that.

**Comment by certik** [comment]
I would say let's enable C and C++ tests at our CI and start testing this.

**Comment by Smit-create** [comment]
That sounds good. I'll start working on that from Monday.

**Comment by certik** [comment]
Thanks! You can enable the C test. I am getting the C++ tests working again, a lot of them are broken, but some still work. https://github.com/lfortran/lfortran/pull/1751

**Comment by certik** [comment]
The C++ backend is now enabled. I rebased this branch to see if it still passes. Next let's enable the C backend (@Smit-create I'll let you do it). After that I'll add a test for all the above commits, as all were needed --- alternatively we can enable some passes that do the same, but I want to have the testsuite in place, so that we can make sure that it doesn't break other tests.

**Comment by certik** [comment]
LPython test: https://github.com/lcompilers/lpython/pull/1873, it works.

Now when the C backend is enabled, I'll write tests for this and get it working

**Review by czgdp1807 — COMMENTED** [review]
Shouldn't we be using `IntrinsicFunction` node for representing `log` in ASR? Then I guess you can directly use `log` in C's math library while generating C code.

**Comment by certik** [comment]
I rebased it, added a C and C++ test, and made everything pass on my local machine.

**Review by Smit-create — APPROVED** [review]
This looks perfect. Thanks!

**Comment by certik** [comment]
The C++ output still needs some fixes, see https://github.com/lfortran/lfortran/pull/1834.
