### PR TITLE
ENH: support runtime dim for intrinsic `sum`

### LINKED ISSUE #3540: runtime values for dim argument is not supported yet
```fortran
program main
    real :: a(4, 4)
    integer :: dim
    a = 1.0
    dim = 1
    print *, sum(a, dim)
end program
```

```console
% lfortran b.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2391
    LCompilers::print_stack_on_segfault();
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2355
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 949
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 360
    compiler_options, run_fn, infile);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9656
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 306
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 164
    _passes_db[passes[i]](al, *asr, pass_options);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/intrinsic_function.cpp", line 383
    u.visit_TranslationUnit(unit);
  File "../libasr/asr.h", line 46364
  File "../libasr/asr.h", line 5114
  File "../libasr/asr.h", line 4827
  File "../libasr/asr.h", line 46403
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/intrinsic_function.cpp", line 363
    visit_stmt(*m_body[i]);
  File "../libasr/asr.h", line 5131
  File "../libasr/asr.h", line 4851
  File "../libasr/asr.h", line 46596
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/intrinsic_function.cpp", line 346
    replacer.replace_expr(*current_expr);
  File "../libasr/asr.h", line 45335
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/intrinsic_function.cpp", line 293
    throw LCompilersException("Runtime values for dim argument is not supported yet.");
LCompilersException: Runtime values for dim argument is not supported yet.
```

### PR DESCRIPTION
**Pull request by Pranavchiku**
Fixes #3540

### CODE REVIEW

File: src/libasr/pass/pass_utils.h [hunk 1]
```diff
@@ -137,6 +137,133 @@ namespace LCompilers {
...
+                    dims.push_back(al_, dim);
+                }
+                ret_type = ASRUtils::TYPE(ASR::make_Array_t(al_, arr->base.base.loc, arr->m_type,
+                            dims.p, dims.n, ASR::array_physical_typeType::DescriptorArray));
+                if (is_allocatable) {
+                    ret_type = ASRUtils::TYPE(ASR::make_Allocatable_t(al_, arr->base.base.loc, ret_type));
+                }
+            }
+            return ret_type;
+        }
```
Comment (Pranavchiku) [inline src/libasr/pass/pass_utils.h:265]: this will be same, I do not think there can be any other variations possible for this function.

File: src/libasr/pass/intrinsic_function.cpp [hunk 2]
```diff
@@ -287,8 +287,13 @@ class ReplaceFunctionCallReturningArray: public ASR::BaseExprReplacer<ReplaceFun
...
             if( !ASRUtils::is_value_constant(ASRUtils::expr_value(dim)) ) {
-                // Possibly can be replaced by calling "get_result_var_for_runtime_dim"
-                throw LCompilersException("Runtime values for dim argument is not supported yet.");
+                result_var_ = PassUtils::create_var(result_counter,
+                    std::string(ASRUtils::symbol_name(x->m_name)) + "_res",
+                    x->base.base.loc, x->m_type, al, current_scope);
+                ASR::expr_t* func_call_merge = nullptr;
+                if (func2intrinsicid[x_m_name] == ASRUtils::IntrinsicArrayFunctions::Sum) {
+                    PassUtils::allocate_res_var(al, x, new_args, result_var_, pass_result, {0, 0, 1});
+                }
```
Comment (Pranavchiku) [inline src/libasr/pass/intrinsic_function.cpp:296]: We will have to map corresponding arguments based on intrinsic function we are replacing.

File: integration_tests/intrinsics_177.f90 [hunk 3]
```diff
@@ -0,0 +1,22 @@
...
+    dim = 2
+    print *, sum(aa, dim)
+    if (abs(sum(sum(aa, dim)) - 20.0) > 1e-8) error stop
+    dim = 3
+    print *, sum(aaa, dim)
+    if (abs(sum(sum(aaa, dim)) - 120.0) > 1e-8) error stop
+    dim = 4
+    print *, sum(aaaa, dim)
+    if (abs(sum(sum(aaaa, dim)) - 840.0) > 1e-8) error stop
+end program
```
Comment (Pranavchiku) [inline integration_tests/intrinsics_177.f90:22]: I'll add test for `sum` with `mask` if required.

File: src/libasr/pass/pass_utils.h (hunk 1 above)
Comment (certik) [reply src/libasr/pass/pass_utils.h:265]: What does this function do?

File: src/libasr/pass/intrinsic_array_function_registry.h [hunk 4]
```diff
@@ -75,6 +75,180 @@ typedef void (*verify_array_function)(
...
+            ASR::Character_t* tsource_char = ASR::down_cast<ASR::Character_t>(tsource_type);
+            ASR::Character_t* fsource_char = ASR::down_cast<ASR::Character_t>(fsource_type);
+            tsource_char->m_len_expr = nullptr; fsource_char->m_len_expr = nullptr;
+            tsource_char->m_len = -2; fsource_char->m_len = -2;
+            ASR::Character_t* return_char = ASR::down_cast<ASR::Character_t>(
+                ASRUtils::type_get_past_allocatable(return_type));
+            return_char->m_len = -2; return_char->m_len_expr = nullptr;
+
+        }
+        std::string new_name = "_lcompilers_merge_" + get_type_code(tsource_type);
```
Comment (certik) [inline src/libasr/pass/intrinsic_array_function_registry.h:217]: This is unrelated: I wonder if `merge` can be just an elemental function.

File: integration_tests/intrinsics_177.f90 [hunk 5]
```diff
@@ -0,0 +1,32 @@
...
+    print *, sum(aaaa, dim)
+    if (abs(sum(sum(aaaa, dim)) - 840.0) > 1e-8) error stop
+    print *, sum(aaaa, dim, mask)
+    if (abs(sum(sum(aaaa, dim)) - 840.0) > 1e-8) error stop
+    mask = .false.
+    print *, sum(aaaa, dim, mask)
+    if (abs(sum(sum(aaaa, dim, mask)) - 0.0) > 1e-8) error stop
+    mask(1, 1, :, :) = .true.
+    print *, sum(sum(aaaa, dim, mask))
+    if (abs(sum(sum(aaaa, dim, mask)) - 42.0) > 1e-8) error stop
```
Comment (certik) [inline integration_tests/intrinsics_177.f90:31]: We need to improve this test suite:
* test `aaa` with dim=1, 2, 3
* test `aaaa` with dim=1, 2, 3, 4
* test the shape of the output for each case
* initialize the elements of `aa`, `aaa`, `aaaa` to something like `modulo(i*j, 13)`, which will give it quite unique numbers (integers), and so the sum with dim will also be more unique
* We need to compare the result of sum element by element, so for `aa` and `aaa` we can compare the result directly (just but the reference result in the code), for `aaaa` maybe lower the sizes of each dimension a bit, so that we can create a reference array

File: src/libasr/pass/pass_utils.h [hunk 6]
```diff
@@ -137,6 +137,133 @@ namespace LCompilers {
...
+                    Vec<ASR::alloc_arg_t> alloc_args; alloc_args.reserve(al, 1);
+                    ASR::alloc_arg_t alloc_arg; alloc_arg.loc = x->base.base.loc;
+                    alloc_arg.m_a = result_var_; alloc_arg.m_len_expr = nullptr;
+                    alloc_arg.m_type = nullptr; alloc_arg.m_dims = res_arr->m_dims;
+                    alloc_arg.n_dims = res_arr->n_dims;
+                    alloc_args.push_back(al, alloc_arg);
+
+                    ASR::stmt_t* allocate_stmt = ASRUtils::STMT(ASR::make_Allocate_t(al, 
+                                            x->base.base.loc, alloc_args.p, alloc_args.n, nullptr, nullptr, nullptr));
+                    pass_result.push_back(al, allocate_stmt);
```
Comment (certik) [inline src/libasr/pass/pass_utils.h:184]: Is this deallocated properly?

**Comment by certik** [comment]
How is this runtime `dim` feature implemented? I see just a slight modification there to use `merge` for the return argument, which is good. But how is the loop structure modified? My understanding is that currently we decided at compile time what the loop structure will be, but now we need to decide at runtime, but I don't see any such runtime implementation.

We also need to improve tests, as indicated above. Those more robust tests would reveal any possible issues with the implementation.

File: src/libasr/pass/intrinsic_array_function_registry.h (hunk 4 above)
Comment (Pranavchiku) [reply src/libasr/pass/intrinsic_array_function_registry.h:217]: To ensure return type do not have variables from other scope. As it is passed from create_Sum to instantiate_Sum, it has parameters from different scope.

File: src/libasr/pass/pass_utils.h (hunk 1 above)
Comment (Pranavchiku) [reply src/libasr/pass/pass_utils.h:265]: Ensures return type do not have variables from other scope. As it is passed from create_Sum to instantiate_Sum, it has parameters from different scope.

**Comment by Pranavchiku** [comment]
>  But how is the loop structure modified?

Implementation of sum is independent of compile time value of `dim`, so we need not to modify anything.

https://github.com/lfortran/lfortran/blob/755ad600e9ff89c80883ed4755b07505987f4c24/src/libasr/asr_builder.h#L723-L739

> we decide at compile time what the loop structure will be

For intrinsic `Count`, we have this problem, but it is problem in implementation that needs to resolved separately.

File: src/libasr/pass/pass_utils.h (hunk 6 above)
Comment (Pranavchiku) [reply src/libasr/pass/pass_utils.h:184]: Yes, it gets implicitly deallocated in pass `insert_deallocate`

Comment (czgdp1807) [reply src/libasr/pass/pass_utils.h:184]: Actually this is problematic in general (not here only but other places as well). We need to allocate only when extremely necessary like when there is no other way left. Same for creating auxiliary variables, create only when extremely necessary. Otherwise they lead to a lot of bugs.

File: src/libasr/pass/intrinsic_array_function_registry.h (hunk 4 above)
Comment (czgdp1807) [reply src/libasr/pass/intrinsic_array_function_registry.h:217]: `merge` is an elemental function.

**Comment by czgdp1807** [comment]
This is fine in general.
