### PR TITLE
enh: support additional IO keywords in fixed-form tokenizer

### LINKED ISSUE #11142: INQUIRE: Regression compiling some forms of the statement
The following used to compile fine until the past couple days.  When compiling with `--fixed-form` I get a 'tokenizer error: Expecting terminating symbol for program' error.  This particular MRE can also be compiled in default free-form, and produces a an ICE.  Perhaps the fix for PR #11108 broke it?
```
      program inquire1

! Compilation regression - perhaps due to the fix for PR 11108?

        implicit none
        logical :: seq
        INQUIRE(UNIT=6,SEQUENTIAL=seq)
        print *, 'seq =', seq

      end
```
```
$ lfortran --fixed-form inquire1.f
tokenizer error: Expecting terminating symbol for program
 --> inquire1.f:7:9
  |
7 |         INQUIRE(UNIT=6,SEQUENTIAL=seq)
  |         ^ 


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
$
```
```
$ lfortran inquire1.f
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/wws/computer/fortran/lfortran/src/bin/lfortran", in _start
  File "/build/glibc-B3wQXB/glibc-2.31/csu/../csu/libc-start.c", line 308, in __libc_start_main
  File "/home/wws/computer/fortran/lfortran/src/bin/lfortran.cpp", line 2939, in main
    return main_app(argc, argv);
  File "/home/wws/computer/fortran/lfortran/src/bin/lfortran.cpp", line 2863, in main_app(int, char**)
    err = compile_src_to_object_file(arg_file, tmp_o, compiler_options.time_report, false,
  File "/home/wws/computer/fortran/lfortran/src/bin/lfortran.cpp", line 1279, in (anonymous namespace)::compile_src_to_object_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, LCompilers::CompilerOptions&, LCompilers::PassManager&, bool)
    res = fe.get_llvm3(*asr, lpm, diagnostics, lm, infile, &time_opt);
  File "/home/wws/computer/fortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 406, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, LCompilers::LocationManager&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int*)
    compiler_options, run_fn, "", infile, lm);
  File "/home/wws/computer/fortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 25420, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::LocationManager&)
    v.visit_asr((ASR::asr_t&)asr);
  File "/home/wws/computer/fortran/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 370, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_asr(LCompilers::ASR::asr_t const&)
    void visit_asr(const asr_t &b) { visit_asr_t(b, self()); }
  File "/home/wws/computer/fortran/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 344, in void LCompilers::ASR::visit_asr_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::asr_t const&, LCompilers::ASRToLLVMVisitor&)
    case asrType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/home/wws/computer/fortran/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 371, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_unit(LCompilers::ASR::unit_t const&)
    void visit_unit(const unit_t &b) { visit_unit_t(b, self()); }
  File "/home/wws/computer/fortran/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 22, in void LCompilers::ASR::visit_unit_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::unit_t const&, LCompilers::ASRToLLVMVisitor&)
    case unitType::TranslationUnit: { v.visit_TranslationUnit((const TranslationUnit_t &)x); return; }
  File "/home/wws/computer/fortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 1799, in LCompilers::ASRToLLVMVisitor::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    visit_symbol(*item.second);
  File "/home/wws/computer/fortran/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 373, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/wws/computer/fortran/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 30, in void LCompilers::ASR::visit_symbol_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::symbol_t const&, LCompilers::ASRToLLVMVisitor&)
    case symbolType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/home/wws/computer/fortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 6011, in LCompilers::ASRToLLVMVisitor::visit_Program(LCompilers::ASR::Program_t const&)
    this->visit_stmt(*x.m_body[i]);
  File "/home/wws/computer/fortran/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 391, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/wws/computer/fortran/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 81, in void LCompilers::ASR::visit_stmt_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::stmt_t const&, LCompilers::ASRToLLVMVisitor&)
    case stmtType::FileInquire: { v.visit_FileInquire((const FileInquire_t &)x); return; }
  File "/home/wws/computer/fortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 18259, in LCompilers::ASRToLLVMVisitor::visit_FileInquire(LCompilers::ASR::FileInquire_t const&)
    tmp);
AssertFailed: is_character(*expr_type(s))
$
```

### PR DESCRIPTION
**Pull request by kmr-srbh**
Resolves #11142 

These keywords were previoulsy being tokenized correctly due to a weak assignment check. The assignment check was fixed recently causing the bug to show up.

### CODE REVIEW

File: src/lfortran/parser/fixedform_tokenizer.cpp [hunk 1]
```diff
@@ -1124,7 +1125,6 @@ struct FixedFormRecursiveDescent {
         }
 
         // assignment
-        // TODO: this is fragile
```
Comment (kmr-srbh) [inline src/lfortran/parser/fixedform_tokenizer.cpp:1127]: Address https://github.com/lfortran/lfortran/pull/11101#discussion_r3103983604.

**Review by HarshilShah1804 — APPROVED** [review]
Looks good to me.
