### PR TITLE
ci: upgrade LAPACK to v3.12.1 (fixes flaky SQK tests)

### LINKED ISSUE #9371: CI: LAPACK failures
https://github.com/lfortran/lfortran/actions/runs/20702112236/job/59425986197

```
++ exit_code=0
++ set -e
++ echo 'xlintsts exit code: 0'
++ '[' 0 -ne 0 ']'
++ grep -qE 'failed to pass the threshold' xlintsts_stest.out
xlintsts exit code: 0
++ echo 'ERROR: threshold failures detected'
++ grep 'failed to pass the threshold' xlintsts_stest.out
ERROR: threshold failures detected
 SQK:  36885 out of 241365 tests failed to pass the threshold
++ exit 1
```

### PR DESCRIPTION
**Pull request by krystophny**
Upgrade Reference-LAPACK from v3.12.0 to v3.12.1, which includes the upstream fix for uninitialized `RESULT(4)` in `schkqp3rk.f`.

Release: https://github.com/Reference-LAPACK/lapack/releases/tag/v3.12.1

Fixes #9371

### CODE REVIEW

File: ci/test_third_party_codes.sh [hunk 1]
```diff
@@ -987,11 +987,16 @@ time_section "🧪 Testing Reference-LAPACK v3.12.0 with BUILD_TESTING" '
...
+    # Check for threshold failures, excluding SQK (flaky, tracked in #9371)
+    if grep -E "failed to pass the threshold" xlintsts_stest.out | grep -v "SQK:" > /dev/null; then
+        echo "ERROR: threshold failures detected (excluding SQK)"
+        grep "failed to pass the threshold" xlintsts_stest.out | grep -v "SQK:"
         exit 1
     fi
+    if grep -qE "SQK:.*failed to pass the threshold" xlintsts_stest.out; then
+        echo "WARNING: SQK threshold failures detected (known flaky, see #9371)"
+        grep "SQK:.*failed to pass the threshold" xlintsts_stest.out || true
+    fi
```
Comment (certik) [inline ci/test_third_party_codes.sh]: This skips any tests which fail treshold, even new ones.

Instead, is there a way to just disable the specific tests that are known to fail? That way we will catch any new failures in the future, which is important. With this PR we will not catch any threshold failures.

**Comment by krystophny** [comment]
Updated to disable SQK tests specifically by modifying the input file (`SQK 19` -> `SQK 0`), rather than ignoring failures in the output. This way any new threshold failures from other tests will still be caught.

**Comment by krystophny** [comment]
Updated to patch flaky LAPACK test. It was not our fault in the end.

**Comment by krystophny** [comment]
Updated: now just upgrades to v3.12.1 which includes the upstream fix.
https://github.com/Reference-LAPACK/lapack/releases/tag/v3.12.1

**Comment by certik** [comment]
Apparently this upstream PR fixed it: https://github.com/Reference-LAPACK/lapack/pull/961.

**Review by certik — APPROVED** [review]
This is good, let's see if tests pass.

**Comment by certik** [comment]
It looks very good. I think we have time, let's see if everything passes, to have a good starting point, then we'll merge it.

**Comment by certik** [comment]
Everything passed, except two tests that failed due to network error. I restarted them. Let's merge this.
