### PR TITLE
Tighten the accuracy for random number checks

### LINKED ISSUE #3185: intrinsics_126_FAST fails in main
Only with LLVM 15: https://github.com/lfortran/lfortran/actions/runs/7645900679/job/20833524284
```
320/761 Test #321: intrinsics_126_FAST ....................***Failed    0.01 sec
163178 7.11991727e-01 7.11597681e-01
ERROR STOP
```

This first happened after merging https://github.com/lfortran/lfortran/pull/3181.

### PR DESCRIPTION
**Pull request by certik**
Fixes #3185.

### CODE REVIEW

File: integration_tests/intrinsics_126.f90 [hunk 1]
```diff
@@ -13,6 +13,7 @@ program intrinsic_126
 
     print *, arg, num1, num2
 
-    if (abs(num1 - num2) <= 1e-3) error stop
+    ! Ensure num1 and num2 are different
+    if (abs(num1 - num2) <= 1e-8) error stop
```
Comment (Shaikh-Ubaid) [inline integration_tests/intrinsics_126.f90:17]: I think the initial check ensured that the difference between the generated two random numbers is atleast `1e-3`. If the difference/distance is less than `1e-3`, then the generated random numbers do not seem to be far apart.

`1e-8` seems to be a very short distance that would almost always be satisfied. So, if the random numbers generated are `0.1000001`, `0.1000002`, `0.1000003`, etc. although they are different, they might not be random since they are very close to each other. I think the previous implementation would have caught it, but this would get skipped in the newer implementation.

PS: We already have another `intrinsics_125.f90` which implements a more robust/suitable test. This current test `intrinsics_126.f90` was just to add an extra safety.

Comment (Shaikh-Ubaid) [inline integration_tests/intrinsics_126.f90:17]: I think this would always be a flaky test, since there is a possibility that the two numbers generated would be equal in some CI run. It seems the best we could do is to reduce the flakiness (so it never occurs in practical life) or maybe the remove the test altogether.

Comment (certik) [reply integration_tests/intrinsics_126.f90:17]: Random numbers can be arbitrarily close. In real life, 1e-3 is almost good, but not good enough. 1e-8 should be good enough.

Comment (Shaikh-Ubaid) [reply integration_tests/intrinsics_126.f90:17]: I have a doubt. I think the idea of the above test was to ensure that the two random numbers generated are considerably far apart. Thus, I think `1e-3` was more of a stricter condition (which seems to be too strict and hence fails at the CI) for this specific case. By changing the sufficiently large distance from `1e-3` to `1e-8`, it seems we are relaxing the constraints instead of tightening?

Comment (certik) [reply integration_tests/intrinsics_126.f90:17]: Go ahead and open up an issue for this. We have two (in this case competing) requirements:

* CI must be 100% robust
* robust test for random numbers, ensuring they are actually random

I recommend we implement proper random number testing, there are several solid tests that will work 100% at the CI in practice.

Comment (Shaikh-Ubaid) [reply integration_tests/intrinsics_126.f90:17]: >I recommend we implement proper random number testing, there are several solid tests that will work 100% at the CI in practice.

Yes, I think we already have a good test for random numbers `integration_tests/intrinsics_125.f90` which implements the `Kolmogorov–Smirnov` test. This current test `intrinsics_126.f90` was more for an added extra safety.
