### PR TITLE
fix: fix pack intrinsic for scalar runtime mask 

### LINKED ISSUE #6631: `pack` intrinsic gives segfault for calls inside subroutine with scalar `mask`
MRE
```fortran
program test_pack
  implicit none

  real :: input(2)
  real :: output(2)  
  input = [1, 2]
  call forward(input, output)
contains

  subroutine forward(input, output)
    real, intent(inout) :: input(:)
    real, intent(inout) :: output(:)
    output = pack(input, .true.)  
  end subroutine forward

end program test_pack
```
GFortran compiles it without any errors. LFortran gives segfault on compiling. 
```console
(lf) harshil-shah@harshil-shah-HP-Pavilion-Laptop-15-eg2xxx:~/lfortran$ lfortran a.f90
Traceback (most recent call last):
  Binary file "/home/harshil-shah/lfortran/src/bin/lfortran", in _start
  File "./csu/../csu/libc-start.c", line 360, in __libc_start_main
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main
  File "/home/harshil-shah/lfortran/src/bin/lfortran.cpp", line 2577, in main
    return main_app(argc, argv);
  File "/home/harshil-shah/lfortran/src/bin/lfortran.cpp", line 2515, in main_app(int, char**)
    err = compile_src_to_object_file(arg_file, tmp_o, opts.time_report, false,
  File "/home/harshil-shah/lfortran/src/bin/lfortran.cpp", line 1024, in (anonymous namespace)::compile_src_to_object_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, LCompilers::CompilerOptions&, LCompilers::PassManager&)
    result = fe.get_asr2(input, lm, diagnostics);
  File "/home/harshil-shah/lfortran/src/lfortran/fortran_evaluator.cpp", line 275, in LCompilers::FortranEvaluator::get_asr2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::diag::Diagnostics&)
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics, lm);
  File "/home/harshil-shah/lfortran/src/lfortran/fortran_evaluator.cpp", line 297, in LCompilers::FortranEvaluator::get_asr3(LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::LocationManager&)
    compiler_options.symtab_only, compiler_options, lm);
  File "/home/harshil-shah/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 111, in LCompilers::LFortran::ast_to_asr(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::SymbolTable*, bool, LCompilers::CompilerOptions&, LCompilers::LocationManager&)
    );
  File "/home/harshil-shah/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 4761, in LCompilers::LFortran::body_visitor(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::ASR::asr_t*, LCompilers::CompilerOptions&, std::map<unsigned long, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > > > > >&, std::map<unsigned long, LCompilers::ASR::symbol_t*, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, LCompilers::ASR::symbol_t*> > >&, std::map<unsigned long, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >&, std::map<unsigned long, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >&, std::map<unsigned int, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > > > > >&, std::map<unsigned int, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::symbol_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::symbol_t*> > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::symbol_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::symbol_t*> > > > > >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> > > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> > > > > > > >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<int, std::allocator<int> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<int, std::allocator<int> > > > >&, std::vector<LCompilers::ASR::stmt_t*, std::allocator<LCompilers::ASR::stmt_t*> >&, LCompilers::LocationManager&)
    this->visit_unit_decl2(*x.m_decl[i]);
  File "/home/harshil-shah/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 163, in LCompilers::LFortran::BodyVisitor::visit_TranslationUnit(LCompilers::LFortran::AST::TranslationUnit_t const&)
    for (size_t i=0; i<x.n_items; i++) {
  File "/home/harshil-shah/lfortran/src/lfortran/ast.h", line 4969, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_ast(LCompilers::LFortran::AST::ast_t const&)
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/home/harshil-shah/lfortran/src/lfortran/ast.h", line 4925, in void LCompilers::LFortran::AST::visit_ast_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::ast_t const&, LCompilers::LFortran::BodyVisitor&)
    case astType::mod: { v.visit_mod((const mod_t &)x); return; }
  File "/home/harshil-shah/lfortran/src/lfortran/ast.h", line 4972, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_mod(LCompilers::LFortran::AST::mod_t const&)
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/home/harshil-shah/lfortran/src/lfortran/ast.h", line 4549, in void LCompilers::LFortran::AST::visit_mod_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::mod_t const&, LCompilers::LFortran::BodyVisitor&)
    case modType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/home/harshil-shah/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1997, in LCompilers::LFortran::BodyVisitor::visit_Program(LCompilers::LFortran::AST::Program_t const&)
    for (size_t i=0; i<x.n_decl; i++) {
  File "/home/harshil-shah/lfortran/src/lfortran/ast.h", line 4977, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_program_unit(LCompilers::LFortran::AST::program_unit_t const&)
    void visit_program_unit(const program_unit_t &b) { visit_program_unit_t(b, self()); }
  File "/home/harshil-shah/lfortran/src/lfortran/ast.h", line 4557, in void LCompilers::LFortran::AST::visit_program_unit_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::program_unit_t const&, LCompilers::LFortran::BodyVisitor&)
    case program_unitType::Subroutine: { v.visit_Subroutine((const Subroutine_t &)x); return; }
  File "/home/harshil-shah/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 2414, in LCompilers::LFortran::BodyVisitor::visit_Subroutine(LCompilers::LFortran::AST::Subroutine_t const&)
    add_subroutine_call(x.base.base.loc, it.first, v->m_name, label++);
  File "/home/harshil-shah/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 125, in LCompilers::LFortran::BodyVisitor::transform_stmts(LCompilers::Vec<LCompilers::ASR::stmt_t*>&, unsigned long, LCompilers::LFortran::AST::stmt_t**)
    // Visit the statement
  File "/home/harshil-shah/lfortran/src/lfortran/ast.h", line 5017, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_stmt(LCompilers::LFortran::AST::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/harshil-shah/lfortran/src/lfortran/ast.h", line 4659, in void LCompilers::LFortran::AST::visit_stmt_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::stmt_t const&, LCompilers::LFortran::BodyVisitor&)
    case stmtType::Assignment: { v.visit_Assignment((const Assignment_t &)x); return; }
  File "/home/harshil-shah/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 2865, in LCompilers::LFortran::BodyVisitor::visit_Assignment(LCompilers::LFortran::AST::Assignment_t const&)
    "dimension 1 (" + std::to_string(dim_a_int) + " and " +
  File "/home/harshil-shah/lfortran/src/lfortran/ast.h", line 5069, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_expr(LCompilers::LFortran::AST::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/home/harshil-shah/lfortran/src/lfortran/ast.h", line 4722, in void LCompilers::LFortran::AST::visit_expr_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::expr_t const&, LCompilers::LFortran::BodyVisitor&)
    case exprType::FuncCallOrArray: { v.visit_FuncCallOrArray((const FuncCallOrArray_t &)x); return; }
  File "/home/harshil-shah/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 8065, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::visit_FuncCallOrArray(LCompilers::LFortran::AST::FuncCallOrArray_t const&)
    } else {
  File "/home/harshil-shah/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 7421, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::intrinsic_as_node(LCompilers::LFortran::AST::FuncCallOrArray_t const&, bool&)
    throw SemanticAbort();
  File "/home/harshil-shah/lfortran/src/libasr/pass/intrinsic_array_function_registry.h", line 4868, in LCompilers::ASRUtils::Pack::create_Pack(Allocator&, LCompilers::Location const&, LCompilers::Vec<LCompilers::ASR::expr_t*>&, LCompilers::diag::Diagnostics&)
    ASR::expr_t* count = EXPR(Count::create_Count(al, loc, args_count, diag));
  File "/home/harshil-shah/lfortran/src/libasr/pass/intrinsic_array_function_registry.h", line 4079, in LCompilers::ASRUtils::Count::create_Count(Allocator&, LCompilers::Location const&, LCompilers::Vec<LCompilers::ASR::expr_t*>&, LCompilers::diag::Diagnostics&)
    value = eval_Count(al, loc, return_type, arg_values, diag);
  File "/home/harshil-shah/lfortran/src/libasr/pass/intrinsic_array_function_registry.h", line 4000, in LCompilers::ASRUtils::Count::eval_Count(Allocator&, LCompilers::Location const&, LCompilers::ASR::ttype_t*, LCompilers::Vec<LCompilers::ASR::expr_t*>&, LCompilers::diag::Diagnostics&)
    count += int(((bool*)(mask_array->m_data))[i]);
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in <invalid>
Segfault: Signal SIGSEGV (segmentation fault) received

```

### PR DESCRIPTION
**Pull request by HarshilShah1804**
Fixes #6631

### CODE REVIEW

File: src/libasr/pass/intrinsic_array_function_registry.h [hunk 1]
```diff
@@ -4919,11 +4919,7 @@ namespace Pack {
         if (is_vector_present) {
             vector_rank = extract_dimensions_from_ttype(type_vector, vector_dims);
         }
-        if (array_rank != mask_rank) {
-            append_error(diag, "The argument `mask` must be of rank " + std::to_string(array_rank) +
-                ", provided an array with rank, " + std::to_string(mask_rank), mask->base.loc);
-            return nullptr;
-        }
+        // TODO: throw error here if mask is not a scalar and array rank != mask_rank
```
Comment (certik) [inline src/libasr/pass/intrinsic_array_function_registry.h]: I think this was a good error message, you just have to not throw it for scalars, correct?

We should also add tests for this error message.

How difficult is to fix it?

Otherwise the PR is fine.

Comment (HarshilShah1804) [reply src/libasr/pass/intrinsic_array_function_registry.h]: > I think this was a good error message, you just have to not throw it for scalars, correct?

Yes.

> How difficult is to fix it?

We just have to add a statement in if `mask_rank > 0` and this should work fine. I'll update this. Please suggest if any other changes are required. Thanks

Comment (certik) [reply src/libasr/pass/intrinsic_array_function_registry.h]: Also add a test for this error message into continue_compilation.

Comment (HarshilShah1804) [reply src/libasr/pass/intrinsic_array_function_registry.h]: Sure.

**Comment by HarshilShah1804** [comment]
I have corrected that error message to address https://github.com/lfortran/lfortran/pull/7639#discussion_r2136246414. I have also add the error test in continue_compilation_1.f90

File: src/libasr/pass/intrinsic_array_function_registry.h [hunk 2]
```diff
@@ -4919,7 +4919,7 @@ namespace Pack {
         if (is_vector_present) {
             vector_rank = extract_dimensions_from_ttype(type_vector, vector_dims);
         }
-        if (array_rank != mask_rank) {
+        if (array_rank != mask_rank && mask_rank != 0) {
             append_error(diag, "The argument `mask` must be of rank " + std::to_string(array_rank) +
                 ", provided an array with rank, " + std::to_string(mask_rank), mask->base.loc);
```
Comment (certik) [inline src/libasr/pass/intrinsic_array_function_registry.h]:
```suggestion
                ", provided an array with rank " + std::to_string(mask_rank) + " was provided", mask->base.loc);
```

Comment (HarshilShah1804) [reply src/libasr/pass/intrinsic_array_function_registry.h]: Applied.

File: tests/reference/asr-continue_compilation_1-04b6d40.stderr [hunk 3]
```diff
@@ -727,3 +727,9 @@ semantic error: Different `character` lengths 2 and 3 in array constructor
     |
 314 |     print *, ["aa", string(x+1:x+2), "aaa"]
     |                                      ^^^^^ 
+
+semantic error: The argument `mask` must be of rank 2, provided an array with rank, 1 was provided.
```
Comment (certik) [inline tests/reference/asr-continue_compilation_1-04b6d40.stderr:731]: I apologize, my correction was also incorrect. It should read:
```suggestion
semantic error: The argument `mask` must be of rank 2, an array with rank 1 was provided.
```
Let's fix this in the subsequent PR, that's a simple change.

**Comment by certik** [comment]
I set this to automerge. You can send a new PR with the fix.

File: tests/reference/asr-continue_compilation_1-04b6d40.stderr (hunk 3 above)
Comment (HarshilShah1804) [reply tests/reference/asr-continue_compilation_1-04b6d40.stderr:731]: Oh! right. I'll fix that in a subsequent PR.
