### PR TITLE
fix: Fix read bugs from AoC-2024

### LINKED ISSUE #10635: handle multiple variables inside `read()`
Towards #5629

MRE:
```
program mre_read

implicit none

integer, parameter :: n = 3
integer,dimension(:),allocatable :: a, b
character(len=20), dimension(n) :: lines
integer :: i
allocate(a(n), b(n))

lines(1)  = '5   42'
lines(2)  = '3   7'
lines(3)  = '9   15'
do i = 1, n
    read(lines(i), *) a(i), b(i)
    print *, "Iteration ", i
    print *, "Lines ", lines(i)
    print *, "Read Values a = ",a(i), "b = ", b(i)
end do
end program mre_read
```

```
$ lfortran a.f90
Iteration     1
Lines 5   42              
Read Values a =     5    b =     0
Iteration     2
Lines 3   7               
Read Values a =     3    b =     0
Iteration     3
Lines 9   15              
Read Values a =     9    b =     0

$ gfortran a.f90 & ./a.out
[1]+  Done                    gfortran a.f90
[1] 33524
 Iteration            1
 Lines 5   42              
 Read Values a =            5 b =           42
 Iteration            2
 Lines 3   7               
 Read Values a =            3 b =            7
 Iteration            3
 Lines 9   15              
 Read Values a =            9 b =           15
```

### LINKED ISSUE #10637: `read()` function accepting incorrect string as integers
Towards #5629 (problem_03.f90)

MRE:
```
program problem_03

implicit none

integer :: val, istat
character(len=6) :: str

istat = 0; 
val = 0; 
str = '577;'
read(str, *, iostat=istat) val
print *, str,'val=', val,'istat=', istat

end program problem_03
```

Main:
```
$ lfortran a.f90 
577;  val=    577    istat=    0
```

gfortran, ifx and flang:
```
$ gfortran a.f90 & ./a.out
[1]+  Done                    gfortran a.f90
[1] 53683
 577;  val=           0 istat=        5010
```

### LINKED ISSUE #10638: `read()` of string of integer digits into integer array doesn't work
Towards #5629 (problem_10.f90)

MRE:
```
program problem_10

    implicit none

    integer, parameter :: n_lines = 3, n_cols = 3
    integer :: i
    character(len=n_cols) :: line
    integer, dimension(:,:), allocatable :: array
    character(len=n_cols), dimension(n_lines) :: file_str = ['890', '781', '874']

    allocate(array(n_lines, n_cols))

    do i = 1, n_lines
        line = file_str(i)
        read(line, '(*(I1))') array(i, 1:n_cols)
        print *, 'run ', i, ': ', array(i,:)
    end do

end program problem_10
```

gfortran, ifx, flang all give same output:
```
$ lfortran a.f90 
run     1    :     0    0    0
run     2    :     0    0    0
run     3    :     0    0    0

$ gfortran a.f90 & ./a.out
[1]+  Done                    gfortran a.f90
[1] 61601
 run            1 :            8           9           0
 run            2 :            7           8           1
 run            3 :            8           7           4
```

### PR DESCRIPTION
**Pull request by YashNagda17**
Fixes #10638 
Fixes #10637 
Fixes #10635 

Each commit solves a separate problem, so I have tried to add detailed description for fixes inside commit message. I have tried to be as descriptive as possible, kindly ask for any clarifications if needed, since it would be a feedback for me to take care next time. 

Thank you for your time!

### CODE REVIEW

**Comment by HarshitaKalani** [comment]
Hey @YashNagda17 , can you please resolve the conficts and run the exhaustive checks?

File: src/libasr/runtime/lfortran_intrinsics.c [hunk 1]
```diff
@@ -7497,6 +7526,26 @@ static bool handle_read_real(InputSource *inputSource, va_list *args, int width,
...
+        size_t esz = (elem_tc == 5) ? sizeof(double) : sizeof(float);
+        parse_decimals(fmt, fmt_len, fmt_pos);
+        int read_width = (width > 0) ? width : 15;
+        for (int32_t i = 0; i < n_elems; i++) {
+            void* elem_ptr = (char*)data_ptr + (size_t)i * (size_t)stride * esz;
+            char* buffer = NULL; int field_len = 0;
+            if (!read_field(inputSource, read_width, advance_no, iostat, chunk,
+                            consumed_newline, &buffer, &field_len)) break;
+            parse_real_from_buffer(buffer, field_len, elem_ptr, elem_tc, scale_factor);
+            free(buffer);
```
Comment (certik) [inline src/libasr/runtime/lfortran_intrinsics.c]: Use `internal_free`.

File: src/libasr/runtime/lfortran_intrinsics.c [hunk 2]
```diff
@@ -7462,6 +7470,27 @@ static bool handle_read_L(InputSource *inputSource, va_list *args, int width, bo
...
+        size_t esz = (elem_tc == 3) ? sizeof(int64_t) : sizeof(int32_t);
+        int read_width = (width > 0) ? width : 10;
+        for (int32_t i = 0; i < n_elems; i++) {
+            void* elem_ptr = (char*)data_ptr + (size_t)i * (size_t)stride * esz;
+            char* buffer = NULL; int field_len = 0;
+            if (!read_field(inputSource, read_width, advance_no, iostat, chunk,
+                            consumed_newline, &buffer, &field_len)) break;
+            bool parse_error = false;
+            parse_integer_from_buffer(buffer, field_len, elem_ptr, elem_tc, blank_mode, &parse_error);
+            free(buffer);
```
Comment (certik) [inline src/libasr/runtime/lfortran_intrinsics.c]: internal_free

File: src/libasr/codegen/asr_to_llvm.cpp [hunk 3]
```diff
@@ -15850,6 +15895,45 @@ class ASRToLLVMVisitor : public ASR::BaseVisitor<ASRToLLVMVisitor>
...
+                } else if (ASR::is_a<ASR::Logical_t>(*val_type)) {
+                    type_code_val = 1;
+                }
+                // Push: is_descriptor_array=1, elem_tc, data_ptr, n_elems, stride
+                args.push_back(llvm::ConstantInt::get(context, llvm::APInt(32, 1)));
+                args.push_back(llvm::ConstantInt::get(
+                    llvm::Type::getInt32Ty(context), type_code_val));
+                args.push_back(data_ptr_val);
+                args.push_back(n_elems);
+                args.push_back(stride_val);
```
Comment (certik) [inline src/libasr/codegen/asr_to_llvm.cpp]: Let's figure out how to refactor the two identical (?) blobs into a function

**Review by certik — APPROVED** [review]
Otherwise good!

**Comment by YashNagda17** [comment]
@certik can you please verify once and enable exhaustive checks here? 
Thanks!

**Review by HarshitaKalani — APPROVED** [review]

**Comment by YashNagda17** [comment]
Resolved all conflicts... This PR is ready to be merged

File: src/libasr/runtime/lfortran_intrinsics.c [hunk 4]
```diff
@@ -8010,6 +8014,10 @@ static bool handle_read_A(InputSource *inputSource, va_list *args, int width, bo
 static bool handle_read_L(InputSource *inputSource, va_list *args, int width, bool advance_no,
         int32_t *iostat, int32_t *chunk, bool *consumed_newline, int *arg_idx)
 {
+    int32_t is_descriptor_array = va_arg(*args, int32_t);
+    // descriptor-array path for L not yet supported
+    // TODO: Add support for read into descriptor-arrays for logical reads
```
Comment (certik) [inline src/libasr/runtime/lfortran_intrinsics.c:8153]: Should we give a runtime not implemented error?

File: src/libasr/codegen/asr_to_llvm.cpp [hunk 5]
```diff
@@ -16407,6 +16422,10 @@ class ASRToLLVMVisitor : public ASR::BaseVisitor<ASRToLLVMVisitor>
                     }
                     add_formatted_read_arg(args, val_type, elem_ptr);
                 }
+            } else if (ASRUtils::is_array(expr_type_full)) {
+        // DescriptorArray target: push is_descriptor_array=1, elem_tc, data_ptr, n_elems, stride
```
Comment (certik) [inline src/libasr/codegen/asr_to_llvm.cpp]: Incorrect indentation

**Comment by certik** [comment]
My apologies, I didn't managed to merge this, we had lots of urgent PRs to go in. Do you mind please rebasing one more time? I left some minor comments, you can fix those too while at it.

File: src/libasr/runtime/lfortran_intrinsics.c (hunk 4 above)
Comment (YashNagda17) [reply src/libasr/runtime/lfortran_intrinsics.c:8153]: Implemented CodeGenError inside `src/libasr/codegen/llvm_array_utils.h`, line 1881 (using same pattern to generate CodeGenError in `asr_to_llvm.cpp` for not implemented error)

I intend to add support for reads into characters and logical allocatable arrays as well in subsequent PRs, for completeness

**Comment by YashNagda17** [comment]
Rebased this PR and resolved comments, all tests passed... Please have a look once

Thank you for your time!

**Comment by YashNagda17** [comment]
@certik can you please have a look once? PR is ready to be merged without any conflicts

**Review by certik — APPROVED** [review]
I think this is good enough to merge, we can fix any subsequent issues later.
