### PR TITLE
enh: add support for `c_funptr` and `c_funloc`

### LINKED ISSUE #3989: add support for `c_funptr`
Required in #3777, #3991

```fortran
module libgompinterop
use iso_c_binding
implicit none

interface
subroutine GOMP_parallel (fn) bind (C, name="GOMP_parallel")
import :: c_funptr
type(c_funptr), value :: fn
end subroutine
end interface
end module
```

```console
% lfortran -c a.f90 
LCOMPILERS_ASSERT failed: /Users/pranavchiku/repos/lfortran/src/libasr/asr_utils.h
function replace_Struct(), line number 3972 at 
derived_type_sym != nullptr
ERROR MESSAGE:
derived_type_sym cannot be nullptr
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2459
    LCompilers::print_stack_on_segfault();
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2391
    return compile_to_object_file(arg_file, outfile, false,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 906
    result = fe.get_asr2(input, lm, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 252
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 274
    compiler_options.symtab_only, compiler_options);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 77
    if (res.ok) {
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 3457
    v.visit_TranslationUnit(ast);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 120
    visit_ast(*x.m_items[i]);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4878
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4834
    case astType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4881
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4465
    case modType::Module: { v.visit_Module((const Module_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 471
    visit_ModuleSubmoduleCommon<AST::Module_t, ASR::Module_t>(x);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 427
    visit_unit_decl2(*x.m_decl[i]);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4892
    void visit_unit_decl2(const unit_decl2_t &b) { visit_unit_decl2_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4495
    case unit_decl2Type::DeclarationPragma: { v.visit_DeclarationPragma((const DeclarationPragma_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 1815
    visit_interface_item(*x.m_items[i]);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4911
    void visit_interface_item(const interface_item_t &b) { visit_interface_item_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4525
    case interface_itemType::InterfaceProc: { v.visit_InterfaceProc((const InterfaceProc_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 1702
    is_interface = true;
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4886
    void visit_program_unit(const program_unit_t &b) { visit_program_unit_t(b, self()); }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/ast.h", line 4476
    case program_unitType::Subroutine: { v.visit_Subroutine((const Subroutine_t &)x); return; }
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/semantics/ast_symboltable_visitor.cpp", line 1064
    tmp = ASRUtils::make_Function_t_util(
  File "/Users/pranavchiku/repos/lfortran/src/libasr/asr_utils.h", line 4059
    ASR::ttype_t* func_type = ASRUtils::TYPE(ASRUtils::make_FunctionType_t_util(
  File "/Users/pranavchiku/repos/lfortran/src/libasr/asr_utils.h", line 4025
    expr_type(a_args[i]), current_scope);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/asr_utils.h", line 3989
    replace_ttype(t);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/asr.h", line 46232
    self().replace_Struct(down_cast<ASR::Struct_t>(x));
  File "/Users/pranavchiku/repos/lfortran/src/libasr/asr_utils.h", line 3971
    LCOMPILERS_ASSERT_MSG( derived_type_sym != nullptr,
  Binary file "/usr/lib/system/libsystem_c.dylib", local address: 0x180353a1f
  Binary file "/usr/lib/system/libsystem_pthread.dylib", local address: 0x180446c1f
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x180477583
Abort: Signal SIGABRT (abort) received

zsh: abort      lfortran -c a.f90
```

cc @certik @Thirumalai-Shaktivel

### LINKED ISSUE #3991: compile toy openmp example
Towards #3777

> libgompinterop.f90

```fortran
module libgompinterop
use iso_c_binding
implicit none

interface
subroutine GOMP_parallel (fn, data, num_threads, flags) bind (C, name="GOMP_parallel")
import :: c_funptr, c_ptr, c_int
type(c_funptr), value :: fn
type(c_ptr), value :: data
integer(c_int), value :: num_threads
integer(c_int), value :: flags
end subroutine

subroutine GOMP_barrier() bind(C, name="GOMP_barrier")
end subroutine

subroutine GOMP_critical_start() bind(C, name="GOMP_critical_start")
end subroutine

subroutine GOMP_critical_end() bind(C, name="GOMP_critical_end")
end subroutine

function omp_get_max_threads() bind(c, name="omp_get_max_threads")
import :: c_int
integer(c_int) :: omp_get_max_threads
end function omp_get_max_threads

function omp_get_thread_num() bind(c, name="omp_get_thread_num")
import :: c_int
integer(c_int) :: omp_get_thread_num
end function omp_get_thread_num

end interface

end module
```

> a-transformed.f90

```fortran
subroutine lcompilers_function() bind(c)
use libgompinterop
implicit none

integer(c_int) :: thread_id
thread_id = omp_get_thread_num()
print *, "Hello from thread ", thread_id
end subroutine

program openmp
use libgompinterop
implicit none

interface
subroutine lcompilers_function() bind(c)
end subroutine
end interface

integer :: max_threads
max_threads = omp_get_max_threads()

print *, "Max threads: ", max_threads
call GOMP_parallel(c_funloc(lcompilers_function), c_null_ptr, max_threads, 0)

!lfortran -c libgompinterop.f90 && lfortran a-transformed.f90 -L/Users/pranavchiku/repos/llvm-project/openmp/build/runtime/src/ -lomp -Wl,-rpath,/Users/pranavchiku/repos/llvm-project/openmp/build/runtime/src/
end program
```

With diff

```diff
diff --git a/src/runtime/pure/lfortran_intrinsic_iso_c_binding.f90 b/src/runtime/pure/lfortran_intrinsic_iso_c_binding.f90
index 64f2661a8..29b3e6211 100644
--- a/src/runtime/pure/lfortran_intrinsic_iso_c_binding.f90
+++ b/src/runtime/pure/lfortran_intrinsic_iso_c_binding.f90
@@ -5,6 +5,10 @@ type :: c_ptr
     integer ptr
 end type
 
+type :: c_funptr
+    integer ptr
+end type
+
 integer, parameter :: c_int8_t = 1
```

```console
% lfortran -c libgompinterop.f90 && lfortran a-transformed.f90 -L/Users/pranavchiku/repos/llvm-project/openmp/build/runtime/src/ -lomp -Wl,-rpath,/Users/pranavchiku/repos/llvm-project/openmp/build/runtime/src/
semantic error: Intrinsic function 'c_funloc' compile time evaluation is not implemented yet
  --> a-transformed.f90:23:20
   |
23 | call GOMP_parallel(c_funloc(lcompilers_function), c_null_ptr, max_threads, 0)
   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

### LINKED ISSUE #3992: add support for `c_funloc`
Required for #3777 and compiling #3991

### PR DESCRIPTION
**Pull request by Pranavchiku**
Fixes #3989. Fixes #3992. Fixes #3991.

With this PR we get the toy example compiled with LFortran

```console
% lfortran -c libgompinterop.f90 && lfortran d.f90 -L/Users/pranavchiku/repos/llvm-project/openmp/build/runtime/src/ -lomp -Wl,-rpath,/Users/pranavchiku/repos/llvm-project/openmp/build/runtime/src/
Max threads:  8
Hello from thread  3
Hello from thread  1
Hello from thread  2
Hello from thread  0
Hello from thread  4
Hello from thread  6
Hello from thread  7
Hello from thread  5
```

### CODE REVIEW

**Comment by Pranavchiku** [comment]
To test locally, assuming file names  are `c.f90` and `c.cpp`

```script
lfortran -c c.f90 -o c.o
gcc -c c.cpp -o c_cpp.o
lfortran c.o c_cpp.o
```

**Review by certik — COMMENTED** [review]
I think that this looks good, thanks for fixing it!

File: src/libasr/asr_utils.h [hunk 1]
```diff
@@ -921,6 +921,21 @@ static inline bool is_c_ptr(ASR::symbol_t* v, std::string v_name="") {
...
+    }
+    ASR::symbol_t* v_orig = ASRUtils::symbol_get_past_external(v);
+    if( ASR::is_a<ASR::StructType_t>(*v_orig) ) {
+        ASR::Module_t* der_type_module = ASRUtils::get_sym_module0(v_orig);
+        return (der_type_module && std::string(der_type_module->m_name) ==
+                "lfortran_intrinsic_iso_c_binding" &&
+                der_type_module->m_intrinsic &&
+                v_name == "c_funptr");
+    }
+    return false;
```
Comment (certik) [inline src/libasr/asr_utils.h:936]: This and `c_ptr` must be later changed to be LFortran independent. For now since we already do this for `c_ptr`, it's fine.
