### PR TITLE
fix: Kind for CMPLX and ArrayConstructor doesn't work

### LINKED ISSUE #3601: Kind for CMPLX and ArrayConstructor doesn't work
```f90
program main
    implicit none
    print *, kind([real:: 1])
end program main
```

raises an error complaining (limited stacktrace):
```bash
AssertFailed: check_equal_type(expr_type(lhs), expr_type(rhs))
```

and for `CMPLX`:
```f90
program main
    implicit none
    print *, kind(cmplx(1))
end program main
```

it throws a semantic error:
```bash
semantic error: Unexpected args, Kind expects (int) or (real) or (bool) or (char) as arguments
 --> m.f90:3:14
  |
3 |     print *, kind(cmplx(1))
  |              ^^^^^^^^^^^^^^ 


Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

There are other issues with `KIND` as well: https://github.com/lfortran/lfortran/issues/1484 & https://github.com/lfortran/lfortran/issues/345, but I think this one's different

### PR DESCRIPTION
**Pull request by Pranavchiku**
Fixes #3601

### CODE REVIEW

File: src/lfortran/semantics/ast_common_visitor.h [hunk 1]
```diff
@@ -5129,6 +5129,9 @@ class CommonVisitor : public AST::BaseVisitor<Derived> {
                 Vec<ASR::expr_t*> args; args.reserve(al, 1);
                 args.push_back(al, arg);
                 array->m_args[i] = ASRUtils::expr_value(ASRUtils::EXPR(create_func(al, loc, args, diag)));
+                ASR::Array_t* arr_type = ASR::down_cast<ASR::Array_t>(array->m_type);
```
Comment (gxyd) [inline src/lfortran/semantics/ast_common_visitor.h:5132]: Here, it seems like `kind` is being treated as an elemental intrinsic function.

While in the documentation, `kind` is actually an "Inquiry function" (screenshot from page 384, J3/18-007r1):
Screenshot 2024-03-19 at 11 38 34 AM.

So here, `kind([real :: 1, 2, 3, 4])` would act on the array element-wise, which isn't what `kind` is supposed to do though.

Comment (Pranavchiku) [reply src/lfortran/semantics/ast_common_visitor.h:5132]: Okay then this will be a design change, that can be done in another PR?

**Comment by Pranavchiku** [comment]
The example maybe wrong, we can put `X[real::1]` that returns `integer` and can reproduce `intrinsics_190`.

File: src/lfortran/semantics/ast_common_visitor.h (hunk 1 above)
Comment (gxyd) [reply src/lfortran/semantics/ast_common_visitor.h:5132]: > Okay then this will be a design change, that can be done in another PR?

That sounds like a good way. Can re-think implications of the added code on other element-wise intrinsic function?

Comment (Pranavchiku) [reply src/lfortran/semantics/ast_common_visitor.h:5132]: Yes, we just need to find an elemental intrinsic that takes `real` and returns `integer`.

Comment (gxyd) [reply src/lfortran/semantics/ast_common_visitor.h:5132]: I thought of `floor` and `ceiling`, but seems like they raise an error on array constructor input (a bug).

Comment (gxyd) [reply src/lfortran/semantics/ast_common_visitor.h:5132]: I created a bug report here: https://github.com/lfortran/lfortran/issues/3673 for issues with `floor`, `ceiling` etc.

I do agree that these changes look good, I'm happy with it.

File: integration_tests/intrinsics_191.f90 [hunk 2]
```diff
@@ -0,0 +1,9 @@
+program intrinsics_191
+    implicit none
+    complex :: a
+    integer :: res
+    a = cmplx(1)
```
Comment (gxyd) [inline integration_tests/intrinsics_191.f90:5]: another example for `cmplx` with `kind=8` would be good to have.

**Review by gxyd — COMMENTED** [review]
I'm happy with the changes, if you could ensure that it doesn't actually close the issue #3601, as the constructor issue isn't handled in this.

**Review by certik — APPROVED** [review]
I think this PR is fine. @Pranavchiku if you are ok with it, you can merge it.

File: src/lfortran/semantics/ast_common_visitor.h (hunk 1 above)
Comment (Pranavchiku) [reply src/lfortran/semantics/ast_common_visitor.h:5132]: Thank you for that, I'll check why it fails and try to fix it.
