### PR TITLE
Fix bounds checking in legacy array sections

### LINKED ISSUE #9512: legacy minpack fails on macOS
https://github.com/lfortran/lfortran-conda-testing/actions/runs/20997553639/job/60358274561?pr=75

```
+ git clone https://github.com/fortran-lang/minpack modern_minpack_01
Cloning into 'modern_minpack_01'...
+ cd modern_minpack_01
+ git checkout c0b5aea9fcd2b83865af921a7a7e881904f8d3c2
HEAD is now at c0b5aea Merge pull request #75 from jacobwilliams/74-goto
+ lfortran ./src/minpack.f90 -c --legacy-array-sections
+ lfortran ./examples/example_hybrd.f90 --legacy-array-sections
     FINAL L2 NORM OF THE RESIDUALS  0.1192636D-07

     NUMBER OF FUNCTION EVALUATIONS        14

     EXIT PARAMETER                         1

     FINAL APPROXIMATE SOLUTION

      -0.5706545D+00 -0.6816283D+00 -0.7017325D+00
      -0.7042129D+00 -0.7013690D+00 -0.6918656D+00
      -0.6657920D+00 -0.5960342D+00 -0.4164121D+00
+ lfortran ./examples/example_hybrd1.f90 --legacy-array-sections
At 1015:52 of file ./src/minpack.f90
Runtime error: Array '__libasr_created__subroutine_call_hybrd1' index out of bounds.
```

### PR DESCRIPTION
**Pull request by certik**
Fixes #9512.

### CODE REVIEW

File: src/lfortran/semantics/ast_common_visitor.h [hunk 1]
```diff
@@ -7801,9 +7801,18 @@ class CommonVisitor : public AST::BaseVisitor<Derived> {
...
+                            if (expected_n_dims_cast != actual_n_dims) {
+                                section_type = ASRUtils::duplicate_type_with_empty_dims(
+                                    al, ASRUtils::expr_type(array_expr),
+                                    ASR::array_physical_typeType::DescriptorArray, true
+                                );
+                            } else {
+                                section_type = ASRUtils::duplicate_type_with_empty_dims(
+                                    al, expected_arg_type, ASR::array_physical_typeType::DescriptorArray, true
+                                );
+                            }
```
Comment (xaerru) [inline src/lfortran/semantics/ast_common_visitor.h:7815]: Running the MRE on linux the output is different:
```shell
$ ./src/bin/lfortran a.f90 --legacy-array-sections                                                                                                                         
At 8:20 of file a.f90
Runtime error: Array '__libasr_created__subroutine_call_process2d1' index out of bounds.

Tried to access index 0 of dimension 2, but valid range is 1 to 19.
```

After applying only this diff to main, the MRE and the test added in this PR pass on linux.

Are the `asr_to_llvm.cpp` changes fixing something else? The MRE doesn't have `ArrayPhysicalCast` from descriptor to descriptor.

Comment (certik) [reply src/lfortran/semantics/ast_common_visitor.h:7815]: Yes, it was fixing some issue, but I think it is not needed, the above fix is the fix. I also removed the i+1 changes. We should investigate those later.

**Comment by certik** [comment]
@xaerru good catch, now the PR is super simple.
