### PR TITLE
fix: type mismatch in dim size of array reshape

### LINKED ISSUE #3763: type mismatch in dim size for array reshape
```fortran
program main
use iso_fortran_env, only: int8
integer(int8), dimension(8) :: x
x = [1_1, 2_1, 3_1, 4_1, 5_1, 6_1, 7_1, 8_1]
print *, median_all_1_iint8_dp(x)
if (abs(median_all_1_iint8_dp(x) - 36.0) > 1e-16) error stop

contains
function median_all_1_iint8_dp(x) result(res)
use iso_fortran_env, only: int64, int8, dp => real64
integer(int8), intent(inout) :: x(:)
real(dp) :: res
integer(kind = int64) :: n

n = size(x)
x = reshape(x, [n])
res = sum(x)
end function median_all_1_iint8_dp
end program
```

### PR DESCRIPTION
**Pull request by Pranavchiku**
Fixes #3763. Towards LLVM compilation of `stdlib_stats_median`. Fix is similar to #3093.

### CODE REVIEW

File: integration_tests/arrays_reshape_17.f90 [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+use iso_fortran_env, only: int64, int8, dp => real64
+integer(int8), intent(inout) :: x(:)
+real(dp) :: res
+integer(kind = int64) :: n
+
+n = size(x)
+x = reshape(x, [n])
+res = sum(x)
+end function median_all_1_iint8_dp
+end program
```
Comment (HarshitaKalani) [inline integration_tests/arrays_reshape_17.f90:19]: I think this will look better with some indentation. What do you think?

Comment (Pranavchiku) [reply integration_tests/arrays_reshape_17.f90:19]: Yes, will do it, thanks for noticing.

**Review by certik — APPROVED** [review]
