### PR TITLE
fix: location information of imported symbols from another Module

### LINKED ISSUE #5772: LSP with modules
With https://github.com/lfortran/lfortran-lsp/pull/44

* [ ] LSP shall generate a `.mod` file as soon as we open a module file so that it can be used by other programs ( https://github.com/lfortran/lfortran-lsp/pull/44 )
* [ ] Fix the location information, currently it points to line 1, column 1

> a.f90

```fortran
subroutine add()
end subroutine
program expr2
use module_expr2
implicit none
integer :: x
x = (2+3)*5
print *, x, xy
call sub()
call add()
end program

```

> b.f90

```fortran
module module_expr2
    implicit none
    integer :: xy, yz
contains
subroutine sub()
    implicit none
end subroutine
subroutine sub2()
    implicit none
end subroutine
end module module_expr2
```

Ideally, if I click on `b.f90`, it shall generate `module_expr2.mod` file which then opening `a.f90` shall be linked automatically  (https://github.com/lfortran/lfortran-lsp/pull/44)

Right now, I need to first do `lfortran -c b.f90` and then open `a.f90`

On hover to elements of module, it returns `line=1, column=1` location

image

### PR DESCRIPTION
**Pull request by Pranavchiku**
Fixes #5772. With this we have correct location information of symbols that are imported from another module.

> a.f90

```fortran
subroutine add()
end subroutine

program expr2
use module_expr2
implicit none
integer :: x
x = (2+3)*5
print *, x, xy
call sub()
call add()
end program
```

> b.f90

```fortran
module module_expr2
    implicit none
    integer :: xy, yz
contains
subroutine sub()
    implicit none
end subroutine
subroutine sub2()
    implicit none
end subroutine
end module module_expr2
```

```console
% lfortran a.f90 --show-document-symbols | jq
[
  {
    "kind": 12,
    "location": {
      "range": {
        "start": {
          "character": 1,
          "line": 0
        },
        "end": {
          "character": 14,
          "line": 1
        }
      },
      "uri": "uri"
    },
    "name": "add",
    "filename": "a.f90"
  },
  {
    "kind": 12,
    "location": {
      "range": {
        "start": {
          "character": 1,
          "line": 3
        },
        "end": {
          "character": 11,
          "line": 11
        }
      },
      "uri": "uri"
    },
    "name": "expr2",
    "filename": "a.f90"
  },
  {
    "kind": 12,
    "location": {
      "range": {
        "start": {
          "character": 1,
          "line": 4
        },
        "end": {
          "character": 14,
          "line": 6
        }
      },
      "uri": "uri"
    },
    "name": "sub",
    "filename": "b.f90"
  },
  {
    "kind": 12,
    "location": {
      "range": {
        "start": {
          "character": 1,
          "line": 7
        },
        "end": {
          "character": 14,
          "line": 9
        }
      },
      "uri": "uri"
    },
    "name": "sub2",
    "filename": "b.f90"
  },
  {
    "kind": 13,
    "location": {
      "range": {
        "start": {
          "character": 12,
          "line": 6
        },
        "end": {
          "character": 12,
          "line": 6
        }
      },
      "uri": "uri"
    },
    "name": "x",
    "filename": "a.f90"
  },
  {
    "kind": 12,
    "location": {
      "range": {
        "start": {
          "character": 16,
          "line": 2
        },
        "end": {
          "character": 17,
          "line": 2
        }
      },
      "uri": "uri"
    },
    "name": "xy",
    "filename": "b.f90"
  },
  {
    "kind": 12,
    "location": {
      "range": {
        "start": {
          "character": 20,
          "line": 2
        },
        "end": {
          "character": 21,
          "line": 2
        }
      },
      "uri": "uri"
    },
    "name": "yz",
    "filename": "b.f90"
  },
  {
    "kind": 2,
    "location": {
      "range": {
        "start": {
          "character": 1,
          "line": 0
        },
        "end": {
          "character": 23,
          "line": 10
        }
      },
      "uri": "uri"
    },
    "name": "module_expr2",
    "filename": "b.f90"
  },
  {
    "kind": 12,
    "location": {
      "range": {
        "start": {
          "character": 1,
          "line": 4
        },
        "end": {
          "character": 14,
          "line": 6
        }
      },
      "uri": "uri"
    },
    "name": "sub",
    "filename": "b.f90"
  },
  {
    "kind": 12,
    "location": {
      "range": {
        "start": {
          "character": 1,
          "line": 7
        },
        "end": {
          "character": 14,
          "line": 9
        }
      },
      "uri": "uri"
    },
    "name": "sub2",
    "filename": "b.f90"
  },
  {
    "kind": 13,
    "location": {
      "range": {
        "start": {
          "character": 16,
          "line": 2
        },
        "end": {
          "character": 17,
          "line": 2
        }
      },
      "uri": "uri"
    },
    "name": "xy",
    "filename": "b.f90"
  },
  {
    "kind": 13,
    "location": {
      "range": {
        "start": {
          "character": 20,
          "line": 2
        },
        "end": {
          "character": 21,
          "line": 2
        }
      },
      "uri": "uri"
    },
    "name": "yz",
    "filename": "b.f90"
  }
]
```

### CODE REVIEW

File: src/libasr/serialization.cpp [hunk 1]
```diff
@@ -61,13 +61,13 @@ class ASRDeserializationVisitor :
...
     ASRDeserializationVisitor(Allocator &al, const std::string &s,
-        bool load_symtab_id) :
+        bool load_symtab_id, uint32_t offset) :
 #ifdef WITH_LFORTRAN_BINARY_MODFILES
             BinaryReader(s),
 #else
             TextReader(s),
 #endif
-            DeserializationBaseVisitor(al, load_symtab_id) {}
+            DeserializationBaseVisitor(al, load_symtab_id, offset) {}
```
Comment (dylon) [inline src/libasr/serialization.cpp:70]: When I try to build this branch, I get the following error, here:

```
/home/dylon/Workspace/lcompilers/lfortran/src/libasr/serialization.cpp: In constructor 'LCompilers::ASRDeserializationVisitor::ASRDeserializationVisitor(Allocator&, const std::string&, bool, uint32_t)':
/home/dylon/Workspace/lcompilers/lfortran/src/libasr/serialization.cpp:70:66: error: no matching function for call to 'LCompilers::ASR::DeserializationBaseVisitor<LCompilers::ASRDeserializationVisitor>::DeserializationBaseVisitor(Allocator&, bool&, uint32_t&)'
   70 |             DeserializationBaseVisitor(al, load_symtab_id, offset) {}
      |                                                                  ^
In file included from /home/dylon/Workspace/lcompilers/lfortran/src/libasr/serialization.cpp:11:
/home/dylon/Workspace/lcompilers/lfortran/src/libasr/../libasr/asr_deserialization_visitor.h:28:5: note: candidate: 'LCompilers::ASR::DeserializationBaseVisitor<StructType>::DeserializationBaseVisitor(Allocator&, bool) [with StructType = LCompilers::ASRDeserializationVisitor]'
   28 |     DeserializationBaseVisitor(Allocator &al, bool load_symtab_id) : al{al}, load_symtab_id{load_symtab_id} {}
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/dylon/Workspace/lcompilers/lfortran/src/libasr/../libasr/asr_deserialization_visitor.h:28:5: note:   candidate expects 2 arguments, 3 provided
/home/dylon/Workspace/lcompilers/lfortran/src/libasr/../libasr/asr_deserialization_visitor.h:20:7: note: candidate: 'LCompilers::ASR::DeserializationBaseVisitor<LCompilers::ASRDeserializationVisitor>::DeserializationBaseVisitor(const LCompilers::ASR::DeserializationBaseVisitor<LCompilers::ASRDeserializationVisitor>&)'
   20 | class DeserializationBaseVisitor : public BaseVisitor<StructType>
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/dylon/Workspace/lcompilers/lfortran/src/libasr/../libasr/asr_deserialization_visitor.h:20:7: note:   candidate expects 1 argument, 3 provided
/home/dylon/Workspace/lcompilers/lfortran/src/libasr/../libasr/asr_deserialization_visitor.h:20:7: note: candidate: 'LCompilers::ASR::DeserializationBaseVisitor<LCompilers::ASRDeserializationVisitor>::DeserializationBaseVisitor(LCompilers::ASR::DeserializationBaseVisitor<LCompilers::ASRDeserializationVisitor>&&)'
/home/dylon/Workspace/lcompilers/lfortran/src/libasr/../libasr/asr_deserialization_visitor.h:20:7: note:   candidate expects 1 argument, 3 provided
```

It looks like the header is missing the `offset` parameter and respective initializer:

```
src/libasr/asr_deserialization_visitor.h:28:    DeserializationBaseVisitor(Allocator &al, bool load_symtab_id) : al{al}, load_symtab_id{load_symtab_id} {}
```

Comment (dylon) [reply src/libasr/serialization.cpp:70]: I added dummy parameters to the respective constructor definitions in libasr and lfortran, and was able to compile the changes. I ran `--show-document-symbols` against [analyze.f90](https://github.com/certik/SNAP/blob/master/src/analyze.f90) from the [SNAP](https://github.com/certik/SNAP/tree/master) repo after rebuilding it with this version of lfortran, but all imported symbols showed up as being part of `analyze.f90`. I've included the output, below, for one of the affected symbols (`i_knd`). It was imported from the `global_module` but is returned as part of `analyze.f90`:

```shell
lfortran --show-document-symbols analyze.f90 | jq
[
  // ...
  {
    "kind": 12,
    "location": {
      "range": {
        "start": {
          "character": 1,
          "line": 0
        },
        "end": {
          "character": 1,
          "line": 0
        }
      },
      "uri": "uri"
    },
    "name": "i_knd",
    "filename": "analyze.f90"
  },
  // ...
]
```

Comment (assem2002) [reply src/libasr/serialization.cpp:70]: Try running `build0.sh` it builds cpp visitors out of the ASDL file.

Comment (dylon) [reply src/libasr/serialization.cpp:70]: Ah, I didn't realize these were generated files. I'll do that and check again, thank you!

**Comment by Pranavchiku** [comment]
We have it, I'll post json.

**Comment by Pranavchiku** [comment]
We have all information, steps to build:

```
cd src
make -j8 FORTRAN=lfortran FFLAGS= MPI=no OPENMP=no
cd ../
lfortran src/analyze.f90 --show-document-symbols -Isrc/
```
[output.json](https://github.com/user-attachments/files/18230742/output.json)

File: src/libasr/serialization.cpp (hunk 1 above)
Comment (dylon) [reply src/libasr/serialization.cpp:70]: That got me closer, but it is now reporting that `i_knd` is from `time_module` instead of `global_module`, and the location information seems wrong (line- and character-range):

```json
  {
    "kind": 12,
    "location": {
      "range": {
        "start": {
          "character": 575,
          "line": 98
        },
        "end": {
          "character": 604,
          "line": 98
        }
      },
      "uri": "uri"
    },
    "name": "i_knd",
    "filename": "time.0.f90"
  }
```

Comment (Pranavchiku) [reply src/libasr/serialization.cpp:70]: Refer https://github.com/lfortran/lfortran/pull/5796#issuecomment-2559872162

**Comment by assem2002** [comment]
Great work! the json return looks good.

**Comment by dylon** [comment]
> We have all information, steps to build:
> 
> ```
> cd src
> make -j8 FORTRAN=lfortran FFLAGS= MPI=no OPENMP=no
> cd ../
> lfortran src/analyze.f90 --show-document-symbols -Isrc/
> ```
> 
> [output.json](https://github.com/user-attachments/files/18230742/output.json)

The location information in the `output.json` looks incorrect. Take `i_knd` from my example above. In `output.json`, it is reported in `time.0.f90` when it should be in `global.f90`, and the line- and character-ranges are incorrect. The ranges also differ from what it gives me on my machine:

```json
{
    "kind": 12,
    "location": {
      "range": {
        "start": {
          "character": 575,
          "line": 128
        },
        "end": {
          "character": 604,
          "line": 128
        }
      },
      "uri": "uri"
    },
    "name": "i_knd",
    "filename": "time.0.f90"
  }
```

**Comment by Pranavchiku** [comment]
Yes, that won't be difficult to debug. The main thing is to get this in so that we can integrate this with LSP and even if incorrect we can go to definition, etc.

**Comment by dylon** [comment]
Okay, I can work with that. Once @certik gives his approval and we merge this, I will file a bug report if the issue is still present.

**Review by certik — APPROVED** [review]
I think this is good, great job!

The rest we can fix up after it's merged.

**Comment by certik** [comment]
Here is a bug I noticed: https://github.com/lfortran/lfortran/issues/5802
