### PR TITLE
test: add test for issue #7780

### LINKED ISSUE #7780: Handle formatted read from a string
MRE:
```fortran
program read_nan_string
  implicit none
  character(len=3) :: nan_string
  real :: valu

  nan_string = 'NaN'
  read(nan_string, '(f3.3)') valu

  print *, 'Read value:', valu
end program read_nan_string
```

LFortran Error:
```console
code generation error: asr_to_llvm: module failed verification. Error:
Call parameter type does not match function signature!
  %4 = load i8*, i8** %nan_string, align 8
 i32  call void (i32, i32*, i32*, i8*, i8*, i32, ...) @_lfortran_formatted_read(i8* %4, i32* %5, i32* %6, i8* getelementptr inbounds ([4 x i8], [4 x i8]* @1, i32 0, i32 0), i8* getelementptr inbounds ([7 x i8], [7 x i8]* @2, i32 0, i32 0), i32 1, float* %valu)
```

### PR DESCRIPTION
**Pull request by opixdown**
fixes #7780

### CODE REVIEW

File: integration_tests/read_25.f90 [hunk 1]
```diff
@@ -0,0 +1,12 @@
+program read_nan_string
+  implicit none
+  character(len=3) :: nan_string
+  real :: valu
+
+  nan_string = 'NaN'
+  read(nan_string, '(f3.3)') valu
+
+  if (valu == valu) error stop "wrong value read"
```
Comment (certik) [inline integration_tests/read_25.f90]: This should trigger a failure. I think this condition is incorrect.

Comment (certik) [reply integration_tests/read_25.f90]: The tests passed, but I would expect them to fail, since the condition `valu == valu` should evaluate to true.

So something is wrong.

Comment (opixdown) [reply integration_tests/read_25.f90]: You’re right  the test should only check that the READ doesn’t crash

Comment (certik) [reply integration_tests/read_25.f90]: No, the test needs to test what read should read with an if statement.

**Comment by certik** [comment]
Add an if test per https://github.com/lfortran/lfortran/pull/9441#discussion_r2678751205. Then it should be good. You can use some ieee intrinsic to obtain NaN, which should be the correct answer I think.

**Comment by certik** [comment]
Looks good now, thanks!
