### PR TITLE
fix: Correctly validate ichar(char(0)) by evaluating inner function return type

### LINKED ISSUE #7576: bug: incorrect error for `ichar(char(0))`
```fortran
program main
    print *, ichar(char(0))
end program
```
```console
$ lfortran b.f90
semantic error: Argument to Ichar must have length one
 --> b.f90:2:14
  |
2 |     print *, ichar(char(0))
  |              ^^^^^^^^^^^^^^ 


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
$ gfortran b.f90 && ./a.out
           0
```

### PR DESCRIPTION
**Pull request by Jatinagarwal24**
Fixes #7576

### CODE REVIEW

**Comment by certik** [comment]
Please change the title for a good description of what was fixed, then in the PR description add details and say "Fixes ###." and the issue number.

File: src/libasr/pass/intrinsic_functions.h [hunk 1]
```diff
@@ -5503,12 +5503,14 @@ namespace Ichar {
     static ASR::expr_t *eval_Ichar(Allocator &al, const Location &loc,
             ASR::ttype_t* t1, Vec<ASR::expr_t*> &args, diag::Diagnostics& /*diag*/) {
         char* str = ASR::down_cast<ASR::StringConstant_t>(args[0])->m_s;
-        LCOMPILERS_ASSERT((std::strlen(str)) == 1);
+        // Note: We don't use strlen() here because it fails for '\0' (null char)
+        // The length validation is done in create_Ichar
```
Comment (certik) [inline src/libasr/pass/intrinsic_functions.h]: Just change it to something like:
```c++
LCOMPILERS_ASSERT(str == "\0" || std::strlen(str) == 1);
```
That way we are still ensuring the length is good.

File: src/libasr/intrinsic_func_registry_util_gen.py [hunk 2]
```diff
@@ -1051,6 +1051,13 @@ def add_create_func_arg_type_src(func_name):
                 constraint = list(arg_spec.values())[0]
                 src += 3 * indent + f'if (ASR::is_a<ASR::String_t>(*arg_type{arg_pos})) {{\n'
                 src += 4 * indent + f'int64_t len = ASRUtils::get_fixed_string_len(arg_type{arg_pos});\n'
+                # If type-based length is unknown, try to get length from compile-time value
+                src += 4 * indent + f'if (len == -1) {{\n'
+                src += 5 * indent + f'ASR::expr_t* value = ASRUtils::expr_value(args[{arg_pos}]);\n'
+                src += 5 * indent + f'if (value && ASR::is_a<ASR::StringConstant_t>(*value)) {{\n'
+                src += 6 * indent + f'len = std::string(ASR::down_cast<ASR::StringConstant_t>(value)->m_s).size();\n'
+                src += 5 * indent + f'}}\n'
+                src += 4 * indent + f'}}\n'
```
Comment (certik) [inline src/libasr/intrinsic_func_registry_util_gen.py:1060]: @HarshitaKalani is this the right fix?

Comment (HarshitaKalani) [reply src/libasr/intrinsic_func_registry_util_gen.py:1060]: I believe it is correct. And this also fixes the bug.

**Comment by Jatinagarwal24** [comment]
Hi @certik ,
Can you please review this.
