### PR TITLE
fix: append unique string to intermediate object file name

### LINKED ISSUE #8294: Concurrent trivial lfortran invocations race
As of LFortran 0.54.0:

```console
$ cat main.f
      PROGRAM main
      END
$ lfortran -v main.f
clang -o main.out /tmp/main.tmp.o ...
```

If multiple `lfortran -v main.f` occur concurrently in separate directories, their use of `/tmp/main.tmp.o` races, and can collide and fail.

### PR DESCRIPTION
**Pull request by kmr-srbh**
resolves #8294

> test.f90
```fortran
program main
   implicit none

   print *, 1
end program
```

> test_compiler.sh
```shell
seq 1 10 | parallel -j 10 "
    mkdir -p compilertest_{};
    cd compilertest_{};
    cp /Users/saurabhkumar/OpenSource/lfortran/test.f90 .;
    lfortran test.f90
"
```

#### Before
```console
1
1
1
1
clang: error: no such file or directory: '/var/folders/f7/1xrqkz0d2t10r5dftx8zyfzm0000gn/T/test.tmp.o'
The command 'clang -o test.out /var/folders/f7/1xrqkz0d2t10r5dftx8zyfzm0000gn/T/test.tmp.o  -L"/Users/saurabhkumar/OpenSource/lfortran/src/bin/../runtime" -Wl,-rpath,"/Users/saurabhkumar/OpenSource/lfortran/src/bin/../runtime" -llfortran_runtime -lm' failed.
Tip: If there is a linker issue, switch the linker using --linker=<CC> option or create an environment variable `export LFORTRAN_LINKER=<CC>`, where CC is clang or gcc
Also, if required use --linker-path=<PATH>, where PATH has location to look for the linker execuatable
clang: error: no such file or directory: '/var/folders/f7/1xrqkz0d2t10r5dftx8zyfzm0000gn/T/test.tmp.o'
The command 'clang -o test.out /var/folders/f7/1xrqkz0d2t10r5dftx8zyfzm0000gn/T/test.tmp.o  -L"/Users/saurabhkumar/OpenSource/lfortran/src/bin/../runtime" -Wl,-rpath,"/Users/saurabhkumar/OpenSource/lfortran/src/bin/../runtime" -llfortran_runtime -lm' failed.
Tip: If there is a linker issue, switch the linker using --linker=<CC> option or create an environment variable `export LFORTRAN_LINKER=<CC>`, where CC is clang or gcc
Also, if required use --linker-path=<PATH>, where PATH has location to look for the linker execuatable
1
1
clang: error: no such file or directory: '/var/folders/f7/1xrqkz0d2t10r5dftx8zyfzm0000gn/T/test.tmp.o'
The command 'clang -o test.out /var/folders/f7/1xrqkz0d2t10r5dftx8zyfzm0000gn/T/test.tmp.o  -L"/Users/saurabhkumar/OpenSource/lfortran/src/bin/../runtime" -Wl,-rpath,"/Users/saurabhkumar/OpenSource/lfortran/src/bin/../runtime" -llfortran_runtime -lm' failed.
Tip: If there is a linker issue, switch the linker using --linker=<CC> option or create an environment variable `export LFORTRAN_LINKER=<CC>`, where CC is clang or gcc
Also, if required use --linker-path=<PATH>, where PATH has location to look for the linker execuatable
clang: error: no such file or directory: '/var/folders/f7/1xrqkz0d2t10r5dftx8zyfzm0000gn/T/test.tmp.o'
The command 'clang -o test.out /var/folders/f7/1xrqkz0d2t10r5dftx8zyfzm0000gn/T/test.tmp.o  -L"/Users/saurabhkumar/OpenSource/lfortran/src/bin/../runtime" -Wl,-rpath,"/Users/saurabhkumar/OpenSource/lfortran/src/bin/../runtime" -llfortran_runtime -lm' failed.
Tip: If there is a linker issue, switch the linker using --linker=<CC> option or create an environment variable `export LFORTRAN_LINKER=<CC>`, where CC is clang or gcc
Also, if required use --linker-path=<PATH>, where PATH has location to look for the linker execuatable
```

#### After

```console
Object file name: /var/folders/f7/1xrqkz0d2t10r5dftx8zyfzm0000gn/T/test.tmp_QWh3gaRhvEJfHNmISar5cF.o
1
Object file name: /var/folders/f7/1xrqkz0d2t10r5dftx8zyfzm0000gn/T/test.tmp_VsqPS3DSskrUAJqlhyGmtc.o
1
Object file name: /var/folders/f7/1xrqkz0d2t10r5dftx8zyfzm0000gn/T/test.tmp_6bX2wDzDRCee8PNScf3bgx.o
1
Object file name: /var/folders/f7/1xrqkz0d2t10r5dftx8zyfzm0000gn/T/test.tmp_rdpATwFuuk1ZcmJGRbGqgv.o
1
Object file name: /var/folders/f7/1xrqkz0d2t10r5dftx8zyfzm0000gn/T/test.tmp_MOZZ4c7dYm09ZRrTAozFMv.o
1
Object file name: /var/folders/f7/1xrqkz0d2t10r5dftx8zyfzm0000gn/T/test.tmp_b7MnsEbqLZslRX1wrnw2QK.o
1
Object file name: /var/folders/f7/1xrqkz0d2t10r5dftx8zyfzm0000gn/T/test.tmp_OIHXJ4FTzsSUjq2tRUEabS.o
1
Object file name: /var/folders/f7/1xrqkz0d2t10r5dftx8zyfzm0000gn/T/test.tmp_0iZeXHmdbyZOeCXtrceR3l.o
1
Object file name: /var/folders/f7/1xrqkz0d2t10r5dftx8zyfzm0000gn/T/test.tmp_pJSrwHs3wqghQNqzq9FziJ.o
1
Object file name: /var/folders/f7/1xrqkz0d2t10r5dftx8zyfzm0000gn/T/test.tmp_lmtjEKOl5E7d4TEa66ERlU.o
1
```

### CODE REVIEW

**Comment by kmr-srbh** [comment]
The `clang` error in the "Before" section occurs because we delete the temporary files after we are done with the executable linking. When doing multiple executions in parallel, it led to an error.

**Comment by kmr-srbh** [comment]
The CI failure is unrelated:

```console
The following tests FAILED:
	 20 - sorting (Failed)
Errors while running CTest
```

It is similar to #8171. It fails randomly.

**Comment by certik** [comment]
CI fails.

File: src/bin/lfortran.cpp [hunk 1]
```diff
@@ -127,6 +128,9 @@ std::string get_unique_ID() {
     return res;
 }
 
+// The unique compilation ID for this invocation of the compiler.
+const std::string LFORTRAN_COMPILATION_ID = get_unique_ID();
```
Comment (certik) [inline src/bin/lfortran.cpp:132]: We already have `lcompilers_unique_ID`, cannot you use that?

Comment (kmr-srbh) [reply src/bin/lfortran.cpp:132]: We are setting and using that variable when we use separate compilation. This string is empty otherwise. In our case, we always want a value, so I created a different variable.

Comment (certik) [reply src/bin/lfortran.cpp:132]: I think we should always set it, this PR shows that it is needed for monolithic compilation also.

Do you mind unifying this in a subsequent PR?

Comment (kmr-srbh) [reply src/bin/lfortran.cpp:132]: Yes! :)
