### PR TITLE
fix: implement specifiers for file inquire

### LINKED ISSUE #9434: INQUIRE returning mostly uninitialized values
INQUIRE doesn't return valid results for most keywords yet.  Here are tests for a Fortran-77-ish subset of INQUIREs capabilities:
```
program inquiries
  implicit none

! Test Fortran-77-ish subset of INQUIRE capabilities

  integer :: unit, unit_no
  logical :: exists, opened, named
  character(32) :: name, access, seq, direct, blank
  character(32) :: form, formatted, unformatted
  integer :: recl, nextrec
  integer :: i

  character(*), parameter :: testfn = 'inqtest.dat'
  character(*), parameter :: uninitc = '(uninit)'

! Sequential formatted by filename

  print *, 'sequential formatted by filename'
  open (newunit=unit, file=testfn, form='formatted', status='unknown')
  write (unit, '(i4)') 42
  rewind (unit)

  call init_test ()
  inquire (file=testfn, exist=exists, opened=opened, number=unit_no,  &
      named=named, name=name, access=access, sequential=seq, direct=direct,  &
      form=form, formatted=formatted, unformatted=unformatted, blank=blank)
  print *, 'exist      = ', exists, ' :', pf (exists)
  print *, 'opened     = ', opened, ' :', pf (opened)
  print *, 'number     = ', unit_no, ' :', pf (unit == unit_no)
  print *, 'named      = ', named, ' :', pf (named)
  print *, 'name       = ', trim (name), ' :', pf (name == testfn)
  print *, 'access     = ', trim (access), ' :', pf (access == 'SEQUENTIAL')
  print *, 'sequential = ', trim (seq), ' :', pf (seq == 'YES')
  print *, 'direct     = ', trim (direct), ' :', pf (direct == 'NO')
  print *, 'form       = ', trim (form), ' :', pf (form == 'FORMATTED')
  print *, 'formatted  = ', trim (formatted), ' :', pf (formatted == 'YES')
  print *, 'unformatted =', trim (unformatted), ' :', pf (unformatted == 'NO')
  print *, 'blank      = ', trim (blank), ' :', pf (blank == 'NULL')
  close (unit, status='keep')

! Sequential formatted by unitno

  print *; print *, 'sequential formatted by unitno'
  open (newunit=unit, file=testfn, form='formatted', status='old', blank='zero')
  write (unit, '(i4)') 42
  rewind (unit)

  call init_test ()
  inquire (unit=unit, exist=exists, opened=opened, number=unit_no,  &
      named=named, name=name, access=access, sequential=seq, direct=direct,  &
      form=form, formatted=formatted, unformatted=unformatted, blank=blank)
  print *, 'exist      = ', exists, ' :', pf (exists)
  print *, 'opened     = ', opened, ' :', pf (opened)
  print *, 'number     = ', unit_no, ' :', pf (unit == unit_no)
  print *, 'named      = ', named, ' :', pf (named)
  print *, 'name       = ', trim (name), ' :', pf (name == testfn)
  print *, 'access     = ', trim (access), ' :', pf (access == 'SEQUENTIAL')
  print *, 'sequential = ', trim (seq), ' :', pf (seq == 'YES')
  print *, 'direct     = ', trim (direct), ' :', pf (direct == 'NO')
  print *, 'form       = ', trim (form), ' :', pf (form == 'FORMATTED')
  print *, 'formatted  = ', trim (formatted), ' :', pf (formatted == 'YES')
  print *, 'unformatted =', trim (unformatted), ' :', pf (unformatted == 'NO')
  print *, 'blank      = ', trim (blank), ' :', pf (blank == 'ZERO')
  close (unit, status='delete')

! Sequential unformatted by filename

  print *; print *, 'sequential formatted by filename'
  open (newunit=unit, file=testfn, form='unformatted', status='new')
  write (unit) 42
  rewind (unit)

  call init_test ()
  inquire (file=testfn, exist=exists, opened=opened, number=unit_no,  &
      named=named, name=name, access=access, sequential=seq, direct=direct,  &
      form=form, formatted=formatted, unformatted=unformatted, blank=blank)
  print *, 'exist      = ', exists, ' :', pf (exists)
  print *, 'opened     = ', opened, ' :', pf (opened)
  print *, 'number     = ', unit_no, ' :', pf (unit == unit_no)
  print *, 'named      = ', named, ' :', pf (named)
  print *, 'name       = ', trim (name), ' :', pf (name == testfn)
  print *, 'access     = ', trim (access), ' :', pf (access == 'SEQUENTIAL')
  print *, 'sequential = ', trim (seq), ' :', pf (seq == 'YES')
  print *, 'direct     = ', trim (direct), ' :', pf (direct == 'NO')
  print *, 'form       = ', trim (form), ' :', pf (form == 'UNFORMATTED')
  print *, 'formatted  = ', trim (formatted), ' :', pf (formatted == 'NO')
  print *, 'unformatted =', trim (unformatted), ' :', pf (unformatted == 'YES')
  print *, 'blank      = ', trim (blank), ' :', pf (blank == 'UNDEFINED')
  close (unit, status='keep')

! Sequential unformatted by unitno

  print *; print *, 'sequential formatted by unitno'
  open (newunit=unit, file=testfn, form='unformatted', status='old')
  write (unit) 42
  rewind (unit)

  call init_test ()
  inquire (unit=unit, exist=exists, opened=opened, number=unit_no,  &
      named=named, name=name, access=access, sequential=seq, direct=direct,  &
      form=form, formatted=formatted, unformatted=unformatted, blank=blank)
  print *, 'exist      = ', exists, ' :', pf (exists)
  print *, 'opened     = ', opened, ' :', pf (opened)
  print *, 'number     = ', unit_no, ' :', pf (unit == unit_no)
  print *, 'named      = ', named, ' :', pf (named)
  print *, 'name       = ', trim (name), ' :', pf (name == testfn)
  print *, 'access     = ', trim (access), ' :', pf (access == 'SEQUENTIAL')
  print *, 'sequential = ', trim (seq), ' :', pf (seq == 'YES')
  print *, 'direct     = ', trim (direct), ' :', pf (direct == 'NO')
  print *, 'form       = ', trim (form), ' :', pf (form == 'UNFORMATTED')
  print *, 'formatted  = ', trim (formatted), ' :', pf (formatted == 'NO')
  print *, 'unformatted =', trim (unformatted), ' :', pf (unformatted == 'YES')
  print *, 'blank      = ', trim (blank), ' :', pf (blank == 'UNDEFINED')
  close (unit, status='delete')

! Record length inquiry

  inquire (iolength=recl) 42, 42.0, 'xyzzy'
  print *; print *, 'record length =', recl

! Direct unformatted by filename

  print *; print *, 'direct formatted by filename'
  open (newunit=unit, file=testfn, access='direct', recl=recl, form='unformatted', status='new')
  do, i=1, 5
    write (unit, rec=i) 42+i, 42.0+i, 'xyzzy'
  end do

  call init_test ()
  inquire (file=testfn, exist=exists, opened=opened, number=unit_no,  &
      named=named, name=name, access=access, sequential=seq, direct=direct,  &
      form=form, formatted=formatted, unformatted=unformatted,  &
      recl=recl, nextrec=nextrec)
  print *, 'exist      = ', exists, ' :', pf (exists)
  print *, 'opened     = ', opened, ' :', pf (opened)
  print *, 'number     = ', unit_no, ' :', pf (unit == unit_no)
  print *, 'named      = ', named, ' :', pf (named)
  print *, 'name       = ', trim (name), ' :', pf (name == testfn)
  print *, 'access     = ', trim (access), ' :', pf (access == 'DIRECT')
  print *, 'sequential = ', trim (seq), ' :', pf (seq == 'NO')
  print *, 'direct     = ', trim (direct), ' :', pf (direct == 'YES')
  print *, 'form       = ', trim (form), ' :', pf (form == 'UNFORMATTED')
  print *, 'formatted  = ', trim (formatted), ' :', pf (formatted == 'NO')
  print *, 'unformatted =', trim (unformatted), ' :', pf (unformatted == 'YES')
  print *, 'recl       = ', recl, ' :', pf (recl == 13)
  print *, 'nextrec    = ', nextrec, ' :', pf (nextrec == 6)
  close (unit, status='keep')

! Direct unformatted by unitno

  print *; print *, 'direct formatted by unitno'
  open (newunit=unit, file=testfn, access='direct', recl=recl, form='unformatted', status='old')
  do, i=1, 5
    write (unit, rec=i) 42+i, 42.0+i, 'xyzzy'
  end do

  call init_test ()
  inquire (unit=unit, exist=exists, opened=opened, number=unit_no,  &
      named=named, name=name, access=access, sequential=seq, direct=direct,  &
      form=form, formatted=formatted, unformatted=unformatted,  &
      recl=recl, nextrec=nextrec)
  print *, 'exist      = ', exists, ' :', pf (exists)
  print *, 'opened     = ', opened, ' :', pf (opened)
  print *, 'number     = ', unit_no, ' :', pf (unit == unit_no)
  print *, 'named      = ', named, ' :', pf (named)
  print *, 'name       = ', trim (name), ' :', pf (name == testfn)
  print *, 'access     = ', trim (access), ' :', pf (access == 'DIRECT')
  print *, 'sequential = ', trim (seq), ' :', pf (seq == 'NO')
  print *, 'direct     = ', trim (direct), ' :', pf (direct == 'YES')
  print *, 'form       = ', trim (form), ' :', pf (form == 'UNFORMATTED')
  print *, 'formatted  = ', trim (formatted), ' :', pf (formatted == 'NO')
  print *, 'unformatted =', trim (unformatted), ' :', pf (unformatted == 'YES')
  print *, 'recl       = ', recl, ' :', pf (recl == 13)
  print *, 'nextrec    = ', nextrec, ' :', pf (nextrec == 6)
  close (unit, status='delete')

contains

  subroutine init_test ()

    exists = .false.; opened = .false.; unit_no = -99999
    named = .false.; name = uninitc
    access = uninitc; seq = uninitc; direct = uninitc
    form = uninitc; formatted = uninitc; unformatted = uninitc
    blank = uninitc
    recl = -99999; nextrec = -99999

  end subroutine

  function pf (l)
    logical, intent(in) :: l
    character(4) :: pf

    pf = merge ('pass', 'FAIL', l)

  end function
end program
```
```
$ lfortran inquiries.f90
warning: Argument `blank` isn't supported yet
  --> inquiries.f90:44:3
   |
44 |   open (newunit=unit, file=testfn, form='formatted', status='old', blank='zero')
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ignored for now


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
sequential formatted by filename
exist      =     T     :    pass
opened     =     F     :    FAIL
number     =     -99999     :    FAIL
named      =     F     :    FAIL
name       =     (uninit)     :    FAIL
access     =     (uninit)     :    FAIL
sequential =     (uninit)     :    FAIL
direct     =     (uninit)     :    FAIL
form       =     (uninit)     :    FAIL
formatted  =     (uninit)     :    FAIL
unformatted =    (uninit)     :    FAIL
blank      =     (uninit)     :    FAIL

sequential formatted by unitno
exist      =     F     :    FAIL
opened     =     T     :    pass
number     =     -99999     :    FAIL
named      =     F     :    FAIL
name       =     inqtest.dat     :    pass
access     =     SEQUENTIAL     :    pass
sequential =     (uninit)     :    FAIL
direct     =     (uninit)     :    FAIL
form       =     (uninit)     :    FAIL
formatted  =     (uninit)     :    FAIL
unformatted =    (uninit)     :    FAIL
blank      =     (uninit)     :    FAIL

sequential formatted by filename
exist      =     T     :    pass
opened     =     F     :    FAIL
number     =     -99999     :    FAIL
named      =     F     :    FAIL
name       =     (uninit)     :    FAIL
access     =     (uninit)     :    FAIL
sequential =     (uninit)     :    FAIL
direct     =     (uninit)     :    FAIL
form       =     (uninit)     :    FAIL
formatted  =     (uninit)     :    FAIL
unformatted =    (uninit)     :    FAIL
blank      =     (uninit)     :    FAIL

sequential formatted by unitno
exist      =     F     :    FAIL
opened     =     T     :    pass
number     =     -99999     :    FAIL
named      =     F     :    FAIL
name       =     inqtest.dat     :    pass
access     =     SEQUENTIAL     :    pass
sequential =     (uninit)     :    FAIL
direct     =     (uninit)     :    FAIL
form       =     (uninit)     :    FAIL
formatted  =     (uninit)     :    FAIL
unformatted =    (uninit)     :    FAIL
blank      =     (uninit)     :    FAIL

record length =    -99999

direct formatted by filename
exist      =     T     :    pass
opened     =     F     :    FAIL
number     =     -99999     :    FAIL
named      =     F     :    FAIL
name       =     (uninit)     :    FAIL
access     =     (uninit)     :    FAIL
sequential =     (uninit)     :    FAIL
direct     =     (uninit)     :    FAIL
form       =     (uninit)     :    FAIL
formatted  =     (uninit)     :    FAIL
unformatted =    (uninit)     :    FAIL
recl       =     -99999     :    FAIL
nextrec    =     -99999     :    FAIL

direct formatted by unitno
exist      =     F     :    FAIL
opened     =     T     :    pass
number     =     -99999     :    FAIL
named      =     F     :    FAIL
name       =     inqtest.dat     :    pass
access     =     DIRECT     :    pass
sequential =     (uninit)     :    FAIL
direct     =     (uninit)     :    FAIL
form       =     (uninit)     :    FAIL
formatted  =     (uninit)     :    FAIL
unformatted =    (uninit)     :    FAIL
recl       =     -99999     :    FAIL
nextrec    =     -99999     :    FAIL
$
```

### PR DESCRIPTION
**Pull request by HarshilShah1804**
Fixes #9434 

Since the last PR #9470 hasn't received any updates since past a week, I have opened this PR adding support for all the specifiers for `inquire` statement.

### CODE REVIEW

File: integration_tests/file_45.f90 [hunk 1]
```diff
@@ -0,0 +1,197 @@
...
+  end subroutine
+
+  function pf (l)
+    logical, intent(in) :: l
+    character(4) :: pf
+
+    if (l .eqv. .false.) error stop
+
+  end function
+end program
```
Comment (certik) [inline integration_tests/file_45.f90]: I think this test is not actually testing the result, correct? I think we need to check that inquire returns correct answers.

**Comment by certik** [comment]
Otherwise I think it's ok.

**Comment by certik** [comment]
You'll have to isolate an MRE from the CI failure and add it to integration tests, to ensure it gets caught by integration tests directly.

File: integration_tests/file_45.f90 (hunk 1 above)
Comment (HarshilShah1804) [reply integration_tests/file_45.f90]: Ah, yes. I'll fix it.

**Comment by HarshilShah1804** [comment]
I have isolated the MRE and opened #9611 to add it to integration tests.

Edit: The created MRE in #9611 was not the correct MRE. But, I had found the logic of the failure and fixed it. Also, I have tested `fpm` locally. So, I believe it should pass on the CI as well now.

**Comment by certik** [comment]
This is ready to merge --- but we are sprinting to get fpm working and have PRs that modify the runtime, so let's wait until those are in first, just in case there were conflicts.

**Comment by certik** [comment]
Now is a good time to merge this.
