### PR TITLE
[LLVM] Initial implementation for BitCast

### LINKED ISSUE #2875: [LLVM][FC8]: Implement `visit_BitCast`
```fortran
program main
    integer :: i = 123456
    real :: r

    r = transfer(i, r)
    print *, r
end program
```

```console
% lfortran ./src/a.f90 
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2357
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 959
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 360
    compiler_options, run_fn, infile);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9243
    v.visit_asr((ASR::asr_t&)asr);
  File "../libasr/asr.h", line 5057
  File "../libasr/asr.h", line 5033
  File "../libasr/asr.h", line 5058
  File "../libasr/asr.h", line 4766
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 945
    visit_symbol(*item.second);
  File "../libasr/asr.h", line 5060
  File "../libasr/asr.h", line 4774
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3061
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 5077
  File "../libasr/asr.h", line 4799
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4738
    this->visit_expr_wrapper(x.m_value, true);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5074
    this->visit_expr(*x);
  File "../libasr/asr.h", line 5124
  File "../libasr/asr.h", line 4921
  File "../libasr/asr.h", line 5197
LCompilersException: visit_BitCast() not implemented
```

### PR DESCRIPTION
**Pull request by Pranavchiku**
Fixes #2875. I am not sure if this is correct approach. For 
```fortran
program main
    implicit none
    integer :: i = 123456
    real :: r
    real :: result

    result = transfer(i, r)
    print *, result
end program main
```

> LFortran

```console
% lfortran a.f90 
1.23456000e+05
```

> GFortran

```console
% gfortran a.f90 && ./a.out
   1.72998703E-40
```

I feel output of GFortran is incorrect.

### CODE REVIEW

**Comment by certik** [comment]
The code looks good, but I need to think about the correctness. Most likely GFortran is correct.

**Comment by certik** [comment]
Note: I can reproduce the above results on my Apple M1 Max for both LFortran and GFortran.

File: src/libasr/codegen/asr_to_llvm.cpp [hunk 1]
```diff
@@ -6613,6 +6613,36 @@ class ASRToLLVMVisitor : public ASR::BaseVisitor<ASRToLLVMVisitor>
...
+        ASR::ttype_t* source_type = ASRUtils::expr_type(x.m_source);
+
+        this->visit_expr_wrapper(x.m_mold, true);
+        ASR::ttype_t* target_type = x.m_type;
+
+        if (source_type->type == ASR::ttypeType::Integer) {
+            if (target_type->type == ASR::ttypeType::Real) {
+                int target_kind = ASRUtils::extract_kind_from_ttype_t(target_type);
+                llvm::Type* target_type = llvm_utils->getFPType(target_kind);
+                tmp = builder->CreateSIToFP(source, target_type);
```
Comment (czgdp1807) [inline src/libasr/codegen/asr_to_llvm.cpp:6633]: You should be doing `CreateBitCast`? That re-interprets the type. `CreateSIToFP` does the actual cast and the underlying value remains the same which is what happening in your case.

Comment (Pranavchiku) [reply src/libasr/codegen/asr_to_llvm.cpp:6633]: Yes, correct. I am just pushing it with `CreateBitCast`

**Comment by Pranavchiku** [comment]
For 
```fortran
program main
    implicit none
    integer :: i = 123456
    real :: r
    real :: result

    result = transfer(i, r)
    print *, result
end program main
```

Generated LLVM

```llvm
; ModuleID = 'LFortran'
source_filename = "LFortran"

@main.i = internal global i32 0
@0 = private unnamed_addr constant [2 x i8] c" \00", align 1
@1 = private unnamed_addr constant [2 x i8] c"\0A\00", align 1
@2 = private unnamed_addr constant [9 x i8] c"%13.8e%s\00", align 1

define i32 @main(i32 %0, i8** %1) {
.entry:
  call void @_lpython_set_argv(i32 %0, i8** %1)
  store i32 123456, i32* @main.i, align 4
  %r = alloca float, align 4
  %result = alloca float, align 4
  %2 = load i32, i32* @main.i, align 4
  %3 = load float, float* %r, align 4
  %4 = bitcast i32 %2 to float
  store float %4, float* %result, align 4
  %5 = load float, float* %result, align 4
  %6 = fpext float %5 to double
  call void (i8*, ...) @_lfortran_printf(i8* getelementptr inbounds ([9 x i8], [9 x i8]* @2, i32 0, i32 0), double %6, i8* getelementptr inbounds ([2 x i8], [2 x i8]* @1, i32 0, i32 0))
  ret i32 0
}

declare void @_lpython_set_argv(i32, i8**)

declare void @_lfortran_printf(i8*, ...)
```

File: integration_tests/transfer_01.f90 [hunk 2]
```diff
@@ -0,0 +1,9 @@
+program transfer_01
+    implicit none
+    integer :: i = 123456
+    real :: r
+    real :: result
+
+    result = transfer(i, r)
+    print *, result
```
Comment (certik) [inline integration_tests/transfer_01.f90:8]: This can be done in subsequent PRs, but let's add tests for the actual values, since on all modern platforms (and all platforms that we support), the internal representation of f32/i32 is given by IEEE, so you can simply test some floating point and some integer. Say `result=3.1` and the corresponding integer. 

Test 32 and 64 bit.

Test integer to real and real to integer.

**Review by certik — APPROVED** [review]
I think this looks good, but the test should be improved per my comment below. Either in this PR or in subsequent PRs.

File: src/libasr/codegen/asr_to_llvm.cpp [hunk 3]
```diff
@@ -6659,6 +6659,36 @@ class ASRToLLVMVisitor : public ASR::BaseVisitor<ASRToLLVMVisitor>
...
+            if (target_type->type == ASR::ttypeType::Integer) {
+                int target_kind = ASRUtils::extract_kind_from_ttype_t(target_type);
+                llvm::Type* target_type = llvm_utils->getIntType(target_kind);
+                tmp = builder->CreateBitCast(source, target_type);
+            }
+        } else {
+            throw CodeGenError("Bitcast from" + ASRUtils::type_to_str_python(source_type) + " to " +  ASRUtils::type_to_str_python(target_type) + " not supported yet.");
+        }
+    }
+
```
Comment (czgdp1807) [inline src/libasr/codegen/asr_to_llvm.cpp:6691]: This approach is very verbose. I don't think that's needed. You shouldn't be needing to use the `source_type`. Just get the LLVM type for `target_type` and then do `CreateBitCast`. I am -1 on merging this as is. First add tests for a bunch of type combinations and then improvise the approach. Testing it for a single type combination doesn't help in verifying whether the approach is good enough or not.

**Review by czgdp1807 — CHANGES_REQUESTED** [review]

File: src/libasr/codegen/asr_to_llvm.cpp (hunk 3 above)
Comment (Pranavchiku) [reply src/libasr/codegen/asr_to_llvm.cpp:6691]: Yes, I agree. I'll improve it and test. In subsequent PRs, I'll try to get every case working.

File: integration_tests/transfer_01.f90 (hunk 2 above)
Comment (Pranavchiku) [reply integration_tests/transfer_01.f90:8]: I am not sure how can we test with actual values.

Comment (certik) [reply integration_tests/transfer_01.f90:8]: See the equivalence tests that @HarshitaKalani did which does exactly that. Set i = something, and check that result = something_else.

File: integration_tests/transfer_02.f90 [hunk 4]
```diff
@@ -0,0 +1,9 @@
+program transfer_02
+    integer :: result
+    double precision :: d
+
+    d = 3.14D0
+    result = transfer(d, result)
```
Comment (Pranavchiku) [inline integration_tests/transfer_02.f90:6]:
```console
% lfortran ./integration_tests/transfer_02.f90 
; ModuleID = 'LFortran'
source_filename = "LFortran"

@0 = private unnamed_addr constant [2 x i8] c" \00", align 1
@1 = private unnamed_addr constant [2 x i8] c"\0A\00", align 1
@2 = private unnamed_addr constant [5 x i8] c"%d%s\00", align 1
@3 = private unnamed_addr constant [12 x i8] c"ERROR STOP\0A\00", align 1

define i32 @main(i32 %0, i8** %1) {
.entry:
  call void @_lpython_set_argv(i32 %0, i8** %1)
  %d = alloca double, align 8
  %result = alloca i32, align 4
  store double 3.140000e+00, double* %d, align 8
  %2 = load double, double* %d, align 8
  %3 = bitcast double %2 to i32
  store i32 %3, i32* %result, align 4
  %4 = load i32, i32* %result, align 4
  call void (i8*, ...) @_lfortran_printf(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @2, i32 0, i32 0), i32 %4, i8* getelementptr inbounds ([2 x i8], [2 x i8]* @1, i32 0, i32 0))
  %5 = load i32, i32* %result, align 4
  %6 = icmp ne i32 %5, 1374389535
  br i1 %6, label %then, label %else

then:                                             ; preds = %.entry
  call void (i8*, ...) @_lcompilers_print_error(i8* getelementptr inbounds ([12 x i8], [12 x i8]* @3, i32 0, i32 0))
  call void @exit(i32 1)
  br label %ifcont

else:                                             ; preds = %.entry
  br label %ifcont

ifcont:                                           ; preds = %else, %then
  ret i32 0
}

declare void @_lpython_set_argv(i32, i8**)

declare void @_lfortran_printf(i8*, ...)

declare void @_lcompilers_print_error(i8*, ...)

declare void @exit(i32)
code generation error: asr_to_llvm: module failed verification. Error:
Invalid bitcast
  %3 = bitcast double %2 to i32



Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

Comment (certik) [reply integration_tests/transfer_02.f90:6]: I think that's because double is 64 bit, but integer is 32 bit.

I would worry about this case later, we can merge the other case where both sizes are the same.

**Comment by certik** [comment]
I think this looks good now.

**Review by certik — APPROVED** [review]
I think that this is good to merge now. Good test.

File: src/libasr/codegen/asr_to_llvm.cpp [hunk 5]
```diff
@@ -6659,6 +6659,29 @@ class ASRToLLVMVisitor : public ASR::BaseVisitor<ASRToLLVMVisitor>
...
+        llvm::Value* source = tmp;
+        ASR::ttype_t* target_type = x.m_type;
+
+        if (target_type->type == ASR::ttypeType::Real) {
+            int target_kind = ASRUtils::extract_kind_from_ttype_t(target_type);
+            llvm::Type* target_type = llvm_utils->getFPType(target_kind);
+            tmp = builder->CreateBitCast(source, target_type);
+        } else if (target_type->type == ASR::ttypeType::Integer) {
+            int target_kind = ASRUtils::extract_kind_from_ttype_t(target_type);
+            llvm::Type* target_type = llvm_utils->getIntType(target_kind);
```
Comment (czgdp1807) [inline src/libasr/codegen/asr_to_llvm.cpp:6678]: Here is the problem. You don't need to do this. Just pass `llvm::Type* target_llvm_type = llvm_utils->get_type_from_ttype_t_util(x.m_type, module.get())`. Then just call, `tmp = builder->CreateBitCast(source, target_type);`. These two lines should complete the implementation. No need to do `if-else-if` checks. Then you can also add extensive tests in this PR. No need to wait for another PR to complete that.

**Review by czgdp1807 — CHANGES_REQUESTED** [review]

File: src/libasr/codegen/asr_to_llvm.cpp (hunk 5 above)
Comment (Pranavchiku) [reply src/libasr/codegen/asr_to_llvm.cpp:6678]: Yes, perfect. This works, thank you! @czgdp1807 can you please give a small example of extensive test that you are willing to add? I'll push the simplified approach and prefer to merge this.

Comment (czgdp1807) [reply src/libasr/codegen/asr_to_llvm.cpp]: Try for real to complex or integer to complex. I feel there will be problems with complex type. Just try it out.

Comment (Pranavchiku) [reply src/libasr/codegen/asr_to_llvm.cpp]:
```fortran
program main
    real :: r
    complex :: result

    r = 1.0
    result = transfer(r, result)
    print *, result
end program
```

```
code generation error: asr_to_llvm: module failed verification. Error:
Invalid bitcast
  %3 = bitcast float %2 to %complex_4
```

```console
% gfortran a.f90 && ./a.out
        (1.00000000,5.559368163E+27)
```

**Review by czgdp1807 — APPROVED** [review]
