### PR TITLE
Fix ICE in procedure pointer association by correctly setting m_type_declaration and handling null function expressions

### LINKED ISSUE #10861: ICE : LCompilersException: `ASR::Var_t` symbol is a `ASR::Variable_t` without type declared
MRE 
```
module benchmark_method
    implicit none

    type :: arg
       integer :: dummy
    end type arg
    
    public :: method, arg
    
    private

    type :: method
        private
        integer, public                         :: nargs !< Number of dummy arguments
        procedure(), nopass, pointer            :: f => null() !< Procedure pointer
        procedure(), nopass, pointer, public    :: caller => null() !< Wrapper to call the procedure pointer.
        type(arg), allocatable, public          :: args(:) !< Array of arguments
    contains
    end type
    
    interface method
        module procedure :: method_create, &
                            method_create_0
    end interface
 
    contains

    function method_create(nargs, f) result(that)
        integer, intent(in)             :: nargs
        procedure()                     :: f
        type(method)                    :: that        
        
        that%f => f
        that%nargs = nargs
        allocate(that%args(nargs))
    end function
    
    function method_create_0(f, caller) result(that)
        procedure()                     :: f
        procedure(), optional           :: caller
        type(method)                    :: that        
        
        that%f => f
        that%nargs = 0
        allocate(that%args(0))
        if (present(caller)) then
            that%caller => caller
        end if
    end function
    
end module
```
Lfortran 
```
(lf) root@LAPTOP-8SLTQKJO:~/lfortran# lfortran examples/expr2.f90 --implicit-interface
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/root/lfortran/src/bin/lfortran", in _start
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main
  File "/root/lfortran/src/bin/lfortran.cpp", line 2812, in main
    return main_app(argc, argv);
  File "/root/lfortran/src/bin/lfortran.cpp", line 2736, in main_app(int, char**)   
    err = compile_src_to_object_file(arg_file, tmp_o, compiler_options.time_report, false,
  File "/root/lfortran/src/bin/lfortran.cpp", line 1192, in (anonymous namespace)::compile_src_to_object_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, LCompilers::CompilerOptions&, LCompilers::PassManager&, bool)
    result = fe.get_asr2(input, lm, diagnostics);
  File "/root/lfortran/src/lfortran/fortran_evaluator.cpp", line 292, in LCompilers::FortranEvaluator::get_asr2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::diag::Diagnostics&)
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics, lm);
  File "/root/lfortran/src/lfortran/fortran_evaluator.cpp", line 314, in LCompilers::FortranEvaluator::get_asr3(LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::LocationManager&)
    compiler_options.symtab_only, compiler_options, lm);
  File "/root/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 114, in LCompilers::LFortran::ast_to_asr(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::SymbolTable*, bool, LCompilers::CompilerOptions&, LCompilers::LocationManager&)
    );
  File "/root/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 8788, in LCompilers::LFortran::body_visitor(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::ASR::asr_t*, LCompilers::CompilerOptions&, std::map<unsigned long, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > > > > >&, std::map<unsigned long, LCompilers::ASR::symbol_t*, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, LCompilers::ASR::symbol_t*> > >&, std::map<unsigned long, unsigned long, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, unsigned long> > >&, std::map<unsigned long, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >&, std::map<unsigned long, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >&, std::map<unsigned int, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<LCompilers::ASR::ttype_t*, LCompilers::ASR::symbol_t*>, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::pair<LCompilers::ASR::ttype_t*, LCompilers::ASR::symbol_t*> > > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<LCompilers::ASR::ttype_t*, LCompilers::ASR::symbol_t*>, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::pair<LCompilers::ASR::ttype_t*, LCompilers::ASR::symbol_t*> > > > > > >&, std::map<unsigned int, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::symbol_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::symbol_t*> > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::symbol_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::symbol_t*> > > > > >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> > > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> > > > > > > >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<int, std::allocator<int> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<int, std::allocator<int> > > > >&, std::map<unsigned int, std::vector<LCompilers::ASR::stmt_t*, std::allocator<LCompilers::ASR::stmt_t*> >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::vector<LCompilers::ASR::stmt_t*, std::allocator<LCompilers::ASR::stmt_t*> > > > >&, LCompilers::LocationManager&)
    b.visit_TranslationUnit(ast);
  File "/root/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 273, in LCompilers::LFortran::BodyVisitor::visit_TranslationUnit(LCompilers::LFortran::AST::TranslationUnit_t const&)
    visit_ast(*x.m_items[i]);
  File "/root/lfortran/src/lfortran/ast.h", line 5046, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_ast(LCompilers::LFortran::AST::ast_t const&)
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/root/lfortran/src/lfortran/ast.h", line 5002, in void LCompilers::LFortran::AST::visit_ast_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::ast_t const&, LCompilers::LFortran::BodyVisitor&)
    case astType::mod: { v.visit_mod((const mod_t &)x); return; }
  File "/root/lfortran/src/lfortran/ast.h", line 5049, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_mod(LCompilers::LFortran::AST::mod_t const&)
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/root/lfortran/src/lfortran/ast.h", line 4620, in void LCompilers::LFortran::AST::visit_mod_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::mod_t const&, LCompilers::LFortran::BodyVisitor&)
    case modType::Module: { v.visit_Module((const Module_t &)x); return; }
  File "/root/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 4324, in LCompilers::LFortran::BodyVisitor::visit_Module(LCompilers::LFortran::AST::Module_t const&)
    visit_SubmoduleModuleCommon(x);
  File "/root/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 4296, in void LCompilers::LFortran::BodyVisitor::visit_SubmoduleModuleCommon<LCompilers::LFortran::AST::Module_t>(LCompilers::LFortran::AST::Module_t const&)
    visit_program_unit(*x.m_contains[i]);
  File "/root/lfortran/src/lfortran/ast.h", line 5054, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_program_unit(LCompilers::LFortran::AST::program_unit_t const&)
    void visit_program_unit(const program_unit_t &b) { visit_program_unit_t(b, self()); }
  File "/root/lfortran/src/lfortran/ast.h", line 4633, in void LCompilers::LFortran::AST::visit_program_unit_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::program_unit_t const&, LCompilers::LFortran::BodyVisitor&)
    case program_unitType::Function: { v.visit_Function((const Function_t &)x); return; }
  File "/root/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 4947, in LCompilers::LFortran::BodyVisitor::visit_Function(LCompilers::LFortran::AST::Function_t const&)
    transform_stmts(body, x.n_body, x.m_body);
  File "/root/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 234, in LCompilers::LFortran::BodyVisitor::transform_stmts(LCompilers::Vec<LCompilers::ASR::stmt_t*>&, unsigned long, LCompilers::LFortran::AST::stmt_t**)
    this->visit_stmt(*m_body[i]);
  File "/root/lfortran/src/lfortran/ast.h", line 5095, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_stmt(LCompilers::LFortran::AST::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/root/lfortran/src/lfortran/ast.h", line 4736, in void LCompilers::LFortran::AST::visit_stmt_t<LCompilers::LFortran::BodyVisitor>(LCompilers::LFortran::AST::stmt_t const&, LCompilers::LFortran::BodyVisitor&)
    case stmtType::Associate: { v.visit_Associate((const Associate_t &)x); return; }
  File "/root/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 2673, in LCompilers::LFortran::BodyVisitor::visit_Associate(LCompilers::LFortran::AST::Associate_t const&)
    } else if (ASRUtils::types_equal(target_type, value_type, target, value)) {     
  File "/root/lfortran/src/libasr/asr_utils.h", line 4422, in LCompilers::ASRUtils::types_equal(LCompilers::ASR::ttype_t*, LCompilers::ASR::ttype_t*, LCompilers::ASR::expr_t*, LCompilers::ASR::expr_t*, bool)
    ASR::Function_t* left_func = const_cast<ASR::Function_t*>(ASRUtils::get_function_from_expr(a_expr));
LCompilersException: `ASR::Var_t` symbol is a `ASR::Variable_t` without type declared
```
Gfortran
```
(lf) root@LAPTOP-8SLTQKJO:~/lfortran# gfortran examples/expr2.f90 -c
```

### PR DESCRIPTION
**Pull request by Jatinagarwal24**
fixes #10861 
fix: handle null/variable procedure pointers in associate and LLVM codegen

- In ast_body_visitor.cpp, propagate updated pointer type to
  PointerNullConstants on m_symbolic_value and m_value when
  upgrading var->m_type to Pointer_t(value_type_underlying)

- Fix m_type_declaration assignment to only resolve to Function_t
  symbols, skipping Variable_t intermediates that caused crashes
  in get_function_from_expr downstream ("ASR::Variable_t without
  type declared")

- In llvm_utils.cpp, guard get_function_from_expr(arg_expr) against
  null arg_expr and non-Function_t resolutions; fall back to
  constructing LLVM function type directly from FunctionType_t for
  implicit interfaces and null procedure pointers

- Add CreateBitCastForStore helper in llvm_utils to encapsulate
  typed-pointer compatibility logic for LLVM < 15, replacing
  scattered #if LLVM_VERSION_MAJOR < 15 blocks

Fixes crashes when associating procedure pointers with null or
variable-backed targets, and when lowering calls through implicit
interface procedure pointers.

### CODE REVIEW

File: src/libasr/codegen/asr_to_llvm.cpp [hunk 1]
```diff
@@ -8538,6 +8538,7 @@ class ASRToLLVMVisitor : public ASR::BaseVisitor<ASRToLLVMVisitor>
                     llvm_target = llvm_utils->get_string_data(
                         ASRUtils::get_string_type(target_type), llvm_target, true);
                 }
+                llvm_value = llvm_utils->CreateBitCastForStore(llvm_value, llvm_target);
```
Comment (certik) [inline src/libasr/codegen/asr_to_llvm.cpp:8541]: We should figure out why we need to cast the pointer in LLVM < 15. It's likely a bug in our ASR lowering, some types were created incorrectly, or ASR is missing a cast.

File: src/libasr/codegen/llvm_utils.cpp [hunk 2]
```diff
@@ -1668,7 +1668,29 @@ namespace LCompilers {
...
                     llvm_type = get_function_type(*fn, module)->getPointerTo();
                 } else {
-                    llvm_type = get_function_type(*ASRUtils::get_function_from_expr(arg_expr), module)->getPointerTo();
+                    const ASR::Function_t* fn_from_expr = nullptr;
+                    if (arg_expr) {
+                        fn_from_expr = ASRUtils::get_function_from_expr(arg_expr);
+                    }
+                    if (fn_from_expr) {
+                        llvm_type = get_function_type(*fn_from_expr, module)->getPointerTo();
+                    } else {
```
Comment (certik) [inline src/libasr/codegen/llvm_utils.cpp:1677]: It would be good to figure out why the pointer is null. Is this a bug somewhere?

File: integration_tests/procedure_pointer_20.f90 [hunk 3]
```diff
@@ -0,0 +1,61 @@
...
+    m1 = method(0, sub_a)
+
+    if (m1%nargs /= 0) error stop
+
+contains
+
+    subroutine sub_a()
+    end subroutine sub_a
+
+end program procedure_pointer_20
```
Comment (certik) [inline integration_tests/procedure_pointer_20.f90:61]: I tested this test in main and it fails as it should with:
```
LCompilersException: `ASR::Var_t` symbol is a `ASR::Variable_t` without type declared
```
