### PR TITLE
fix: set `ArrayPhysicalCast` type correctly when passing an `allocatable`  array as argument to a fixed-size array

### LINKED ISSUE #5933: bug: passing allocatable array as argument to a function/subroutine expecting fixed-size array fails
### Minimal Reproducible Example

```fortran
program main
   implicit none

   integer, allocatable :: x(:)

   allocate(x(2))
   x = [1, 2]
   call my_func(x)

contains

   subroutine my_func(arr)
      integer, intent(in) :: arr(2)
      print *, arr
   end subroutine my_func

end program main
```

### Output

```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ gfortran test.f90 && ./a.out
           1           2
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran test.f90
ASR verify pass error: Length of allocatable should be deferred (empty).
 --> test.f90:4:4
  |
4 |    integer, allocatable :: x(:)
  |    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ failed here


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

The program executes correctly without the `simplifier` pass.

```console
(lf) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran test.f90 --no-experimental-simplifier
1    2
```

### PR DESCRIPTION
**Pull request by kmr-srbh**
fixes #5933

Looking at the `asr_verify` code for `Allocatable_t` with the `simplifier` pass, we see that it requires an `allocatable` type to have a deferred length to work. This is the required behavior also, but for `ArrayPhysicalCast`, we were setting the `ttype` wrapped inside `Allocatable_t` causing issues. As it turns out, the implementation before the `simplifier` pass had handled this with `Allocatable_t`, but `simplifier` pass is stricter in this regard.

### CODE REVIEW

File: src/libasr/asr_utils.h [hunk 1]
```diff
@@ -5893,10 +5893,23 @@ static inline void Call_t_body(Allocator& al, ASR::symbol_t* a_name,
...
+                                                arg->base.loc,
+                                                arg,
+                                                arg_array_t->m_physical_type,
+                                                orig_arg_array_t->m_physical_type,
+                                                ASRUtils::duplicate_type(
+                                                    al,
+                                                    use_experimental_simplifier
+                                                        ? ASRUtils::type_get_past_allocatable(
+                                                            ASRUtils::expr_type(arg))
+                                                        : ASRUtils::expr_type(arg),
```
Comment (kmr-srbh) [inline src/libasr/asr_utils.h:5908]: This is the new change. The rest is only formatting.

File: src/libasr/asr_utils.h [hunk 2]
```diff
@@ -5893,10 +5893,23 @@ static inline void Call_t_body(Allocator& al, ASR::symbol_t* a_name,
...
-                    ASRUtils::duplicate_type(al, ASRUtils::expr_type(arg), dimensions, orig_arg_array_t->m_physical_type, true),
-                    nullptr));
+                physical_cast_arg.m_value = ASRUtils::EXPR(
+                                            ASRUtils::make_ArrayPhysicalCast_t_util(
+                                                al,
+                                                arg->base.loc,
+                                                arg,
+                                                arg_array_t->m_physical_type,
+                                                orig_arg_array_t->m_physical_type,
+                                                ASRUtils::duplicate_type(
```
Comment (gxyd) [inline src/libasr/asr_utils.h:5903]: why don't you assign this a new variable, the new formatting doesn't really make it more readable, the older one was relatively easier to read.

Comment (kmr-srbh) [reply src/libasr/asr_utils.h:5903]: Sure, will do it.
