### PR TITLE
test: handle assignment of an allocatable of a custom type

### LINKED ISSUE #8640: Handle assignment of an allocatable of a custom type from a function result
### MRE
```fortran
module my_definitions
  implicit none

  type :: person
    character(len=50) :: name
    integer, allocatable :: scores(:)
  end type person

contains

  function update_person(original) result(updated)
    type(person), allocatable, intent(in) :: original

    type(person), allocatable :: updated

    integer :: num_scores

    allocate(updated)

    updated%name = "modified: " // trim(original%name)

    num_scores = size(original%scores)
    allocate(updated%scores(num_scores + 1))

    if (num_scores > 0) then
      updated%scores(1:num_scores) = original%scores + 10
    end if
    updated%scores(num_scores + 1) = 999

  end function update_person

end module my_definitions

program main_demo
  use my_definitions
  implicit none

  type(person), allocatable :: x

  allocate(x)
  x%name = "john doe"
  allocate(x%scores(3))
  x%scores = [85, 92, 78]

  print *, "name: ", trim(x%name)
  print *, "scores: ", x%scores

  x = update_person(x)

  print *, "name: ", trim(x%name)
  print *, "scores: ", x%scores

end program main_demo
```

### LFortran Output
```sh
(lf)  🐍 lf  akramhany@akramhany  ~/Akram/Projects/Fortran/lfortran   main ±  lfortran ../d.f90
name:     john doe
scores:     85    92    78
Runtime Error: Size mismatch in assignment to '__libasr_created__array_section_'

LHS size is 1 and RHS size is 2
```

### GFortran Output
```sh
(lf)  ✘  🐍 lf  akramhany@akramhany  ~/Akram/Projects/Fortran/lfortran   main ±  gfortran ../d.f90 && ./a.out
 name: john doe
 scores:           85          92          78
 name: modified: john doe
 scores:           95         102          88         999
```

### PR DESCRIPTION
**Pull request by opixdown**
fixes #8640

### CODE REVIEW

File: integration_tests/allocate_32.f90 [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+    num_scores = size(original%scores)
+    allocate(updated%scores(num_scores + 1))
+    if (num_scores > 0) then
+      updated%scores(1:num_scores) = original%scores + 10
+    end if
+    updated%scores(num_scores + 1) = 999
+  end function update_person
+end module my_definitions
+
+program main_demo
```
Comment (HarshitaKalani) [inline integration_tests/allocate_32.f90]:
```suggestion
program allocate_32
```

File: integration_tests/allocate_32.f90 [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+  x = update_person(x)
+  
+  if (x%scores(1) /= 95) error stop
+  if (x%scores(2) /= 102) error stop
+  if (x%scores(3) /= 88) error stop
+  if (x%scores(4) /= 999) error stop
+
+  print *, "All tests passed."
+  
+end program main_demo
```
Comment (HarshitaKalani) [inline integration_tests/allocate_32.f90]:
```suggestion
end program allocate_32
```

File: integration_tests/allocate_32.f90 [hunk 3]
```diff
@@ -0,0 +1,42 @@
+module my_definitions
```
Comment (HarshitaKalani) [inline integration_tests/allocate_32.f90]:
```suggestion
module allocate_32_mod
```

File: integration_tests/allocate_32.f90 [hunk 4]
```diff
@@ -0,0 +1,42 @@
...
+    allocate(updated)
+    updated%name = "modified: " // trim(original%name)
+    num_scores = size(original%scores)
+    allocate(updated%scores(num_scores + 1))
+    if (num_scores > 0) then
+      updated%scores(1:num_scores) = original%scores + 10
+    end if
+    updated%scores(num_scores + 1) = 999
+  end function update_person
+end module my_definitions
```
Comment (HarshitaKalani) [inline integration_tests/allocate_32.f90]:
```suggestion
end module allocate_32_mod
```

**Comment by certik** [comment]
Conflicts have to be resolved

File: integration_tests/allocate_33.f90 [hunk 5]
```diff
@@ -0,0 +1,42 @@
...
+  x = update_person(x)
+  
+  if (x%scores(1) /= 95) error stop
+  if (x%scores(2) /= 102) error stop
+  if (x%scores(3) /= 88) error stop
+  if (x%scores(4) /= 999) error stop
+
+  print *, "All tests passed."
+  
+end program allocate_33_mod
```
Comment (HarshitaKalani) [inline integration_tests/allocate_33.f90]:
```suggestion
end program allocate_33
```

**Review by certik — APPROVED** [review]
