### PR TITLE
fix: fix cmplx function for pointer arguments

### LINKED ISSUE #7312: bug in comparison of complex pointer values
## Minimal Reproducible Example

```f90
program main
   implicit none
   complex, pointer :: ptr_complex4
   complex(8), pointer :: ptr_complex8
   complex, target :: complex4_1
   complex(8), target :: complex8_1
   complex8_1 = (1, 2)
   complex4_1 = (1, 2)
   ptr_complex8 => complex8_1
   ptr_complex4 => complex4_1
   if (ptr_complex8 /= cmplx(ptr_complex4, kind=8)) error stop
end program main

```

On running it with LFortran, we get the below error:
```console
(lf) gxyd@Gauravs-MacBook-Air OpenSource/lfortran (main) » lfortran test.f90                                 
ERROR STOP
(lf) gxyd@Gauravs-MacBook-Air OpenSource/lfortran (main) » echo $?                                                      1 ↵
1
(lf) gxyd@Gauravs-MacBook-Air OpenSource/lfortran (main) » gfortran test.f90 -o test.o && ./test.o
(lf) gxyd@Gauravs-MacBook-Air OpenSource/lfortran (main) » echo $?
0
```

With GFortran, it worked just fine

### PR DESCRIPTION
**Pull request by HarshilShah1804**
Closes #7312

### CODE REVIEW

File: src/libasr/codegen/asr_to_llvm.cpp [hunk 1]
```diff
@@ -9388,6 +9392,7 @@ class ASRToLLVMVisitor : public ASR::BaseVisitor<ASRToLLVMVisitor>
             }
             default : throw CodeGenError("Cast kind not implemented");
         }
+        ptr_loads = ptr_loads_copy;
```
Comment (certik) [inline src/libasr/codegen/asr_to_llvm.cpp:9395]: We really should refactor this: https://github.com/lfortran/lfortran/issues/4245, but probably after beta.
