### PR TITLE
[ASR] convert multi-label goto into select properly

### LINKED ISSUE #767: [SciPy] Semantic error: ```GOTO``` label must be an integer
```
semantic error: A goto label must be an integer
   --> /home/pranavchiku/scipy/scipy/optimize/slsqp/slsqp_optmz.f:482:11
    |
482 |           GOTO (200, 210) iexact+1
    |           ^^^^^^^^^^^^^^^^^^^^^^^^ 
```

### PR DESCRIPTION
**Pull request by lucifer1004**
Currently, only when the goto label is a name will the multi-label goto be converted into a select node. This PR fixes this and will thus fix #767.

### CODE REVIEW

**Comment by lucifer1004** [comment]
The notorious

```
subprocess.CalledProcessError: Command '['jupyter', 'nbconvert', '--to', 'notebook', '--execute', '--ExecutePreprocessor.timeout=60', '--output', 'Demo2_out.ipynb', 'Demo2.ipynb']' returned non-zero exit status 1.
```

just happened again.

File: src/lfortran/semantics/ast_body_visitor.cpp [hunk 1]
```diff
@@ -1593,29 +1584,29 @@ class BodyVisitor : public CommonVisitor<BodyVisitor> {
...
+                        throw SemanticError("Only integer labels are supported in GOTO.",
                             x.base.base.loc);
                     } else {
                         auto l = AST::down_cast<AST::Num_t>(x.m_labels[i]); // l->m_n gets the target -> if l->m_n == (i+1) ...
                         Vec<ASR::stmt_t*> body;
                         body.reserve(al, 1);
                         body.push_back(al, ASRUtils::STMT(ASR::make_GoTo_t(al, x.base.base.loc, l->m_n)));
+                        if (i == 0) {
+                            def_body.push_back(al, ASRUtils::STMT(ASR::make_GoTo_t(al, x.base.base.loc, l->m_n)));
+                        }
```
Comment (certik) [inline src/lfortran/semantics/ast_body_visitor.cpp:1596]: Is that the Fortran semantics that if no label matches at runtime, that it jumps to the first one?

Or should we rather give a runtime error?

File: src/lfortran/semantics/ast_body_visitor.cpp [hunk 2]
```diff
@@ -1570,19 +1570,10 @@ class BodyVisitor : public CommonVisitor<BodyVisitor> {
             if (AST::is_a<AST::Num_t>(*x.m_goto_label)) {
                 int goto_label = AST::down_cast<AST::Num_t>(x.m_goto_label)->m_n;
                 tmp = ASR::make_GoTo_t(al, x.base.base.loc, goto_label);
+            } else {
+                this->visit_expr(*x.m_goto_label);
+                ASR::expr_t *goto_label = LFortran::ASRUtils::EXPR(tmp);
```
Comment (certik) [inline src/lfortran/semantics/ast_body_visitor.cpp:1575]:
```suggestion
                ASR::expr_t *goto_label = ASRUtils::EXPR(tmp);
```

Comment (certik) [reply src/lfortran/semantics/ast_body_visitor.cpp:1575]: Also let's add a test for the label being an expression.

**Review by certik — COMMENTED** [review]
I think this generally looks good, but I have some questions.

File: src/lfortran/semantics/ast_body_visitor.cpp (hunk 1 above)
Comment (lucifer1004) [reply src/lfortran/semantics/ast_body_visitor.cpp:1596]: I might misread something when I looked for documentation. I remembered seeing this, but when I checked now, 

- https://docs.oracle.com/cd/E19957-01/805-4939/6j4m0vn9l/index.html
- https://www.ibm.com/docs/en/openxl-fortran-aix/17.1.0?topic=attributes-go-computed
- https://www.intel.com/content/www/us/en/develop/documentation/fortran-compiler-oneapi-dev-guide-and-reference/top/language-reference/a-to-z-reference/g-1/goto-computed.html

They all say that it should be a no-op when the computed value is out of range.

Comment (certik) [reply src/lfortran/semantics/ast_body_visitor.cpp:1596]: We can check what gfortran does. If it is undefined, then let's return a runtime error.

Comment (lucifer1004) [reply src/lfortran/semantics/ast_body_visitor.cpp:1596]: GFortran does not throw errors but simply goes ahead to the next statement (making the goto a no-op).

File: src/lfortran/semantics/ast_body_visitor.cpp (hunk 2 above)
Comment (lucifer1004) [reply src/lfortran/semantics/ast_body_visitor.cpp:1575]: I can add a test for this. BTW, I found that in `integration_tests/goto_03.f90`, there was assigned GOTO which has been deprecated. Should we support this obsolete feature?

Comment (lucifer1004) [reply src/lfortran/semantics/ast_body_visitor.cpp]: Tests added. Assigned GOTO is not handled at the moment (actually Assign has not been dealt with).

File: src/lfortran/semantics/ast_body_visitor.cpp (hunk 1 above)
Comment (lucifer1004) [reply src/lfortran/semantics/ast_body_visitor.cpp]: Changed out-of-range values to no-op as the listed documentation.

**Comment by lucifer1004** [comment]
I think this PR is ready to be merged now @certik

File: integration_tests/goto_04.f90 [hunk 3]
```diff
@@ -0,0 +1,31 @@
...
+go to (1, 2, 3), n - 1
+
+1 a = a + 10
+2 a = a + 20
+3 a = a + 30
+
+if(a /= 70) error stop
+
+go to (4, 5, 6), n + 1
+
```
Comment (certik) [inline integration_tests/goto_04.f90:16]: This should test the default case
```suggestion
a = a + 30
```

File: integration_tests/goto_04.f90 [hunk 4]
```diff
@@ -0,0 +1,31 @@
...
+go to (1, 2, 3), n - 1
+
+1 a = a + 10
+2 a = a + 20
+3 a = a + 30
+
+if(a /= 70) error stop
+
+go to (4, 5, 6), n + 1
```
Comment (certik) [inline integration_tests/goto_04.f90:15]: Note: `n == 2` here

File: integration_tests/goto_04.f90 [hunk 5]
```diff
@@ -0,0 +1,31 @@
...
+a = 10
+
+go to (1, 2, 3), n - 1
+
+1 a = a + 10
+2 a = a + 20
+3 a = a + 30
+
+if(a /= 70) error stop
+
```
Comment (certik) [inline integration_tests/goto_04.f90:14]:
```suggestion
! Jump to n+1 == 3  -> noop.
```

File: integration_tests/goto_04.f90 [hunk 6]
```diff
@@ -0,0 +1,31 @@
+program goto_04
+implicit none
+integer :: a, n
+n = 2
+a = 10
+
```
Comment (certik) [inline integration_tests/goto_04.f90:6]:
```suggestion
! ! Jump to n-1 == 1  -> noop.
```

File: integration_tests/goto_04.f90 [hunk 7]
```diff
@@ -0,0 +1,31 @@
...
+if(a /= 70) error stop
+
+go to (4, 5, 6), n + 1
+
+4 a = a + 40
+5 a = a + 50
+6 a = a + 60
+
+if(a /= 130) error stop
+
```
Comment (certik) [inline integration_tests/goto_04.f90:22]:
```suggestion
! Jump to the label n*n -> 4 -> noop
```

Comment (certik) [reply integration_tests/goto_04.f90:22]: It seems both the first and last case is noop -- only the middle case is a jump, and only to the first. Let's also test the second and third option.

File: integration_tests/goto_04.f90 [hunk 8]
```diff
@@ -0,0 +1,31 @@
+program goto_04
+implicit none
+integer :: a, n
+n = 2
+a = 10
+
+go to (1, 2, 3), n - 1
+
```
Comment (certik) [inline integration_tests/goto_04.f90:8]: We need to add this in here, to distinguish the jump to 1 from noop:
```suggestion
a = a + 5
```

File: src/lfortran/semantics/ast_body_visitor.cpp (hunk 2 above)
Comment (certik) [reply src/lfortran/semantics/ast_body_visitor.cpp]: We have to implement all obsolete and deleted features as long as they are in use. Right now we are only implementing those features needed by SciPy.

We can print a warning for all obsolete or deleted features, but we have to support them.

File: tests/tests.toml [hunk 9]
```diff
@@ -1798,6 +1798,13 @@ filename = "../integration_tests/goto_03.f90"
 ast = true
 ast_f90 = true
 
+[[test]]
+filename = "../integration_tests/goto_04.f90"
+ast = true
+ast_f90 = true
```
[the remark this answers is not in the document]
Comment (certik) [reply tests/tests.toml:1804]: (We want to keep the redundant testing to minimum, since it increases the length of our testing suite.)

File: integration_tests/goto_04.f90 [hunk 10]
```diff
@@ -0,0 +1,31 @@
...
+if(a /= 130) error stop
+
+go to (7, 8, 9), n * n
+
+7 a = a + 70
+8 a = a + 80
+9 a = a + 90
+
+if(a /= 370) error stop
```
[the remark this answers is not in the document]
Comment (lucifer1004) [reply integration_tests/goto_04.f90:29]: The n * n expression already tests this.

[the remark this answers is not in the document]
Comment (certik) [reply integration_tests/goto_04.f90:29]: I think that's right.

**Comment by certik** [comment]
When you update tests, do it like this: `rm tests/reference/*` and `./run_tests.py -u` then `git add tests/reference`. This will remove unused files.

**Comment by lucifer1004** [comment]
> When you update tests, do it like this: `rm tests/reference/*` and `./run_tests.py -u` then `git add tests/reference`. This will remove unused files.

I usually cannot do this due to the LLVM issue.

**Comment by certik** [comment]
Ah, that's right. Just remove the ast and ast_f90 by hand then, since they are not used anymore.

File: integration_tests/goto_04.f90 [hunk 11]
```diff
@@ -0,0 +1,32 @@
...
+! Jump to the label n - 1 = 1 -> 1
+go to (1, 2, 3), n - 1
+a = a + 5
+1 a = a + 10
+2 a = a + 20
+3 a = a + 30
+if(a /= 70) error stop
+
+! Jump to the label n + 1 = 3 -> 6
+go to (4, 5, 6), n + 1
```
Comment (certik) [inline integration_tests/goto_04.f90:16]: Ah I see how it works -- I am glad you put the comment there. I confused it with assigned goto, where you assign the actual label itself.

**Review by certik — APPROVED** [review]
I think this looks great, thanks for fixing it!

**Comment by konradha** [comment]
@certik ICould you help clarifying the semantics for this? We discussed the behavior for goto targets that are variables and thought of the implementation in #769. Because essentially it isn't a, say, "GOTO SELECT" anymore but a select with a variable.

**Comment by lucifer1004** [comment]
@konradha Assigned gotos have the variable    go first, then the labels. See http://www.lahey.com/docs/lfpro78help/F95ARAssigned_GOTOStmt.htm

**Comment by certik** [comment]
@konradha I think your revised comment is correct, that is my understanding. Yes, super confusing! I think we do the right thing in LFortran. If you discover anything that does not work, please open up an issue. The good news is that we take care of this in the frontend, so everything is clean in ASR.
