### PR TITLE
fix: ICE in comparison operator handling

### LINKED ISSUE #9664: ICE when comparing ieee_class_type values with "=="
## **MRE**
```
program mre
  use, intrinsic :: ieee_arithmetic, only: ieee_class, ieee_quiet_nan, ieee_class_type
  use iso_fortran_env, only: real64
  implicit none

  type(ieee_class_type) :: cls
  logical :: b

  cls = ieee_class(0.0_real64)

  ! invalid should be a clean error
  b = (cls == ieee_quiet_nan)

  print *, b
end program

```

## **Current Behaviour**
```
Internal Compiler Error: Unhandled exception
```

## **Expected Behaviour**
```
(lf) opixdown@Atharvs-MacBook-Air lfortran % gfortran t.f90 && ./a.out 
t.f90:10:7:

   10 |   b = (cls == ieee_quiet_nan)
      |       1
Error: Operands of comparison operator '==' at (1) are TYPE(ieee_class_type)/TYPE(ieee_class_type)
  
```

### PR DESCRIPTION
**Pull request by opixdown**
fixes #9664

### CODE REVIEW

File: tests/errors/continue_compilation_1.f90 [hunk 1]
```diff
@@ -440,6 +440,10 @@ program continue_compilation_1
         print *, q1
     end do q1
 
+    ! Test: comparison between incompatible types 
+    ieee_cls = ieee_class(0.0)
+    b = (ieee_cls == ieee_quiet_nan)
```
Comment (certik) [inline tests/errors/continue_compilation_1.f90]: You have to add these at the very end of this file, to avoid the huge diff below with the line number changes. See the documentation in this file.

**Comment by certik** [comment]
Otherwise I think it's fine.

**Comment by certik** [comment]
Do you mind resolving the conflicts please?
