### PR TITLE
fix: add direct with stream access

### LINKED ISSUE #9019: Add support for recl parameter in open() for direct access
### **Current Behaviour**
LFortran ignores the recl parameter and shows:
```
warning: Argument `recl` isn't supported yet
```
### **MRE**
```
program test_recl
    integer :: x, y
    x = 12345
    open(unit=10, file="data.bin", access="direct", recl=4)
    write(10, rec=1) x
    close(10)
    open(unit=10, file="data.bin", access="direct", recl=4)
    read(10, rec=1) y
    print *, y  
end program
```
### **Expected Behaviour**

```
lf) opixdown@Atharvs-MacBook-Air lfortran % gfortran ./t.f90 && ./a.out
       12345
```

### LINKED ISSUE #9443: Runtime Error in lfortran with open()
**MRE**

```fortran
program test_recl
    integer :: x, y
    x = 12345
    open(unit=10, file="data.bin", access="direct", recl=4)
    write(10, rec=1) x
    close(10)
    open(unit=10, file="data.bin", access="direct", recl=4)
    read(10, rec=1) y
    print *, y  
end program
```

`gfortran` response:

```
/lfortran$ gfortran a.f90 && ./a.out
       12345
```

`lfortran` response:

```
/lfortran$ ./src/bin/lfortran a.f90
Runtime Error: Format mismatch between OPEN statement and WRITE statement on unit 10.
```

Related to:

#9091 and #9019

### PR DESCRIPTION
**Pull request by yuvrajsinghgmx**
Closes #9443 
Closes #9019 

**MRE**

```fortran

program test_recl
    integer :: x, y
    x = 12345
    open(unit=10, file="data.bin", access="direct", recl=4)
    write(10, rec=1) x
    close(10)
    open(unit=10, file="data.bin", access="direct", recl=4)
    read(10, rec=1) y
    print *, y  
end program

```

Previous Response : 

```
Runtime Error: Format mismatch between OPEN statement and WRITE statement on unit 10.
```

Current Response:

```
12345
```

Same in both `lfortran` as well as `gfortran`.

### CODE REVIEW

**Comment by certik** [comment]
Can you please add tests for both bugs? It can be one test that covers both. See other tests for file handling how to do it. Add it to integration tests.

**Comment by yuvrajsinghgmx** [comment]
> Can you please add tests for both bugs? It can be one test that covers both. See other tests for file handling how to do it. Add it to integration tests.

Done

File: integration_tests/file_open_03.f90 [hunk 1]
```diff
@@ -0,0 +1,21 @@
+program open_direct_form
+    use iso_fortran_env, only: int32
+    implicit none
+
+    integer(int32) :: x, y
+
+    x = 654321
+
+    open(10, file="data.bin", access="direct", recl=4)
```
Comment (certik) [inline integration_tests/file_open_03.f90]: `data.bin` -> `file_open_03_data.bin` and the same for the other test. To prevent races when running in parallel.

**Comment by certik** [comment]
Perfect. Now ensure the tests run.

File: integration_tests/file_open_03.f90 (hunk 1 above)
Comment (yuvrajsinghgmx) [reply integration_tests/file_open_03.f90]: Sure, I made the required changes.

**Comment by yuvrajsinghgmx** [comment]
Need to fix write() for direct access in a separate PR
