### PR TITLE
enh: add support for passing `class` arguments  to functions expecting `type`

### LINKED ISSUE #7423: Handle `ClassType` variable passed to subroutine which expects a `StructType`
MRE:
```fortran
module toml_val_mod
  implicit none
  type :: val_type
        integer :: origin = 3
        integer :: dest = 2
    end type

end module toml_val_mod

program merge_example
    use toml_val_mod
    class(val_type), allocatable :: val1
    call merge(val1)
contains

    subroutine merge(val1)
        type(val_type), intent(inout) :: val1
    end subroutine merge

end program merge_example
```

LFortran Error:
```console
code generation error: asr_to_llvm: module failed verification. Error:
Call parameter type does not match function signature!
  %val1 = alloca %val_type_polymorphic, align 8
 %val_type*  call void @merge(%val_type_polymorphic* %val1)
```

### PR DESCRIPTION
**Pull request by kmr-srbh**
fixes #7423

### CODE REVIEW

File: integration_tests/class_29.f90 [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+   allocate(val1)
+
+   call sub(val1)
+   print *, "Outside val1%origin: ", val1%origin
+   if (val1%origin /= 5) error stop
+contains
+
+   subroutine sub(val)
+      type(val_type), allocatable, intent(out) :: val
+      allocate(val)
```
Comment (kmr-srbh) [inline integration_tests/class_29.f90:18]: I had to change the test here to not check for `val%origin == 3` because the allocate statement initialises the values to zero. The added non-allocatable test `class_28.f90` work fine with this check though.

Comment (kmr-srbh) [reply integration_tests/class_29.f90:18]: #7530 is the bug report for this.
