### PR TITLE
Fix : Read from allocatable string

### LINKED ISSUE #5738: bug: allocatable character not supported as input source in formatted read
### Minimal Reproducible Example

```fortran
program main

   implicit none

   character(len=2), allocatable :: line
   character(len=2) :: c

   allocate(character(len=2) :: line)
   line = "ab"

   read(line, *) c
   
   print *, c

end program main
```

### Output

```console
(lf) saurabh-kumar@Awadh:~/Projects/System/lfortran$ gfortran test.f90 && ./a.out
 ab
(lf) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran test.f90
; ModuleID = 'LFortran'
source_filename = "LFortran"

%string_descriptor = type { i8*, i64, i64 }

@0 = private unnamed_addr constant [3 x i8] c"ab\00", align 1
@1 = private unnamed_addr constant [3 x i8] c"%s\00", align 1
@2 = private unnamed_addr constant [2 x i8] c"\0A\00", align 1
@3 = private unnamed_addr constant [5 x i8] c"%s%s\00", align 1

define i32 @main(i32 %0, i8** %1) {
.entry:
  call void @_lpython_call_initial_functions(i32 %0, i8** %1)
  %c = alloca i8*, align 8
  %2 = call i8* @_lfortran_malloc(i32 3)
  call void @_lfortran_string_init(i32 3, i8* %2)
  store i8* %2, i8** %c, align 8
  %3 = load i8*, i8** %c, align 8
  %line = alloca %string_descriptor, align 8
  %4 = getelementptr %string_descriptor, %string_descriptor* %line, i32 0, i32 0
  store i8* null, i8** %4, align 8
  %5 = getelementptr %string_descriptor, %string_descriptor* %line, i32 0, i32 1
  store i64 0, i64* %5, align 4
  %6 = getelementptr %string_descriptor, %string_descriptor* %line, i32 0, i32 2
  store i64 0, i64* %6, align 4
  %7 = getelementptr %string_descriptor, %string_descriptor* %line, i32 0, i32 0
  %8 = getelementptr %string_descriptor, %string_descriptor* %line, i32 0, i32 1
  %9 = getelementptr %string_descriptor, %string_descriptor* %line, i32 0, i32 2
  call void @_lfortran_alloc(i8** %7, i32 3, i64* %8, i64* %9)
  %10 = load i8*, i8** %7, align 8
  call void @_lfortran_string_init(i32 3, i8* %10)
  %casted_string_ptr_to_desc = alloca %string_descriptor, align 8
  %11 = getelementptr %string_descriptor, %string_descriptor* %casted_string_ptr_to_desc, i32 0, i32 0
  %12 = getelementptr %string_descriptor, %string_descriptor* %casted_string_ptr_to_desc, i32 0, i32 1
  %13 = getelementptr %string_descriptor, %string_descriptor* %casted_string_ptr_to_desc, i32 0, i32 2
  store i8* getelementptr inbounds ([3 x i8], [3 x i8]* @0, i32 0, i32 0), i8** %11, align 8
  store i64 -1, i64* %12, align 4
  store i64 -1, i64* %13, align 4
  %14 = getelementptr %string_descriptor, %string_descriptor* %line, i32 0, i32 0
  %15 = getelementptr %string_descriptor, %string_descriptor* %line, i32 0, i32 1
  %16 = getelementptr %string_descriptor, %string_descriptor* %line, i32 0, i32 2
  %17 = getelementptr %string_descriptor, %string_descriptor* %casted_string_ptr_to_desc, i32 0, i32 0
  %18 = load i8*, i8** %17, align 8
  call void @_lfortran_strcpy_descriptor_string(i8** %14, i8* %18, i64* %15, i64* %16)
  %19 = alloca i32, align 4
  %20 = alloca i32, align 4
  call void @_lfortran_string_read_str(%string_descriptor* %line, i8* getelementptr inbounds ([3 x i8], [3 x i8]* @1, i32 0, i32 0), i8** %c)
  %21 = load i8*, i8** %c, align 8
  call void (i8*, ...) @_lfortran_printf(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @3, i32 0, i32 0), i8* %21, i8* getelementptr inbounds ([2 x i8], [2 x i8]* @2, i32 0, i32 0))
  %22 = getelementptr %string_descriptor, %string_descriptor* %line, i32 0, i32 0
  %23 = getelementptr %string_descriptor, %string_descriptor* %line, i32 0, i32 1
  %24 = getelementptr %string_descriptor, %string_descriptor* %line, i32 0, i32 2
  %25 = load i8*, i8** %22, align 8
  call void @_lfortran_free(i8* %25)
  store i8* null, i8** %22, align 8
  store i64 0, i64* %23, align 4
  store i64 0, i64* %24, align 4
  call void @_lpython_free_argv()
  br label %return

return:                                           ; preds = %.entry
  ret i32 0
}

declare void @_lpython_call_initial_functions(i32, i8**)

declare i8* @_lfortran_malloc(i32)

declare void @_lfortran_string_init(i32, i8*)

declare void @_lfortran_alloc(i8**, i32, i64*, i64*)

declare void @_lfortran_strcpy_descriptor_string(i8**, i8*, i64*, i64*)

declare void @_lfortran_string_read_str(i8*, i8*, i8**)

declare void @_lfortran_printf(i8*, ...)

declare void @_lfortran_free(i8*)

declare void @_lpython_free_argv()
asr_to_llvm: module failed verification. Error:
Call parameter type does not match function signature!
  %line = alloca %string_descriptor, align 8
 i8*  call void @_lfortran_string_read_str(%string_descriptor* %line, i8* getelementptr inbounds ([3 x i8], [3 x i8]* @1, i32 0, i32 0), i8** %c)

code generation error: asr_to_llvm: module failed verification. Error:
Call parameter type does not match function signature!
  %line = alloca %string_descriptor, align 8
 i8*  call void @_lfortran_string_read_str(%string_descriptor* %line, i8* getelementptr inbounds ([3 x i8], [3 x i8]* @1, i32 0, i32 0), i8** %c)



Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

### PR DESCRIPTION
**Pull request by assem2002**
fixes #5738

### CODE REVIEW

File: integration_tests/string_42.f90 [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+ 
+    character(len=2), allocatable :: line
+    character(len=2) :: c
+ 
+    allocate(character(len=2) :: line)
+    line = "ab"
+ 
+    read(line, *) c ! Test reading from allocatable string.
+    
+    print *, c
```
Comment (Pranavchiku) [inline integration_tests/string_42.f90:13]: let's check what is `c` using `if(c /= 'xx') error stop`

**Review by Pranavchiku — APPROVED** [review]
a minor change, feel free to do it in subsequent PR

File: integration_tests/string_42.f90 (hunk 1 above)
Comment (assem2002) [reply integration_tests/string_42.f90:13]: done here https://github.com/lfortran/lfortran/pull/5742/commits/4d68100bc54223c1ab0301801019e4601003543a

**Review by certik — APPROVED** [review]
