### PR TITLE
Fix implicit callback

### LINKED ISSUE #971: Bug in implicit callback
The following minimal example:
```fortran
subroutine hybrd(fcn, n)
integer, intent(in) :: n
external fcn
print *, "in hybrd, calling fcn"
call fcn(n)
print *, "done"
end

program example_hybrd
interface
    subroutine hybrd(fcn, n)
        integer, intent(in) :: n
        interface
            subroutine fcn(n)
                integer, intent(in) :: n
            end subroutine fcn
        end interface
    end subroutine hybrd
end interface
integer :: n
n = 9
print *, "Calling the driver with n =", n
call hybrd(fcn, n)
print *, "Done"

contains

    subroutine fcn(i)
    integer, intent(in) :: i
    print *, "fnc called", i
    end subroutine

end program example_hybrd
```
Works with GFortran:
```console
$ gfortran example_hybrd.f90 
$ ./a.out 
 Calling the driver with n =           9
 in hybrd, calling fcn
 fnc called           9
 done
 Done
```
But fails with LFortran:
```console
$ lfortran --implicit-typing --allow-implicit-interface example_hybrd.f90
; ModuleID = 'LFortran'
source_filename = "LFortran"

@0 = private unnamed_addr constant [2 x i8] c" \00", align 1
@1 = private unnamed_addr constant [2 x i8] c"\0A\00", align 1
@2 = private unnamed_addr constant [22 x i8] c"in hybrd, calling fcn\00", align 1
@3 = private unnamed_addr constant [5 x i8] c"%s%s\00", align 1
@4 = private unnamed_addr constant [2 x i8] c" \00", align 1
@5 = private unnamed_addr constant [2 x i8] c"\0A\00", align 1
@6 = private unnamed_addr constant [5 x i8] c"done\00", align 1
@7 = private unnamed_addr constant [5 x i8] c"%s%s\00", align 1
@8 = private unnamed_addr constant [2 x i8] c" \00", align 1
@9 = private unnamed_addr constant [2 x i8] c"\0A\00", align 1
@10 = private unnamed_addr constant [11 x i8] c"fnc called\00", align 1
@11 = private unnamed_addr constant [9 x i8] c"%s%s%d%s\00", align 1
@12 = private unnamed_addr constant [2 x i8] c" \00", align 1
@13 = private unnamed_addr constant [2 x i8] c"\0A\00", align 1
@14 = private unnamed_addr constant [28 x i8] c"Calling the driver with n =\00", align 1
@15 = private unnamed_addr constant [9 x i8] c"%s%s%d%s\00", align 1
@16 = private unnamed_addr constant [2 x i8] c" \00", align 1
@17 = private unnamed_addr constant [2 x i8] c"\0A\00", align 1
@18 = private unnamed_addr constant [5 x i8] c"Done\00", align 1
@19 = private unnamed_addr constant [5 x i8] c"%s%s\00", align 1

define void @hybrd(float* %fcn, i32* %n) {
.entry:
  call void (i8*, ...) @_lfortran_printf(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @3, i32 0, i32 0), i8* getelementptr inbounds ([22 x i8], [22 x i8]* @2, i32 0, i32 0), i8* getelementptr inbounds ([2 x i8], [2 x i8]* @1, i32 0, i32 0))
  call void @"fcn@change_by_implicit_interface"(i32* %n)
  call void (i8*, ...) @_lfortran_printf(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @7, i32 0, i32 0), i8* getelementptr inbounds ([5 x i8], [5 x i8]* @6, i32 0, i32 0), i8* getelementptr inbounds ([2 x i8], [2 x i8]* @5, i32 0, i32 0))
  br label %return

return:                                           ; preds = %.entry
  ret void

.entry1:                                          ; No predecessors!
  br label %return2

return2:                                          ; preds = %.entry1
  ret void
}

declare void @"fcn@change_by_implicit_interface"(i32*)

declare void @_lfortran_printf(i8*, ...)

define void @fcn(i32* %i) {
.entry:
  %0 = load i32, i32* %i, align 4
  call void (i8*, ...) @_lfortran_printf(i8* getelementptr inbounds ([9 x i8], [9 x i8]* @11, i32 0, i32 0), i8* getelementptr inbounds ([11 x i8], [11 x i8]* @10, i32 0, i32 0), i8* getelementptr inbounds ([2 x i8], [2 x i8]* @8, i32 0, i32 0), i32 %0, i8* getelementptr inbounds ([2 x i8], [2 x i8]* @9, i32 0, i32 0))
  br label %return

return:                                           ; preds = %.entry
  ret void
}

define i32 @main() {
.entry:
  %n = alloca i32, align 4
  store i32 9, i32* %n, align 4
  %0 = load i32, i32* %n, align 4
  call void (i8*, ...) @_lfortran_printf(i8* getelementptr inbounds ([9 x i8], [9 x i8]* @15, i32 0, i32 0), i8* getelementptr inbounds ([28 x i8], [28 x i8]* @14, i32 0, i32 0), i8* getelementptr inbounds ([2 x i8], [2 x i8]* @12, i32 0, i32 0), i32 %0, i8* getelementptr inbounds ([2 x i8], [2 x i8]* @13, i32 0, i32 0))
  call void @hybrd(void (i32*)* @fcn, i32* %n)
  call void (i8*, ...) @_lfortran_printf(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @19, i32 0, i32 0), i8* getelementptr inbounds ([5 x i8], [5 x i8]* @18, i32 0, i32 0), i8* getelementptr inbounds ([2 x i8], [2 x i8]* @17, i32 0, i32 0))
  ret i32 0
}
code generation error: asr_to_llvm: module failed verification. Error:
Call parameter type does not match function signature!
void (i32*)* @fcn
 float*  call void @hybrd(void (i32*)* @fcn, i32* %n)



Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).
```

When compiled in separate translation units and generating code right away, it then at runtime the callback is not called, but it is most likely the same problem.

### PR DESCRIPTION
**Pull request by certik**
Fixes #971.

### CODE REVIEW

File: src/lfortran/semantics/ast_body_visitor.cpp [hunk 1]
```diff
@@ -1490,6 +1515,21 @@ class BodyVisitor : public CommonVisitor<BodyVisitor> {
...
 
+    // Changes argument `sub_name` to the new symbol from the current symbol
+    // table of the function `x`.
+    void redo_function_argument(ASR::Function_t &x, const std::string &sub_name) {
+        for (size_t i=0; i<x.n_args; i++) {
+            ASR::symbol_t *sym = ASR::down_cast<ASR::Var_t>(x.m_args[i])->m_v;
+            std::string arg_s = ASRUtils::symbol_name(sym);
+            if (arg_s == sub_name) {
+                ASR::symbol_t *var = x.m_symtab->get_symbol(arg_s);
+                x.m_args[i] = ASRUtils::EXPR(ASR::make_Var_t(al, x.base.base.loc, var));
```
Comment (certik) [inline src/lfortran/semantics/ast_body_visitor.cpp:1526]: There is a problem here: for function callbacks `var` is not a `Variable`, but `Function`. By passing it to `Var` should fail verify() (until then, it fails later in Minpack)...

We need to rethink how we handle function arguments.

Comment (certik) [reply src/lfortran/semantics/ast_body_visitor.cpp:1526]: See #974.

Comment (certik) [reply src/lfortran/semantics/ast_body_visitor.cpp:1526]: Until #974 is fixed, we'll simply use the current mechanism, which allows `Var` to point to a `Function`.

Comment (certik) [reply src/lfortran/semantics/ast_body_visitor.cpp:1526]: Fixed in subsequent commits. Tests added.
